src/objects/Alert__c.object
<CustomObject>
    <fields>
        <fullName>MessagePDA_ID__c</fullName>
        <label>MessagePDA_ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>alert_type__c</fullName>
        <label>Alert Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                    <isActive>false</isActive>
                    <label>3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_missguided_Part_cause_closure__c</fullName>
        <label>Response missguided Part cause closure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_missguided_full_cause_closure__c</fullName>
        <label>Response missguided full cause closure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_missguided_full_cause_refuse__c</fullName>
        <label>Response missguided full cause refuse</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_missguided_part_cause_refuse__c</fullName>
        <label>Response missguided part cause refuse</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_new_Contractual_threshold__c</fullName>
        <label>Response new Contractual threshold</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>response_new_temporary_threshold__c</fullName>
        <label>Response new temporary threshold</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>response_overload_capacity_reach__c</fullName>
        <label>Response overload capacity reach</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Alert</label>
    <nameField>
        <displayFormat>ASD-{00000}</displayFormat>
        <label>Alerte Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WsReturnMessagePDA.cls
@RestResource(urlMapping='/alert/ReturnMsgPDA')
global with sharing class WsReturnMessagePDA {
    @HttpPost
    global static Boolean  updateAlertByMessagePDA(List<ResponseMessagePDA> listResponse){
        System.debug('listResponse'+listResponse);
        Set<ID>  gi = new Set<Id>();
        List<Alert__c> listAlertToRequest = new List<Alert__c>();
        List<Alert__c> listAlertToUpdate = new List<Alert__c>();
        String SOQL_IDs = '';
        Boolean ReturnStatus;
        Integer i =0;
        For(ResponseMessagePDA response: listResponse){
             i++;
            String id_in_quotes = '\''+response.IDMessagePDA+'\'';
            
            SOQL_IDs += id_in_quotes;
            if(response.IDMessagePDA!='' && i<listResponse.size()){
                SOQL_IDs+=',';
            }
           
        }
        String SOQL ='';
        if(SOQL_IDs!=''){
            SOQL = 'Select ID, MessagePDA_ID__c, alert_type__c from Alert__c  where MessagePDA_ID__c IN ('+SOQL_IDs+')';
            System.debug('SOQL'+SOQL);
            listAlertToRequest =database.query(SOQL);
        }
        For(ResponseMessagePDA response: listResponse){
            For(Alert__c alert: listAlertToRequest){
                if(response.IDMessagePDA==alert.MessagePDA_ID__c){
                    if(alert.alert_type__c =='2'){
                        alert.response_missguided_full_cause_closure__c = response.response_missguided_full_cause_closure;
                        alert.response_missguided_full_cause_refuse__c= response.response_missguided_full_cause_refuse;
                        alert.response_missguided_Part_cause_closure__c=response.response_missguided_Part_cause_closure;
                        alert.response_missguided_part_cause_refuse__c=response.response_missguided_part_cause_refuse;
                    }
                    if(alert.alert_type__c =='1'){
                        alert.response_overload_capacity_reach__c = response.response_overload_capacity_reach;
                        if(response.response_new_temporary_threshold!=null){
                            try {
                                alert.response_new_temporary_threshold__c = Decimal.valueOf(String.valueOf(response.response_new_temporary_threshold));
                            }catch (TypeException e) {
                                alert.response_new_temporary_threshold__c= null;
                            }
                        }
                        if(response.response_new_Contractual_threshold!=null){
                            try{
                                alert.response_new_Contractual_threshold__c = Decimal.valueOf(String.valueOf(response.response_new_Contractual_threshold));
                            }catch (TypeException e) {
                                alert.response_new_Contractual_threshold__c=null;
                            }
                        }
                        
                    }
                    listAlertToUpdate.add(alert);
                }
            }
        }
        try {
            update listAlertToUpdate;
            ReturnStatus=True;
        }
        catch(DmlException e) {
	        System.debug('The following exception has occurred:  ' + e.getMessage());
            ReturnStatus=False;
        }
        return ReturnStatus;
    }

    global class ResponseMessagePDA{
        public String IDMessagePDA {get;set;}
        public String response_overload_capacity_reach {get;set;}
        public String response_new_temporary_threshold {get;set;}
        public String response_new_Contractual_threshold {get;set;}
        public String response_missguided_full_cause_closure {get;set;}
        public String response_missguided_full_cause_refuse {get;set;}
        public String response_missguided_Part_cause_closure {get;set;}
        public String response_missguided_part_cause_refuse {get;set;}
    }
}