src/objects/Alert__c.object
<CustomObject>
    <fields>
        <fullName>Age_Alert__c</fullName>
        <formula>NOW() - CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age Alert</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                    <isActive>false</isActive>
                    <label>6</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_missguided_Part_cause_closure__c</fullName>
        <label>Response missguided Part cause closure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_missguided_full_cause_closure__c</fullName>
        <label>Response missguided full cause closure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_missguided_full_cause_refuse__c</fullName>
        <label>Response missguided full cause refuse</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_missguided_part_cause_refuse__c</fullName>
        <label>Response missguided part cause refuse</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>response_overload_capacity_reach__c</fullName>
        <label>Response overload capacity reach</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Alert</label>
    <nameField>
        <displayFormat>ASD-{00000}</displayFormat>
        <label>Alerte Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchCloseAlert.cls
/*
* Author: Gildas ADOUKONOU
* Modified By: -
* Date : 17/07/2018
* Test classe: BatchUpdateAlert_Test
*/
global class BatchCloseAlert implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Set<ID> setRT = new Set<ID>();
        //Date EndDate = Date.Today().addDays(-7);
        //Date EndDate = Date.Today().addDays(-2);
        String query ='select id, CreatedDate, Age_Alert__c, status__c, response_overload_capacity_reach__c, response_missguided_part_cause_refuse__c, response_missguided_full_cause_refuse__c,response_missguided_full_cause_closure__c,response_missguided_Part_cause_closure__c from Alert__c ';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC , List<Alert__c> scope) {
        list<Alert__c> listAlertToUpdate = new list<Alert__c>();
        For(Alert__c  alertRecord : scope){
            if((alertRecord.Age_Alert__c > 7) ){
                alertRecord.Status__c = '5';
            }
            
            listAlertToUpdate.add(alertRecord);
        }
        if(listAlertToUpdate.size() > 0) {
            Database.SaveResult[] srList = Database.update(listAlertToUpdate,false);
        }
    }
    global void finish(Database.BatchableContext BC){
        System.debug('Batch Alert executed');
    }
}