src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Piste__c</fullName>
        <label>ID Piste</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassWorkflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AP12_Lead.cls
/*
* Author: John Boutros
* Modified By: John Boutros
* Date : 07/02/2018
* Description:
* Test classe: AP12_Lead_TEST
Coverage : 100%
*/
public class AP12_Lead {
    public static void VRShippingCountryRT(List<Lead> newLeads, Map<Id, Lead> oldLeads)
    {
        system.debug('VRShippingCountryRT entered');
        User currentUser = [Select id , name , BypassProcessBuilder__c, BypassValidationRule__c, BypassWorkflow__c
                            from User
                            where id =: UserInfo.getUserId()];
        if(currentUser.BypassValidationRule__c  == false)
        {
            system.debug('BypassValidationRule__c entered');
            // Liste de type d'enregistrement et de pays
            List<Association_Record_Type_et_pays__mdt> metadataRTPays = [SELECT ID_Piste__c, MasterLabel
                                                                         FROM Association_Record_Type_et_pays__mdt];
            Set<String> AssocPaysRT = new Set<String>();
            // ajouter les pays et les types d'enregistrement correspondants dans un set
            for(Association_Record_Type_et_pays__mdt metadataAssocPaysRT : metadataRTPays)
            {
                AssocPaysRT.add(metadataAssocPaysRT.MasterLabel+'_'+ metadataAssocPaysRT.ID_Piste__c);
            }
            String paysRTID ='';
            system.debug('newLeads '+newLeads);
            for(Lead leadRecord: newLeads)
            {
                if(!Label.RT_Consigne_Compte.Contains(leadRecord.RecordTypeId) )
                {
                    if(leadRecord.Country !=null)
                    {
                        //if updating
                        if(oldLeads!= null && oldLeads.ContainsKey(leadRecord.Id))
                        {
                            if(oldLeads.get(leadRecord.Id).Country != leadRecord.Country)
                            {
                                // valider le choix du pays
                                if(!AssocPaysRT.contains(leadRecord.Country+'_'+leadRecord.RecordTypeId))
                                {
                                    leadRecord.Country.addError(Label.Pays_TypeEnregistrment);
                                }
                            }
                        }
                        //if inserting
                        else{    
                            paysRTID = leadRecord.Country+'_'+leadRecord.RecordTypeId;
                            // valider le choix du pays
                            system.debug('paysRTID '+paysRTID);
                            system.debug('AssocPaysRT '+AssocPaysRT);
                            if(!AssocPaysRT.contains(paysRTID))
                            {
                                system.debug('leadRecord 4 '+leadRecord);
                                leadRecord.Country.addError(Label.Pays_TypeEnregistrment);
                            }
                        }
                    }
                }
            }
        }
    }
}