src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Requete_Conge__c</fullName>
        <label>ID_Requête_Congé</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Nom_du_compte__c</fullName>
        <label>Nom du compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TECH_Conges_Dispo_Juillet_Aout__c</fullName>
        <formula>IF( 
	AND(Date_de_debut__c &gt;= DATE( YEAR( TODAY()),07, 01 ), 
		Date_de_debut__c &lt;= DATE( YEAR( TODAY()),08, 31 ), 
		Date_de_fin__c &gt;= DATE( YEAR( TODAY()),07, 01 ), 
		Date_de_fin__c &lt;= DATE( YEAR( TODAY()),08, 31), 
		OR(RecordType.Id == $Label.RT_Conge_Indispo_Conge ,RecordType.Id == $Label.RT_Conge_Indispo_Disponibilite ) 
), true, false)</formula>
        <label>TECH Conges Dispo Juillet Aout</label>
        <type>Checkbox</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AP08_Conge_Indispo.cls
/*--------------------------------------------------------------------------
*Author: Chahid Khalil
*Company : EI Technologies Liban
*Description: Helper class for Conge_Indispo trigger (after insert and after update)
			  Case to status "Terminee" if criteria met
*Test Class: AP08_Conge_Indispo_Test
*Created Date: 30/04/2018
--------------------------------------------------------------------------*/
public class AP08_Conge_Indispo {
    
    public static void UpdateCase(List<Conge_Indispo__c> newConge_Indispo, map<id,Conge_Indispo__c> mapOldConge_Indispo){	
        set<Id> AccountIds = new set<Id>();
        Set<ID> congesRecordTypeIDs = new Set<Id>();
        List< Association_Record_Type_et_pays__mdt> associationRTPaysBNL = [Select Id, MasterLabel, ID_Requete_Conge__c
                                                                            FROM Association_Record_Type_et_pays__mdt];
        Map<String,Association_Record_Type_et_pays__mdt> mapassociationRTPaysBNL =  new Map<String,Association_Record_Type_et_pays__mdt>();
        
        for(Association_Record_Type_et_pays__mdt mdtRecord: associationRTPaysBNL)
        {
            mapassociationRTPaysBNL.put(mdtRecord.MasterLabel, mdtRecord);
            congesRecordTypeIDs.add(mdtRecord.ID_Requete_Conge__c);
        }
        for (Conge_Indispo__c current_Conge_Indispo : newConge_Indispo)
        {
            if (mapOldConge_Indispo != Null)//case update
            {
                Conge_Indispo__c OldConge_Indispo = mapOldConge_Indispo.get(current_Conge_Indispo.id);
                if(current_Conge_Indispo.TECH_Conges_Dispo_Juillet_Aout__c == true && 
                   OldConge_Indispo.TECH_Conges_Dispo_Juillet_Aout__c == false)
                {
                    AccountIds.add(current_Conge_Indispo.Nom_du_compte__c);
                }
            }
            else //case insert
            {
               if(current_Conge_Indispo.TECH_Conges_Dispo_Juillet_Aout__c == true  )
                {
                    AccountIds.add(current_Conge_Indispo.Nom_du_compte__c);
                } 
            }
        }
        List<Case> Cases = [SELECT id, status
                            FROM Case
                            WHERE AccountId in:AccountIds and
                            RecordTypeId in : congesRecordTypeIDs];
        for(case current_case : Cases) 
        {
            current_case.status = Label.Requete_Terminee;//no translation needed
        }  
        update Cases;
    }
    
}