src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Piste__c</fullName>
        <label>ID Piste</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/CountriesSequence__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CountriesSequence</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Activite_commerciale_principale__c</fullName>
        <label>Activité commerciale principale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_ACT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Liechtenstein</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ACT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>1861</fullName>
    </customValue>
    <customValue>
        <fullName>1862</fullName>
    </customValue>
    <customValue>
        <fullName>1863</fullName>
    </customValue>
    <customValue>
        <fullName>1864</fullName>
    </customValue>
    <customValue>
        <fullName>1865</fullName>
    </customValue>
    <customValue>
        <fullName>1866</fullName>
    </customValue>
    <customValue>
        <fullName>1867</fullName>
    </customValue>
    <customValue>
        <fullName>1868</fullName>
    </customValue>
    <customValue>
        <fullName>1869</fullName>
    </customValue>
    <customValue>
        <fullName>1870</fullName>
    </customValue>
    <customValue>
        <fullName>1871</fullName>
    </customValue>
    <customValue>
        <fullName>1872</fullName>
    </customValue>
    <customValue>
        <fullName>1873</fullName>
    </customValue>
    <customValue>
        <fullName>1874</fullName>
    </customValue>
    <customValue>
        <fullName>1875</fullName>
    </customValue>
    <customValue>
        <fullName>1876</fullName>
    </customValue>
    <customValue>
        <fullName>1877</fullName>
    </customValue>
    <customValue>
        <fullName>1878</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>2167</fullName>
    </customValue>
    <customValue>
        <fullName>2168</fullName>
    </customValue>
    <customValue>
        <fullName>2169</fullName>
    </customValue>
    <customValue>
        <fullName>2170</fullName>
    </customValue>
    <customValue>
        <fullName>2171</fullName>
    </customValue>
    <customValue>
        <fullName>2172</fullName>
    </customValue>
    <customValue>
        <fullName>2173</fullName>
    </customValue>
    <customValue>
        <fullName>2174</fullName>
    </customValue>
    <customValue>
        <fullName>2175</fullName>
    </customValue>
    <description>Activité commerciale principale</description>
    <masterLabel>LOV_GLO_ACT</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/VFC02_LeadConversionController_Test.cls
@isTest
public class VFC02_LeadConversionController_Test {
    public static  testmethod void  convertLeads()
    {  
		// retrieve ID of belgium
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel,ID_Piste__c, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt
                                                                         Where MasterLabel ='Belgium'
                                                                         Limit 1];        
        //Create Custom Settings
        CountriesSequence__c cs = new CountriesSequence__c(Name='France' , Sequence__c = 'FR00001');
        insert cs;
        CountriesSequence__c cs1 = new CountriesSequence__c(Name='Belgium' , Sequence__c = 'BE00001');
        insert cs1;
        
        Lead lead1 = Utils_TestMethods.createLead('Georges','Hobeika','EI-Technologies','Qualifie');
        lead1.Postal_Code__c = '77777';
        lead1.RecordTypeId = Label.RT_Prospect_France;
        //lead1.Activite_commerciale_principale__c=null;
        insert lead1;
        ApexPages.StandardController sc = new ApexPages.StandardController(lead1); 
        VFC02_LeadConversionController leadController = new VFC02_LeadConversionController(sc);  
        Lead lead2 = Utils_TestMethods.createLead('John','Boutros','EI-Technologies','Qualifie');
        lead2.Postal_Code__c = '77777';
        lead2.RecordTypeId = associationRTPays[0].ID_Piste__c;
        lead2.Activite_commerciale_principale__c='2168';
        lead2.Status    =  null; 
        lead2.Country__c   = 'Belgium'; 
        lead2.Industry = '226';
        lead2.Postal_Code__c = '1234';
        insert lead2;
        ApexPages.StandardController sc1 = new ApexPages.StandardController(lead2); 
        VFC02_LeadConversionController leadController1 = new VFC02_LeadConversionController(sc);  
        
        // convert the lead
        leadController.convertLeadAndRedirectToAccount();
        System.debug('###gho leadController.showLink ' +  leadController.showLink); 
        
        // convert the lead for the second time
        leadController.convertLeadAndRedirectToAccount();
        // System.assertEquals(true, leadController.showLink);
        
        Lead lead3 = Utils_TestMethods.createLead('John','Boutros','EI-Technologies','Qualifie');
        lead3.RecordTypeId = associationRTPays[0].ID_Piste__c;
        lead3.Country__c   = 'Belgium'; 
        lead3.Street__c    =  'lead street';
        lead3.Activite_commerciale_principale__c = null;
        lead3.Postal_Code__c ='1235';
        insert lead3;
        //lead3.Postal_Code__c ='1234';
        //update lead3;
        test.startTest(); 
        ApexPages.StandardController sc3 = new ApexPages.StandardController(lead3); 
        VFC02_LeadConversionController leadController3 = new VFC02_LeadConversionController(sc3); 
        leadController3.convertLeadAndRedirectToAccount();
        
        
        
        // redirect to the lead page 
        PageReference pageref = leadController.redirectToLead();
        // system.assertEquals('/' + lead1.Id, pageref.getUrl());
        //test.stopTest();
    }
    
}