src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Piste__c</fullName>
        <label>ID Piste</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CountriesSequence__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CountriesSequence</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Activite_commerciale_principale__c</fullName>
        <label>Activité commerciale principale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_ACT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Liechtenstein</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ACT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>1861</fullName>
    </customValue>
    <customValue>
        <fullName>1862</fullName>
    </customValue>
    <customValue>
        <fullName>1863</fullName>
    </customValue>
    <customValue>
        <fullName>1864</fullName>
    </customValue>
    <customValue>
        <fullName>1865</fullName>
    </customValue>
    <customValue>
        <fullName>1866</fullName>
    </customValue>
    <customValue>
        <fullName>1867</fullName>
    </customValue>
    <customValue>
        <fullName>1868</fullName>
    </customValue>
    <customValue>
        <fullName>1869</fullName>
    </customValue>
    <customValue>
        <fullName>1870</fullName>
    </customValue>
    <customValue>
        <fullName>1871</fullName>
    </customValue>
    <customValue>
        <fullName>1872</fullName>
    </customValue>
    <customValue>
        <fullName>1873</fullName>
    </customValue>
    <customValue>
        <fullName>1874</fullName>
    </customValue>
    <customValue>
        <fullName>1875</fullName>
    </customValue>
    <customValue>
        <fullName>1876</fullName>
    </customValue>
    <customValue>
        <fullName>1877</fullName>
    </customValue>
    <customValue>
        <fullName>1878</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>2167</fullName>
    </customValue>
    <customValue>
        <fullName>2168</fullName>
    </customValue>
    <customValue>
        <fullName>2169</fullName>
    </customValue>
    <customValue>
        <fullName>2170</fullName>
    </customValue>
    <customValue>
        <fullName>2171</fullName>
    </customValue>
    <customValue>
        <fullName>2172</fullName>
    </customValue>
    <customValue>
        <fullName>2173</fullName>
    </customValue>
    <customValue>
        <fullName>2174</fullName>
    </customValue>
    <customValue>
        <fullName>2175</fullName>
    </customValue>
    <description>Activité commerciale principale</description>
    <masterLabel>LOV_GLO_ACT</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AP12_Lead_TEST.cls
@isTest
public class AP12_Lead_TEST {
    static testmethod void test()
    {
        /*// retrieve ID of belgium
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel,ID_Piste__c, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt
                                                                         Where MasterLabel ='Belgium'
                                                                         Limit 1];
        //Create Custom Settings country sequence
        CountriesSequence__c cs = new CountriesSequence__c(Name='Belgium' , Sequence__c = 'BE0001');
        try{
            insert cs;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        try{
            insert testContact;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        //Create lead France
        Lead lead1= Utils_TestMethods.createLead('firstName', 'lastName', 'company', 'Non');
        lead1.RecordTypeId = Label.RT_Prospect_France;
        lead1.Country__c ='France';
        lead1.CountryCode = 'FR';
        lead1.Postal_Code__c = '12345';
        insert lead1;
        lead1.Country__c ='Belgium';
        lead1.CountryCode='BE';
        // update lead and enter error
        //try{
        //    update lead1;
        //} catch(DmlException e) {
         //   system.assert(e.getMessage().contains(Label.Pays_TypeEnregistrment) );
        //}
        //Create lead BNL
        Lead lead2= Utils_TestMethods.createLead('firstName1', 'lastName1', 'company1', 'Non');
        lead2.RecordTypeId = associationRTPays[0].ID_Piste__c;
        lead2.Country__c ='Belgium';
        lead2.CountryCode='BE';
        lead2.Industry ='227';
        lead2.Activite_commerciale_principale__c = '2175';
        insert lead2;
        // update lead and enter error
        try{
            lead2.Country__c='France';
            lead2.CountryCode ='FR';
            update lead2;
        } catch(DmlException e) {
            system.assert(e.getMessage().contains(Label.Pays_TypeEnregistrment) );
        }
        //Create lead France and enter error
        Lead lead3= Utils_TestMethods.createLead('firstName2', 'lastName2', 'company2', 'Non');
        lead3.RecordTypeId = Label.RT_Prospect_France;
        lead3.Country__c ='Belgium';
        lead3.CountryCode='BE';
        try{
            insert lead3;
        } catch(DmlException e) {
            system.assert(e.getMessage().contains(Label.Pays_TypeEnregistrment) );
        }
        //Create lead BNL
        Lead lead4= Utils_TestMethods.createLead('firstName3', 'lastName3', 'company3', 'Non');
        lead4.RecordTypeId = associationRTPays[0].ID_Piste__c;
        lead4.Activite_commerciale_principale__c =null;
        lead4.Country__c ='France';
        lead4.CountryCode ='FR';
        try{
            insert lead4;
        } catch(DmlException e) {
            system.debug('e.getMessage() '+e.getMessage());
            system.assert(e.getMessage().contains(Label.Pays_TypeEnregistrment) );
        }*/
    }
}