src/objects/Batch_Log__c.object
<CustomObject>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status_Code</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch_Log</label>
    <nameField>
        <displayFormat>BL-{0000000000}</displayFormat>
        <label>Nom de Batch_Logs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_de_rappel_planifiee__c</fullName>
        <label>Date de rappel planifiée</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planifier_un_rappel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Planifier un rappel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Point_relais_ne_repond_pas__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Champ tech pour sortie de vue de liste et rentrée à H+2</description>
        <label>NRP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Traitement_interrompu__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Traitement interrompu</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch11_ScheduleDACases.cls
/**
* @author John Boutros
* @date 3/20/2019
* @description Batch that runs every day at 4 A.M to update cases 
* in order to make them visible in list view 'mes requêtes en cours'
*/
global class Batch11_ScheduleDACases implements Database.Batchable<sObject>{
    String queryDAInter = '';
    String casesIDLabel = Label.RT_DA_Requete.replace(';', '\',\'' );
    /**
	* @author John Boutros
	* @date 3/20/2019
	* @description Scheduler start method that queries INTER DA cases that has a call scheduled 
	* Ticket 144210
	* @param SchedulableContext
	* @return None
	*/
    global Batch11_ScheduleDACases ()
    {
        queryDAInter = 'SELECT id, Date_de_rappel_planifiee__c, Traitement_interrompu__c, Planifier_un_rappel__c ' +
            'FROM Case '+
            'WHERE RecordtypeID in (\'' + casesIDLabel + '\') ' +
            'AND Account.shippingcountry != \'France\' ' +
            'AND Date_de_rappel_planifiee__c != null'; 
    }
    global Batch11_ScheduleDACases (ID idCase)
    {
        queryDAInter = 'SELECT id, Date_de_rappel_planifiee__c, Traitement_interrompu__c, Planifier_un_rappel__c ' +
            'FROM Case '+
            'WHERE RecordtypeID in (\'' + casesIDLabel + '\') ' +
            'AND Account.shippingcountry != \'France\' ' +
            'AND Date_de_rappel_planifiee__c != null '+
            'AND Id=\'' + idCase + '\'';
    }
    /**
	* @author John Boutros
	* @date 3/20/2019
	* @description Scheduler start method that queries INTER DA cases that has a call scheduled 
	* Ticket 144210
	* @param SchedulableContext
	* @return None
	*/
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(queryDAInter);
    }
    
	/**
	* @author John Boutros
	* @date 3/20/2019
	* @description Scheduler execute method that queries INTER DA cases that has a call scheduled 
	* Ticket 144210
	* @param SchedulableContext
	* @return None
	*/
    global void execute(Database.BatchableContext BC, List<Case> scopeCasesListCasesList){
        List<Case> daCasesList = new List<Case>();
        for(Case caseFiltered : scopeCasesListCasesList){
            System.debug('Batch11_ScheduleDACases caseFiltered ' + caseFiltered);            
            if(caseFiltered.Date_de_rappel_planifiee__c == system.today()){
                caseFiltered.Traitement_interrompu__c= false;
                caseFiltered.Planifier_un_rappel__c= false;
                caseFiltered.Date_de_rappel_planifiee__c = null;
                caseFiltered.Point_relais_ne_repond_pas__c = false;
                daCasesList.add(caseFiltered);
            }
        }
        System.debug('Batch11_ScheduleDACases daCasesList '+daCasesList);
        if(daCasesList.size() > 0) {
            Database.SaveResult[] srList = Database.update(daCasesList,false);
            List<Batch_Log__c> batchLogsList = new List<Batch_Log__c>();
            for (Integer i = 0; i < daCasesList.size(); i++) {
                Database.SaveResult sr = srList[i];
                Case origRecord = daCasesList[i];
                if (!sr.isSuccess()) {
                    for(Database.Error err : sr.getErrors()) {
                        batchLogsList.add(new Batch_log__c(Status_Code__c = '' + err.getStatusCode(),Message__c = err.getMessage(),Fields__c = '' + err.getFields(),ID__c = origRecord.Id));
                    }
                }
            }
            if(batchLogsList.size() > 0){
                insert batchLogsList;
            }
        }
    }
    
	/**
	* @author John Boutros
	* @date 3/20/2019
	* @description Scheduler finish method that checks if job is Done succesfully
	* Ticket 144210
	* @param SchedulableContext
	* @return None
	*/
    global void finish(Database.BatchableContext BC){
        AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :BC.getJobId()]; 
        System.debug('Batch11_ScheduleDACases  >>>> finish ' + job.Status);
    }
    
}