src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Age_de_la_requete__c</fullName>
        <formula>FLOOR(NOW()-DATETIMEVALUE(CreatedDate))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age de la requête (J)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sens_du_contact__c</fullName>
        <label>Sens du contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Entrant</fullName>
                    <default>true</default>
                    <label>Entrant</label>
                </value>
                <value>
                    <fullName>Sortant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sous_motif_1__c</fullName>
        <label>Sous-motif 1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Actions à réaliser</fullName>
                </value>
                <value>
                    <fullName>Anomalie colis</fullName>
                </value>
                <value>
                    <fullName>Autres</fullName>
                </value>
                <value>
                    <fullName>Changement de coordonnees</fullName>
                    <label>Changement de coordonnées</label>
                </value>
                <value>
                    <fullName>Colis volumineux</fullName>
                </value>
                <value>
                    <fullName>Collecte</fullName>
                </value>
                <value>
                    <fullName>Collecte Transporteur</fullName>
                </value>
                <value>
                    <fullName>Commandes</fullName>
                </value>
                <value>
                    <fullName>Comportement du point relais</fullName>
                </value>
                <value>
                    <fullName>Congé et disponibilité du point relais</fullName>
                </value>
                <value>
                    <fullName>Contre-remboursement (COD)</fullName>
                </value>
                <value>
                    <fullName>Demande d&apos;enlèvement colis</fullName>
                </value>
                <value>
                    <fullName>Demande de retour colis</fullName>
                </value>
                <value>
                    <fullName>Dépôt</fullName>
                </value>
                <value>
                    <fullName>Dévoyés</fullName>
                </value>
                <value>
                    <fullName>Dévoyés 100% cause relais</fullName>
                </value>
                <value>
                    <fullName>Dévoyés partiels cause relais</fullName>
                </value>
                <value>
                    <fullName>Echange</fullName>
                </value>
                <value>
                    <fullName>État du colis</fullName>
                </value>
                <value>
                    <fullName>Événement grave</fullName>
                </value>
                <value>
                    <fullName>Exclusion</fullName>
                </value>
                <value>
                    <fullName>Facturation</fullName>
                </value>
                <value>
                    <fullName>Horaires</fullName>
                </value>
                <value>
                    <fullName>Indemnisation colis</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité</fullName>
                </value>
                <value>
                    <fullName>Informations colis</fullName>
                </value>
                <value>
                    <fullName>Inventaire colis</fullName>
                </value>
                <value>
                    <fullName>Inventaire colis non réalisé</fullName>
                </value>
                <value>
                    <fullName>Livraison</fullName>
                </value>
                <value>
                    <fullName>Menace de résiliation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Traite__c</fullName>
        <label>Traité</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>TM_FR</fullName>
        <active>true</active>
        <businessProcess>TM_France</businessProcess>
        <description>Permet de créer une requête Ticket Manager FR</description>
        <label>TM_FR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchCloseCaseOverload.cls
/*
* Author: Gildas ADOUKONOU
* Modified By: - 
* Date : 16/03/2019
* Test classe: BatchCloseCaseOverload_Test
*/
global class BatchCloseCaseOverload implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query ='Select id,Age_de_la_requete__c,recordtypeId, status, Sous_motif_1__c,Sens_du_contact__c from Case Where status=\'0\' AND Sous_motif_1__c=\'Surcharge\' AND Sens_du_contact__c=\'Sortant\'';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC , List<Case> scope) {
        Id CaseRecordTypeId = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SObjectType = 'Case' and developerName='TM_FR'].Id;
        list<Case> listCaseToClose= new list<Case>();
        For(Case  caseRecord : scope){
            if(caseRecord.Age_de_la_requete__c>=6 && caseRecord.recordtypeId==CaseRecordTypeId ){
                caseRecord.Status = 'Terminée';
                caseRecord.Traite__c='Non';
                listCaseToClose.add(caseRecord);
            }
            
        }
        if(listCaseToClose.size() > 0) {
            Database.SaveResult[] srList = Database.update(listCaseToClose,false);
        }
    }
    global void finish(Database.BatchableContext BC){
        System.debug('Batch executed ');
    }
}