src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Indisponibilite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Indisponibilité</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Conge_Indispo__c.Nom_du_compte__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Conge_Indispo__c</referenceTo>
        <relationshipLabel>Requêtes</relationshipLabel>
        <relationshipName>Requ_tes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Date_de_debut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Injoignable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Injoignable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Injoignable_depuis_le__c</fullName>
        <label>Injoignable depuis le</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nom_du_compte__c</fullName>
        <label>Nom du compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Historique_Injoignabilites__c.object
<CustomObject>
    <description>Cet objet permet d&apos;historiser les période d&apos;injoignabilité d&apos;un PUDO.</description>
    <fields>
        <fullName>Compte__c</fullName>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Historique Injoignabilités</relationshipLabel>
        <relationshipName>Historique_Injoignabilites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_de_debut1__c</fullName>
        <label>Date de début</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_de_fin1__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Indisponibilite__c</fullName>
        <label>Indisponibilité</label>
        <referenceTo>Conge_Indispo__c</referenceTo>
        <relationshipLabel>Historique Injoignabilités</relationshipLabel>
        <relationshipName>Historique_Injoignabilites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Historique Injoignabilité</label>
    <nameField>
        <displayFormat>HIN-{0000}</displayFormat>
        <label>Numero d&apos;historique d&apos;injoignabilité</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historique Injoignabilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AP05_Conge_Indispo.cls
public class AP05_Conge_Indispo {

    Id congeRTypeId = Label.CongeRT_15;
    Id indispoStandardRTypeId = Label.IndispoStandardRT_15;
    Id indispoConsigneRTypeId = Label.IndispoConsigneRT_15;
    Id dispoRTypeId = Label.DispoRT_15;

    
    // Cas où suite à la création d'une indisponibilité, il y a création de l'injoignabilité correspondante si la case 'Injoignable' est cochée
    public void insertInjoignabilite(List<Conge_Indispo__c> newIndispo){
        
        List<Conge_Indispo__c> listeIndispoInjoignables = new List<Conge_Indispo__c>();
        
        for(Conge_Indispo__c cong : newIndispo){
            System.debug(' Injoignabilite : new ' + cong.Injoignable__c  );
            
            if(cong.RecordTypeId == indispoStandardRTypeId || cong.RecordTypeId == indispoConsigneRTypeId){
                   
                   System.debug('Appel méthode de création d\'une injoignabilité pour indispo nouvellement créee : ' + cong);
                   listeIndispoInjoignables.add(cong);
               }
        }
        
        
        if(listeIndispoInjoignables.isEmpty() != true ){ 
            newInjoignabilite(listeIndispoInjoignables); }
    }
    
    
    
    public void newInjoignabilite(List<Conge_Indispo__c> listeIndispoInjoignables){
        
        List<Historique_Injoignabilites__c> injoignabiliteToInsert = new List<Historique_Injoignabilites__c>();
     
        for(Conge_Indispo__c indispo : listeIndispoInjoignables){
            if( indispo.Injoignable__c == true){
                // si le champs 'Injoignable_depuis_le__c' (= date de debut de l'injoignabilité) est renseigné ou non 
                if(indispo.Injoignable_depuis_le__c != null){
                    Historique_Injoignabilites__c inj = new Historique_Injoignabilites__c( Compte__c = indispo.Nom_du_compte__c , Indisponibilite__c = indispo.Id, 
                                                                                          Date_de_debut1__c = indispo.Injoignable_depuis_le__c, Date_de_fin1__c = null);
                    injoignabiliteToInsert.add(inj);
                    system.debug(' nouvel injoignabilité avec date de début indiquée : ' + inj);
                }else{
                    Historique_Injoignabilites__c inj = new Historique_Injoignabilites__c( Compte__c = indispo.Nom_du_compte__c , Indisponibilite__c = indispo.Id, Date_de_debut1__c = indispo.Date_de_debut__c, Date_de_fin1__c = null);   
                    injoignabiliteToInsert.add(inj);
                    system.debug(' nouvel injoignabilité sans date de début indiquée : ' + inj);
                }
            }
                         
                     }

        if(injoignabiliteToInsert.IsEmpty() != true){ 
            try{
                insert injoignabiliteToInsert;
            }catch(Exception e){
                System.debug(LoggingLevel.Error, e.getMessage());
            }
        }    
         
    }
    
}