src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_de_rappel_planifiee__c</fullName>
        <label>Date de rappel planifiée</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Object_de_la_requete__c</fullName>
        <label>Objet de la requête</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anomalie de synchronisation d’un relais</fullName>
                    <label>Anomalie de synchronisation d&apos;un relais</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Sinistre / Travaux / Santé</fullName>
                    <label>Indisponibilité - Problème opérationnel Sinistre / Travaux / Santé</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Qualité de Service</fullName>
                    <label>Indisponibilité - Problème opérationnel Qualité de Service</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Panne PDA</fullName>
                    <label>Indisponibilité - Problème PDA / Panne PDA</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Problème de synchronisation</fullName>
                    <label>Indisponibilité - Problème PDA / Problème de synchronisation</label>
                </value>
                <value>
                    <fullName>Indisponibilité problème opérationnel - Injoignabilité</fullName>
                </value>
                <value>
                    <fullName>Démarrage d&apos;activité</fullName>
                </value>
                <value>
                    <fullName>Relais sans formation avec moyens de scans associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif avec plusieurs moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Les relais actifs avec terme contrat non respecté</fullName>
                </value>
                <value>
                    <fullName>Les Congés du relais</fullName>
                </value>
                <value>
                    <fullName>Relais inactif avec moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif sans moyen de scan associé</fullName>
                </value>
                <value>
                    <fullName>Les horaires insuffisants du relais</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Anomalie colis</fullName>
                    <isActive>false</isActive>
                    <label>Indisponibilité Problème opérationnel Anomalie colis</label>
                </value>
                <value>
                    <fullName>Relais actif sans formation avec moyen de scan associé</fullName>
                    <isActive>false</isActive>
                    <label>Relais actif sans formation avec moyen de scan associé</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operateur__c</fullName>
        <formula>text(Account.Operateur_Global__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opérateur</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Point_relais_ne_repond_pas__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Champ tech pour sortie de vue de liste et rentrée à H+2</description>
        <label>NRP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tech_Is_Manual_Modif__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tech_Is_Manual_Modif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Traitement_interrompu__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Traitement interrompu</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/LC02_ConsignerUnAppel_Controller.cls
public class LC02_ConsignerUnAppel_Controller {
    @auraEnabled
    public static String getCaseStatus (String caseId){
        system.debug('caseId'+ caseId);
        Case queryCase = [select id, caseNumber,  toLabel(status)
                          from case
                          where id =: caseId];
        
        String retVal = queryCase.status;
        system.debug('retVal '+retVal);
        return retVal;
    }
    @auraEnabled
    public static string consignerUnappelController (string SelectedRadioBoxValue, String CaseIDRetrieved )
    {
        Case currentRequest = [select id, Object_de_la_requete__c, Subject, Status, Point_relais_ne_repond_pas__c, Operateur__c, ContactId, AccountId,Date_de_rappel_planifiee__c,Tech_Is_Manual_Modif__c
                               from Case 
                               where id =: CaseIDRetrieved];

        system.debug('SelectedRadioBoxValue'+ SelectedRadioBoxValue);
        system.debug('Label.DA_OuiRelaisRepond'+ Label.DA_OuiRelaisRepond);
        string objet = '';
        
        if(currentRequest.Object_de_la_requete__c == null || currentRequest.Object_de_la_requete__c == ''){
            objet = currentRequest.Subject; 
             system.debug('christine enter 1');
            
        }
        else{
             system.debug('christine enter objet '+objet);
             objet = currentRequest.Object_de_la_requete__c; 
            }
        
         system.debug('christine enter objet '+objet);
        if(SelectedRadioBoxValue == Label.DA_OuiRelaisRepond)
        {
            createTask(CaseIDRetrieved, currentRequest.ContactId, objet +' - '+ Label.CA_contactEffLb, Label.DA_Tache_StatutTraite, null); //change to label
            //currentRequest.Sous_statut__c = '';
            //update currentRequest;
            return 'repond';
        }
        //si le relais ne repond pas
        else if(SelectedRadioBoxValue == Label.DA_NonRelaisRepond) {
            createTask(CaseIDRetrieved, currentRequest.ContactId, objet +' - '+ Label.CA_NRPLb, Label.DA_Tache_StatutTraite, null); //change to label
            //currentRequest.Sous_statut__c = 'NRP';
            currentRequest.Point_relais_ne_repond_pas__c = true;
            update currentRequest;
            return 'ne repond pas';
        }
        
        else if (SelectedRadioBoxValue == Label.DA_InterrompuLbl){
            createTask(CaseIDRetrieved, currentRequest.ContactId, objet +' - '+ Label.DA_InterrompuLbl, Label.DA_Tache_StatutTraite, null); //change to label
            //currentRequest.Sous_statut__c = 'Traitement interrompu';
            currentRequest.Traitement_interrompu__c  = true;
            update currentRequest;
            return 'interrompu';
        }
        return 'Task Created';
    }
    
    public static void createTask(string whatId, string whoId, string subject, string status, date datePlannifiable){
        Task tacheToInsert = new Task();
        tacheToInsert.WhatId = whatId;
        tacheToInsert.WhoId = whoId;
        tacheToInsert.Subject = subject;
        tacheToInsert.status = status;
        tacheToInsert.ActivityDate = date.today();
        tacheToInsert.OwnerId = UserInfo.getUserId();
        system.debug(tacheToInsert);
        insert tacheToInsert;
    }
    
}