src/objects/Compte_rendu__c.object
<CustomObject>
    <description>Cet objet permet de sélectionner les questions CR en fonction du compte rendu sélectionné.</description>
    <fields>
        <fullName>Compte_rendu__c</fullName>
        <label>Compte rendu</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>INTER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compte rendu</label>
    <nameField>
        <label>Nom de compte rendu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes rendus</pluralLabel>
    <recordTypes>
        <fullName>VA</fullName>
        <active>true</active>
        <label>VA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compte_rendu_rempli__c.object
<CustomObject>
    <description>Compte rendu VA/VAP rempli suite à la visite d&apos;un animateur chez un PUDO.</description>
    <fields>
        <fullName>Compte_rendu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte rendu</label>
        <referenceTo>Compte_rendu__c</referenceTo>
        <relationshipName>Comptes_rendus_remplis</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Compte rendu de visite</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Nom de compte rendu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comptes rendus de visite</pluralLabel>
    <recordTypes>
        <fullName>VA</fullName>
        <active>true</active>
        <label>VA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questions_CR__c.object
<CustomObject>
    <description>Questions utilisés pour les questionnaires VA/VAP.</description>
    <fields>
        <fullName>Compte_rendu__c</fullName>
        <label>Nom du compte rendu</label>
        <referenceTo>Compte_rendu__c</referenceTo>
        <relationshipName>Questionnaires_VA_VAP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Questions CR</label>
    <nameField>
        <label>Numéro de question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions CR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reponse__c.object
<CustomObject>
    <description>Objet utilisé pour stocker les réponses d&apos;un PUDO lors du démarrage d&apos;activité.</description>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Réponses</relationshipLabel>
        <relationshipName>Reponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Réponse</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Numéro de Réponse</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reponse_CR__c.object
<CustomObject>
    <description>Réponses des questionnaires VA/VAP.</description>
    <fields>
        <fullName>Compte_rendu_rempli__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte rendu rempli</label>
        <referenceTo>Compte_rendu_rempli__c</referenceTo>
        <relationshipLabel>Comptes rendu de visite</relationshipLabel>
        <relationshipName>Reponses_CR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Questions_CR__c</fullName>
        <label>Questions CR</label>
        <referenceTo>Questions_CR__c</referenceTo>
        <relationshipLabel>Réponses CR (Questions CR)</relationshipLabel>
        <relationshipName>Reponses_CR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reponse__c</fullName>
        <label>Réponse</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Réponse CR</label>
    <nameField>
        <label>Nom de réponse CR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réponses CR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/C01_EmailTemplate_CRR_Controller_Test.cls
/*--------------------------------------------------------------------------------------------------------------------------
Author: Fadi Tannoury
Company: Ei-Technologies Lebanon
Description: TestClass C01_EmailTemplateController
History
2018-06-05  Fadi Tannoury	  Creation
--------------------------------------------------------------------------------------------------------------------------*/

@isTest
public class C01_EmailTemplate_CRR_Controller_Test {    
    
    @isTest
    public static void EmailTemplateTest(){
        
        Id CompteRendu_RTId = [SELECT id FROM RecordType WHERE DeveloperName = 'VA' AND SobjectType = 'Compte_rendu__c' LIMIT 1].Id;
        
        Account compte = Utils_TestMethods.CreateAccount(null, null, 'compte');
        insert compte;
        
        Compte_rendu_rempli__c CRR = Utils_TestMethods.createCompteRenduRempli(compte.Id, Label.VAVAP_statutTermine);
        insert CRR;
        
        Compte_rendu__c CR = Utils_TestMethods.createCompteRendu('Compte Rendu', CompteRendu_RTId);
        insert CR;
        
        Questions_CR__c ques = Utils_TestMethods.createQuestionsCR(CR.id, 'Oui;Non', 'test?', 'Choix');
        insert ques;
        
        Reponse_CR__c Reponse = Utils_TestMethods.createReponseCR(CRR.id, ques.Id, 'Question', 'Reponse');
        insert Reponse; 
        
        Folder folder = [SELECT id, Name FROM Folder WHERE DeveloperName  = 'EmailTemplates']; system.debug('folder: '+folder);
        Document header = Utils_TestMethods.createDocument('Header', 'HeaderTest', folder.Id);
        Document footer = Utils_TestMethods.createDocument('Footer', 'FooterTest', folder.Id);
        insert new List<Document>{header, footer};
        
        Test.startTest();
        C01_EmailTemplate_CRR_Controller ETC = new C01_EmailTemplate_CRR_Controller();
        ETC.CompteRenduRempli = CRR;
        ETC.setListReponses(new List<Reponse_CR__c>{Reponse});
        List<Reponse_CR__c> reponses = ETC.getListReponses();
        String HeaderUrl = ETC.getHeaderUrl();
        ETC.HeaderUrl='header';
        String FooterUrl = ETC.getFooterUrl();
        ETC.FooterUrl='footer';
        Test.stopTest();
        
        System.assertEquals(Reponse.Question__c, reponses[0].Question__c);
        System.assertEquals(Reponse.Reponse__c, reponses[0].Reponse__c);
        
    }

}