src/objects/Compte_rendu_rempli__c.object
<CustomObject>
    <description>Compte rendu VA/VAP rempli suite à la visite d&apos;un animateur chez un PUDO.</description>
    <fields>
        <fullName>Envoi_email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Envoi email</label>
        <type>Checkbox</type>
    </fields>
    <label>Compte rendu de visite</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Nom de compte rendu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comptes rendus de visite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AP03_Task.cls
/*--------------------------------------------------------------------------------------------------------------------------
Author: Fadi Tannoury
Company: Ei-Technologies Lebanon
Description: MAJ si un email est envoyé depuis le compte rendu rempli
History
2018-06-07  Fadi Tannoury	  Creation
--------------------------------------------------------------------------------------------------------------------------*/

public class AP03_Task {
    
    public static void CheckCRREmailSent(List<Task> TasksList){
        
        List<Id> WhatIdsList = new List<Id>();
        
        for(Task task : TasksList){
            if (task.TaskSubtype == 'Email' && task.WhatId.getSObjectType() == Compte_rendu_rempli__c.sObjectType){
                WhatIdsList.add(task.WhatId);
            }
        }
        
        List<Compte_rendu_rempli__c> CRRList = [SELECT Id, Envoi_email__c 
                                                FROM Compte_rendu_rempli__c 
                                                WHERE Id IN :WhatIdsList];
        System.debug('CRRList: ' + CRRList);
        
        for(Compte_rendu_rempli__c CRR : CRRList){        
            CRR.Envoi_email__c = true;
        }
        
        if(CRRList.size()>0){
            try{update CRRList;} catch(DMLException ex){system.debug(ex.getMessage());}
        }
        
    }

}