src/objects/Compte_rendu_rempli__c.object
<CustomObject>
    <description>Compte rendu VA/VAP rempli suite à la visite d&apos;un animateur chez un PUDO.</description>
    <label>Compte rendu de visite</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Nom de compte rendu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comptes rendus de visite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questions_CR__c.object
<CustomObject>
    <description>Questions utilisés pour les questionnaires VA/VAP.</description>
    <fields>
        <fullName>Options_de_reponses__c</fullName>
        <label>Options de réponses</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Question_Order__c</fullName>
        <formula>VALUE( Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Numéro</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Questions CR</label>
    <nameField>
        <label>Numéro de question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions CR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reponse__c.object
<CustomObject>
    <description>Objet utilisé pour stocker les réponses d&apos;un PUDO lors du démarrage d&apos;activité.</description>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Réponses</relationshipLabel>
        <relationshipName>Reponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Réponse</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Numéro de Réponse</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reponse_CR__c.object
<CustomObject>
    <description>Réponses des questionnaires VA/VAP.</description>
    <fields>
        <fullName>Compte_rendu_rempli__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte rendu rempli</label>
        <referenceTo>Compte_rendu_rempli__c</referenceTo>
        <relationshipLabel>Comptes rendu de visite</relationshipLabel>
        <relationshipName>Reponses_CR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Questions_CR__c</fullName>
        <label>Questions CR</label>
        <referenceTo>Questions_CR__c</referenceTo>
        <relationshipLabel>Réponses CR (Questions CR)</relationshipLabel>
        <relationshipName>Reponses_CR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reponse__c</fullName>
        <label>Réponse</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_de_r_ponse__c</fullName>
        <label>Type de réponse</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aucun</fullName>
                </value>
                <value>
                    <fullName>Choix</fullName>
                </value>
                <value>
                    <fullName>Multi-choix</fullName>
                </value>
                <value>
                    <fullName>Texte</fullName>
                </value>
                <value>
                    <fullName>Titre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Réponse CR</label>
    <nameField>
        <label>Nom de réponse CR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réponses CR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/C01_EmailTemplate_CRR_Controller.cls
/*--------------------------------------------------------------------------------------------------------------------------
Author: Fadi Tannoury
Company: Ei-Technologies Lebanon
Description: Controller for C01_EmailTemplate
History
2018-06-05  Fadi Tannoury	  Creation
--------------------------------------------------------------------------------------------------------------------------*/

public class C01_EmailTemplate_CRR_Controller {
     
    public Compte_rendu_rempli__c CompteRenduRempli {get; set;}
    public List<Reponse_CR__c> listReponses;
    public String HeaderUrl {set;}
    public String FooterUrl {set;}
    public String OrgId {get;set;}
    
    public C01_EmailTemplate_CRR_Controller() {
       OrgId = [SELECT id, Name FROM Organization].Id;      
    }
    
    public string getHeaderUrl(){
        
        String HeaderUrl = '';
        String DevName = !Test.isRunningTest() ? 'Header_EmailTemplate' : 'HeaderTest';
        List<Document> Header = [SELECT Id, DeveloperName FROM Document WHERE DeveloperName = :DevName LIMIT 1]; 
        if(Header.size()>0){
            HeaderUrl = System.URL.getSalesforceBaseUrl().toExternalForm() + '/servlet/servlet.ImageServer?id=' + Header[0].Id + '&oid=' + OrgId;
        }
        return HeaderUrl;
    }
    
    public string getFooterUrl(){
        
        String FooterUrl = '';
        String DevName = !Test.isRunningTest() ? 'Footer_EmailTemplate' : 'FooterTest';
        List<Document> Footer = [SELECT Id, DeveloperName FROM Document WHERE DeveloperName = :DevName LIMIT 1];
        if(Footer.size()>0){
            FooterUrl = System.URL.getSalesforceBaseUrl().toExternalForm() + '/servlet/servlet.ImageServer?id=' + Footer[0].Id + '&oid=' + OrgId;
        }
        return FooterUrl;
    }

    public void setListReponses(List<Reponse_CR__c> lst){
        listReponses = lst;
    }
    
    public List<Reponse_CR__c> getListReponses(){
        
        system.debug('CompteRenduRempli: ' + CompteRenduRempli);

        List<Reponse_CR__c> lstRep = [SELECT Id, Name, Compte_rendu_rempli__c, Question__c, Reponse__c, Type_de_r_ponse__c, 
                                      Questions_CR__r.Tech_Question_Order__c, Questions_CR__r.Options_de_reponses__c
                                      FROM Reponse_CR__c
                                      WHERE Compte_rendu_rempli__c = :CompteRenduRempli.Id];
        system.debug('lstRep: '+lstRep);
            return lstRep;
        
    }

}