src/objects/Compte_rendu_rempli__c.object
<CustomObject>
    <description>Compte rendu VA/VAP rempli suite à la visite d&apos;un animateur chez un PUDO.</description>
    <fields>
        <fullName>Envoi_email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Envoi email</label>
        <type>Checkbox</type>
    </fields>
    <label>Compte rendu de visite</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Nom de compte rendu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comptes rendus de visite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AP03_Task_Test.cls
/*--------------------------------------------------------------------------------------------------------------------------
Author: Fadi Tannoury
Company: Ei-Technologies Lebanon
Description: Test class for AP03_Task
History
2018-06-07  Fadi Tannoury	  Creation
--------------------------------------------------------------------------------------------------------------------------*/

@isTest
public class AP03_Task_Test {

    @isTest
    public static void testEmailSent(){
        
        Account compte = Utils_TestMethods.CreateAccount(null, null, 'compte');
        insert compte;
        
        Compte_rendu_rempli__c CRR = Utils_TestMethods.createCompteRenduRempli(compte.Id, 'Terminé');
        CRR.Envoi_email__c = false;
        insert CRR;
        
        Task email = Utils_TestMethods.createEmailTask(CRR.Id, 'Email');
        
        Test.startTest();
        insert email;
        Test.stopTest();
        
        Compte_rendu_rempli__c CRRUpdated = [SELECT Id, Envoi_email__c
                                             FROM Compte_rendu_rempli__c 
                                             WHERE Id = :CRR.Id
                                             LIMIT 1];
        
        System.assertEquals(true, CRRUpdated.Envoi_email__c);
        
    }
    
}