src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Date_de_debut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_de_fin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nom_du_compte__c</fullName>
        <label>Nom du compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>IF ( Date_de_debut__c &gt;  TODAY() ,$Label.CongeIndispo_A_Venir_2,
IF ( Date_de_fin__c  &lt;   TODAY() ,$Label.Conge_Indispo_Passe_2,$Label.CongeIndispo_En_Cours_2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Batch01_Account.cls
global class Batch01_Account implements Database.Batchable<sObject> {
    
    AP07_Conge_Indispo congeIndispo = null;
    String errorAccountIds = '';
    private Id congeRTypeId = Label.CongeRT_15;
    private Id indispoStandardRTypeId = Label.IndispoStandardRT_15;
    private Id indispoConsigneRTypeId = Label.IndispoConsigneRT_15;
    private Id dispoRTypeId = Label.DispoRT_15;
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = ' Select Date_de_debut__c, Date_de_fin__c, Statut__c ,Nom_du_compte__c, RecordTypeId From Conge_Indispo__c  ' + 
            		   ' WHERE Statut__c = \'' + Label.CongeIndispo_En_Cours + '\' OR Statut__c = \'' + Label.CongeIndispo_A_Venir + '\'' +
            		   ' OR (Statut__c = \'' + Label.Conge_Indispo_Passe + '\' )' ; 
	    return Database.getQueryLocator(query);    
    }
    
    global void execute(Database.BatchableContext BC , List<sObject> scope) {
        congeIndispo = new AP07_Conge_Indispo(); 
    	congeIndispo.updateAccountCongesIndispo(scope , null , true); 
    }
    
    global void finish(Database.BatchableContext BC){ 
       
    } 
}