src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Date_de_debut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>IF ( Date_de_debut__c &gt;  TODAY() ,$Label.CongeIndispo_A_Venir_2,
IF ( Date_de_fin__c  &lt;   TODAY() ,$Label.Conge_Indispo_Passe_2,$Label.CongeIndispo_En_Cours_2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_d_indisponibilite__c</fullName>
        <description>Ne pas activer l&apos;option &quot;Restreindre la liste sélectionnée aux valeurs définies dans l’ensemble de valeurs.	&quot; pour ne pas bloquer le PB qui crée automatiquement les indispos suite à des créations d&apos;anomalies.</description>
        <label>Type d&apos;indisponibilité</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>Planifiée</fullName>
                </value>
                <value>
                    <fullName>Imprévue</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AP03_Conge_Indispo.cls
public class AP03_Conge_Indispo {
    
    Id congeRTypeId = Label.CongeRT_15;
    Id indispoStandardRTypeId = Label.IndispoStandardRT_15;
    Id indispoConsigneRTypeId = Label.IndispoConsigneRT_15;
    Id dispoRTypeId = Label.DispoRT_15;
    
    // vérifie si le congé est en cours, si c'est le cas sa suppression est impossible
    public void datesEnCours(List<Conge_Indispo__c> congesToDelete){
        //congeIndispo.Statut__c.equals(Label.CongeIndispo_En_Cours
        for(Conge_Indispo__c c : congesToDelete){  
            //if(c.Date_de_debut__c <= Date.today() && c.Type_d_indisponibilite__c != Label.pas_de_PDA_assos ){
                if(c.Date_de_debut__c <= Date.today() ){
                    if(c.Statut__c.equalsIgnoreCase(Label.CongeIndispo_En_Cours)) {
                        c.addError( Label.Suppression_date_en_cours);
                    } else if(c.Statut__c.equalsIgnoreCase(Label.Conge_Indispo_Passe)){
                        c.addError( Label.supp_cong_date_passe);
                    }
                }
            }
        }   
    }