src/objects/Service__c.object
<CustomObject>
    <description>Un ensemble de prestations standards proposés aux destinataires par un relais.</description>
    <fields>
        <fullName>Nom_du_service_translated__c</fullName>
        <label>Nom du service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_SER</valueSetName>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Nom du Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Associe__c.object
<CustomObject>
    <description>Ensemble de services proposés par le Pudo selon le macro-profil affecté. Des services seront pilotables par l’action d’activation ou de désactivation.</description>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nom_du_service_traduit__c</fullName>
        <label>Nom du service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_SER</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Points relais pouvant activer le service</relationshipLabel>
        <relationshipName>Services_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service associé</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Numéro du Service associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_SER.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Chronofresh</fullName>
    </customValue>
    <customValue>
        <fullName>Contre remboursement</fullName>
        <label>Contre-remboursement</label>
    </customValue>
    <customValue>
        <fullName>Contre remboursement_CASH</fullName>
        <label>Contre-remboursement CASH</label>
    </customValue>
    <customValue>
        <fullName>Contre remboursement_CB</fullName>
        <label>Contre-remboursement CB</label>
    </customValue>
    <customValue>
        <fullName>CtoC en sacoches bleues scellées</fullName>
    </customValue>
    <customValue>
        <fullName>Dépôt en sacoche bleue</fullName>
    </customValue>
    <customValue>
        <fullName>Dépôt express</fullName>
    </customValue>
    <customValue>
        <fullName>Dépôt payant</fullName>
    </customValue>
    <customValue>
        <fullName>Dépôt simple</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Parcel Label</fullName>
    </customValue>
    <customValue>
        <fullName>Instance</fullName>
    </customValue>
    <customValue>
        <fullName>LA POSTE RELAIS (LPR)</fullName>
    </customValue>
    <customValue>
        <fullName>PickupPassCAB2D</fullName>
        <label>PickupPass CAB2D</label>
    </customValue>
    <customValue>
        <fullName>Printer activation</fullName>
    </customValue>
    <customValue>
        <fullName>Redirection</fullName>
    </customValue>
    <customValue>
        <fullName>Relivraison STUART</fullName>
    </customValue>
    <customValue>
        <fullName>Retour</fullName>
    </customValue>
    <customValue>
        <fullName>Retrait</fullName>
    </customValue>
    <customValue>
        <fullName>Retrait de colis prepares</fullName>
        <label>Retrait de colis préparé</label>
    </customValue>
    <customValue>
        <fullName>Reverse swap desyncho en sacoches grises scellées</fullName>
        <label>Reverse swap desynchro en sacoches grises scellées</label>
    </customValue>
    <customValue>
        <fullName>ROD</fullName>
    </customValue>
    <customValue>
        <fullName>Shopident</fullName>
        <label>Shop Ident</label>
    </customValue>
    <customValue>
        <fullName>Swap Colis avec contrôle de contenu</fullName>
    </customValue>
    <customValue>
        <fullName>Swap Colis contre colis</fullName>
    </customValue>
    <customValue>
        <fullName>Transporteur multiple - DPD FR</fullName>
    </customValue>
    <customValue>
        <fullName>CARTE_FIDELITE</fullName>
        <label>Carte fidélité</label>
    </customValue>
    <description>Cette valeur de liste globale contient tous les services de la plate-forme Pickup.</description>
    <masterLabel>LOV_GLO_SER</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AP01_ServiceAssocie.cls
/*
* The aim of this class is to modify the field ServiceNameTranslation in the related service
* @author: Christine Bayssary
* @date: 30/08/2018
* @Test: AP01_ServiceAssocie_Test
*/
public class AP01_ServiceAssocie {
    
    public static boolean isRunning = true;
    
    public static void fillNomService(list<Service_Associe__c> listServiceAssocie){
        
        list<id> listServiceIds = new list<id>();
        for(Service_Associe__c s : listServiceAssocie){
            listServiceIds.add(s.Service__c);}
        
        map<id,service__c> mpServices  = new map<id, service__c>([select id, name, Nom_du_service_translated__c 
                                                                  from service__c 
                                                                  where id in:listServiceIds]);
        for(Service_Associe__c s : listServiceAssocie){
            if(mpServices.containskey(s.Service__c)){
                s.Nom_du_service_traduit__c = mpServices.get(s.Service__c).Nom_du_service_translated__c;}}        
    } 
    
    public static void fillNomService2(list<Service_Associe__c> listServiceAssocie, map<id,Service_Associe__c> oldMapServiceAssociee){
        list<id> listServiceIds = new list<id>();
        list<Service_Associe__c> listServicesAssocieeUpdated  = new list<Service_Associe__c>();
        for(Service_Associe__c s : listServiceAssocie){
            if(s.Service__c != oldMapServiceAssociee.get(s.id).Service__c){
                listServiceIds.add(s.Service__c);
            }}
        
        map<id,Service__c> mapServices = new map<id,Service__c>([select id,Nom_du_service_translated__c 
                                                                 from service__c 
                                                                 where id in :listServiceIds]);
        
        for(Service_Associe__c s :listServiceAssocie){
            if(mapServices.containsKey(s.Service__c)){
                s.Nom_du_service_traduit__c =  mapServices.get(s.Service__c).Nom_du_service_translated__c;
            }
            
        }
        
    }
    
    public static void updateNomService(list<Service__c> listServices, map<id,Service__c> oldMapService){
        
        list<id> listServiceIds = new list<id>();
        map<id,service__c> mpServices  = new map<id, service__c>();
        for(Service__c s : listServices){
            if(s.Nom_du_service_translated__c != oldMapService.get(s.id).Nom_du_service_translated__c){
                listServiceIds.add(s.id);
                mpServices.put(s.id,s);}}
        
        list<Service_Associe__c> listServiceAssocie  = [select id, name, Nom_du_service_traduit__c,Service__c 
                                                        from Service_Associe__c 
                                                        where service__c in:listServiceIds
                                                        and Modifiable__c = true];
        for(Service_Associe__c s : listServiceAssocie){
            if(mpServices.containskey(s.Service__c)){
                s.Nom_du_service_traduit__c = mpServices.get(s.Service__c).Nom_du_service_translated__c;}}  
        isRunning =  false;
        update listServiceAssocie;
    } 
}