force-app/main/default/objects/Account/fields/Activite_commerciale_principale__c.field-meta.xml
<CustomField>
    <fullName>Activite_commerciale_principale__c</fullName>
    <label>Activité commerciale principale</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ACT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Amplitude_horaire_du_relais__c.field-meta.xml
<CustomField>
    <fullName>Amplitude_horaire_du_relais__c</fullName>
    <label>Amplitude horaire du relais</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_operationnel_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_operationnel_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact opérationnel</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Duree_pause_dejeuner_respectee__c.field-meta.xml
<CustomField>
    <fullName>Duree_pause_dejeuner_respectee__c</fullName>
    <description>Entre lundi et samedi</description>
    <formula>IF( 
AND( 
VALUE(SUBSTITUTE(TEXT( lundi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( lundi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( mardi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( mardi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( mercredi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( mercredi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( jeudi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( jeudi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( vendredi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( vendredi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( samedi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( samedi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )) ), 

IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;) 
)</formula>
    <inlineHelpText>Between Monday and Saturday</inlineHelpText>
    <label>Durée pause déjeuner respectée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Heure_fermeture_minimale_respectee__c.field-meta.xml
<CustomField>
    <fullName>Heure_fermeture_minimale_respectee__c</fullName>
    <formula>IF( 
AND( 
OR( 
VALUE(LEFT( TEXT( Lundi_Fermeture__c ) , 2)) &gt;=  VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c) ), 
VALUE(LEFT( TEXT( Lundi_Fermeture__c ) , 2)) = 00), 

OR( 
VALUE(LEFT( TEXT( Mardi_Fermeture__c ) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT( TEXT( Mardi_Fermeture__c ) , 2)) = 00), 

OR( 
VALUE(LEFT( TEXT(Mercredi_Fermeture__c ) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Mercredi_Fermeture__c ), 2))=00), 


OR( 
VALUE(LEFT( TEXT(Jeudi_Fermeture__c) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Jeudi_Fermeture__c), 2))=00), 

OR( 
VALUE(LEFT( TEXT(Vendredi_Fermeture__c) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Vendredi_Fermeture__c), 2))=00), 

OR( 
VALUE(LEFT( TEXT(Samedi_Fermeture__c) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Samedi_Fermeture__c), 2))=00)), 


IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Heure fermeture minimale respectée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Heure_ouverture_matinee__c.field-meta.xml
<CustomField>
    <fullName>Heure_ouverture_matinee__c</fullName>
    <formula>IF( 
AND( 
 
VALUE(LEFT(TEXT(Lundi_Ouverture__c), 2))&lt;12, 
VALUE(LEFT(TEXT(Mardi_Ouverture__c), 2))&lt;12, 
VALUE(LEFT(TEXT(Mercredi_Ouverture__c), 2))&lt;12, 
VALUE(LEFT(TEXT(Jeudi_Ouverture__c), 2))&lt;12, 
VALUE(LEFT(TEXT(Vendredi_Ouverture__c), 2))&lt;12, 
VALUE(LEFT(TEXT(Samedi_Ouverture__c), 2))&lt;12), 
IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Heure ouverture matinée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Heure_ouverture_minimale_respect_e__c.field-meta.xml
<CustomField>
    <fullName>Heure_ouverture_minimale_respect_e__c</fullName>
    <formula>IF( 
AND( 
OR( 
AND( 
VALUE(LEFT( TEXT(Lundi_Ouverture__c) , 2))&gt;=05, 
VALUE(LEFT(TEXT(Lundi_Ouverture__c), 2))&lt;= VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c )))), 



VALUE(LEFT( TEXT(Mardi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Mardi_Ouverture__c), 2))&lt;=VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c )), 
VALUE(LEFT( TEXT( Mercredi_Ouverture__c ) , 2))&gt;=05 , VALUE(LEFT(TEXT(Mercredi_Ouverture__c), 2))&lt;=10, 
VALUE(LEFT( TEXT(Jeudi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Jeudi_Ouverture__c), 2))&lt;=VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c )), 
VALUE(LEFT( TEXT(Vendredi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Vendredi_Ouverture__c), 2))&lt;=10, 
VALUE(LEFT( TEXT(Samedi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Samedi_Ouverture__c), 2))&lt;=VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c ))), 


IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Heure ouverture minimale respectée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seuil_de_l_amplitude_horaire_respect__c.field-meta.xml
<CustomField>
    <fullName>Seuil_de_l_amplitude_horaire_respect__c</fullName>
    <formula>IF( Amplitude_horaire_du_relais__c &gt;= Value(Text(Seuil_de_l_amplitude_horaire_en_h_c__c)),IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;),IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <label>Seuil de l&#39;amplitude horaire respecté</label>
    <type>Text</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Requete_ContratNonRespecte__c</fullName>
        <label>ID_Requete_ContratNonRespecte</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Object_de_la_requete__c</fullName>
        <label>Objet de la requête</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anomalie de synchronisation d’un relais</fullName>
                    <label>Anomalie de synchronisation d&apos;un relais</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Sinistre / Travaux / Santé</fullName>
                    <label>Indisponibilité - Problème opérationnel Sinistre / Travaux / Santé</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Qualité de Service</fullName>
                    <label>Indisponibilité - Problème opérationnel Qualité de Service</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Panne PDA</fullName>
                    <label>Indisponibilité - Problème PDA / Panne PDA</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Problème de synchronisation</fullName>
                    <label>Indisponibilité - Problème PDA / Problème de synchronisation</label>
                </value>
                <value>
                    <fullName>Indisponibilité problème opérationnel - Injoignabilité</fullName>
                </value>
                <value>
                    <fullName>Démarrage d&apos;activité</fullName>
                </value>
                <value>
                    <fullName>Relais sans formation avec moyens de scans associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif avec plusieurs moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Les relais actifs avec terme contrat non respecté</fullName>
                </value>
                <value>
                    <fullName>Les Congés du relais</fullName>
                </value>
                <value>
                    <fullName>Relais inactif avec moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif sans moyen de scan associé</fullName>
                </value>
                <value>
                    <fullName>Les horaires insuffisants du relais</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Anomalie colis</fullName>
                    <isActive>false</isActive>
                    <label>Indisponibilité Problème opérationnel Anomalie colis</label>
                </value>
                <value>
                    <fullName>Relais actif sans formation avec moyen de scan associé</fullName>
                    <isActive>false</isActive>
                    <label>Relais actif sans formation avec moyen de scan associé</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ACT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>1861</fullName>
    </customValue>
    <customValue>
        <fullName>1862</fullName>
    </customValue>
    <customValue>
        <fullName>1863</fullName>
    </customValue>
    <customValue>
        <fullName>1864</fullName>
    </customValue>
    <customValue>
        <fullName>1865</fullName>
    </customValue>
    <customValue>
        <fullName>1866</fullName>
    </customValue>
    <customValue>
        <fullName>1867</fullName>
    </customValue>
    <customValue>
        <fullName>1868</fullName>
    </customValue>
    <customValue>
        <fullName>1869</fullName>
    </customValue>
    <customValue>
        <fullName>1870</fullName>
    </customValue>
    <customValue>
        <fullName>1871</fullName>
    </customValue>
    <customValue>
        <fullName>1872</fullName>
    </customValue>
    <customValue>
        <fullName>1873</fullName>
    </customValue>
    <customValue>
        <fullName>1874</fullName>
    </customValue>
    <customValue>
        <fullName>1875</fullName>
    </customValue>
    <customValue>
        <fullName>1876</fullName>
    </customValue>
    <customValue>
        <fullName>1877</fullName>
    </customValue>
    <customValue>
        <fullName>1878</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>2167</fullName>
    </customValue>
    <customValue>
        <fullName>2168</fullName>
    </customValue>
    <customValue>
        <fullName>2169</fullName>
    </customValue>
    <customValue>
        <fullName>2170</fullName>
    </customValue>
    <customValue>
        <fullName>2171</fullName>
    </customValue>
    <customValue>
        <fullName>2172</fullName>
    </customValue>
    <customValue>
        <fullName>2173</fullName>
    </customValue>
    <customValue>
        <fullName>2174</fullName>
    </customValue>
    <customValue>
        <fullName>2175</fullName>
    </customValue>
    <description>Activité commerciale principale</description>
    <masterLabel>LOV_GLO_ACT</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_ETA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP06_Account.cls
/*
* The aim of this class is to create/close case if the criteria of the contract is not respected
* @author: Christine Bayssary
* @date: 02/05/2018
* @Test: AP06_Account_Test
*/
public class AP06_Account {
    
    /*--------------------------------------------------------------------------------------------------------------------------
      Author: Christine Bayssary
      Company: EI-technologies
      Description: Close case if the conditions of the contract are met
      Creation of case if the conditions of the contract are not met
      Inputs: list of modified accounts & map of the old values of the account
      Returns: -
    --------------------------------------------------------------------------------------------------------------------------*/
    public static void createCaseUpdate(list<account> listAccounts,map<id,account> mapOldAccount){
        Set<ID> casesRecordTypeIDs = new Set<Id>();
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id, MasterLabel, ID_Requete_ContratNonRespecte__c 
                                                                            FROM Association_Record_Type_et_pays__mdt];
        system.debug('AP06_Account associationRTPays ' + associationRTPays);
        Map<String,Association_Record_Type_et_pays__mdt> mapassociationRTPays =  new Map<String,Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord: associationRTPays)
        {
            mapassociationRTPays.put(mdtRecord.MasterLabel, mdtRecord);
            if (mdtRecord.ID_Requete_ContratNonRespecte__c  != null)
            {                
                casesRecordTypeIDs.add(mdtRecord.ID_Requete_ContratNonRespecte__c );
            }
        }
        system.debug('AP06_Account casesRecordTypeIDs ' + casesRecordTypeIDs);
        list<id> listAccountIds = new list<id>();
        for(account acc : listAccounts){
            listAccountIds.add(acc.id);   
        }
        system.debug('AP06_Account listAccountIds ' + listAccountIds);
        list<case> listRequetCreation = new list<case>();
        map<id,account> mapCase = new map<id,account>([select id,name,(select id,subject,status  
                                                                       from cases
                                                                       where status <> :label.Requete_Terminee//= :label.Requette_En_attente_de_traitement
                                                                       /*and (Subject= :label.Requete_ObjetContratNonRespecte
                                                                            OR Subject = :label.Requete_HoraireInsuffisantsDuRelais)*/
                                                                       and recordtypeId in:casesRecordTypeIDs)
                                                       from account 
                                                       where id in:listAccountIds]);
        system.debug('AP06_Account mapCase ' + mapCase);
        system.debug('AP06_Account listAccounts ' + listAccounts);
        for(account account: listAccounts){
        system.debug('AP06_Account mapCase.get(account.id).cases.size() ' + mapCase.get(account.id).cases.size());
            if(account.ShippingCountry !='' && account.ShippingCountry != null){
                system.debug('AP06_Account 0');
                //BNL+Hungary
                if((account.Seuil_de_l_amplitude_horaire_respect__c .contains('Red') 
                    || account.Heure_fermeture_minimale_respectee__c .contains('Red') 
                    || account.Heure_ouverture_minimale_respect_e__c .contains('Red') 
                    || account.Duree_pause_dejeuner_respectee__c .contains('Red')
                    || (label.Pudo_ActiviteCommerciale.contains(';'+account.Activite_commerciale_principale__c+';')))
                   && mapCase.get(account.id).cases.size()==0
                   && (account.etat__c == '4' || account.etat__c == '5' || account.etat__c=='6')
                   && account.ShippingCountry != 'France'){
                       system.debug('AP06_Account 1');
                       case requete = new case();
                       requete.Subject=label.Requete_ObjetContratNonRespecte;
                       requete.Status = label.Requette_En_attente_de_traitement;
                       Association_Record_Type_et_pays__mdt temp_Association_R = mapassociationRTPays.get(account.ShippingCountry);
                       requete.RecordTypeId = temp_Association_R.ID_Requete_ContratNonRespecte__c;
                       requete.AccountId = account.id;
                       requete.ContactId = account.Contact_operationnel_1__c;
                       requete.Object_de_la_requete__c = 'Les relais actifs avec terme contrat non respecté';
                       listRequetCreation.add(requete);
                   }
                //France
                else if(mapCase.get(account.id).cases.size()==0
                        && (account.etat__c == '4' || account.etat__c == '5')
                        &&(account.Amplitude_horaire_du_relais__c < 35
                          /* || account.Heure_fermeture_minimale_respectee__c .contains('Red') 
                           || account.Heure_ouverture_minimale_respect_e__c .contains('Red') 
                           || account.Duree_pause_dejeuner_respectee__c .contains('Red')
                           || account.Heure_ouverture_matinee__c.contains('Red')*/)
                        && account.ShippingCountry == 'France'
                        && account.Type == '2'){
                            system.debug('AP06_Account 2');
                            case requete = new case();
                            requete.Subject= Label.Requete_HoraireInsuffisantsDuRelais;
                            requete.Status = '0';
                            Association_Record_Type_et_pays__mdt temp_Association_R = mapassociationRTPays.get(account.ShippingCountry);
                            requete.RecordTypeId = temp_Association_R.ID_Requete_ContratNonRespecte__c;
                            requete.AccountId = account.id;
                            requete.ContactId = account.Contact_operationnel_1__c;
                            requete.Object_de_la_requete__c = 'Les horaires insuffisants du relais';
                            requete.OwnerId = label.FileGestionContractuelle;
                            listRequetCreation.add(requete);
                            system.debug('AP06_Account listRequetCreation ' + listRequetCreation);
                        }
                else  if(account.Seuil_de_l_amplitude_horaire_respect__c .contains('Green')
                         && account.Heure_fermeture_minimale_respectee__c .contains('Green')
                         && account.Heure_ouverture_minimale_respect_e__c .contains('Green')
                         && account.Duree_pause_dejeuner_respectee__c .contains('Green')
                         && !label.Pudo_ActiviteCommerciale.contains(';'+account.Activite_commerciale_principale__c+';')
                         && account.ShippingCountry == 'France'
                         && mapCase.get(account.id).cases.size()>0)
                {
                    system.debug('AP06_Account 3');
                    list<case> listCases = mapCase.get(account.id).cases;
                    for(case requete : listCases){
                        requete.Status = label.Requete_Terminee;  
                        listRequetCreation.add(requete);
                    }      
                }
                else  if(account.Seuil_de_l_amplitude_horaire_respect__c .contains('Green')
                         && account.Heure_fermeture_minimale_respectee__c .contains('Green')
                         && account.Heure_ouverture_minimale_respect_e__c .contains('Green')
                         && account.Duree_pause_dejeuner_respectee__c .contains('Green')
                         && account.Heure_ouverture_matinee__c.contains('Green')
                         && account.ShippingCountry != 'France'
                         && mapCase.get(account.id).cases.size()>0)
                {
                    system.debug('AP06_Account 4');
                    list<case> listCases = mapCase.get(account.id).cases;
                    for(case requete : listCases){
                        requete.Status = label.Requete_Terminee;  
                        listRequetCreation.add(requete);
                    }      
                }
            }
            else if(account.ShippingCountry =='' || account.ShippingCountry == null)
            {
                account.addError(Label.Message_No_Shipping_Country);
            }}
        upsert listRequetCreation;
        system.debug('AP06_Account listRequetCreation ' + listRequetCreation);
    }
}