force-app/main/default/objects/Account/fields/Activite_commerciale_principale__c.field-meta.xml
<CustomField>
    <fullName>Activite_commerciale_principale__c</fullName>
    <label>Activité commerciale principale</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ACT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Langue_Principale_de_l_adresse__c.field-meta.xml
<CustomField>
    <fullName>Langue_Principale_de_l_adresse__c</fullName>
    <label>Langue Principale de l&#39;adresse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_LAN</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <label>Partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_PAR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_internationale__c.field-meta.xml
<CustomField>
    <fullName>Reference_internationale__c</fullName>
    <externalId>true</externalId>
    <label>Référence internationale</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Reseau_Concurrent__c.field-meta.xml
<CustomField>
    <fullName>Reseau_Concurrent__c</fullName>
    <label>Réseau Concurrent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aucun</fullName>
            </value>
            <value>
                <fullName>Kiala</fullName>
            </value>
            <value>
                <fullName>Mondial Relay</fullName>
            </value>
            <value>
                <fullName>Relais Colis</fullName>
            </value>
            <value>
                <fullName>Relais Poste</fullName>
            </value>
            <value>
                <fullName>UPS Acces Point</fullName>
            </value>
            <value>
                <fullName>Kariboo</fullName>
            </value>
            <value>
                <fullName>Bpost</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>GLS</fullName>
            </value>
            <value>
                <fullName>MPL</fullName>
            </value>
            <value>
                <fullName>Expressone</fullName>
            </value>
            <value>
                <fullName>PickPost (La Poste)</fullName>
            </value>
            <value>
                <fullName>Geis</fullName>
            </value>
            <value>
                <fullName>Intime</fullName>
            </value>
            <value>
                <fullName>Czech Post</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_CountryCode__c.field-meta.xml
<CustomField>
    <fullName>Tech_CountryCode__c</fullName>
    <label>Tech CountryCode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>LI</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Type_de_point__c</fullName>
        <formula>Text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type de point</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CountriesSequence__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CountriesSequence</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Activite_commerciale_principale__c</fullName>
        <label>Activité commerciale principale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_ACT</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>58</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Liechtenstein</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Langue_Principale_de_l_adresse__c</fullName>
        <label>Langue Principale de l&apos;adresse</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_LAN</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partenaire__c</fullName>
        <label>Partenaire</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_de_point__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_PAR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reseau_Concurrent__c</fullName>
        <label>Réseau concurrent</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Kiala</fullName>
                </value>
                <value>
                    <fullName>Mondial Relay</fullName>
                </value>
                <value>
                    <fullName>Relais Colis</fullName>
                </value>
                <value>
                    <fullName>Relais Poste</fullName>
                </value>
                <value>
                    <fullName>UPS Acces Point</fullName>
                </value>
                <value>
                    <fullName>Kariboo</fullName>
                </value>
                <value>
                    <fullName>Bpost</fullName>
                </value>
                <value>
                    <fullName>DHL</fullName>
                </value>
                <value>
                    <fullName>GLS</fullName>
                </value>
                <value>
                    <fullName>MPL</fullName>
                </value>
                <value>
                    <fullName>Expressone</fullName>
                </value>
                <value>
                    <fullName>PickPost (La Poste)</fullName>
                </value>
                <value>
                    <fullName>Geis</fullName>
                </value>
                <value>
                    <fullName>Intime</fullName>
                </value>
                <value>
                    <fullName>Czech Post</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Antwerp</fullName>
                </value>
                <value>
                    <fullName>Walloon Brabant</fullName>
                </value>
                <value>
                    <fullName>Hainaut</fullName>
                </value>
                <value>
                    <fullName>Liège</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Namur</fullName>
                </value>
                <value>
                    <fullName>East Flanders</fullName>
                </value>
                <value>
                    <fullName>Flemish Brabant</fullName>
                </value>
                <value>
                    <fullName>West Flanders</fullName>
                </value>
                <value>
                    <fullName>Drenthe</fullName>
                </value>
                <value>
                    <fullName>Flevoland</fullName>
                </value>
                <value>
                    <fullName>Friesland</fullName>
                </value>
                <value>
                    <fullName>Gelderland</fullName>
                </value>
                <value>
                    <fullName>Groningen</fullName>
                </value>
                <value>
                    <fullName>Noord-Brabant</fullName>
                </value>
                <value>
                    <fullName>Noord-Holland</fullName>
                </value>
                <value>
                    <fullName>Overijssel</fullName>
                </value>
                <value>
                    <fullName>Utrecht</fullName>
                </value>
                <value>
                    <fullName>Zuid-Holland</fullName>
                </value>
                <value>
                    <fullName>Limburg</fullName>
                </value>
                <value>
                    <fullName>Lux</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>Zeeland</fullName>
                </value>
                <value>
                    <fullName>Aargau</fullName>
                </value>
                <value>
                    <fullName>Appenzell Innerrhoden</fullName>
                </value>
                <value>
                    <fullName>Appenzell Ausserrhoden</fullName>
                </value>
                <value>
                    <fullName>Bern</fullName>
                </value>
                <value>
                    <fullName>Basel-Landschaft</fullName>
                </value>
                <value>
                    <fullName>Basel-Stadt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tech_CountryCode__c</fullName>
        <label>Tech CountryCode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>LU</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>HU</fullName>
                </value>
                <value>
                    <fullName>CH</fullName>
                </value>
                <value>
                    <fullName>CZ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tech_Operateur__c</fullName>
        <description>Ce champ est utilisé pour le partage des propsects au sein d&apos;un même opérateur.</description>
        <label>Tech_Operateur</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_OPE</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_de_point__c</fullName>
        <label>Type de point</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_TYP</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassWorkflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ACT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>1861</fullName>
    </customValue>
    <customValue>
        <fullName>1862</fullName>
    </customValue>
    <customValue>
        <fullName>1863</fullName>
    </customValue>
    <customValue>
        <fullName>1864</fullName>
    </customValue>
    <customValue>
        <fullName>1865</fullName>
    </customValue>
    <customValue>
        <fullName>1866</fullName>
    </customValue>
    <customValue>
        <fullName>1867</fullName>
    </customValue>
    <customValue>
        <fullName>1868</fullName>
    </customValue>
    <customValue>
        <fullName>1869</fullName>
    </customValue>
    <customValue>
        <fullName>1870</fullName>
    </customValue>
    <customValue>
        <fullName>1871</fullName>
    </customValue>
    <customValue>
        <fullName>1872</fullName>
    </customValue>
    <customValue>
        <fullName>1873</fullName>
    </customValue>
    <customValue>
        <fullName>1874</fullName>
    </customValue>
    <customValue>
        <fullName>1875</fullName>
    </customValue>
    <customValue>
        <fullName>1876</fullName>
    </customValue>
    <customValue>
        <fullName>1877</fullName>
    </customValue>
    <customValue>
        <fullName>1878</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>2167</fullName>
    </customValue>
    <customValue>
        <fullName>2168</fullName>
    </customValue>
    <customValue>
        <fullName>2169</fullName>
    </customValue>
    <customValue>
        <fullName>2170</fullName>
    </customValue>
    <customValue>
        <fullName>2171</fullName>
    </customValue>
    <customValue>
        <fullName>2172</fullName>
    </customValue>
    <customValue>
        <fullName>2173</fullName>
    </customValue>
    <customValue>
        <fullName>2174</fullName>
    </customValue>
    <customValue>
        <fullName>2175</fullName>
    </customValue>
    <description>Activité commerciale principale</description>
    <masterLabel>LOV_GLO_ACT</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_LAN.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Français</fullName>
    </customValue>
    <customValue>
        <fullName>Anglais</fullName>
    </customValue>
    <customValue>
        <fullName>Espagnol</fullName>
    </customValue>
    <customValue>
        <fullName>Hollandais</fullName>
    </customValue>
    <customValue>
        <fullName>Allemand</fullName>
    </customValue>
    <customValue>
        <fullName>Hongrois</fullName>
    </customValue>
    <customValue>
        <fullName>Italien</fullName>
    </customValue>
    <customValue>
        <fullName>Tchèque</fullName>
    </customValue>
    <description>Liste des langues</description>
    <masterLabel>LOV_GLO_LAN</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_PAR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <customValue>
        <fullName>124</fullName>
    </customValue>
    <customValue>
        <fullName>125</fullName>
    </customValue>
    <customValue>
        <fullName>126</fullName>
    </customValue>
    <customValue>
        <fullName>134</fullName>
    </customValue>
    <customValue>
        <fullName>135</fullName>
    </customValue>
    <customValue>
        <fullName>140</fullName>
    </customValue>
    <customValue>
        <fullName>146</fullName>
    </customValue>
    <customValue>
        <fullName>177</fullName>
    </customValue>
    <customValue>
        <fullName>178</fullName>
    </customValue>
    <customValue>
        <fullName>179</fullName>
    </customValue>
    <customValue>
        <fullName>180</fullName>
    </customValue>
    <customValue>
        <fullName>181</fullName>
    </customValue>
    <customValue>
        <fullName>182</fullName>
    </customValue>
    <customValue>
        <fullName>183</fullName>
    </customValue>
    <customValue>
        <fullName>184</fullName>
    </customValue>
    <customValue>
        <fullName>185</fullName>
    </customValue>
    <customValue>
        <fullName>188</fullName>
    </customValue>
    <customValue>
        <fullName>189</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>190</fullName>
    </customValue>
    <customValue>
        <fullName>194</fullName>
    </customValue>
    <customValue>
        <fullName>195</fullName>
    </customValue>
    <customValue>
        <fullName>-2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>211</fullName>
    </customValue>
    <description>Liste des partenaires</description>
    <masterLabel>LOV_GLO_PAR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_TYP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>-3</fullName>
    </customValue>
    <customValue>
        <fullName>Pudo non suivi par le CO</fullName>
        <isActive>false</isActive>
        <label>Pudo non suivi par le CO</label>
    </customValue>
    <customValue>
        <fullName>Agences Coliposte</fullName>
        <isActive>false</isActive>
        <label>Agences Coliposte</label>
    </customValue>
    <customValue>
        <fullName>Bureaux de Postes</fullName>
        <isActive>false</isActive>
        <label>Bureaux de Postes</label>
    </customValue>
    <customValue>
        <fullName>Cytissimo</fullName>
        <isActive>false</isActive>
        <label>Cytissimo</label>
    </customValue>
    <customValue>
        <fullName>Centre Distribution Coliposte</fullName>
        <isActive>false</isActive>
        <label>Centre Distribution Coliposte</label>
    </customValue>
    <description>Type de point utilisé sur réseau et Prospect. Doit correspondre au champ standard type (Compte).</description>
    <masterLabel>LOV_GLO_TYP</masterLabel>
</GlobalValueSet>

src/classes/VFC02_LeadConversionController.cls
public class VFC02_LeadConversionController 
{
    private ApexPages.StandardController controller; 
    private Id recordId;
    public boolean showLink {get;set;}
    public String errorMessage {get;set;}
    public String waitingMessage {get;set;}
    private Lead lead = null;
    
    public VFC02_LeadConversionController(ApexPages.StandardController stdController) {

        //this link should be visible only if an error occured
        //redirectleto the ad page
        this.showLink = false;
        this.controller = stdController; 
        lead = (lead) this.controller.getRecord();
        recordId = this.controller.getRecord().Id; 
    }
    
    /*
* Check if Lead already converted 
* Case of lead opened in two tabs at the same time
*/
    private boolean checkIfLeadAlreadyConverted() {
        return [SELECT Id, IsConverted 
                FROM LEAD 
                WHERE ID = : recordId
               ].IsConverted; 
    }
    
    public PageReference convertLeadAndRedirectToAccount() {
        User currentUser = [Select id , name , BypassProcessBuilder__c, BypassValidationRule__c, BypassWorkflow__c
                            from User
                            where id =: UserInfo.getUserId()];
        currentUser.BypassValidationRule__c = true;
        update currentUser;
        Lead lead = [SELECT Id , Partenaire__c , Address, RecordTypeId, Country,Reseau_Concurrent__c , Type_de_point__c, 
                     Activite_commerciale_principale__c, Industry, LeadSource, Langue_Principale_de_l_adresse__c,Tech_Operateur__c,
                     Email, Country__c, city__c, Street__c, State_Province__c,Postal_Code__c, Tech_CountryCode__c
                     FROM Lead 
                     Where Id =: recordId];
        string reseauConcurrent = lead.Reseau_Concurrent__c;
        string activiteCommercialePrincipale = lead.Activite_commerciale_principale__c;
        string partenaire = lead.Partenaire__c;
        string typeDePoint = lead.Type_de_point__c;
        String industry = lead.Industry;
        String languePrincipale =lead.Langue_Principale_de_l_adresse__c; 
        String operateur = lead.Tech_Operateur__c ;
        String Country = lead.Country__c;
        String CountryCode = lead.Tech_CountryCode__c;
		String StateProvince = lead.State_Province__c;
        system.debug('Country '+Country);
        system.debug('CountryCode '+CountryCode);
        system.debug('StateProvince '+StateProvince);
        PageReference acctPage = null;
        try {
            
            boolean isConverted = checkIfLeadAlreadyConverted();
            system.debug('isConverted'+ isConverted);
            // map added to put values of the picklists of the lead
            if(!isConverted) {
                
                lead.Reseau_Concurrent__c= '';  
                lead.Activite_commerciale_principale__c = '';
                lead.Type_de_point__c = '';
                lead.Partenaire__c = '';
                lead.Industry = '';
                lead.Langue_Principale_de_l_adresse__c = '';
                lead.Tech_Operateur__c = '';
                update lead;
                lead = [SELECT Id , Partenaire__c , Address, RecordTypeId, Country, Type_de_point__c,
                        Activite_commerciale_principale__c,Industry, email, Street__c, City__c, Postal_Code__c
                        FROM Lead 
                        Where Id =: recordId];
                system.debug('lead.Address '+lead.Address);
                String leadCountry = Country;
                leadCountry = leadCountry.substring(0, 1).toUpperCase() + leadCountry.substring(1).toLowerCase();
                CountriesSequence__c countryInstance = CountriesSequence__c.getInstance(leadCountry); 
                System.debug('!!!!! I am here countryInstance !!!!' + countryInstance);
                if(countryInstance != null) {
                    List<Account> listAccounts = [SELECT Id 
                                                  FROM Account
                                                  Where Reference_internationale__c =: countryInstance.Sequence__c 
                                                 ];
                    System.debug('!!!!! I am here 1 !!!!');
                    if(listAccounts.size() > 0) {
                        String error = Label.LeadConversionErrorMessage + ' (' + Label.Duplicate_Reference + ')'; 
                        ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR,error));
                        showLink = true;
                    } else {
                        waitingMessage = 'Converting';
                        System.debug('!!!!! I am here 2 !!!!');
                        //create instance from leadConvert
                        Database.LeadConvert lc = new Database.LeadConvert();
                        lc.setLeadId(recordId);
                        System.debug('!!!!! I am here 3 !!!!');
                        LeadStatus convertStatus = [SELECT Id, MasterLabel
                                                    FROM LeadStatus 
                                                    WHERE IsConverted = true LIMIT 1];
                        System.debug('!!!!! I am here convertStatus !!!!' + convertStatus);
                        lc.setConvertedStatus(convertStatus.MasterLabel);
                        //conversion should only include new account and contact.
                        lc.setDoNotCreateOpportunity(true);
                        System.debug('!!!!! I am here 4 !!!!');
                        system.debug('lc '+lc);
                        //convert the lead using LeadConvert instance
                        Database.LeadConvertResult lcr = Database.convertLead(lc);
                        System.assert(lcr.isSuccess());
                        system.debug('RT_Prospect_INTER '+Label.RT_Prospect_INTER);
                        system.debug('lead.RecordTypeId '+lead.RecordTypeId);
                        
                        System.debug('!!!!! I am here 5 !!!!');
                        //redirect to the new account view page
                        //waitingMessage = 'Waiting';
                        Id newAccountId = lcr.getAccountId(); 
                        if(label.RT_Prospect_France.contains(lead.RecordTypeId)){
                            Map<String, Association_Record_Type_et_pays__mdt> associationRTPaysMap = new Map<String, Association_Record_Type_et_pays__mdt>();
                            List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_Converti__c
                                                                                             FROM Association_Record_Type_et_pays__mdt]; 
                            
                            for(Association_Record_Type_et_pays__mdt assRTPays : associationRTPays){
                                associationRTPaysMap.put(assRTPays.MasterLabel, assRTPays);
                            }
                            if(associationRTPaysMap.containskey(lead.Country)){
                                System.debug('lead.Country' + lead.Country ); 
                                Account acct = new Account (Id = newAccountId, 
                                                            Type = typeDePoint, 
                                                            RecordTypeId = associationRTPaysMap.get(lead.Country).ID_Prospect_Converti__c, 
                                                            etat__c = '0', 
                                                            mode__c = 'En attente de signature',
                                                            //JMB
                                                            Activite_commerciale_principale__c = activiteCommercialePrincipale,
                                                            Reseau_Concurrent__c = reseauConcurrent,
                                                            Partenaire__c = partenaire,
                                                            Industry = industry,
                                                            Langue_Principale_de_l_adresse__c = languePrincipale,
                                                            Operateur_Global__c = Operateur,
                                                            Langue_secondaire_de_l_adresse__c =null,
                                                            Email_du_magasin__c = lead.Email,
                                                            
                                                            //Tech_CountryCode__c = Countrycode,
                                                            shipping_Country__c = Country,
                                                            shipping_street__c = lead.Street__c,
                                                            Shipping_City__c = lead.City__c,
                                                            Shipping_Zip_Postal_Code__c = lead.Postal_Code__c,
                                                            Shipping_State_Province__c = StateProvince,
                                                            billing_Country__c = Country,
                                                            billing_street__c = lead.Street__c,
                                                            billing_City__c = lead.City__c,
                                                            billing_Zip_Postal_Code__c = lead.Postal_Code__c,
                                                            billing_State_Province__c = StateProvince
                                                            //JMB
                                                           );
                                
                                if(typeDePoint == '-3'){
                                  acct.RecordTypeId = label.RT_ProspectConvertiPickupContact_Compte;
                                  acct.Version_de_contrat__c = 'V1116';
                                  acct.Grille_tarifaire__c = 'GTCONTACT';
                                  acct.Macroprofil_actuel__c=Label.Macroprofil_MP2; 
                                  acct.Macroprofil_de_reference__c = Label.Macroprofil_MP2;
                                }
                                update acct;
                            }
                        }
                        lead.Activite_commerciale_principale__c = activiteCommercialePrincipale;
                        lead.Reseau_Concurrent__c = reseauConcurrent;
                        lead.Type_de_point__c = typeDePoint;
                        lead.Partenaire__c = partenaire;
                        lead.Industry = industry;
                        lead.Langue_Principale_de_l_adresse__c = languePrincipale;
                        lead.Tech_Operateur__c = operateur;
                        update lead;
                        acctPage =  new PageReference('/' + newAccountId);
                        acctPage.setRedirect(true);
                    }
                }  
            } else {
                showLink = true;
                errorMessage = Label.Lead_Already_Converted;
            }
        }
        catch(Exception e) { 
            lead.Activite_commerciale_principale__c = activiteCommercialePrincipale;
            lead.Reseau_Concurrent__c = reseauConcurrent;
            lead.Type_de_point__c = typeDePoint;
            lead.Partenaire__c = partenaire;
            lead.Industry = industry;
            lead.Langue_Principale_de_l_adresse__c = languePrincipale;
            lead.Tech_Operateur__c = operateur;
            update lead;
            currentUser.BypassValidationRule__c = true;
            update currentUser;
            String ex = e.getMessage(); 
            System.debug('!!!gho exception : ' + e.getMessage());
            errorMessage = System.Label.LeadConversionErrorMessage;
            System.debug('!!!gho Label.Lead_FirstName : ' + Label.Lead_FirstName);
            if(ex.contains(Label.Lead_FirstName)) {
                errorMessage += ' : ' + Label.Lead_FillField + ' ' + Label.Lead_FirstName; 
            }
            showLink = true;  
        }
        
        currentUser.bypassValidationRule__c = false;
        update currentUser;
        
        return acctPage;
    } 
    
    public PageReference redirectToLead() {
        PageReference leadPage = new PageReference('/' + recordId); 
        leadPage.setRedirect(true);
        return leadPage;
    }
    
}