force-app/main/default/objects/Account/fields/Activite_commerciale_principale__c.field-meta.xml
<CustomField>
    <fullName>Activite_commerciale_principale__c</fullName>
    <label>Activité commerciale principale</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ACT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Assujetti_la_TVA__c.field-meta.xml
<CustomField>
    <fullName>Assujetti_la_TVA__c</fullName>
    <label>Assujetti à la TVA ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ConversionTerminated__c.field-meta.xml
<CustomField>
    <fullName>ConversionTerminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ConversionTerminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>Debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche__c.field-meta.xml
<CustomField>
    <fullName>Dimanche__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_ferme__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>Fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Fermeture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Fermeture_Reference__c</fullName>
    <label>Horaire de fermeture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Ouverture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Ouverture_Reference__c</fullName>
    <label>Horaire d&#39;ouverture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi__c.field-meta.xml
<CustomField>
    <fullName>Jeudi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi__c.field-meta.xml
<CustomField>
    <fullName>Lundi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Lundi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi__c.field-meta.xml
<CustomField>
    <fullName>Mardi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mardi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi__c.field-meta.xml
<CustomField>
    <fullName>Mercredi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/N_de_rue_facturation__c.field-meta.xml
<CustomField>
    <fullName>N_de_rue_facturation__c</fullName>
    <label>N° de rue (adresse de facturation)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi__c.field-meta.xml
<CustomField>
    <fullName>Samedi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Samedi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi__c.field-meta.xml
<CustomField>
    <fullName>Vendredi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi fermé</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Anomalie__c.object
<CustomObject>
    <description>Objet technique permettant de stocker les anomalies associées au PUDO, en particulier les anomalies provenant de la télécollecte.</description>
    <fields>
        <fullName>PUDO__c</fullName>
        <label>PUDO</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Anomalies_de_Telecollecte</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SyncPudo</fullName>
                </value>
                <value>
                    <fullName>NoDevice</fullName>
                </value>
                <value>
                    <fullName>TooManyDevices</fullName>
                </value>
                <value>
                    <fullName>NoDecommissioned</fullName>
                </value>
                <value>
                    <fullName>Association à tort Etat 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Anomalie</label>
    <nameField>
        <label>Numéro de l&apos;anomalie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ACT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>1861</fullName>
    </customValue>
    <customValue>
        <fullName>1862</fullName>
    </customValue>
    <customValue>
        <fullName>1863</fullName>
    </customValue>
    <customValue>
        <fullName>1864</fullName>
    </customValue>
    <customValue>
        <fullName>1865</fullName>
    </customValue>
    <customValue>
        <fullName>1866</fullName>
    </customValue>
    <customValue>
        <fullName>1867</fullName>
    </customValue>
    <customValue>
        <fullName>1868</fullName>
    </customValue>
    <customValue>
        <fullName>1869</fullName>
    </customValue>
    <customValue>
        <fullName>1870</fullName>
    </customValue>
    <customValue>
        <fullName>1871</fullName>
    </customValue>
    <customValue>
        <fullName>1872</fullName>
    </customValue>
    <customValue>
        <fullName>1873</fullName>
    </customValue>
    <customValue>
        <fullName>1874</fullName>
    </customValue>
    <customValue>
        <fullName>1875</fullName>
    </customValue>
    <customValue>
        <fullName>1876</fullName>
    </customValue>
    <customValue>
        <fullName>1877</fullName>
    </customValue>
    <customValue>
        <fullName>1878</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>2167</fullName>
    </customValue>
    <customValue>
        <fullName>2168</fullName>
    </customValue>
    <customValue>
        <fullName>2169</fullName>
    </customValue>
    <customValue>
        <fullName>2170</fullName>
    </customValue>
    <customValue>
        <fullName>2171</fullName>
    </customValue>
    <customValue>
        <fullName>2172</fullName>
    </customValue>
    <customValue>
        <fullName>2173</fullName>
    </customValue>
    <customValue>
        <fullName>2174</fullName>
    </customValue>
    <customValue>
        <fullName>2175</fullName>
    </customValue>
    <description>Activité commerciale principale</description>
    <masterLabel>LOV_GLO_ACT</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_HOR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <description>Horaires d&apos;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

src/classes/AP04_Anomalie_Test.cls
/* Class that test the functionality of AP04_Anomalie*/
@isTest
public class AP04_Anomalie_Test {
    
    static testMethod void testClotureAnomalie(){
        User us =  Utils_TestMethods.createUser('usr','a','aUsr@usr.com','aUsr@mail.com');
        us.BypassValidationRule__c = true;
        insert us;

        system.runAs(us){
        //Create Contact
        Contact c = Utils_TestMethods.CreateContact('c1');
        Insert c;
        
        //Create Macroprofil
        Macroprofil__c m1 = Utils_TestMethods.CreateMacroprofil('m1');
        insert new List<Macroprofil__c>{m1};
            
        //Create Account
        Map<String, Id> mapRecordTypeDevNameToId = new Map<String, Id>();
        for(RecordType rt : [SELECT Id, DeveloperName
                             FROM RecordType
                             WHERE DeveloperName='PUS_FR_Pickup_Contact' or  DeveloperName='PUS_FR_Point_non_Suivi_par_le_CO' OR DeveloperName = 'PUS_FR_Consigne' OR DeveloperName = 'PUS_FR_Point_non_Suivi_par_le_CO' OR DeveloperName = 'PUS_FR_PUDO_Suivi_CO'])
        {
            mapRecordTypeDevNameToId.put(rt.DeveloperName, rt.Id);
        }
        
        Id PUS_FR_Pickup_Contact = mapRecordTypeDevNameToId.get('PUS_FR_Pickup_Contact');
        Id PUS_FR_ConsigneId = mapRecordTypeDevNameToId.get('PUS_FR_Consigne');
        Id PUS_FR_Point_non_Suivi_par_le_CO = mapRecordTypeDevNameToId.get('PUS_FR_Point_non_Suivi_par_le_CO');
        Id PUS_FR_non_Suivi_COId = mapRecordTypeDevNameToId.get('PUS_FR_Point_non_Suivi_par_le_CO');
        Id PUS_FR_PUDO_Suivi_CO = mapRecordTypeDevNameToId.get('PUS_FR_PUDO_Suivi_CO');
        Account account= Utils_TestMethods.CreateAccount(c,m1, 'a1');
        account.Lundi_ferme__c = false;
        account.Mardi_ferme__c = false;
        account.Industry='1';
        account.Activite_commerciale_principale__c='18';
        account.Mercredi_ferme__c = false;
        account.Jeudi_ferme__c = false;
        account.Vendredi_ferme__c = false;
        account.Samedi_ferme__c = false;
        account.Assujetti_la_TVA__c='Non';
        account.Dimanche_ferme__c = false;
        account.Lundi__c = true;
        account.Mardi__c = true;
        account.Mercredi__c = true;
        account.Jeudi__c = true;
        account.Vendredi__c = true;
        account.Samedi__c = true;
        account.Dimanche__c = true;
        account.Horaire_Ouverture_Reference__c = '11:30';
        account.Horaire_Fermeture_Reference__c = '23:00';
        account.Debut_pause_dejeuner__c = '12:00';
        account.Fin_pause_dejeuner__c = '12:00';
        account.ConversionTerminated__c =true;
        account.Etat__c ='2';
        account.RecordTypeId= PUS_FR_Pickup_Contact;
        
        account.BillingStreet = 'Test';
        account.BillingPostalCode = '25142';
        account.BillingCountry = 'France';
        account.BillingCountryCode = 'FR';
        account.BillingCity = 'Paris';
        account.ShippingPostalCode = '25142';
        account.ShippingCountry = 'France';
        account.ShippingCountryCode = 'FR';
        account.ShippingCity = 'Paris';
        account.ShippingStreet = 'Test';
        account.N_de_rue_facturation__c = 'test';        
        
        
        insert account; 
        c.AccountId = account.id;
        update c;
        Test.startTest();
        
        List<Anomalie__c> ListAnomalie = new List<Anomalie__c> ();
        Anomalie__c a=new Anomalie__c();
        a.Name='test';
        a.PUDO__c=account.id;
        a.Statut__c='1';
        a.Type__c='Association à tort Etat 2';
        ListAnomalie.add(a);
        insert ListAnomalie;
        account.Etat__c = '5';
        update account;
      Test.stopTest();}
    }
}