force-app/main/default/objects/Account/fields/Activite_commerciale_principale__c.field-meta.xml
<CustomField>
    <fullName>Activite_commerciale_principale__c</fullName>
    <label>Activité commerciale principale</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ACT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Assujetti_la_TVA__c.field-meta.xml
<CustomField>
    <fullName>Assujetti_la_TVA__c</fullName>
    <label>Assujetti à la TVA ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ConversionTerminated__c.field-meta.xml
<CustomField>
    <fullName>ConversionTerminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ConversionTerminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>Debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche__c.field-meta.xml
<CustomField>
    <fullName>Dimanche__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_ferme__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>Fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Fermeture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Fermeture_Reference__c</fullName>
    <label>Horaire de fermeture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Ouverture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Ouverture_Reference__c</fullName>
    <label>Horaire d&#39;ouverture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi__c.field-meta.xml
<CustomField>
    <fullName>Jeudi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi__c.field-meta.xml
<CustomField>
    <fullName>Lundi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Lundi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi__c.field-meta.xml
<CustomField>
    <fullName>Mardi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mardi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi__c.field-meta.xml
<CustomField>
    <fullName>Mercredi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/N_de_rue_facturation__c.field-meta.xml
<CustomField>
    <fullName>N_de_rue_facturation__c</fullName>
    <label>N° de rue (adresse de facturation)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi__c.field-meta.xml
<CustomField>
    <fullName>Samedi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Samedi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi__c.field-meta.xml
<CustomField>
    <fullName>Vendredi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi fermé</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Anomalie__c.object
<CustomObject>
    <description>Objet technique permettant de stocker les anomalies associées au PUDO, en particulier les anomalies provenant de la télécollecte.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Anomalie</label>
    <nameField>
        <label>Numéro de l&apos;anomalie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil_Service__c.object
<CustomObject>
    <description>Services ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Services par défaut</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Macroprofil liés à ce service</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service par défaut</label>
    <nameField>
        <displayFormat>SPD-{0000}</displayFormat>
        <label>Numéro du Service par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil_Transporteur__c.object
<CustomObject>
    <description>Transporteurs ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Transporteur par defaut</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <label>Transporteur</label>
        <referenceTo>Transporteur__c</referenceTo>
        <relationshipLabel>Macroprofils liés à ce transporteur</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transporteur par defaut</label>
    <nameField>
        <displayFormat>TPD-{0000}</displayFormat>
        <label>Numéro du Transporteur par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteur par defaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassApex__c</fullName>
        <label>BypassApex</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP01_Account</fullName>
                </value>
                <value>
                    <fullName>AP05_Account</fullName>
                </value>
                <value>
                    <fullName>AP06_MacroprofilReseau</fullName>
                </value>
                <value>
                    <fullName>Utils_PUS</fullName>
                </value>
                <value>
                    <fullName>AP04_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP02_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_CaseComment</fullName>
                </value>
                <value>
                    <fullName>AP08_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_CompteRenduRempli</fullName>
                </value>
                <value>
                    <fullName>AP01_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_Task</fullName>
                </value>
                <value>
                    <fullName>AP02_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP02_MacroprofilTransporteur</fullName>
                </value>
                <value>
                    <fullName>AP02_Task</fullName>
                </value>
                <value>
                    <fullName>AP03_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP03_MacroprofilService</fullName>
                </value>
                <value>
                    <fullName>AP03_ReseauAssocie</fullName>
                </value>
                <value>
                    <fullName>AP03_Task</fullName>
                </value>
                <value>
                    <fullName>AP04_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP05_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Account</fullName>
                </value>
                <value>
                    <fullName>AP08_Attachement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BypassProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassWorkflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ACT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>1861</fullName>
    </customValue>
    <customValue>
        <fullName>1862</fullName>
    </customValue>
    <customValue>
        <fullName>1863</fullName>
    </customValue>
    <customValue>
        <fullName>1864</fullName>
    </customValue>
    <customValue>
        <fullName>1865</fullName>
    </customValue>
    <customValue>
        <fullName>1866</fullName>
    </customValue>
    <customValue>
        <fullName>1867</fullName>
    </customValue>
    <customValue>
        <fullName>1868</fullName>
    </customValue>
    <customValue>
        <fullName>1869</fullName>
    </customValue>
    <customValue>
        <fullName>1870</fullName>
    </customValue>
    <customValue>
        <fullName>1871</fullName>
    </customValue>
    <customValue>
        <fullName>1872</fullName>
    </customValue>
    <customValue>
        <fullName>1873</fullName>
    </customValue>
    <customValue>
        <fullName>1874</fullName>
    </customValue>
    <customValue>
        <fullName>1875</fullName>
    </customValue>
    <customValue>
        <fullName>1876</fullName>
    </customValue>
    <customValue>
        <fullName>1877</fullName>
    </customValue>
    <customValue>
        <fullName>1878</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>2167</fullName>
    </customValue>
    <customValue>
        <fullName>2168</fullName>
    </customValue>
    <customValue>
        <fullName>2169</fullName>
    </customValue>
    <customValue>
        <fullName>2170</fullName>
    </customValue>
    <customValue>
        <fullName>2171</fullName>
    </customValue>
    <customValue>
        <fullName>2172</fullName>
    </customValue>
    <customValue>
        <fullName>2173</fullName>
    </customValue>
    <customValue>
        <fullName>2174</fullName>
    </customValue>
    <customValue>
        <fullName>2175</fullName>
    </customValue>
    <description>Activité commerciale principale</description>
    <masterLabel>LOV_GLO_ACT</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_HOR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <description>Horaires d&apos;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

src/classes/AP03_Anomalie_TEST.cls
/* 
 * Author        : RFO
 * Date          : 2018-06-05
 * Description   : Test AP03_Anomalie 
 */
@isTest
public class AP03_Anomalie_TEST {
    
    static testMethod void testExtractDataFromAnomalyDescription(){
        User currentUser = [SELECT Id, Name, BypassValidationRule__c
                            FROM User
                            WHERE Id = : UserInfo.getUserId()];
        currentUser.BypassValidationRule__c = true;
        currentUser.BypassWorkflow__c= true;
        currentUser.BypassProcessBuilder__c= true;
        currentUser.BypassApex__c = 'AP01_Account;AP05_Account;AP06_MacroprofilReseau;Utils_PUS;AP04_Account;AP03_Conge_Indispo;AP06_Conge_Indispo;AP07_Conge_Indispo;AP01_Conge_Indispo;AP02_Conge_Indispo';
        update currentUser;
        
        //Create Contact
        Contact c = Utils_TestMethods.CreateContact('c1');
        Insert c;
        
        //Create Macroprofil
        Macroprofil__c m1 = Utils_TestMethods.CreateMacroprofil('m1');
           
        //Create Services
        Service__c s1 = Utils_TestMethods.CreateService('s1');
            
        //Create Transporteurs
        Transporteur__c t1 = Utils_TestMethods.CreateTransporteur('t1');
            
        //Create Macroprofil Service
        Macroprofil_Service__c ms1 = Utils_TestMethods.CreateMacroprofilService(m1,s1);
            
        //Create Macroprofil Tranporteur
        Macroprofil_Transporteur__c mt1 = Utils_TestMethods.CreateMacroprofilTransporteur(m1,t1);
        
        //Create Account
        Account account= Utils_TestMethods.CreateAccount(c,m1, 'a1');
        account.Lundi_ferme__c = false;
        account.Mardi_ferme__c = false;
        account.Industry='1';
        account.Activite_commerciale_principale__c='18';
        account.Mercredi_ferme__c = false;
        account.Jeudi_ferme__c = false;
        account.Vendredi_ferme__c = false;
        account.Samedi_ferme__c = false;
        account.Assujetti_la_TVA__c='Non';
        account.Dimanche_ferme__c = false;
        account.Lundi__c = true;
        account.Mardi__c = true;
        account.Mercredi__c = true;
        account.Jeudi__c = true;
        account.Vendredi__c = true;
        account.Samedi__c = true;
        account.Dimanche__c = true;
        account.Horaire_Ouverture_Reference__c = '11:30';
        account.Horaire_Fermeture_Reference__c = '23:00';
        account.Debut_pause_dejeuner__c = '12:00';
        account.Fin_pause_dejeuner__c = '12:00';
        account.ConversionTerminated__c =true;
        account.Etat__c ='2';
       // account.RecordTypeId= [SELECT Id FROM RecordType WHERE DeveloperName = 'PUS_FR_PUDO_Suivi_CO'].get(0).Id;
        
        account.BillingStreet = 'Test';
        account.BillingPostalCode = '25142';
        account.BillingCountry = 'France';
        account.BillingCountryCode = 'FR';
        account.BillingCity = 'Paris';
        account.ShippingPostalCode = '25142';
        account.ShippingCountry = 'France';
        account.ShippingCountryCode = 'FR';
        account.ShippingCity = 'Paris';
        account.ShippingStreet = 'Test';
        account.N_de_rue_facturation__c = 'test';
        
        insert account; 

        list<Anomalie__c> listAnomalie = new list<Anomalie__c>();
       

        //Create multiple PDA anomaly
        Anomalie__c ano2 = Utils_TestMethods.createAnomalie(account);
        ano2.Name ='Multiple Devices';
        ano2.Statut__c = '0';
        ano2.Description__c ='2//[PDA_WINDOWS/M3/////GA5GNCNJD3995639]/[PDA_WINDOWS/M3/////GA5GNCNJD3432545]';
        listAnomalie.add(ano2);
        
        //Create single PDA anomaly
         Anomalie__c ano = Utils_TestMethods.createAnomalie(account);
        ano.Name ='Single Device';
        ano.Statut__c = '0';
        ano.Description__c ='PDA_WINDOWS/M3/////GA5GNCNJD3995639';
        listAnomalie.add(ano);

        //Create unexpected description anomaly
        Anomalie__c ano3 = Utils_TestMethods.createAnomalie(account);
        ano3.Name ='Unexpected desc';
        ano3.Statut__c = '0';
        ano3.Description__c ='qlkdfqkldfqdfqkqsdhfqf';
        listAnomalie.add(ano3);

        //Create empty description anomaly
        Anomalie__c ano4 = Utils_TestMethods.createAnomalie(account);
        ano4.Name ='Empty desc';
        ano4.Statut__c = '0';
        ano4.Description__c ='';
        listAnomalie.add(ano4);
        insert listAnomalie;
        Test.startTest();
  
        list<Anomalie__c> listAnomalieInserted = [Select PDA_type__c, PDA_Ids__c From Anomalie__c where id in (:ano.id)];
        
        for(Anomalie__c anomalie : listAnomalieInserted){
            
            if(anomalie.id == ano.id){
                System.assertEquals('PDA_WINDOWS',anomalie.PDA_type__c);
                System.assertEquals('GA5GNCNJD3995639',anomalie.PDA_Ids__c);

            }
            else if(anomalie.id == ano2.id){
              System.assertEquals('PDA_WINDOWS|PDA_WINDOWS',anomalie.PDA_type__c);
              System.assertEquals('GA5GNCNJD3995639|GA5GNCNJD3432545',anomalie.PDA_Ids__c);    
            }
            else if(anomalie.id == ano4.id){
              System.assertEquals(null,anomalie.PDA_type__c);
              System.assertEquals(null,anomalie.PDA_Ids__c); 
            }
             else if(anomalie.id == ano3.id){
              System.assertEquals(null,anomalie.PDA_type__c);
              System.assertEquals(null,anomalie.PDA_Ids__c); 
            }
            
        }
        
        Test.stopTest();
         
    }
    
}