force-app/main/default/objects/Account/fields/Activite_commerciale_principale__c.field-meta.xml
<CustomField>
    <fullName>Activite_commerciale_principale__c</fullName>
    <label>Activité commerciale principale</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ACT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Configuration_Site__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Configuration_Site__c.Tech_Compte__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Configuration_Site__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_d_installation__c.field-meta.xml
<CustomField>
    <fullName>Date_d_installation__c</fullName>
    <label>Date d&#39;installation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nom_commercial_2__c.field-meta.xml
<CustomField>
    <fullName>Nom_commercial_2__c</fullName>
    <label>Nom commercial 2</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Recopie_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Recopie_Configuration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recopie Configuration?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Conge__c</fullName>
        <label>ID_Conge</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Requete_Conge__c</fullName>
        <label>ID_Requête_Congé</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Configuration__c.object
<CustomObject>
    <label>Configuration</label>
    <nameField>
        <label>Nom de Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Configuration_Locker_Type__c.object
<CustomObject>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>Configurations Locker Type</relationshipLabel>
        <relationshipName>Configurations_Locker_Type</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type_de_casier__c</fullName>
        <label>Type de casier</label>
        <referenceTo>Type_de_casier__c</referenceTo>
        <relationshipLabel>Configurations Locker Type</relationshipLabel>
        <relationshipName>Configurations_Locker_Type</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Configuration Locker Type</label>
    <nameField>
        <displayFormat>CONF_LT_{0000}</displayFormat>
        <label>Nom de Configuration Locker Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurations Locker Type</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Configuration_Site__c.object
<CustomObject>
    <label>Configuration Site</label>
    <nameField>
        <label>Nom de Configuration Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CountriesSequence__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CountriesSequence</label>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Type_de_casier__c.object
<CustomObject>
    <label>Type de casier</label>
    <nameField>
        <label>Nom de Type de casier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de casier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ACT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>1861</fullName>
    </customValue>
    <customValue>
        <fullName>1862</fullName>
    </customValue>
    <customValue>
        <fullName>1863</fullName>
    </customValue>
    <customValue>
        <fullName>1864</fullName>
    </customValue>
    <customValue>
        <fullName>1865</fullName>
    </customValue>
    <customValue>
        <fullName>1866</fullName>
    </customValue>
    <customValue>
        <fullName>1867</fullName>
    </customValue>
    <customValue>
        <fullName>1868</fullName>
    </customValue>
    <customValue>
        <fullName>1869</fullName>
    </customValue>
    <customValue>
        <fullName>1870</fullName>
    </customValue>
    <customValue>
        <fullName>1871</fullName>
    </customValue>
    <customValue>
        <fullName>1872</fullName>
    </customValue>
    <customValue>
        <fullName>1873</fullName>
    </customValue>
    <customValue>
        <fullName>1874</fullName>
    </customValue>
    <customValue>
        <fullName>1875</fullName>
    </customValue>
    <customValue>
        <fullName>1876</fullName>
    </customValue>
    <customValue>
        <fullName>1877</fullName>
    </customValue>
    <customValue>
        <fullName>1878</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>2167</fullName>
    </customValue>
    <customValue>
        <fullName>2168</fullName>
    </customValue>
    <customValue>
        <fullName>2169</fullName>
    </customValue>
    <customValue>
        <fullName>2170</fullName>
    </customValue>
    <customValue>
        <fullName>2171</fullName>
    </customValue>
    <customValue>
        <fullName>2172</fullName>
    </customValue>
    <customValue>
        <fullName>2173</fullName>
    </customValue>
    <customValue>
        <fullName>2174</fullName>
    </customValue>
    <customValue>
        <fullName>2175</fullName>
    </customValue>
    <description>Activité commerciale principale</description>
    <masterLabel>LOV_GLO_ACT</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/AP02_Account_TEST.cls
@isTest
public class AP02_Account_TEST {
    
    static testMethod void testCheckRecordTypeAssignment()
    {
       	// retrieve ID of belgium
         List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c,ID_Requete_Conge__c,ID_CONGE__c
                                                                              FROM Association_Record_Type_et_pays__mdt];
            
            
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
           associationRTPays.put(associationRT.MasterLabel, associationRT);  
        }
        //Create Custom Settings country sequence
        CountriesSequence__c cs = new CountriesSequence__c(Name='Belgium' , Sequence__c = 'BE0001');
        try{
            insert cs;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        try{
            insert testContact;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        //Create Account France
        Account account1= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account1');
        account1.RecordTypeId = associationRTPays.get('France').ID_Prospect_Converti__c;
        account1.ShippingCountry ='France';
        account1.ShippingCountrycode ='FR';
        account1.Etat__c = '0';
        insert account1;
        account1.ShippingCountry ='Belgium';
        account1.ShippingCountryCode='BE';
        account1.Etat__c = '0';
        //Create Account BNL
        Account account2= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account1');
        account2.RecordTypeId = associationRTPays.get('Belgium').ID_Prospect_Converti__c;
        account2.ShippingCountry ='Belgium';
        account2.ShippingCountryCode='BE';
        account2.BillingCountry ='Belgium';
        account2.BillingCountryCode='BE';
        account2.Etat__c = '0';
        account2.Operateur_Global__c = 'DPD_BNL';
        account2.ShippingPostalCode = '1234';
        account2.BillingPostalCode = '1234';
        insert account2;
        //Create Account France and enter error
        Account account3= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account1');
        account3.RecordTypeId = associationRTPays.get('Belgium').ID_Prospect_Converti__c;
        account3.ShippingCountry ='Belgium';
        account3.ShippingCountryCode='BE';
        account3.Etat__c = '0';
        //Create Account BNL
        Account account4= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account1');
        account4.RecordTypeId =associationRTPays.get('France').ID_Prospect_Converti__c;
        account4.ShippingCountry ='France';
        account4.ShippingCountryCode ='FR';
        account4.Activite_commerciale_principale__c = null;
        account4.BillingCountry ='France';
        account4.BillingCountryCode ='FR';
        account4.BillingPostalCode ='12345';
        account4.Etat__c = '0';
    }
    
    static testMethod void testCreateConfigurationandCasierSite() {
        
        //Create Custom Settings country sequence
        CountriesSequence__c cs = new CountriesSequence__c(Name='France' , Sequence__c = 'FR0001');
        try{
            insert cs;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        try{
            insert testContact;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        
        Macroprofil__c testMacro= Utils_TestMethods.CreateMacroprofil('Test Macroprofil');
        try{
            insert testMacro;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        COnfiguration__c testConfig = Utils_TestMethods.createConfiguration('Config 1');
        try{
            insert testConfig;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        Type_de_casier__c testTypeDeCase = Utils_TestMethods.createTypeCasierKEBA('Test Type De Casier');
        try{
            insert testTypeDeCase;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        Configuration_Locker_Type__c testConfigurationLockerType = Utils_TestMethods.createConfigurationLockerType(testConfig.id, testTypeDeCase.id);
        try{
            insert testConfigurationLockerType;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        //Create Account
        List<Account> accountsToAdd = new List<Account>();
        Account account1= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account');
        account1.RecordTypeId = Label.PUS_RT_Consigne;
        account1.Recopie_Configuration__c = true;
        account1.Etat__c = '2';
        account1.ShippingPostalCode = '12345';
        account1.Nom_commercial_2__c = 'test nom commercial'; 
        account1.Date_d_installation__c = date.ValueOf('2017-12-13');
        accountsToAdd.add(account1);
        insert accountsToAdd;
        account1.Recopie_Configuration__c = true;
        account1.Configuration__c = testConfig.id;
        
        update account1;
        
        Account acc = [Select configuration_site__r.name
                       From Account
                       Where id = :accountsToAdd.get(0).id];
        system.assertEquals(acc.configuration_site__r.name, testConfig.Name);
        account1.Recopie_Configuration__c = true;
        account1.Configuration__c  = testConfig.id;
        try{
            update account1;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        account1.Recopie_Configuration__c = false;
        account1.Configuration_site__c  = null;
        try{
            update account1;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        acc = [Select configuration_site__r.name
               From Account
               Where id = :accountsToAdd.get(0).id];
        
    }
    
    static testMethod void testRecordTypeAssignment(){
        
                
        List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c,ID_Requete_Conge__c,ID_CONGE__c
                                                                              FROM Association_Record_Type_et_pays__mdt];
            
            
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
           associationRTPays.put(associationRT.MasterLabel, associationRT);  
        }
        
        //Create Custom Settings country sequence
        CountriesSequence__c cs = new CountriesSequence__c(Name='Belgium' , Sequence__c = 'BE0001');
        try{
            insert cs;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        try{
            insert testContact;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        /*List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt
                                                                         Where MasterLabel ='Belgium'
                                                                         Limit 1];*/
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account');
        account1.recordTypeID = associationRTPays.get('Belgium').ID_Prospect_Converti__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        system.debug('account1.recordTypeID '+account1.recordTypeID); 
        
        account1.Etat__c = '1';
        try{
            update account1;
            account1 = [Select recordTypeID
                        From Account
                        Where Id =: account1.Id];
            system.assertEquals(associationRTPays.get('Belgium').ID_Prospect_A_Valider__c, account1.RecordTypeId); 
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        account1.Etat__c = '2';
        account1.Nom_commercial_2__c='test';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCity='Belgium';
        account1.ShippingCountry='Belgium';
        account1.ShippingCountryCode='BE';
        account1.ShippingStreet='abc'; 
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Date_d_installation__c = date.ValueOf('2017-12-13');
        try{
            update account1;
            account1 = [Select recordTypeID
                        From Account       
                        Where Id =: account1.Id];
            system.assertEquals(associationRTPays.get('Belgium').ID_suivi_CO__c, account1.RecordTypeId);
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
    }
}