force-app/main/default/objects/Account/fields/Activite_commerciale_principale__c.field-meta.xml
<CustomField>
    <fullName>Activite_commerciale_principale__c</fullName>
    <label>Activité commerciale principale</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ACT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Duree_pause_dejeuner_respectee__c.field-meta.xml
<CustomField>
    <fullName>Duree_pause_dejeuner_respectee__c</fullName>
    <description>Entre lundi et samedi</description>
    <formula>IF( 
AND( 
VALUE(SUBSTITUTE(TEXT( lundi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( lundi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( mardi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( mardi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( mercredi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( mercredi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( jeudi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( jeudi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( vendredi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( vendredi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( samedi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( samedi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )) ), 

IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;) 
)</formula>
    <inlineHelpText>Between Monday and Saturday</inlineHelpText>
    <label>Durée pause déjeuner respectée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Heure_fermeture_minimale_respectee__c.field-meta.xml
<CustomField>
    <fullName>Heure_fermeture_minimale_respectee__c</fullName>
    <formula>IF( 
AND( 
OR( 
VALUE(LEFT( TEXT( Lundi_Fermeture__c ) , 2)) &gt;=  VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c) ), 
VALUE(LEFT( TEXT( Lundi_Fermeture__c ) , 2)) = 00), 

OR( 
VALUE(LEFT( TEXT( Mardi_Fermeture__c ) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT( TEXT( Mardi_Fermeture__c ) , 2)) = 00), 

OR( 
VALUE(LEFT( TEXT(Mercredi_Fermeture__c ) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Mercredi_Fermeture__c ), 2))=00), 


OR( 
VALUE(LEFT( TEXT(Jeudi_Fermeture__c) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Jeudi_Fermeture__c), 2))=00), 

OR( 
VALUE(LEFT( TEXT(Vendredi_Fermeture__c) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Vendredi_Fermeture__c), 2))=00), 

OR( 
VALUE(LEFT( TEXT(Samedi_Fermeture__c) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Samedi_Fermeture__c), 2))=00)), 


IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Heure fermeture minimale respectée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Heure_ouverture_minimale_respect_e__c.field-meta.xml
<CustomField>
    <fullName>Heure_ouverture_minimale_respect_e__c</fullName>
    <formula>IF( 
AND( 
OR( 
AND( 
VALUE(LEFT( TEXT(Lundi_Ouverture__c) , 2))&gt;=05, 
VALUE(LEFT(TEXT(Lundi_Ouverture__c), 2))&lt;= VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c )))), 



VALUE(LEFT( TEXT(Mardi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Mardi_Ouverture__c), 2))&lt;=VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c )), 
VALUE(LEFT( TEXT( Mercredi_Ouverture__c ) , 2))&gt;=05 , VALUE(LEFT(TEXT(Mercredi_Ouverture__c), 2))&lt;=10, 
VALUE(LEFT( TEXT(Jeudi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Jeudi_Ouverture__c), 2))&lt;=VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c )), 
VALUE(LEFT( TEXT(Vendredi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Vendredi_Ouverture__c), 2))&lt;=10, 
VALUE(LEFT( TEXT(Samedi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Samedi_Ouverture__c), 2))&lt;=VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c ))), 


IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Heure ouverture minimale respectée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seuil_de_l_amplitude_horaire_respect__c.field-meta.xml
<CustomField>
    <fullName>Seuil_de_l_amplitude_horaire_respect__c</fullName>
    <formula>IF( Amplitude_horaire_du_relais__c &gt;= Value(Text(Seuil_de_l_amplitude_horaire_en_h_c__c)),IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;),IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <label>Seuil de l&#39;amplitude horaire respecté</label>
    <type>Text</type>
</CustomField>

src/objects/Anomalie__c.object
<CustomObject>
    <description>Objet technique permettant de stocker les anomalies associées au PUDO, en particulier les anomalies provenant de la télécollecte.</description>
    <fields>
        <fullName>PUDO__c</fullName>
        <label>PUDO</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Anomalies_de_Telecollecte</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SyncPudo</fullName>
                </value>
                <value>
                    <fullName>NoDevice</fullName>
                </value>
                <value>
                    <fullName>TooManyDevices</fullName>
                </value>
                <value>
                    <fullName>NoDecommissioned</fullName>
                </value>
                <value>
                    <fullName>Association à tort Etat 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Anomalie</label>
    <nameField>
        <label>Numéro de l&apos;anomalie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Requete_Conge__c</fullName>
        <label>ID_Requête_Congé</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Requete_ContratNonRespecte__c</fullName>
        <label>ID_Requete_ContratNonRespecte</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Anomalie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Anomalie</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Anomalie__c.PUDO__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Anomalie__c</referenceTo>
        <relationshipLabel>Requêtes</relationshipLabel>
        <relationshipName>Requ_tes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Anomalie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Champ technique servant à référencer une anomalie</description>
        <label>Anomalie</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Anomalie__c.PUDO__c</field>
                <operation>equals</operation>
                <valueField>$Source.Nom_du_compte__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Anomalie__c</referenceTo>
        <relationshipLabel>Congés/disponibilités/indisponibilités</relationshipLabel>
        <relationshipName>Cong_s_disponibilit_s_indisponibilit_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nom_du_compte__c</fullName>
        <label>Nom du compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>IF ( Date_de_debut__c &gt;  TODAY() ,$Label.CongeIndispo_A_Venir_2,
IF ( Date_de_fin__c  &lt;   TODAY() ,$Label.Conge_Indispo_Passe_2,$Label.CongeIndispo_En_Cours_2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_Conges_Dispo_Juillet_Aout__c</fullName>
        <formula>IF( 
	AND(Date_de_debut__c &gt;= DATE( YEAR( TODAY()),07, 01 ), 
		Date_de_debut__c &lt;= DATE( YEAR( TODAY()),08, 31 ), 
		Date_de_fin__c &gt;= DATE( YEAR( TODAY()),07, 01 ), 
		Date_de_fin__c &lt;= DATE( YEAR( TODAY()),08, 31), 
		OR(RecordType.Id == $Label.RT_Conge_Indispo_Conge ,RecordType.Id == $Label.RT_Conge_Indispo_Disponibilite ) 
), true, false)</formula>
        <label>TECH Conges Dispo Juillet Aout</label>
        <type>Checkbox</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <recordTypes>
        <fullName>Conge</fullName>
        <active>true</active>
        <description>Permet de créer une période de congés.</description>
        <label>Congé</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ACT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>1861</fullName>
    </customValue>
    <customValue>
        <fullName>1862</fullName>
    </customValue>
    <customValue>
        <fullName>1863</fullName>
    </customValue>
    <customValue>
        <fullName>1864</fullName>
    </customValue>
    <customValue>
        <fullName>1865</fullName>
    </customValue>
    <customValue>
        <fullName>1866</fullName>
    </customValue>
    <customValue>
        <fullName>1867</fullName>
    </customValue>
    <customValue>
        <fullName>1868</fullName>
    </customValue>
    <customValue>
        <fullName>1869</fullName>
    </customValue>
    <customValue>
        <fullName>1870</fullName>
    </customValue>
    <customValue>
        <fullName>1871</fullName>
    </customValue>
    <customValue>
        <fullName>1872</fullName>
    </customValue>
    <customValue>
        <fullName>1873</fullName>
    </customValue>
    <customValue>
        <fullName>1874</fullName>
    </customValue>
    <customValue>
        <fullName>1875</fullName>
    </customValue>
    <customValue>
        <fullName>1876</fullName>
    </customValue>
    <customValue>
        <fullName>1877</fullName>
    </customValue>
    <customValue>
        <fullName>1878</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>2167</fullName>
    </customValue>
    <customValue>
        <fullName>2168</fullName>
    </customValue>
    <customValue>
        <fullName>2169</fullName>
    </customValue>
    <customValue>
        <fullName>2170</fullName>
    </customValue>
    <customValue>
        <fullName>2171</fullName>
    </customValue>
    <customValue>
        <fullName>2172</fullName>
    </customValue>
    <customValue>
        <fullName>2173</fullName>
    </customValue>
    <customValue>
        <fullName>2174</fullName>
    </customValue>
    <customValue>
        <fullName>2175</fullName>
    </customValue>
    <description>Activité commerciale principale</description>
    <masterLabel>LOV_GLO_ACT</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AP02_Case.cls
/*--------------------------------------------------------------------------
* Author: Chahid Khalil
* Company : EI Technologies Liban
* Description: trigger before update Requete
* Test Class: AP02_Case_Test
* Created Date: 4/05/2018
--------------------------------------------------------------------------*/
public class AP02_Case {
    
    public static void ValidateCanCloseCase(List<Case> newCases, map<id,Case> mapOldCases)
    {  
        System.debug('JMB AP02_Case ValidateCanCloseCase mapOldCases ' + mapOldCases);
        System.debug('JMB AP02_Case ValidateCanCloseCase newCases ' + newCases);
        List< Association_Record_Type_et_pays__mdt> associationRTPaysBNL = [Select Id, MasterLabel, ID_Requete_ContratNonRespecte__c, ID_Requete_Conge__c 
                                                                            FROM Association_Record_Type_et_pays__mdt
                                                                            where MasterLabel <> 'France'];
        Map<String,Association_Record_Type_et_pays__mdt> mapassociationRTPaysBNL =  new Map<String,Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord: associationRTPaysBNL)
        {
            mapassociationRTPaysBNL.put(mdtRecord.MasterLabel, mdtRecord);           
        }
        
        List<Case> CaseListoUpdate = new List<Case>();
        Set<Id> AccountIds = new Set<Id>();
        set<id> setAnomalies = new set<id>();
        for (Case CurrentCase : newCases)
        {
            if (CurrentCase.Status  == Label.Requete_Terminee) //mapOldCases.get(CurrentCase.id).Status != Label.Requete_Terminee
            {
                AccountIds.add(CurrentCase.AccountId);
                setAnomalies.add(CurrentCase.Anomalie__c);
            }
        }
        
        Map<Id, Account> mapId_Account = new Map<Id, Account> ([SELECT Seuil_de_l_amplitude_horaire_respect__c, Heure_fermeture_minimale_respectee__c,
                                                                Heure_ouverture_minimale_respect_e__c, Duree_pause_dejeuner_respectee__c,Activite_commerciale_principale__c,ShippingCountry
                                                                FROM Account
                                                                WHERE Id in : AccountIds]);
        
        List<Conge_Indispo__c> Conge_IndispoList =[SELECT Nom_du_compte__c 
                                                   FROM Conge_Indispo__c 
                                                   WHERE Nom_du_compte__c in :AccountIds and
                                                   TECH_Conges_Dispo_Juillet_Aout__c = true];
        //Map containing Account with conge List
        Map<Id,List<Conge_Indispo__c>> MapAccount_Conge = new Map<Id,List<Conge_Indispo__c>>();
        for (Conge_Indispo__c ci : Conge_IndispoList)
        {
            if(!MapAccount_Conge.containsKey(ci.Nom_du_compte__c))
            {
                MapAccount_Conge.put(ci.Nom_du_compte__c, new List<Conge_Indispo__c>());
            }              
            MapAccount_Conge.get(ci.Nom_du_compte__c).add(ci);
        } 
        
        List<Anomalie__c > anomalieList = [SELECT  Statut__c , PUDO__c
                                           FROM Anomalie__c
                                           WHERE id in :setAnomalies 
                                           and Statut__c = '1'
                                           and Type__c <> :label.Anomalie_TypeSyncPudo];
        
        Map<id, Anomalie__c> mapAccount_Anomalie = new  Map<id, Anomalie__c>();
        for(Anomalie__c current_anomalie :anomalieList )
        {
            mapAccount_Anomalie.put(current_anomalie.PUDO__c, current_anomalie);  
        }
        for (Case CurrentCase : newCases)
        {
            Account tempAccount = mapId_Account.get(CurrentCase.AccountId);                           
            if (tempAccount != null){
                if(tempAccount.ShippingCountry != null && tempAccount.ShippingCountry!=''){
                    Association_Record_Type_et_pays__mdt temp_Association_R = mapassociationRTPaysBNL.get(tempAccount.ShippingCountry);
                    
                    system.debug('AP02_Case mapassociationRTPaysBNL ' + mapassociationRTPaysBNL);
                    if(temp_Association_R != null)
                    {
                        
                        if (((tempAccount.Seuil_de_l_amplitude_horaire_respect__c.contains('Red') || tempAccount.Heure_fermeture_minimale_respectee__c.contains('Red') ||tempAccount.Heure_ouverture_minimale_respect_e__c.contains('Red') || tempAccount.Duree_pause_dejeuner_respectee__c.contains('Red') 
                              || (tempAccount.Activite_commerciale_principale__c != null 
                                  && label.Pudo_ActiviteCommerciale.contains(';' + tempAccount.Activite_commerciale_principale__c + ';'))) 
                             && CurrentCase.RecordTypeId == temp_Association_R.ID_Requete_ContratNonRespecte__c)
                            || (!MapAccount_Conge.containsKey(CurrentCase.AccountId) && CurrentCase.RecordTypeId == temp_Association_R.ID_Requete_Conge__c) 
                            || mapAccount_Anomalie.containsKey(CurrentCase.AccountId) )
                            
                        {                    
                            CurrentCase.Status = Label.ReQuette_En_attente_de_traitement;
                            system.debug('AP02_Case status cannot be Closed!!!!!');
                        } 
                        
                    }
                }
                else{
                    tempAccount.addError(Label.Message_No_Shipping_Country); 
                } 
            }            
        }        
    }    
}