force-app/main/default/objects/Account/fields/Amplitude_horaire_du_relais__c.field-meta.xml
<CustomField>
    <fullName>Amplitude_horaire_du_relais__c</fullName>
    <label>Amplitude horaire du relais</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Etat__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_MOD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <label>Partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_PAR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Samedi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Association_PUDO_Macroprofil__mdt.object
<CustomObject>
    <description>Cet objet contient les pays et types de point associés à chaque Macroprofil d&apos;un PUDO</description>
    <fields>
        <fullName>Id_du_Macroprofil__c</fullName>
        <label>Id du Macroprofil</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partenaire__c</fullName>
        <label>Partenaire</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <label>Pays</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_de_point__c</fullName>
        <label>Type de point</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Association PUDO Macroprofil</label>
    <pluralLabel>Association PUDO Macroprofils</pluralLabel>
</CustomObject>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Requete_ContratNonRespecte__c</fullName>
        <label>ID_Requete_ContratNonRespecte</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Mode__c</fullName>
        <formula>TEXT( Account.Mode__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <formula>Account.ShippingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pays</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_de_point__c</fullName>
        <formula>Text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type de point</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>DPD_BNL</fullName>
        <active>true</active>
        <businessProcess>DPD_BNL_Requêtes_Ponctuelles</businessProcess>
        <label>DPD_BNL_inactif_avec_scan_associé</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CountriesSequence__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CountriesSequence</label>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <fields>
        <fullName>Pays__c</fullName>
        <label>Pays</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_PAY</valueSetName>
        </valueSet>
    </fields>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_HOR.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <customValue>
        <fullName>16:30</fullName>
    </customValue>
    <customValue>
        <fullName>17:30</fullName>
    </customValue>
    <customValue>
        <fullName>17:45</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <description>Horaires d&#39;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_MOD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>220</fullName>
    </customValue>
    <customValue>
        <fullName>240</fullName>
    </customValue>
    <customValue>
        <fullName>250</fullName>
    </customValue>
    <customValue>
        <fullName>260</fullName>
    </customValue>
    <customValue>
        <fullName>264</fullName>
    </customValue>
    <customValue>
        <fullName>270</fullName>
    </customValue>
    <customValue>
        <fullName>300</fullName>
    </customValue>
    <customValue>
        <fullName>730</fullName>
    </customValue>
    <customValue>
        <fullName>735</fullName>
    </customValue>
    <customValue>
        <fullName>740</fullName>
    </customValue>
    <customValue>
        <fullName>745</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>900</fullName>
    </customValue>
    <customValue>
        <fullName>MC9</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de validation DOR</fullName>
    </customValue>
    <customValue>
        <fullName>65</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de signature</fullName>
    </customValue>
    <customValue>
        <fullName>Accord Pickup : Non retenu</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>280</fullName>
    </customValue>
    <customValue>
        <fullName>290</fullName>
    </customValue>
    <customValue>
        <fullName>310</fullName>
    </customValue>
    <description>Mode du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_MOD</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_PAR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <customValue>
        <fullName>124</fullName>
    </customValue>
    <customValue>
        <fullName>125</fullName>
    </customValue>
    <customValue>
        <fullName>126</fullName>
    </customValue>
    <customValue>
        <fullName>134</fullName>
    </customValue>
    <customValue>
        <fullName>135</fullName>
    </customValue>
    <customValue>
        <fullName>140</fullName>
    </customValue>
    <customValue>
        <fullName>146</fullName>
    </customValue>
    <customValue>
        <fullName>177</fullName>
    </customValue>
    <customValue>
        <fullName>178</fullName>
    </customValue>
    <customValue>
        <fullName>179</fullName>
    </customValue>
    <customValue>
        <fullName>180</fullName>
    </customValue>
    <customValue>
        <fullName>181</fullName>
    </customValue>
    <customValue>
        <fullName>182</fullName>
    </customValue>
    <customValue>
        <fullName>183</fullName>
    </customValue>
    <customValue>
        <fullName>184</fullName>
    </customValue>
    <customValue>
        <fullName>185</fullName>
    </customValue>
    <customValue>
        <fullName>188</fullName>
    </customValue>
    <customValue>
        <fullName>189</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>190</fullName>
    </customValue>
    <customValue>
        <fullName>194</fullName>
    </customValue>
    <customValue>
        <fullName>195</fullName>
    </customValue>
    <customValue>
        <fullName>-2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>211</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <description>Liste des partenaires</description>
    <masterLabel>LOV_GLO_PAR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_PAY.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Belgique</fullName>
        <isActive>false</isActive>
        <label>Belgique</label>
    </customValue>
    <customValue>
        <fullName>Pays-Bas</fullName>
        <isActive>false</isActive>
        <label>Pays-Bas</label>
    </customValue>
    <description>Pays</description>
    <masterLabel>LOV_GLO_PAY</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP06_Account_Test.cls
/* Class that test the functionality of AP06_Account*/
    
    @isTest
    public class AP06_Account_Test {
        
        public testMethod static void TestcreateCase(){
            //Create Custom Settings country sequence
            CountriesSequence__c cs = new CountriesSequence__c(Name='Belgium' , Sequence__c = 'BE0001');
            insert cs;
            //Create Contact
            Contact testContact = Utils_TestMethods.CreateContact('Name');
            Contact testContact2 = Utils_TestMethods.CreateContact('Name2');
            Contact testContact3 = Utils_TestMethods.CreateContact('Name3');
            insert new list<contact>{testContact,testContact2,testContact3}; 
            list<Macroprofil__c> listMacroprofil = new list<Macroprofil__c>();
            Macroprofil__c testMacroprofil = Utils_TestMethods.CreateMacroprofil('test');
            listMacroprofil.add(testMacroprofil);
            Macroprofil__c testMacroprofil2 = Utils_TestMethods.CreateMacroprofil('test2');
            listMacroprofil.add(testMacroprofil2);
            insert listMacroprofil;
            
            String json1 = 
                '   [{'+
                '       \"Id_du_Macroprofil__c\": "'+testMacroprofil.id+'",'+
                '       \"MasterLabel\": \"MPBE1-Standard\",'+
                '       \"Pays__c\": \"Belgium\",'+
                '       \"Type_de_point__c\": \"20\"'+
                '   },{'+
                '       \"Id_du_Macroprofil__c\": "'+testMacroprofil2.id+'",'+
                '       \"MasterLabel\": \"MPBE1-Standard\",'+
                '       \"Type_de_point__c\": \"3\",'+
                '       \"Partenaire__c\": \"124\"'+
                '  }]';        
            AssociationPUDOMacroprofil_Test.setMetadata(
                'Select id, Pays__c, Partenaire__c, Type_de_point__c, Id_du_Macroprofil__c From Association_PUDO_Macroprofil__mdt',
                (List<Association_PUDO_Macroprofil__mdt>) JSON.deserialize( json1,  List<Association_PUDO_Macroprofil__mdt>.class )
            );
            
            List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c,ID_Requete_ContratNonRespecte__c
                                                                                  FROM Association_Record_Type_et_pays__mdt];
            
            
            map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
            for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
              associationRTPays.put(associationRT.MasterLabel, associationRT);  
            }
            
            list<account> listAccount = new list<account>();
            Account account1= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account 1'); 
            account1.RecordTypeId =associationRTPays.get('Belgium').ID_PUDO_Non_Suivi__c;
            account1.Type = '20';
            account1.BillingCountry ='Belgium';
            account1.ShippingCountry ='Belgium';
            account1.BillingCountryCode = 'BE';
            account1.ShippingCountryCode ='BE';
            account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
            account1.Operateur_Global__c = 'DPD_BNL';
            account1.BillingPostalCode ='1234';
            account1.ShippingPostalCode = '1243';
            account1.Long_Lat_adresse_de_livraison__Latitude__s=62;
            account1.Long_Lat_adresse_de_livraison__Longitude__s=21;
            listAccount.add(account1);
 
            //Create Account 2            
            Account account2= Utils_TestMethods.CreateAccount(testContact2, null, 'Test Account 2'); 
            account2.RecordTypeId =associationRTPays.get('Belgium').ID_PUDO_Non_Suivi__c;          
            account2.Mode__c = '';
            account2.Type = '20';
            account2.BillingCountry ='Belgium';
            account2.ShippingCountry ='Belgium';
            account2.BillingCountryCode = 'BE';
            account2.ShippingCountryCode ='BE';
            account2.Ville_de_l_adresse_de_livraison2__c ='Belgium';
            account2.Operateur_Global__c = 'DPD_BNL';
            account2.BillingPostalCode ='1234';
            account2.ShippingPostalCode = '1243';
            account2.Long_Lat_adresse_de_livraison__Latitude__s=62;
            account2.Long_Lat_adresse_de_livraison__Longitude__s=21;
            account2.Amplitude_horaire_du_relais__c = 90.22;
            account2.Lundi_Ouverture__c = '08:00';
            account2.Lundi_Fermeture__c  = '20:00'; 
            account2.Mardi_Ouverture__c = '08:00';
            account2.Mardi_Fermeture__c  = '20:00'; 
            account2.Mercredi_Ouverture__c = '08:00';
            account2.Mercredi_Fermeture__c  = '20:00';
            account2.Jeudi_ferme__c = false;
            account2.Jeudi_Ouverture__c = '08:00';
            account2.Jeudi_Fermeture__c  = '20:00';
            account2.Vendredi_ferme__c = false;
            account2.Vendredi_Ouverture__c = '08:00';
            account2.Vendredi_Fermeture__c  = '20:00';
            account2.Samedi_ferme__c = false;
            account2.Samedi_Ouverture__c = '08:00';
            account2.Samedi_Fermeture__c  = '20:00';
            account2.lundi_debut_pause_dejeuner__c='12:00';
            account2.lundi_fin_pause_dejeuner__c ='12:30';
            account2.mardi_debut_pause_dejeuner__c='12:00';
            account2.mardi_fin_pause_dejeuner__c ='12:30';
            account2.mercredi_debut_pause_dejeuner__c='12:00';
            account2.mercredi_fin_pause_dejeuner__c ='12:30';        
            account2.jeudi_debut_pause_dejeuner__c='12:00';
            account2.jeudi_fin_pause_dejeuner__c ='12:30';
            account2.vendredi_debut_pause_dejeuner__c='12:00';
            account2.vendredi_fin_pause_dejeuner__c ='12:30';
            account2.samedi_debut_pause_dejeuner__c='12:00';
            account2.samedi_fin_pause_dejeuner__c ='12:30';
            listAccount.add(account2);
            
            Account account3= Utils_TestMethods.CreateAccount(null, null, 'Test Account');
        	account3.RecordTypeId = associationRTPays.get('France').ID_PUDO_Non_Suivi__c;    
        	account3.ShippingCountry ='France';
        	account3.ShippingCountryCode='FR';
        	account3.Etat__c = '5';
        	account3.Operateur_Global__c = 'PUS_FR';
        	account3.ShippingPostalCode = '12345';
       		account3.Type ='2';
        	account3.N_TVA__c = 'Non';
            listAccount.add(account3);
            insert(listAccount);
            
            testContact.accountId = account1.id;
            testContact2.accountId = account2.id;
            update new list<contact>{testContact,testContact2};
                
            case requete = new case();
            requete.Subject=label.Requete_ObjetContratNonRespecte;
            requete.Status = label.Requette_En_attente_de_traitement;
            requete.RecordTypeId = associationRTPays.get('Belgium').ID_Requete_ContratNonRespecte__c;
            requete.AccountId = account1.id;
            insert requete;
            list<account> listAccountUpdate = new list<account>();
            account1.Date_de_la_formation_reelle__c = Date.newInstance(2018, 12, 9);
            account1.Amplitude_horaire_du_relais__c = 90.22;
            account1.Lundi_Ouverture__c = '08:00';
            account1.Lundi_Fermeture__c  = '20:00'; 
            account1.Mardi_Ouverture__c = '08:00';
            account1.Mardi_Fermeture__c  = '20:00'; 
            account1.Mercredi_Ouverture__c = '08:00';
            account1.Mercredi_Fermeture__c  = '20:00';
            account1.Jeudi_ferme__c = false;
            account1.Jeudi_Ouverture__c = '08:00';
            account1.Jeudi_Fermeture__c  = '20:00';
            account1.Vendredi_ferme__c = false;
            account1.Vendredi_Ouverture__c = '08:00';
            account1.Vendredi_Fermeture__c  = '20:00';
            account1.Samedi_ferme__c = false;
            account1.Samedi_Ouverture__c = '08:00';
            account1.Samedi_Fermeture__c  = '20:00';
            account1.lundi_debut_pause_dejeuner__c='12:00';
            account1.lundi_fin_pause_dejeuner__c ='12:30';
            account1.mardi_debut_pause_dejeuner__c='12:00';
            account1.mardi_fin_pause_dejeuner__c ='12:30';
            account1.mercredi_debut_pause_dejeuner__c='12:00';
            account1.mercredi_fin_pause_dejeuner__c ='12:30';        
            account1.jeudi_debut_pause_dejeuner__c='12:00';
            account1.jeudi_fin_pause_dejeuner__c ='12:30';
            account1.vendredi_debut_pause_dejeuner__c='12:00';
            account1.vendredi_fin_pause_dejeuner__c ='12:30';
            account1.samedi_debut_pause_dejeuner__c='12:00';
            account1.samedi_fin_pause_dejeuner__c ='12:30';
            listAccountUpdate.add(account1);
            
            account2.Amplitude_horaire_du_relais__c = 30;
            account2.Lundi_Ouverture__c = '10:30';
            account2.Lundi_Fermeture__c  = '17:45';        
            account2.lundi_debut_pause_dejeuner__c='14:30';
            account2.lundi_fin_pause_dejeuner__c ='16:30';	
            account2.Date_de_la_formation_reelle__c = Date.newInstance(2018, 12, 9);
            listAccountUpdate.add(account2);   
            
            account3.Amplitude_horaire_du_relais__c = 30;
            account3.Lundi_Ouverture__c = '10:30';
            account3.Lundi_Fermeture__c  = '17:45';        
            account3.lundi_debut_pause_dejeuner__c='14:30';
            account3.lundi_fin_pause_dejeuner__c ='17:30';	
            account3.Date_de_la_formation_reelle__c = Date.today();
            account3.Nom_Responsable_magasin__c = testcontact3.id;
            listAccountUpdate.add(account3);
            
            update listAccountUpdate;
        }
    }