force-app/main/default/objects/Account/fields/Amplitude_horaire_du_relais__c.field-meta.xml
<CustomField>
    <fullName>Amplitude_horaire_du_relais__c</fullName>
    <label>Amplitude horaire du relais</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/jeudi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>jeudi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/jeudi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>jeudi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/samedi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>samedi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Samedi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/samedi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>samedi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vendredi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>vendredi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vendredi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>vendredi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>DPD_BNL</fullName>
        <active>true</active>
        <businessProcess>DPD_BNL_Requêtes_Ponctuelles</businessProcess>
        <label>DPD_BNL_inactif_avec_scan_associé</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Date_de_debut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_de_fin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_HOR.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:30</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <description>Horaires d&#39;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP08_Conge_Indispo_Test.cls
@isTest
public class AP08_Conge_Indispo_Test {
    
    static testmethod void insertUpdateConge_Indispo() {
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('M1');
        insert macroprofil;
        Contact contact = Utils_TestMethods.CreateContact('Contact1');
        insert contact;
        
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id, MasterLabel,  
                                                                         ID_suivi_CO__c,ID_PUDO_Non_Suivi__c
                                                                         FROM Association_Record_Type_et_pays__mdt
                                                                         Where MasterLabel ='Belgium'
                                                                         Limit 1];
        List<Account> accountList = new List<Account>();
        Account account1 = Utils_TestMethods.CreateAccount(contact, macroprofil, 'Account 1');      
        account1.RecordTypeId = associationRTPays[0].ID_PUDO_Non_Suivi__c;
        account1.Type = '20';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.BillingPostalCode ='1234';
        account1.ShippingPostalCode = '1243';
        account1.Industry = '1';
        account1.Long_Lat_adresse_de_livraison__Latitude__s=62;
        account1.Long_Lat_adresse_de_livraison__Longitude__s=21;
        account1.Amplitude_horaire_du_relais__c = 90.22;
        account1.Lundi_Ouverture__c = '08:00';
        account1.Lundi_Fermeture__c  = '20:00'; 
        account1.Mardi_Ouverture__c = '08:00';
        account1.Mardi_Fermeture__c  = '20:00'; 
        account1.Mercredi_Ouverture__c = '08:00';
        account1.Mercredi_Fermeture__c  = '20:00';
        account1.Jeudi_ferme__c = false;
        account1.Jeudi_Ouverture__c = '08:00';
        account1.Jeudi_Fermeture__c  = '20:00';
        account1.Vendredi_ferme__c = false;
        account1.Vendredi_Ouverture__c = '08:00';
        account1.Vendredi_Fermeture__c  = '20:00';
        account1.Samedi_ferme__c = false;
        account1.Samedi_Ouverture__c = '08:00';
        account1.Samedi_Fermeture__c  = '20:00';
        account1.lundi_debut_pause_dejeuner__c='12:00';
        account1.lundi_fin_pause_dejeuner__c ='12:30';
        account1.mardi_debut_pause_dejeuner__c='12:00';
        account1.mardi_fin_pause_dejeuner__c ='12:30';
        account1.mercredi_debut_pause_dejeuner__c='12:00';
        account1.mercredi_fin_pause_dejeuner__c ='12:30';        
        account1.jeudi_debut_pause_dejeuner__c='12:00';
        account1.jeudi_fin_pause_dejeuner__c ='12:30';
        account1.vendredi_debut_pause_dejeuner__c='12:00';
        account1.vendredi_fin_pause_dejeuner__c ='12:30';
        account1.samedi_debut_pause_dejeuner__c='12:00';
        account1.samedi_fin_pause_dejeuner__c ='12:30';     
        accountList.add(account1);
        
        Account account2 = Utils_TestMethods.CreateAccount(contact, macroprofil, 'Account 2');
        account2.RecordTypeId = associationRTPays[0].ID_PUDO_Non_Suivi__c;
        account2.Type = '20';
        account2.BillingCountry ='Belgium';
        account2.ShippingCountry ='Belgium';
        account2.BillingCountryCode = 'BE';
        account2.ShippingCountryCode ='BE';
        account2.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account2.Operateur_Global__c = 'DPD_BNL';
        account2.BillingPostalCode ='1234';
        account2.ShippingPostalCode = '1243';
        account2.Industry = '1';
        account2.Long_Lat_adresse_de_livraison__Latitude__s=62;
        account2.Long_Lat_adresse_de_livraison__Longitude__s=21;
        account2.Amplitude_horaire_du_relais__c = 90.22;
        account2.Lundi_Ouverture__c = '08:00';
        account2.Lundi_Fermeture__c  = '20:00'; 
        account2.Mardi_Ouverture__c = '08:00';
        account2.Mardi_Fermeture__c  = '20:00'; 
        account2.Mercredi_Ouverture__c = '08:00';
        account2.Mercredi_Fermeture__c  = '20:00';
        account2.Jeudi_ferme__c = false;
        account2.Jeudi_Ouverture__c = '08:00';
        account2.Jeudi_Fermeture__c  = '20:00';
        account2.Vendredi_ferme__c = false;
        account2.Vendredi_Ouverture__c = '08:00';
        account2.Vendredi_Fermeture__c  = '20:00';
        account2.Samedi_ferme__c = false;
        account2.Samedi_Ouverture__c = '08:00';
        account2.Samedi_Fermeture__c  = '20:00';
        account2.lundi_debut_pause_dejeuner__c='12:00';
        account2.lundi_fin_pause_dejeuner__c ='12:30';
        account2.mardi_debut_pause_dejeuner__c='12:00';
        account2.mardi_fin_pause_dejeuner__c ='12:30';
        account2.mercredi_debut_pause_dejeuner__c='12:00';
        account2.mercredi_fin_pause_dejeuner__c ='12:30';        
        account2.jeudi_debut_pause_dejeuner__c='12:00';
        account2.jeudi_fin_pause_dejeuner__c ='12:30';
        account2.vendredi_debut_pause_dejeuner__c='12:00';
        account2.vendredi_fin_pause_dejeuner__c ='12:30';
        account2.samedi_debut_pause_dejeuner__c='12:00';
        account2.samedi_fin_pause_dejeuner__c ='12:30';       
        accountList.add(account2);
        insert accountList;
        
        
        List<Case> CaseList = new List<Case>();
        Case CaseAccount1 = new Case();
        CaseAccount1.Status = Label.ReQuette_En_attente_de_traitement;
        CaseAccount1.RecordTypeId = Label.RT_DPD_BNL_Conges_Requette;
        CaseAccount1.AccountId  =  account1.id; 
        CaseList.add(CaseAccount1);
        
        Case CaseAccount2 = new Case();
        CaseAccount2.Status = Label.ReQuette_En_attente_de_traitement;
        CaseAccount2.RecordTypeId = Label.RT_DPD_BNL_Conges_Requette;
        CaseAccount2.AccountId  =  account2.id; 
        CaseList.add(CaseAccount2);
        insert CaseList; 
        
        Integer thisYear = Date.today().year();
        Integer thisDay = Date.today().day();
        Integer thisMonth = Date.today().month();
        
        List<Conge_Indispo__c> cong_indispoList = new List<Conge_Indispo__c>();
        Conge_Indispo__c cong = Utils_TestMethods.CreateConge_Indispo(Label.RT_Conge_Indispo_Conge, 
                                                                      account1.id, 
                                                                      Date.newInstance(thisYear, thisMonth,thisDay ), 
                                                                      Date.newInstance(thisYear, thisMonth,thisDay ));
        cong_indispoList.add(cong);
        Conge_Indispo__c cong1 = Utils_TestMethods.CreateConge_Indispo(Label.RT_Conge_Indispo_Conge, 
                                                                       account2.id, 
                                                                       Date.newInstance(thisYear, thisMonth+1,thisDay ), 
                                                                       Date.newInstance(thisYear, thisMonth+1,thisDay ));
        
        cong_indispoList.add(cong1);
        insert cong_indispoList;
        
        cong1.Date_de_debut__c =Date.newInstance(thisYear, thisMonth,thisDay );
        cong1.Date_de_fin__c = Date.newInstance(thisYear, thisMonth,thisDay );
        update cong1;                
        
    }
}