force-app/main/default/objects/Account/fields/Amplitude_horaire_du_relais__c.field-meta.xml
<CustomField>
    <fullName>Amplitude_horaire_du_relais__c</fullName>
    <label>Amplitude horaire du relais</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Conge__c</fullName>
        <label>ID_Conge</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Requete_Conge__c</fullName>
        <label>ID_Requête_Congé</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_operationnel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact opérationnel</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_HOR.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <customValue>
        <fullName>16:30</fullName>
    </customValue>
    <customValue>
        <fullName>17:45</fullName>
    </customValue>
    <description>Horaires d&#39;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/customLookUpController_Test.cls
@isTest
public class customLookUpController_Test {
    static testMethod void testCustomLookupField() 
    {
        Contact newTestContact = Utils_TestMethods.CreateContact('John Bo');
        newTestContact.FirstName = 'John Bo';
        newTestContact.LastName = 'Bo';
        newTestContact.Contact_operationnel__c = true;
        insert newTestContact;
        
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('M1');
        insert macroprofil;
        
        List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c,ID_Requete_Conge__c,ID_CONGE__c
                                                                              FROM Association_Record_Type_et_pays__mdt];
            
        
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
            associationRTPays.put(associationRT.MasterLabel, associationRT);  
        }
        Account account1= Utils_TestMethods.CreateAccount(newTestContact, null, 'Test Account 1'); 
        account1.RecordTypeId =associationRTPays.get('Belgium').ID_PUDO_Non_Suivi__c;
        account1.Type = '20';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.BillingPostalCode ='1234';
        account1.ShippingPostalCode = '1243';
        account1.Amplitude_horaire_du_relais__c = 30;
        account1.Lundi_Ouverture__c = '10:30';
        account1.Lundi_Fermeture__c  = '17:45';        
        account1.lundi_debut_pause_dejeuner__c='14:30';
        account1.lundi_fin_pause_dejeuner__c ='16:30';  
        account1.Industry = '6';
        account1.Long_Lat_adresse_de_livraison__Latitude__s=62;
        account1.Long_Lat_adresse_de_livraison__Longitude__s=21;
        insert account1;
        newTestContact.AccountId = account1.id;
        update newTestContact;
        customLookUpController.fetchLookUpValues('John Bo', 'Contact', account1.id);
        customLookUpController.getContactNameApex(newTestContact.id);
    }
}