force-app/main/default/objects/Account/fields/Amplitude_horaire_du_relais__c.field-meta.xml
<CustomField>
    <fullName>Amplitude_horaire_du_relais__c</fullName>
    <label>Amplitude horaire du relais</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Duree_pause_dejeuner_respectee__c.field-meta.xml
<CustomField>
    <fullName>Duree_pause_dejeuner_respectee__c</fullName>
    <description>Entre lundi et samedi</description>
    <formula>IF( 
AND( 
VALUE(SUBSTITUTE(TEXT( lundi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( lundi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( mardi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( mardi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( mercredi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( mercredi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( jeudi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( jeudi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( vendredi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( vendredi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )), 
VALUE(SUBSTITUTE(TEXT( samedi_fin_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100 -VALUE(SUBSTITUTE(TEXT( samedi_debut_pause_dejeuner__c), &#39;:&#39;, &#39;&#39;))/100  &lt;= VALUE(TEXT( Duree_pause_dejeuner_en_h__c )) ), 

IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;) 
)</formula>
    <inlineHelpText>Between Monday and Saturday</inlineHelpText>
    <label>Durée pause déjeuner respectée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Heure_fermeture_minimale_respectee__c.field-meta.xml
<CustomField>
    <fullName>Heure_fermeture_minimale_respectee__c</fullName>
    <formula>IF( 
AND( 
OR( 
VALUE(LEFT( TEXT( Lundi_Fermeture__c ) , 2)) &gt;=  VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c) ), 
VALUE(LEFT( TEXT( Lundi_Fermeture__c ) , 2)) = 00), 

OR( 
VALUE(LEFT( TEXT( Mardi_Fermeture__c ) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT( TEXT( Mardi_Fermeture__c ) , 2)) = 00), 

OR( 
VALUE(LEFT( TEXT(Mercredi_Fermeture__c ) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Mercredi_Fermeture__c ), 2))=00), 


OR( 
VALUE(LEFT( TEXT(Jeudi_Fermeture__c) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Jeudi_Fermeture__c), 2))=00), 

OR( 
VALUE(LEFT( TEXT(Vendredi_Fermeture__c) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Vendredi_Fermeture__c), 2))=00), 

OR( 
VALUE(LEFT( TEXT(Samedi_Fermeture__c) , 2)) &gt;= VALUE(TEXT( Heure_de_fermeture_minimale_en_h__c)), 
VALUE(LEFT(TEXT(Samedi_Fermeture__c), 2))=00)), 


IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Heure fermeture minimale respectée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Heure_ouverture_minimale_respect_e__c.field-meta.xml
<CustomField>
    <fullName>Heure_ouverture_minimale_respect_e__c</fullName>
    <formula>IF( 
AND( 
OR( 
AND( 
VALUE(LEFT( TEXT(Lundi_Ouverture__c) , 2))&gt;=05, 
VALUE(LEFT(TEXT(Lundi_Ouverture__c), 2))&lt;= VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c )))), 



VALUE(LEFT( TEXT(Mardi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Mardi_Ouverture__c), 2))&lt;=VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c )), 
VALUE(LEFT( TEXT( Mercredi_Ouverture__c ) , 2))&gt;=05 , VALUE(LEFT(TEXT(Mercredi_Ouverture__c), 2))&lt;=10, 
VALUE(LEFT( TEXT(Jeudi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Jeudi_Ouverture__c), 2))&lt;=VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c )), 
VALUE(LEFT( TEXT(Vendredi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Vendredi_Ouverture__c), 2))&lt;=10, 
VALUE(LEFT( TEXT(Samedi_Ouverture__c) , 2))&gt;=05 , VALUE(LEFT(TEXT(Samedi_Ouverture__c), 2))&lt;=VALUE(TEXT( Heure_d_ouverture_minimale_en_h__c ))), 


IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;), 
IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Heure ouverture minimale respectée</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Seuil_de_l_amplitude_horaire_respect__c.field-meta.xml
<CustomField>
    <fullName>Seuil_de_l_amplitude_horaire_respect__c</fullName>
    <formula>IF( Amplitude_horaire_du_relais__c &gt;= Value(Text(Seuil_de_l_amplitude_horaire_en_h_c__c)),IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;Green&quot;),IMAGE(&quot;/img/samples/flag_red.gif&quot;, &quot;Red&quot;))</formula>
    <label>Seuil de l&#39;amplitude horaire respecté</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Anomalie__c.object
<CustomObject>
    <description>Objet technique permettant de stocker les anomalies associées au PUDO, en particulier les anomalies provenant de la télécollecte.</description>
    <fields>
        <fullName>Numero_Anomalie__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Numéro Anomalie</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PUDO__c</fullName>
        <label>PUDO</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Anomalies_de_Telecollecte</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Anomalie</label>
    <nameField>
        <label>Numéro de l&apos;anomalie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Conge__c</fullName>
        <label>ID_Conge</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Requete_Conge__c</fullName>
        <label>ID_Requête_Congé</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Anomalie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Anomalie</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Anomalie__c.PUDO__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Anomalie__c</referenceTo>
        <relationshipLabel>Requêtes</relationshipLabel>
        <relationshipName>Requ_tes</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>DPD_BNL</fullName>
        <active>true</active>
        <businessProcess>DPD_BNL_Requêtes_Ponctuelles</businessProcess>
        <label>DPD_BNL_inactif_avec_scan_associé</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Anomalie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Champ technique servant à référencer une anomalie</description>
        <label>Anomalie</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Anomalie__c.PUDO__c</field>
                <operation>equals</operation>
                <valueField>$Source.Nom_du_compte__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Anomalie__c</referenceTo>
        <relationshipLabel>Congés/disponibilités/indisponibilités</relationshipLabel>
        <relationshipName>Cong_s_disponibilit_s_indisponibilit_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>IF ( Date_de_debut__c &gt;  TODAY() ,$Label.CongeIndispo_A_Venir_2,
IF ( Date_de_fin__c  &lt;   TODAY() ,$Label.Conge_Indispo_Passe_2,$Label.CongeIndispo_En_Cours_2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_HOR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>14:30</fullName>
    </customValue>
    <customValue>
        <fullName>16:30</fullName>
    </customValue>
    <customValue>
        <fullName>17:45</fullName>
    </customValue>
    <description>Horaires d&apos;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/AP02_Case_Test.cls
@isTest
public class AP02_Case_Test {
    static testmethod void updateCase() {
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('M1');
        insert macroprofil;
        Contact contact = Utils_TestMethods.CreateContact('Contact1');
        insert contact;
        
        List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c,ID_Requete_Conge__c,ID_CONGE__c
                                                                              FROM Association_Record_Type_et_pays__mdt];
            
            
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
           associationRTPays.put(associationRT.MasterLabel, associationRT);  
        }
        Account account1= Utils_TestMethods.CreateAccount(contact, null, 'Test Account 1'); 
        account1.RecordTypeId =associationRTPays.get('Belgium').ID_PUDO_Non_Suivi__c;
        account1.Type = '20';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.BillingPostalCode ='1234';
        account1.ShippingPostalCode = '1243';
        account1.Amplitude_horaire_du_relais__c = 30;
        account1.Lundi_Ouverture__c = '10:30';
        account1.Lundi_Fermeture__c  = '17:45';        
        account1.lundi_debut_pause_dejeuner__c='14:30';
        account1.lundi_fin_pause_dejeuner__c ='16:30';	
        account1.Industry = '6';
        account1.Long_Lat_adresse_de_livraison__Latitude__s=62;
        account1.Long_Lat_adresse_de_livraison__Longitude__s=21;
        insert account1;
        List<Account> accountList = [SELECT Seuil_de_l_amplitude_horaire_respect__c, Heure_fermeture_minimale_respectee__c,
                                     Heure_ouverture_minimale_respect_e__c, Duree_pause_dejeuner_respectee__c,Industry
                                     FROM Account
                                     WHERE Id =:account1.id ];
        system.debug('accountList: ' + accountList);
        
        
        
        Integer thisYear = Date.today().year();
        Integer thisDay = Date.today().day();
        Integer thisMonth = Date.today().month();
        
        Conge_Indispo__c cong = Utils_TestMethods.CreateConge_Indispo(associationRTPays.get('Belgium').ID_CONGE__C, 
                                                                      account1.id, 
                                                                      Date.newInstance(thisYear, thisMonth,thisDay ), 
                                                                      Date.newInstance(thisYear, thisMonth,thisDay ));
        insert cong;
        
        Anomalie__c anomalie = new Anomalie__c();
        anomalie.PUDO__c = account1.id;
        anomalie.Numero_Anomalie__c = '1';
        anomalie.Statut__c = '1';
        insert anomalie;
        
        Case CaseAccount1 = new Case();
        CaseAccount1.Status = Label.ReQuette_En_attente_de_traitement;
        CaseAccount1.RecordTypeId = associationRTPays.get('Belgium').ID_Requete_Conge__c;
        CaseAccount1.AccountId  =  account1.id; 
        CaseAccount1.Anomalie__c = anomalie.id;
        insert CaseAccount1;
        
        caseAccount1.Status = Label.Requete_Terminee;
        update caseAccount1;
        List<Case> caseList = [select Status from Case where id =: caseAccount1.Id];
        for(Case currentCase: caseList)
        {
            System.assertEquals(currentCase.Status, Label.ReQuette_En_attente_de_traitement);
        }
    }
}