force-app/main/default/objects/Account/fields/Commentaires__c.field-meta.xml
<CustomField>
    <fullName>Commentaires__c</fullName>
    <label>Commentaires</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_operationnel_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_operationnel_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact opérationnel</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Anomalie__c.object
<CustomObject>
    <description>Objet technique permettant de stocker les anomalies associées au PUDO, en particulier les anomalies provenant de la télécollecte.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PUDO__c</fullName>
        <label>PUDO</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Anomalies_de_Telecollecte</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tech_ContactPudo__c</fullName>
        <formula>PUDO__r.Contact_operationnel_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tech_ContactPudo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SyncPudo</fullName>
                </value>
                <value>
                    <fullName>NoDevice</fullName>
                </value>
                <value>
                    <fullName>TooManyDevices</fullName>
                </value>
                <value>
                    <fullName>NoDecommissioned</fullName>
                </value>
                <value>
                    <fullName>Association à tort Etat 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Anomalie</label>
    <nameField>
        <label>Numéro de l&apos;anomalie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_AnomalieSynchro__c</fullName>
        <label>ID_AnomalieSynchro</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_File_service_line__c</fullName>
        <label>ID_File_service_line</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Indisponibilit_partenaire__c</fullName>
        <label>ID_Indisponibilité_partenaire</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Indisponibilite_standard__c</fullName>
        <label>ID_Indisponibilite_standard</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_ManagerQueue__c</fullName>
        <label>ID_ManagerQueue</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_MoyenScan_Actif_Sans__c</fullName>
        <label>ID_MoyenScan_Actif_Sans</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_WebHelpQueue__c</fullName>
        <description>Le propriétaire de la requête de type anomalie de synchronisation</description>
        <inlineHelpText>Le propriétaire de la requête de type anomalie de synchronisation</inlineHelpText>
        <label>ID_WebHelpQueue</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Anomalie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Anomalie</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Anomalie__c.PUDO__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Anomalie__c</referenceTo>
        <relationshipLabel>Requêtes</relationshipLabel>
        <relationshipName>Requ_tes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Indisponibilite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Indisponibilité</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Conge_Indispo__c.Nom_du_compte__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Conge_Indispo__c</referenceTo>
        <relationshipLabel>Requêtes</relationshipLabel>
        <relationshipName>Requ_tes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_de_la_requete__c</fullName>
        <label>Objet de la requête</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anomalie de synchronisation d’un relais</fullName>
                    <label>Anomalie de synchronisation d&apos;un relais</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Sinistre / Travaux / Santé</fullName>
                    <label>Indisponibilité - Problème opérationnel Sinistre / Travaux / Santé</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Qualité de Service</fullName>
                    <label>Indisponibilité - Problème opérationnel Qualité de Service</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Panne PDA</fullName>
                    <label>Indisponibilité - Problème PDA / Panne PDA</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Problème de synchronisation</fullName>
                    <label>Indisponibilité - Problème PDA / Problème de synchronisation</label>
                </value>
                <value>
                    <fullName>Indisponibilité problème opérationnel - Injoignabilité</fullName>
                </value>
                <value>
                    <fullName>Démarrage d&apos;activité</fullName>
                </value>
                <value>
                    <fullName>Relais sans formation avec moyens de scans associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif avec plusieurs moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Les relais actifs avec terme contrat non respecté</fullName>
                </value>
                <value>
                    <fullName>Les Congés du relais</fullName>
                </value>
                <value>
                    <fullName>Relais inactif avec moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif sans moyen de scan associé</fullName>
                </value>
                <value>
                    <fullName>Les horaires insuffisants du relais</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Anomalie colis</fullName>
                    <isActive>false</isActive>
                    <label>Indisponibilité Problème opérationnel Anomalie colis</label>
                </value>
                <value>
                    <fullName>Relais actif sans formation avec moyen de scan associé</fullName>
                    <isActive>false</isActive>
                    <label>Relais actif sans formation avec moyen de scan associé</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Point_relais_ne_repond_pas__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Champ tech pour sortie de vue de liste et rentrée à H+2</description>
        <label>NRP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Anomalie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Champ technique servant à référencer une anomalie</description>
        <label>Anomalie</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Anomalie__c.PUDO__c</field>
                <operation>equals</operation>
                <valueField>$Source.Nom_du_compte__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Anomalie__c</referenceTo>
        <relationshipLabel>Congés/disponibilités/indisponibilités</relationshipLabel>
        <relationshipName>Cong_s_disponibilit_s_indisponibilit_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_de_debut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_de_fin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nom_du_compte__c</fullName>
        <label>Nom du compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sous_type__c</fullName>
        <label>Sous type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_d_indisponibilite__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sinistre / Travaux / Santé</fullName>
                </value>
                <value>
                    <fullName>Qualité de service</fullName>
                </value>
                <value>
                    <fullName>Problème de synchronisation</fullName>
                </value>
                <value>
                    <fullName>Panne PDA</fullName>
                </value>
                <value>
                    <fullName>Injoignabilité</fullName>
                </value>
                <value>
                    <fullName>Pas de PDA associé</fullName>
                </value>
                <value>
                    <fullName>Anomalie colis</fullName>
                    <isActive>false</isActive>
                    <label>Anomalie colis</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>IF ( Date_de_debut__c &gt;  TODAY() ,$Label.CongeIndispo_A_Venir_2,
IF ( Date_de_fin__c  &lt;   TODAY() ,$Label.Conge_Indispo_Passe_2,$Label.CongeIndispo_En_Cours_2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_d_indisponibilite__c</fullName>
        <description>Ne pas activer l&apos;option &quot;Restreindre la liste sélectionnée aux valeurs définies dans l’ensemble de valeurs.	&quot; pour ne pas bloquer le PB qui crée automatiquement les indispos suite à des créations d&apos;anomalies.</description>
        <label>Type d&apos;indisponibilité</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>Planifiée</fullName>
                </value>
                <value>
                    <fullName>Imprévue</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <recordTypes>
        <fullName>Conge</fullName>
        <active>true</active>
        <description>Permet de créer une période de congés.</description>
        <label>Congé</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AP01_AnomaliesPB.cls
/*
* @Description	: Classe pour remplacer le process builder de l'anomalie (ANOM_PB_01_Telecollecte)
* 				  Crée de nouveaux requêtes ou des congés indispo selon les critères des anomalies
* @author		: TMAEITL FEK
* @Test Class	: 
* 
* 
* TODO : Create a batch for the planned actions
*/
public class AP01_AnomaliesPB {
    
    public static void ANOM_PB_01_Telecollecte(List<Anomalie__c> LAnomalies){
        list<Id> listIDs = new list<Id>();
        list<Id> listAccountIDs = new list<Id>();
        for(Anomalie__c a:LAnomalies){
            listIDs.add(a.Id);
            listAccountIDs.add(a.PUDO__c);
        }
        ANOM_PB_01_Telecollecte(listIDs, listAccountIDs);
    }
    
    public static void ANOM_PB_01_Telecollecte(List<Id> LAnomalies,List<Id> listAccountIDs){
        List<Case> LCasesToInsert = new List<Case>();
        List<Case> LCasesToInsert1 = new List<Case>();
        List<Case> LCasesToUpdate = new List<Case>();        
        List<Conge_Indispo__c> LCongesIndispoToInsert = new List<Conge_Indispo__c>();
        List<Conge_Indispo__c> LCongesIndispoToUpdate = new List<Conge_Indispo__c>();
        
        List< Association_Record_Type_et_pays__mdt> associationRTPaysBNL = [Select Id, MasterLabel, ID_AnomalieSynchro__c, ID_ManagerQueue__c, ID_WebHelpQueue__c,ID_Indisponibilite_standard__c,ID_Indisponibilit_partenaire__c,ID_MoyenScan_Actif_Sans__c,ID_File_service_line__c 
                                                                            FROM Association_Record_Type_et_pays__mdt];
        Map<String,Association_Record_Type_et_pays__mdt> mapassociationRTPaysBNL =  new Map<String,Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord: associationRTPaysBNL)
        {
            mapassociationRTPaysBNL.put(mdtRecord.MasterLabel, mdtRecord);
        }
        List<Anomalie__c> LAnomaliesWDetails = [SELECT Id, Type__c, Statut__c, Description__c,Tech_ContactPudo__c, PUDO__c,PUDO__r.type, PUDO__r.Contact_operationnel_1__c, PUDO__r.RecordType.DeveloperName,PUDO__r.ShippingCountry,                                                
                                                (SELECT Id, Status FROM Requ_tes__r),
                                                (SELECT Id, Date_de_fin__c FROM Cong_s_disponibilit_s_indisponibilit_s__r)
                                                FROM Anomalie__c
                                                WHERE Id IN :LAnomalies
                                               ];
        
        //added for 144271
        List<String> listOfIndisStand = Label.CongInd_RT_IndispoStandard_ALL.split(';');
        map<id,Account> mapAccount = new map<id,account>([select id,name, 
                                                          (select id,casenumber,account.ShippingCountry,recordtypeid from cases 
                                                           where Status <> 'Terminée'),
                                                          (select id,Type_d_indisponibilite__c
                                                           from Conges__r 
                                                           where statut__c = :label.CongeIndispo_En_Cours
                                                           //commented for 144271
                                                           /*and ( Type_d_indisponibilite__c = '2'
                                                                or Type_d_indisponibilite__c = '3'
                                                                or Type_d_indisponibilite__c = '4')*/
                                                           and recordtypeId in :listOfIndisStand)
                                                          from account 
                                                          where id in :listAccountIDs]);
        
        system.debug('LAnomaliesWDetails '+LAnomaliesWDetails);
        for(Anomalie__c anom : LAnomaliesWDetails){
            if(anom.Type__c == 'SyncPudo' && anom.Statut__c == '1'){
                list<case> listCases = mapAccount.get(anom.PUDO__c).cases;
                list<case> listCaseSynchro = new list<case>(); 
                for(case requete : listCases){
                    
                    if(requete.recordTypeId == mapassociationRTPaysBNL.get(requete.account.ShippingCountry).ID_AnomalieSynchro__c){
                        listCaseSynchro.add(requete);
                    }
                    
                }                
                list<Conge_Indispo__c> listIndispos = mapAccount.get(anom.PUDO__c).Conges__r; 
                list<Conge_Indispo__c> listInjoignables = new list<Conge_Indispo__c>();
                for(Conge_Indispo__c indispo : listIndispos){
                    if(indispo.Type_d_indisponibilite__c == '3'){
                        listInjoignables.add(indispo);  
                    }
                }

                if(listCaseSynchro.size() == 0 && listIndispos.size() == 0){
                    // if anomalie's account is not France
                    if(anom.PUDO__r.ShippingCountry != 'France'){
                        system.debug('AP01_AnomaliePB here ');
                        //Hungary + BNL
                            LCasesToInsert.add(new Case(AccountId = anom.PUDO__c, Anomalie__c = anom.Id, ContactId = anom.PUDO__r.Contact_operationnel_1__c,
                                                        OwnerId = mapassociationRTPaysBNL.get(anom.PUDO__r.ShippingCountry).ID_File_service_line__c, RecordTypeId = mapassociationRTPaysBNL.get(anom.PUDO__r.ShippingCountry).ID_AnomalieSynchro__c, Status = '0',  Subject = Label.Case_Subject_AnomalieDeSynchro
                                                        ,Object_de_la_requete__c = 'Anomalie de synchronisation d’un relais'
                                                       ));
                        
                    }
                    // if anomalie's account is  France
                    else if(anom.PUDO__r.ShippingCountry == 'France' && listInjoignables.size()==0)
                    {
                        LCasesToInsert.add(new Case(AccountId = anom.PUDO__c, Anomalie__c = anom.Id, ContactId = anom.PUDO__r.Contact_operationnel_1__c,
                                                    OwnerId = mapassociationRTPaysBNL.get(anom.PUDO__r.ShippingCountry).ID_WebHelpQueue__c, RecordTypeId = mapassociationRTPaysBNL.get(anom.PUDO__r.ShippingCountry).ID_AnomalieSynchro__c, Status = Label.Case_Status_AttenteDeTraitement,  Subject = Label.Case_Subject_AnomalieDeSynchro,
                                                    Object_de_la_requete__c = 'Anomalie de synchronisation d’un relais'
                                                   ));
                    }
                    //ID_AnomalieSynchro__c
                }
            }else if(anom.Type__c == 'SyncPudo' && anom.Statut__c == '0'){
                system.debug('JMB AP01_AnomaliesPB SyncPudo 0');
                for(Case c : anom.Requ_tes__r){
                    c.Status = 'Terminée'; LCasesToUpdate.add(c);
                }
            }else if(anom.PUDO__r.RecordType.DeveloperName != 'PUS_FR_Consigne' && anom.PUDO__r.RecordType.DeveloperName != 'DPD_BNL_Consigne' && anom.Type__c == 'NoDevice' && anom.Statut__c == '1'){
                system.debug('JMB AP01_AnomaliesPB NoDevice 1 FR');
                if(Label.RT_France_Compte.contains(anom.PUDO__r.recordtypeId)){
                    LCongesIndispoToInsert.add(new Conge_Indispo__c(Nom_du_compte__c = anom.PUDO__c, Anomalie__c = anom.Id, Commentaires__c = anom.Description__c,
                                                                    Date_de_debut__c = System.today(), RecordTypeId = mapassociationRTPaysBNL.get(anom.PUDO__r.ShippingCountry).ID_Indisponibilite_standard__c, Type_d_indisponibilite__c = '4'
                                                                   ));
                }else if(Label.RT_INT_Compte.contains(anom.PUDO__r.recordtypeId) || Label.RT_INT_Compte2.contains(anom.PUDO__r.recordtypeId)){
                    //Hungary + BNL
                        LCasesToInsert.add(new Case (status = 'En attente de traitement',
                                                     subject = 'Relais actif sans moyen de scan associé',
                                                     Object_de_la_requete__c ='Relais actif sans moyen de scan associé',
                                                     recordtypeID = mapassociationRTPaysBNL.get(anom.PUDO__r.ShippingCountry).ID_MoyenScan_Actif_Sans__c,
                                                     accountid = anom.PUDO__c,
                                                     contactid = anom.Tech_ContactPudo__c,
                                                     Point_relais_ne_repond_pas__c = false,
                                                     Anomalie__c = anom.id));
                    if(anom.PUDO__r.type =='2'){
                        LCongesIndispoToInsert.add(new Conge_Indispo__c(Type_d_indisponibilite__c ='4',
                                                                        Sous_type__c ='Pas de PDA associé',
                                                                        Nom_du_compte__c = anom.pudo__c,
                                                                        Anomalie__c = anom.id,
                                                                        recordtypeID = mapassociationRTPaysBNL.get(anom.PUDO__r.ShippingCountry).ID_Indisponibilite_standard__c,
                                                                        Date_de_debut__c = date.today()
                                                                       ));
                        
                    }else if(anom.PUDO__r.type =='3') {
                        LCongesIndispoToInsert.add(new Conge_Indispo__c(Type_d_indisponibilite__c ='4', Sous_type__c ='Pas de PDA associé', Nom_du_compte__c = anom.pudo__c, Anomalie__c = anom.id,recordtypeID = mapassociationRTPaysBNL.get(anom.PUDO__r.ShippingCountry).ID_Indisponibilit_partenaire__c,Date_de_debut__c = date.today()
                                                                       ));}}
            }else if(anom.Type__c == 'NoDevice' && anom.Statut__c == '0'){
                system.debug('JMB AP01_AnomaliesPB NoDevice 0');
                for(Conge_Indispo__c c : anom.Cong_s_disponibilit_s_indisponibilit_s__r){
                    c.Date_de_fin__c = System.today();LCongesIndispoToUpdate.add(c);}
                for(Case c : anom.Requ_tes__r){
                    c.Status = 'Terminée'; LCasesToUpdate.add(c);}
            }
        }
        
        Map<Integer, List<sObject>> MLsObjectsToInsertUpdate = new Map<Integer, List<sObject>>();
        Map<Integer, List<sObject>> MLsObjectsToInsertUpdate1 = new Map<Integer, List<sObject>>();
        Map<Integer, Boolean> MisUpdate = new Map<Integer, Boolean>();
        Map<Integer, Boolean> MisUpdate1 = new Map<Integer, Boolean>();
        Integer i = 0;
                system.debug('MisUpdate ' + MisUpdate);
        system.debug('LCongesIndispoToInsert ' + LCongesIndispoToInsert);
        system.debug('LCongesIndispoToUpdate ' + LCongesIndispoToUpdate);
        
        if(LCasesToInsert.size() > 0){
            system.debug('case insert');
            MLsObjectsToInsertUpdate.put(i, LCasesToInsert);
            MisUpdate.put(i++, false);
        }//System.enqueueJob(new Queue_AsyncExecution(LCasesToInsert, false));}//insert LCasesToInsert;}
        if(LCasesToUpdate.size() > 0){
            system.debug('case update');
            MLsObjectsToInsertUpdate.put(i, LCasesToUpdate);
            MisUpdate.put(i++, true);
        }//System.enqueueJob(new Queue_AsyncExecution(LCasesToUpdate, true));}//update LCasesToUpdate;}
        if(LCongesIndispoToInsert.size() > 0){
            system.debug('conge insert');
            MLsObjectsToInsertUpdate.put(i, LCongesIndispoToInsert);
            MisUpdate.put(i++, false);
        }//System.enqueueJob(new Queue_AsyncExecution(LCongesIndispoToInsert, false));}//insert LCongesIndispoToInsert; }

        if(LCongesIndispoToUpdate.size() > 0)
        {
            system.debug('conge update');
            MLsObjectsToInsertUpdate.put(i, LCongesIndispoToUpdate);
            MisUpdate.put(i++, true);
        }//System.enqueueJob(new Queue_AsyncExecution(LCongesIndispoToUpdate, true));}// update LCongesIndispoToUpdate;}
        system.debug('MLsObjectsToInsertUpdate '+MLsObjectsToInsertUpdate);
        system.debug('MLsObjectsToInsertUpdate.size() '+MLsObjectsToInsertUpdate.size());
        System.enqueueJob(new Queue_AsyncExecution(MLsObjectsToInsertUpdate, MisUpdate, 0));
        
        
    }
}