force-app/main/default/objects/Account/fields/Commentaires__c.field-meta.xml
<CustomField>
    <fullName>Commentaires__c</fullName>
    <label>Commentaires</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_de_fin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <recordTypes>
        <fullName>Conge</fullName>
        <active>true</active>
        <description>Permet de créer une période de congés.</description>
        <label>Congé</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AP06_Conge_Indispo_Test.cls
@isTest
public class AP06_Conge_Indispo_Test { 
    static testMethod void updateClosedConge(){
        User user = [SELECT id , BypassValidationRule__c from User 
                     WHERE id = : Userinfo.getUserId()];
        user.BypassValidationRule__c = true;
        update user;
       // System.runAs(user) { 
            Macroprofil__c mp = Utils_TestMethods.CreateMacroprofil('mp1');
            insert mp;  
            Contact c = Utils_TestMethods.CreateContact('TestContact');
            insert c;
            Account a = Utils_TestMethods.CreateAccount(c, mp, 'TestPudoNoCo');    
            insert a;
            Id congeRTypeId = Schema.SObjectType.Conge_Indispo__c.getRecordTypeInfosByName().get(Label.CongeRT).getRecordTypeId();
        	
            Conge_Indispo__c conge = Utils_TestMethods.CreateConge_Indispo(congeRTypeId, a.Id , Date.today().addDays(+15), Date.today().addDays(+20) );
            try {
                insert conge; 
                System.debug('!!!gho inserted');
            }catch(Exception e) {
                System.debug('!!!gho inserted exception ');
            }
            
            
            conge.Date_de_fin__c = Date.today().addDays(-9);
            Test.startTest();
            try {
                update conge;
                System.debug('!!!gho updated'); 
                Id indispoRTId  = Schema.SObjectType.Conge_Indispo__c.getRecordTypeInfosByName().get(Label.IndisponibiliteStandardRT).getRecordTypeId();
                Conge_Indispo__c conge1 = Utils_TestMethods.CreateConge_Indispo(indispoRTId, a.Id , Date.today().addDays(-12), Date.today().addDays(-5) );
                insert conge1;
                conge1.Commentaires__c = 'test';
                update conge1;
        	}catch(Exception e) {
                System.assert(true, e.getMessage().contains('Vous n\'avez pas le droit de modifier '  + Label.CongeRT + ' Avec un statut dépassé'));
            }
            Test.stopTest();
        //}
        
    } 
}