force-app/main/default/objects/Account/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Configuration_Site__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Configuration_Site__c.Tech_Compte__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Configuration_Site__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recopie_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Recopie_Configuration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recopie Configuration?</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Casier_Site__c.object
<CustomObject>
    <fields>
        <fullName>Configuration_Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Configuration Site</label>
        <referenceTo>Configuration_Site__c</referenceTo>
        <relationshipLabel>Casier Site</relationshipLabel>
        <relationshipName>Casier_Site</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Casier Site</label>
    <nameField>
        <label>Nom de Casier Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Casier Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Configuration__c.object
<CustomObject>
    <label>Configuration</label>
    <nameField>
        <label>Nom de Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Configuration_Locker_Type__c.object
<CustomObject>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>Configurations Locker Type</relationshipLabel>
        <relationshipName>Configurations_Locker_Type</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type_de_casier__c</fullName>
        <label>Type de casier</label>
        <referenceTo>Type_de_casier__c</referenceTo>
        <relationshipLabel>Configurations Locker Type</relationshipLabel>
        <relationshipName>Configurations_Locker_Type</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Configuration Locker Type</label>
    <nameField>
        <displayFormat>CONF_LT_{0000}</displayFormat>
        <label>Nom de Configuration Locker Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurations Locker Type</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Configuration_Site__c.object
<CustomObject>
    <label>Configuration Site</label>
    <nameField>
        <label>Nom de Configuration Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Type_de_casier__c.object
<CustomObject>
    <label>Type de casier</label>
    <nameField>
        <label>Nom de Type de casier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de casier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VFC07_ConfigurationController.cls
/*
* Author: John Boutros
* Modified By: -
* Date : 06/12/2017
* Description: Ouvrir une page VP et remplir le champ Configuration, puis copier l'ancien objet Configuration (si il y en a un)
* dans Configuration Site et copier l'object Configuration Locker Type Casier Site.
* Test classe: VFC07_Configuration_TEST
Coverage : 100%
*/
public class VFC07_ConfigurationController {
    public boolean displayPopup {get; set;}     
    public String accountID{get; set;}
    public Account thisAccount {get; set;}
    public PageReference pageRef;
    public string error {get;set;}
    
    public VFC07_ConfigurationController(ApexPages.StandardController controller) {
        accountID = ApexPages.currentPage().getParameters().get('id'); 
        thisAccount = (Account)controller.getRecord();
        displayPopup = true;    
    }
    //Method created to update the configuation__c on the Account Object and return to the account's record
    public PageReference save() {
        displayPopup = true;   
        pageRef = new PageReference('/'+accountID);
        if(accountID != null)
        {
            try {
                thisaccount.Recopie_Configuration__c = true;
                update thisaccount;
                return pageRef;
            } catch(exception e) {
                error = e.getMessage();
                System.debug('An unexpected error has occurred: ' + e.getMessage());
            }
        }
        return null;
    }
    //Method created to close the popup and return to the account's record
    public PageReference closePopup() {     
        pageRef = new PageReference('/'+thisAccount.Id);
        displayPopup = false;   
        return pageRef;
    }       
    //Method created to copy Configuration__c to Configuration_Site__c
    //and Configuration_Locker_Type__c &  Type_de_casier__c to Casier_Site__c
    
}