force-app/main/default/objects/Account/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Configuration_Site__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Configuration_Site__c.Tech_Compte__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Configuration_Site__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Recopie_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Recopie_Configuration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recopie Configuration?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seuil_calcule__c.field-meta.xml
<CustomField>
    <fullName>Seuil_calcule__c</fullName>
    <formula>((((Hauteur_cm__c  *  Largeur_cm__c  *  Profondeur_cm__c ) / 1000) / 21) / 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Seuil calculé</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seuil_contractuel__c.field-meta.xml
<CustomField>
    <fullName>Seuil_contractuel__c</fullName>
    <label>Seuil contractuel</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Casier_Site__c.object
<CustomObject>
    <fields>
        <fullName>Coef_Ajustement__c</fullName>
        <label>Coef Ajustement</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Configuration_Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Configuration Site</label>
        <referenceTo>Configuration_Site__c</referenceTo>
        <relationshipLabel>Casier Site</relationshipLabel>
        <relationshipName>Casier_Site</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maximum__c</fullName>
        <label>Maximum</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum__c</fullName>
        <label>Minimum</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Modele__c</fullName>
        <label>Modèle</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_MDL</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Moyenne__c</fullName>
        <label>Moyenne</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Seuil_calcule__c</fullName>
        <description>Nombre disponible de casiers par type.</description>
        <label>Seuil calculé</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Seuil_contractuel__c</fullName>
        <description>Nombre contractuel de casiers par type.</description>
        <label>Seuil contractuel</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Casier Site</label>
    <nameField>
        <label>Nom de Casier Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Casier Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Modele__c</fullName>
        <label>Modèle</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_MDL</valueSetName>
        </valueSet>
    </fields>
    <label>Configuration</label>
    <nameField>
        <label>Nom de Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Configuration_Locker_Type__c.object
<CustomObject>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>Configurations Locker Type</relationshipLabel>
        <relationshipName>Configurations_Locker_Type</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre__c</fullName>
        <label>Nombre</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_de_casier__c</fullName>
        <label>Type de casier</label>
        <referenceTo>Type_de_casier__c</referenceTo>
        <relationshipLabel>Configurations Locker Type</relationshipLabel>
        <relationshipName>Configurations_Locker_Type</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Configuration Locker Type</label>
    <nameField>
        <displayFormat>CONF_LT_{0000}</displayFormat>
        <label>Nom de Configuration Locker Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurations Locker Type</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Configuration_Site__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Modele__c</fullName>
        <label>Modèle</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_MDL</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nom_Configuration__c</fullName>
        <label>Nom Configuration</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Compte__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tech_Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Configurations Site</relationshipLabel>
        <relationshipName>Configurations_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Configuration Site</label>
    <nameField>
        <label>Nom de Configuration Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations Site</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Type_de_casier__c.object
<CustomObject>
    <fields>
        <fullName>Coef_ajustement__c</fullName>
        <label>Coef Ajustement</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum__c</fullName>
        <label>Maximum</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum__c</fullName>
        <label>Minimum</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Modele__c</fullName>
        <label>Modèle</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_MDL</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Moyenne__c</fullName>
        <label>Moyenne</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Type de casier</label>
    <nameField>
        <label>Nom de Type de casier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de casier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_MDL.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>KEBA</fullName>
    </customValue>
    <customValue>
        <fullName>ZHILAI</fullName>
    </customValue>
    <customValue>
        <fullName>KERN</fullName>
    </customValue>
    <description>Modèles de consignes</description>
    <masterLabel>LOV_GLO_MDL</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/AP02_Account.cls
/*
* Author: Amal CHREITEH
* Modified By: John Boutros
* Date : 12/01/2018
* Description:
* Test classe: AP02_Account_TEST
Coverage : 98%
*/
public class AP02_Account {
    // créer configuration locke type à partir de la configuratioin existante
    // créer une configuration casier site à partir de Type de casier existant
    public static void createConfigurationandCasierSite(List<Account> newAccounts ,Map<Id, Account> oldAccounts) {
        Set<Id> configurationIds = new Set<Id>();
        List<Configuration_Site__c> ConfigurationSiteToDelete = new List<Configuration_Site__c>();
        List<Account> AccountsTobeUpdated = new List<Account>();
        Map<Id, Configuration_Site__c> accountConfigSite = new Map <Id, Configuration_Site__c>();
        for(Account newAccount : newAccounts){
            if(Label.RT_Consigne_Compte.contains(newAccount.recordTypeID))
            {
                if(newAccount.Recopie_Configuration__c == true){
                    configurationIds.add(newAccount.Configuration__c);
                    AccountsTobeUpdated.add(newAccount);
                    if(newAccount.Configuration_Site__c != null){
                        ConfigurationSiteToDelete.add(new Configuration_site__c(id = oldAccounts.get(newAccount.Id).Configuration_Site__c ));
                    }
                }
                else if(newAccount.Configuration_Site__c == null){
                    if(oldAccounts!= null && oldAccounts.ContainsKey(newAccount.Id)){
                        if(oldAccounts.get(newAccount.Id).Configuration_Site__c != null)
                        {
                            ConfigurationSiteToDelete.add(new Configuration_site__c(id = oldAccounts.get(newAccount.Id).Configuration_Site__c ));
                        }
                    }
                    newAccount.Configuration__c =null;
                }
                
            }
        }
        Set<Id> configurationIdsWithoutNull = new Set<Id>();
        if(configurationIds.size()>0){
            Map<Id, Configuration__c> newConfigurations = new Map<Id, Configuration__c>([select id, Modele__c,name,Description__c
                                                                                         From Configuration__c
                                                                                         Where id in : configurationIds ]);
            List<Configuration_Locker_Type__c> lockerTypeOfRetrievedConfigurationList = [Select id, Configuration__c, Type_de_casier__c, Name, Type_de_casier__r.name,Type_de_casier__r.Modele__c,
                                                                                         Type_de_casier__r.Minimum__c,Type_de_casier__r.Moyenne__c,Type_de_casier__r.Maximum__c,Type_de_casier__r.Coef_Ajustement__c,
                                                                                         Nombre__c
                                                                                         From Configuration_Locker_Type__c
                                                                                         Where Configuration__c in : configurationIds];
            if(newConfigurations.size()>0){
                Map<Id, List<Configuration_Locker_Type__c>> lockerTypeMap = new Map<Id, List<Configuration_Locker_Type__c>>();
                List<Casier_Site__c> newCasierSiteList = new List<Casier_Site__c>();
                for(Configuration_Locker_Type__c lockerType : lockerTypeOfRetrievedConfigurationList ){
                    if(!lockerTypeMap.containsKey(lockerType.Configuration__c)){
                        lockerTypeMap.put(lockerType.Configuration__c, new List<Configuration_Locker_Type__c>());
                    }
                    lockerTypeMap.get(lockerType.Configuration__c).add(lockerType);
                }
                List<Configuration_Site__c> newConfigSite = new List<Configuration_Site__c>();
                Map<Casier_Site__c, Configuration_site__c> configSiteCasierSite = new Map <Casier_Site__c, Configuration_site__c>();
                for(Account newAccount: AccountsTobeUpdated){
                    Configuration__c accountConfig = newConfigurations.get(newAccount.Configuration__c); 
                    Configuration_Site__c newConfigurationSite = new Configuration_Site__c();
                    newConfigurationSite.Tech_Compte__c = newAccount.Id;
                    newConfigurationSite.name = accountConfig.name;
                    newConfigurationSite.Description__c= accountConfig.Description__c;
                    newConfigurationSite.Nom_Configuration__c = accountConfig.name;
                    newConfigurationSite.Modele__c = accountConfig.Modele__c;
                    newConfigSite.add(newConfigurationSite);
                    accountConfigSite.put(newAccount.Id, newConfigurationSite );
                    if(lockerTypeMap.size() > 0)
                    {
                        for(Configuration_Locker_Type__c lockerTypeOfRetrievedConfiguration : lockerTypeMap.get(accountConfig.Id))
                        {
                            Casier_Site__c newCasierSite = new Casier_Site__c();
                            newCasierSite.Name = lockerTypeOfRetrievedConfiguration.Type_de_casier__r.name;//lockerTypeOfRetrievedConfiguration.name;
                            //newCasierSite.Nombre__c = lockerTypeOfRetrievedConfiguration.Nombre__c;
                            //newCasierSite.Nom_de_Type_de_casier__c  = lockerTypeOfRetrievedConfiguration.Type_de_casier__r.name;
                            newCasierSite.Modele__c = lockerTypeOfRetrievedConfiguration.Type_de_casier__r.Modele__c;
                            newCasierSite.Minimum__c = lockerTypeOfRetrievedConfiguration.Type_de_casier__r.Minimum__c;
                            newCasierSite.Moyenne__c = lockerTypeOfRetrievedConfiguration.Type_de_casier__r.Moyenne__c;
                            newCasierSite.Maximum__c = lockerTypeOfRetrievedConfiguration.Type_de_casier__r.Maximum__c;
                            newCasierSite.Coef_Ajustement__c = lockerTypeOfRetrievedConfiguration.Type_de_casier__r.Coef_Ajustement__c;
                            newCasierSite.Seuil_contractuel__c = lockerTypeOfRetrievedConfiguration.Nombre__c;
                            newCasierSite.Seuil_calcule__c = lockerTypeOfRetrievedConfiguration.Nombre__c;//1;
                            configSiteCasierSite.put(newCasierSite, newConfigurationSite);
                        }
                    }
                }
                try{
                    insert newConfigSite;
                    system.debug('newConfigSite'+ newConfigSite);
                    for(Casier_Site__c casierSite : configSiteCasierSite.keyset())
                    {
                        casierSite.Configuration_Site__c = configSiteCasierSite.get(casierSite).id;
                        newCasierSiteList.add(casierSite);
                    }
                    insert newCasierSiteList;
                    for(Account acc : AccountsTobeUpdated){
                        if(accountConfigSite.containsKey(acc.Id)){
                            acc.Configuration_Site__c = accountConfigSite.get(acc.Id).Id;
                        }
                        acc.Recopie_Configuration__c = false;
                    }
                    
                }
                catch(exception e){
                    AccountsTobeUpdated[0].Configuration__c.addError(e.getMessage());
                }
            }
            
        }
        if(ConfigurationSiteToDelete.size()>0){
            List<Casier_Site__c> casierSiteTodelete = [Select Id 
                                                       from Casier_Site__c
                                                       where Configuration_Site__c in :ConfigurationSiteToDelete];
            if(casierSiteTodelete.size()>0){
                Delete casierSiteTodelete;
            }
            Delete ConfigurationSiteToDelete;            
        }
    }
   
        // modifier le type d'enregistrement selon la valeur de l'état (En utilisant les ID stocké dans la métadonné personnalisé)
    public static void recordTypeEtatAssignment(List<Account> newAccountList, map<id, Account> oldAccountMap){
        Map<String, ID> associationRTPaysValiderMap  = new Map<String, ID>();
        Map<String, ID> associationRTPaysSuiviCOMap  = new Map<String, ID>();
        String key = '';
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel,
                                                                         ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt]; 
        
        for(Association_Record_Type_et_pays__mdt assRTPays  : associationRTPays){
            key = assRTPays.MasterLabel;
            if(!associationRTPaysValiderMap.containsKey(key)){
                associationRTPaysValiderMap.put(key, assRTPays.ID_Prospect_A_Valider__c);
            }
            if(!associationRTPaysSuiviCOMap.containsKey(key))
            {
                associationRTPaysSuiviCOMap.put(key, assRTPays.ID_suivi_CO__c);
            }
        }
        
        for(Account newAccount : newAccountList)
        {
            //if etat changed and new etat = 1 and international
            if(oldAccountMap.get(newAccount.Id).Etat__c != newAccount.Etat__c && newAccount.Etat__c == '1'  
               && ( LABEL.RT_INT_Compte.contains(newAccount.recordTypeID) || LABEL.RT_INT_Compte2.contains(newAccount.recordTypeID))
               && LABEL.RT_ProspectConverti_Compte.contains(newAccount.recordTypeID))
            {    
                //Prospect Converti
                key = newAccount.BillingCountry;
                if(associationRTPaysValiderMap.containsKey(key))
                {
                    newAccount.RecordTypeId = associationRTPaysValiderMap.get(key);
                }
            }
            //if etat changed and new etat = 2 and international
            else if(oldAccountMap.get(newAccount.Id).Etat__c != newAccount.Etat__c && newAccount.Etat__c == '2'  
                    && ( LABEL.RT_INT_Compte.contains(newAccount.recordTypeID) || LABEL.RT_INT_Compte2.contains(newAccount.recordTypeID) )
                    && LABEL.RT_ProspectAValider_Compte.contains(newAccount.recordTypeID))
            {                    
                key = newAccount.BillingCountry;
                if(associationRTPaysSuiviCOMap.containsKey(key))
                {
                    newAccount.RecordTypeId = associationRTPaysSuiviCOMap.get(key);
                }
            }
        }
    }
}