force-app/main/default/objects/Account/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Configuration__c.object
<CustomObject>
    <label>Configuration</label>
    <nameField>
        <label>Nom de Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Configuration_Locker_Type__c.object
<CustomObject>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>Configurations Locker Type</relationshipLabel>
        <relationshipName>Configurations_Locker_Type</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type_de_casier__c</fullName>
        <label>Type de casier</label>
        <referenceTo>Type_de_casier__c</referenceTo>
        <relationshipLabel>Configurations Locker Type</relationshipLabel>
        <relationshipName>Configurations_Locker_Type</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Configuration Locker Type</label>
    <nameField>
        <displayFormat>CONF_LT_{0000}</displayFormat>
        <label>Nom de Configuration Locker Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurations Locker Type</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CountriesSequence__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CountriesSequence</label>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Type_de_casier__c.object
<CustomObject>
    <label>Type de casier</label>
    <nameField>
        <label>Nom de Type de casier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de casier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VFC07_ConfigurationController_TEST.cls
@isTest
public class VFC07_ConfigurationController_TEST {
    static testMethod void testConfiguration() {
        {
            Macroprofil__c newMacroprofil= Utils_TestMethods.CreateMacroprofil('MPFR_Consigne');
            insert newMacroprofil;
            
            Configuration__c newConfig = Utils_TestMethods.createConfiguration('Configuration Name');
            insert newConfig;
            
            Type_de_casier__c newTypeCasier = Utils_TestMethods.createTypeCasierKEBA('Type casier');
            insert newTypeCasier;
            
            Configuration_Locker_Type__c newConfigLockType = Utils_TestMethods.createConfigurationLockerType(newConfig.id, newTypeCasier.id);
            insert newConfigLockType;
            
            //Create Custom Settings
            CountriesSequence__c cs = new CountriesSequence__c(Name='France' , Sequence__c = 'FR00001');
            insert cs;
            
            COntact cont1 = Utils_TestMethods.CreateContact('Test contact');
            insert cont1;
            
            Account acc2 = Utils_TestMethods.CreateAccount(cont1, newMacroprofil ,'Account name');
            insert acc2;
            
            acc2.Configuration__c = newConfig.id;
            update acc2;
          
            ApexPages.StandardController ctlr = new ApexPages.StandardController(acc2);
            VFC07_ConfigurationCOntroller controller = new VFC07_ConfigurationCOntroller(ctlr);
            controller.closePopup();
            try{
                
                controller.save();
            }
            catch (exception e){
                system.debug('exception');
            }
            controller.accountID = acc2.Id;
            controller.save();
            
            controller.accountID = '1234567891234';
            controller.save();
        }
    }
}