force-app/main/default/objects/Account/fields/Conges_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Conges_en_cours__c</fullName>
    <formula>IF(CONTAINS($User.Tech_Locale_Sid_Key__c,&quot;fr&quot;), 
	IF(NOT(ISBLANK(Tech_date_debut_conge_en_cours__c)),
		&#39;Du &#39; + 
		CASE( MOD( Tech_date_debut_conge_en_cours__c - DATE(1900, 1, 7), 7), 0, &quot;dim.&quot;, 1, &quot;lun.&quot;, 2, &quot;mar.&quot;, 3,&quot;mer.&quot;, 4, &quot;jeu.&quot;, 5, &quot;ven.&quot;, 6, &quot;sam.&quot;,&#39;&#39;) + &#39; &#39; + 
		IF(VALUE(TEXT(DAY( Tech_date_debut_conge_en_cours__c ))) &lt;= 9 , &#39;0&#39; + TEXT(DAY( Tech_date_debut_conge_en_cours__c )) , TEXT(DAY(Tech_date_debut_conge_en_cours__c ))) 
		+ &#39;/&#39; + 
		IF(VALUE(TEXT(MONTH(Tech_date_debut_conge_en_cours__c))) &lt;= 9 , &#39;0&#39; + TEXT(MONTH(Tech_date_debut_conge_en_cours__c)) , TEXT(MONTH(Tech_date_debut_conge_en_cours__c))) 
		+ &#39;/&#39; + 
		TEXT(YEAR(Tech_date_debut_conge_en_cours__c)) , &#39;&#39;) + 
	
	IF(NOT(ISBLANK(Tech_date_fin_conge_en_cours__c)),
		&#39; au &#39; + 
		CASE( MOD( Tech_date_fin_conge_en_cours__c - DATE(1900, 1, 7), 7), 0, &quot;dim.&quot;, 1, &quot;lun.&quot;, 2, &quot;mar.&quot;, 3,&quot;mer.&quot;, 4, &quot;jeu.&quot;, 5, &quot;ven.&quot;, 6, &quot;sam.&quot;,&#39;&#39;) + &#39; &#39; + 
		IF(VALUE(TEXT(DAY( Tech_date_fin_conge_en_cours__c ))) &lt;= 9 , &#39;0&#39; + TEXT(DAY( Tech_date_fin_conge_en_cours__c )) , TEXT(DAY(Tech_date_fin_conge_en_cours__c ))) 
		+ &#39;/&#39; + 
		IF(VALUE(TEXT(MONTH(Tech_date_fin_conge_en_cours__c))) &lt;= 9 , &#39;0&#39; + TEXT(MONTH(Tech_date_fin_conge_en_cours__c)) , TEXT(MONTH(Tech_date_fin_conge_en_cours__c))) 
		+ &#39;/&#39; + 
		TEXT(YEAR(Tech_date_fin_conge_en_cours__c)),&#39;&#39;), 
		
	IF(NOT(ISBLANK(Tech_date_debut_conge_en_cours__c)),
		&#39;From &#39; + 
		CASE( MOD( Tech_date_debut_conge_en_cours__c - DATE(1900, 1, 7), 7), 0, &quot;sun.&quot;, 1, &quot;mon.&quot;, 2, &quot;tue.&quot;, 3,&quot;wed.&quot;, 4, &quot;thu.&quot;, 5, &quot;fri.&quot;, 6, &quot;sat.&quot;,&#39;&#39;) + &#39; &#39; +
		IF(VALUE(TEXT(MONTH(Tech_date_debut_conge_en_cours__c))) &lt;= 9 , &#39;0&#39; + TEXT(MONTH(Tech_date_debut_conge_en_cours__c)) , TEXT(MONTH(Tech_date_debut_conge_en_cours__c))) + &#39;/&#39; + 
		IF(VALUE(TEXT(DAY(Tech_date_debut_conge_en_cours__c))) &lt;= 9 , &#39;0&#39; + TEXT(DAY( Tech_date_debut_conge_en_cours__c )) , TEXT(DAY(Tech_date_debut_conge_en_cours__c ))) + &#39;/&#39; + 
		TEXT(YEAR( Tech_date_debut_conge_en_cours__c )),&#39;&#39;) +
		 
	IF(NOT(ISBLANK(Tech_date_fin_conge_en_cours__c)),
		&#39; to &#39; +
		CASE( MOD( Tech_date_fin_conge_en_cours__c - DATE(1900, 1, 7), 7), 0, &quot;sun.&quot;, 1, &quot;mon.&quot;, 2, &quot;tue.&quot;, 3,&quot;wed.&quot;, 4, &quot;thu.&quot;, 5, &quot;fri.&quot;, 6, &quot;sat.&quot;,&#39;&#39;) + &#39; &#39; +
		IF(VALUE(TEXT(MONTH(Tech_date_fin_conge_en_cours__c))) &lt;= 9 , &#39;0&#39; + TEXT(MONTH(Tech_date_fin_conge_en_cours__c)) , TEXT(MONTH(Tech_date_fin_conge_en_cours__c))) + &#39;/&#39; + 
		IF(VALUE(TEXT(DAY( Tech_date_fin_conge_en_cours__c ))) &lt;= 9 , &#39;0&#39; + TEXT(DAY( Tech_date_fin_conge_en_cours__c )) , TEXT(DAY(Tech_date_fin_conge_en_cours__c )))+ &#39;/&#39; + 
		TEXT(YEAR( Tech_date_fin_conge_en_cours__c )),&#39;&#39;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Congés en cours</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_conge_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_conge_a_venir__c</fullName>
    <label>Tech date de début congé à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_conge_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_conge_en_cours__c</fullName>
    <label>Tech date de début congé en cours</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_disp_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_disp_a_venir__c</fullName>
    <label>Tech date de début disp à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_indisp_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_indisp_en_cours__c</fullName>
    <label>Tech date de début indisp en cours</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_fin_conge_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_fin_conge_a_venir__c</fullName>
    <label>Tech date de fin congé à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_fin_conge_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_fin_conge_en_cours__c</fullName>
    <label>Tech date de fin congé en cours</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_fin_disp_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_fin_disp_a_venir__c</fullName>
    <label>Tech date de fin disp à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_fin_indisp_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_fin_indisp_en_cours__c</fullName>
    <label>Tech date de fin indisp en cours</label>
    <type>Date</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Batch_Log__c.object
<CustomObject>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status_Code</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch_Log</label>
    <nameField>
        <displayFormat>BL-{0000000000}</displayFormat>
        <label>Nom de Batch_Logs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Conges_en_cours__c</fullName>
        <formula>IF( ISBLANK( Account.Conges_en_cours__c ),&quot;0&quot;,&quot;1&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Congés en cours</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Date_de_debut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_de_fin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nom_du_compte__c</fullName>
        <label>Nom du compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>IF ( Date_de_debut__c &gt;  TODAY() ,$Label.CongeIndispo_A_Venir_2,
IF ( Date_de_fin__c  &lt;   TODAY() ,$Label.Conge_Indispo_Passe_2,$Label.CongeIndispo_En_Cours_2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <recordTypes>
        <fullName>Conge</fullName>
        <active>true</active>
        <description>Permet de créer une période de congés.</description>
        <label>Congé</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AP10_Account.cls
/*
* Author : gho
* Class called from : Batch (Batch06_AccountCongeIndispo) and Triggers (Conge_Indispo__c --> after insert , update , delete)
* Check Conges for each account and modify its disponibilities fields
* exemple : If we add conge on an account for the current day the field conges_en_cours__c will be filled with Today
*/
public class AP10_Account { 
    
    // Conge Indispo Record Types
    static Id congeRTypeId = Label.CongeRT_15;
    static Id indispoStandardRTypeId = Label.IndispoStandardRT_15;
    static Id indispoConsigneRTypeId = Label.IndispoConsigneRT_15;
    static Id indispoStandardRTypeIdBNL = Label.RT_BNL_Indisponibilite_standard;
    static Id indispoPartnenaireRTypeIdBNL = Label.RT_BNL_Indisponibilit_partenaire;
    static Id dispoRTypeId = Label.DispoRT_15;
    
    // Map of each account with all its CongeIndispo
    private static Map<Id,List<Conge_Indispo__c>> mapAccountCongeIndispo = new Map<Id,List<Conge_Indispo__c>>();
    
    static List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_Converti__c
                                                                                 FROM Association_Record_Type_et_pays__mdt];
            
    
    //private static List<Account> lstAccountsToBeUpdated = new List<Account>();
    
    public static map<string, Association_Record_Type_et_pays__mdt> getAssociationRTPays(){
      map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
      for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
              associationRTPays.put(associationRT.MasterLabel, associationRT);
      }
       
        return associationRTPays;
    }
    
    
    private static void getCongeIndispoByAccount(List<Account> lstAcounts) {
        // This method gets all the CongeIndispo records for all the accounts
        // Records Concerned : Conge (en cours and a venir) , Indispo en cours and Dispo a venir
        for(Conge_Indispo__c congeIndispo : [Select id , date_de_debut__c , date_de_fin__c,Statut__c ,Nom_du_compte__c, RecordTypeId 
                                               From Conge_Indispo__c
                                               Where Nom_du_compte__c IN : lstAcounts AND (
                                                   RecordTypeId =: congeRTypeId
                                                   OR ((RecordTypeId =: indispoStandardRTypeId 
                                                      OR RecordTypeId =: indispoConsigneRTypeId 
                                                      OR RecordTypeId =: indispoStandardRTypeIdBNL 
                                                      OR RecordTypeId =: indispoPartnenaireRTypeIdBNL ) AND Statut__c =:  Label.CongeIndispo_En_Cours )
                                                 OR (RecordTypeId =: dispoRTypeId AND Statut__c =: Label.CongeIndispo_A_Venir)
                                             )]) {
                                                 if(!mapAccountCongeIndispo.containsKey(congeIndispo.Nom_du_compte__c)) {
                                                     mapAccountCongeIndispo.put(congeIndispo.Nom_du_compte__c, new List<Conge_Indispo__c>());
                                                 }
                                                 mapAccountCongeIndispo.get(congeIndispo.Nom_du_compte__c).add(congeIndispo);
                                             }
    } 
    
    public static void updateAccountCongeIndispoInformation(List<Account> lstAccounts) { 
        getCongeIndispoByAccount(lstAccounts);       
        Conge_Indispo__c congeAvenir;
        Conge_Indispo__c dispoAVenir; 
        boolean bCongeEnCoursAssigned;
        boolean bIndispoEnCoursAssigned;
        for(Account compte : lstAccounts) { 
            if(mapAccountCongeIndispo.containsKey(compte.Id)) {
                congeAvenir = null;
                dispoAVenir = null; 
                bCongeEnCoursAssigned 	= false;
                bIndispoEnCoursAssigned = false;
                for(Conge_Indispo__c congeIndisp : mapAccountCongeIndispo.get(compte.Id)) {
                    if(congeIndisp.Statut__c == Label.CongeIndispo_En_Cours) {
                        if(congeIndisp.RecordTypeId == congeRTypeId) {
                            // conge en cours
                            bCongeEnCoursAssigned = true;
                            if(compte.Tech_date_debut_conge_en_cours__c != congeIndisp.Date_de_debut__c || compte.Tech_date_fin_conge_en_cours__c != congeIndisp.Date_de_fin__c){ 
                                compte.Tech_date_debut_conge_en_cours__c = congeIndisp.Date_de_debut__c;
                                compte.Tech_date_fin_conge_en_cours__c   = congeIndisp.Date_de_fin__c;
                                //lstAccountsToBeUpdated.add(compte);
                            }
                            
                        } else if(congeIndisp.RecordTypeId == indispoStandardRTypeId || congeIndisp.RecordTypeId == indispoConsigneRTypeId
                                  || congeIndisp.RecordTypeId == indispoStandardRTypeIdBNL || congeIndisp.RecordTypeId == indispoPartnenaireRTypeIdBNL) {
                            // indispo en cours 
                            bIndispoEnCoursAssigned = true;
                            if(compte.Tech_date_debut_indisp_en_cours__c != congeIndisp.Date_de_debut__c || compte.Tech_date_fin_indisp_en_cours__c != congeIndisp.Date_de_fin__c) {
                                compte.Tech_date_debut_indisp_en_cours__c = congeIndisp.Date_de_debut__c;
                                compte.Tech_date_fin_indisp_en_cours__c   = congeIndisp.Date_de_fin__c;
                                //lstAccountsToBeUpdated.add(compte);
                            }
                            
                        }
                    } else if(congeIndisp.Statut__c == Label.CongeIndispo_A_Venir) {
                        
                        // get the soonest conge or dispo
                        if(congeIndisp.RecordTypeId == congeRTypeId && (congeAvenir == null || congeIndisp.Date_de_debut__c < congeAvenir.Date_de_debut__c)){
                            // conge a venir
                            congeAvenir = congeIndisp;
                        } else if (congeIndisp.RecordTypeId == dispoRTypeId && (dispoAVenir == null || congeIndisp.Date_de_debut__c < dispoAVenir.Date_de_debut__c)){
                            // dispo a venir
                            dispoAVenir = congeIndisp;
                        }
                    }
                }
                
                if(!bCongeEnCoursAssigned) { 
                    // empty the conge en cours tech fields in case the account does not have any conge en cours but the tech fields are still filled for some reason
                    if(compte.Tech_date_debut_conge_en_cours__c != null || compte.Tech_date_fin_conge_en_cours__c != null) {
                        compte.Tech_date_debut_conge_en_cours__c = null;
                        compte.Tech_date_fin_conge_en_cours__c   = null;   
                        //lstAccountsToBeUpdated.add(compte);
                    } 
                }
                
                if(!bIndispoEnCoursAssigned) {
                    // empty the indispo en cours tech fields in case the account does not have any indispo en cours but the tech fields are still filled for some reason
                    if(compte.Tech_date_debut_indisp_en_cours__c != null || compte.Tech_date_fin_indisp_en_cours__c != null) {
                        compte.Tech_date_debut_indisp_en_cours__c = null;
                        compte.Tech_date_fin_indisp_en_cours__c = null; 
                        //lstAccountsToBeUpdated.add(compte);
                    }
                    
                }
                
                // Same for congeAvenir and DispoAVenir
                // We may face some cases (deleted by user with byPass for ex) where tech fields contains data but the actuel conge/Indispo is deleted
                if(congeAvenir != null) {
                    if( compte.Tech_date_debut_conge_a_venir__c != congeAvenir.Date_de_debut__c || compte.Tech_date_fin_conge_a_venir__c  != congeAvenir.Date_de_fin__c) {
                        compte.Tech_date_debut_conge_a_venir__c = congeAvenir.Date_de_debut__c;
                        compte.Tech_date_fin_conge_a_venir__c   = congeAvenir.Date_de_fin__c;
                        //lstAccountsToBeUpdated.add(compte);
                    }
                    
                } else {
                    if(compte.Tech_date_debut_conge_a_venir__c != null || compte.Tech_date_fin_conge_a_venir__c != null) {
                        compte.Tech_date_debut_conge_a_venir__c = null;
                        compte.Tech_date_fin_conge_a_venir__c   = null;
                        //lstAccountsToBeUpdated.add(compte);
                    } 
                }
                
                
                if(dispoAvenir != null) {
                    if (compte.Tech_date_debut_disp_a_venir__c != dispoAvenir.Date_de_debut__c || compte.Tech_date_fin_disp_a_venir__c != dispoAvenir.Date_de_fin__c) {
                        compte.Tech_date_debut_disp_a_venir__c = dispoAvenir.Date_de_debut__c;
                        compte.Tech_date_fin_disp_a_venir__c   = dispoAvenir.Date_de_fin__c;
                        //lstAccountsToBeUpdated.add(compte);
                    }
                    
                } else {
                    if(compte.Tech_date_debut_disp_a_venir__c != null || compte.Tech_date_fin_disp_a_venir__c != null) {
                        compte.Tech_date_debut_disp_a_venir__c = null;
                        compte.Tech_date_fin_disp_a_venir__c = null;
                        //lstAccountsToBeUpdated.add(compte);
                    }
                    
                }
                
            } else {
                // Check if the account had a CongeIndispo which was deleted by a user with byPass. Then the tech fields still contains values.
                //boolean bToUpdate = false;
                if(compte.Tech_date_debut_conge_en_cours__c != null) {
                    compte.Tech_date_debut_conge_en_cours__c = null;
                    compte.Tech_date_fin_conge_en_cours__c = null;
                    //bToUpdate = true; 
                }
                if(compte.Tech_date_debut_conge_a_venir__c != null) {
                    compte.Tech_date_debut_conge_a_venir__c = null;
                    compte.Tech_date_fin_conge_a_venir__c = null;
                    //bToUpdate = true; 
                }
                if(compte.Tech_date_debut_indisp_en_cours__c != null) {
                    compte.Tech_date_debut_indisp_en_cours__c = null;
                    compte.Tech_date_fin_indisp_en_cours__c = null;
                    //bToUpdate = true;
                    //lstAccountsToBeUpdated.add(compte);
                }
                //if(bToUpdate) {
                    //lstAccountsToBeUpdated.add(compte);
                //}
            }
        }
        
        if(lstAccounts.size() > 0) {
            Database.SaveResult[] srList = Database.update(lstAccounts,false);
            if(Label.is_Batch_Logs_Active == 'true'){
                List<Batch_Log__c> LBatchLogs = new List<Batch_Log__c>();
                //for (Database.SaveResult sr : srList) {
                for (Integer i = 0; i < lstAccounts.size(); i++) {
                    Database.SaveResult sr = srList[i];
                    Account origRecord = lstAccounts[i];
                    if (!sr.isSuccess()) {
                        for(Database.Error err : sr.getErrors()) {
                            LBatchLogs.add(new Batch_log__c(Status_Code__c = '' + err.getStatusCode(),
                                                            Message__c = err.getMessage(),
                                                            Fields__c = '' + err.getFields(),
                                                            ID__c = origRecord.Id
                                                           ));
                        }
                    }
                }
                if(LBatchLogs.size() > 0){
                    insert LBatchLogs;
                }
            }
        }
        
    }
    
    public static void updateAccountCongeIndispoInformationFromTrigger(List<Conge_Indispo__c> lstCongeIndispo) {
        // This method is called from CongeIndispo Triggers (after insert/update/delete)
        Set<Id> setAccountIds = new Set<Id>();
        for(Conge_Indispo__c objConge : lstCongeIndispo) {
            if(objConge.Nom_du_compte__c!= null)
                setAccountIds.add(objConge.Nom_du_compte__c);
        }
        if(setAccountIds!= null && setAccountIds.size()>0){
            String query =  'Select Id , Name , Tech_date_debut_conge_en_cours__c , Tech_date_fin_conge_en_cours__c , ' + 
                'Tech_date_debut_conge_a_venir__c , Tech_date_fin_conge_a_venir__c , '+
                'Tech_date_debut_disp_a_venir__c , Tech_date_fin_disp_a_venir__c , '+
                'Tech_date_debut_indisp_en_cours__c , Tech_date_fin_indisp_en_cours__c ' + 
                'From Account where Id IN : setAccountIds';
            List<Account> lstAccounts = Database.query(query);
            if(lstAccounts!= null && lstAccounts.size()>0)
                updateAccountCongeIndispoInformation(lstAccounts);
        }
        
    }
    
}