force-app/main/default/objects/Account/fields/Contexte__c.field-meta.xml
<CustomField>
    <fullName>Contexte__c</fullName>
    <label>Contexte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusion</fullName>
            </value>
            <value>
                <fullName>Résiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_fin_d_activite__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_d_activite__c</fullName>
    <label>Date de fin d&#39;activité</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/En_attente_de_courrier__c.field-meta.xml
<CustomField>
    <fullName>En_attente_de_courrier__c</fullName>
    <label>En attente de courrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Résiliation</fullName>
            </value>
            <value>
                <fullName>Exclusion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Etat__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_MOD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif de fin d&#39;activité</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contexte__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>152</fullName>
            </value>
            <value>
                <fullName>153</fullName>
            </value>
            <value>
                <fullName>154</fullName>
            </value>
            <value>
                <fullName>155</fullName>
            </value>
            <value>
                <fullName>156</fullName>
            </value>
            <value>
                <fullName>157</fullName>
            </value>
            <value>
                <fullName>158</fullName>
            </value>
            <value>
                <fullName>159</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>161</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>Exclusion</fullName>
            </value>
            <value>
                <fullName>Résiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Batch_Log__c.object
<CustomObject>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status_Code</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch_Log</label>
    <nameField>
        <displayFormat>BL-{0000000000}</displayFormat>
        <label>Nom de Batch_Logs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Historique_Etat_Mode__c.object
<CustomObject>
    <description>Cet objet technique sert à historiser les modifications des états et des modes réalisés sur l&apos;objet Account (PUDO).</description>
    <fields>
        <fullName>Compte__c</fullName>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cycle de vie du relais</relationshipLabel>
        <relationshipName>Historiques_Etats_Modes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Creerpar__c</fullName>
        <label>Créer par</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datedecreation__c</fullName>
        <label>Date de création</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Etat__c</fullName>
        <label>Etat</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_ETA</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_MOD</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tech_Age_Mode__c</fullName>
        <description>Différence en jours entre la date de changement d&apos;état/Mode et aujourd&apos;hui.</description>
        <formula>Today()- DATEVALUE (Datedecreation__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Historique Etat/Mode</label>
    <nameField>
        <displayFormat>HEM-{0000}</displayFormat>
        <label>Numéro d&apos;historique Etat/Mode</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historiques Etats/Modes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ETA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_MOD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>220</fullName>
    </customValue>
    <customValue>
        <fullName>240</fullName>
    </customValue>
    <customValue>
        <fullName>250</fullName>
    </customValue>
    <customValue>
        <fullName>260</fullName>
    </customValue>
    <customValue>
        <fullName>264</fullName>
    </customValue>
    <customValue>
        <fullName>270</fullName>
    </customValue>
    <customValue>
        <fullName>300</fullName>
    </customValue>
    <customValue>
        <fullName>730</fullName>
    </customValue>
    <customValue>
        <fullName>735</fullName>
    </customValue>
    <customValue>
        <fullName>740</fullName>
    </customValue>
    <customValue>
        <fullName>745</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>900</fullName>
    </customValue>
    <customValue>
        <fullName>MC9</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de validation DOR</fullName>
    </customValue>
    <customValue>
        <fullName>65</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de signature</fullName>
    </customValue>
    <customValue>
        <fullName>Accord Pickup : Non retenu</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>280</fullName>
    </customValue>
    <customValue>
        <fullName>290</fullName>
    </customValue>
    <customValue>
        <fullName>310</fullName>
    </customValue>
    <description>Mode du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_MOD</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP11_Account.cls
public class AP11_Account {
    //TODO: Change everything to labels
    //TODO: Tidy up
    static Boolean isDFA56 = false;
    public static void changerEtatModeSelonDFA(List<Account> LAccounts){
        
        System.debug('AP11_Account.changerEtatModeSelonDFA start');
        List<Account> LAccRetourEtat = new List<Account>();     //Cette liste sera utilisée pour faire un rollback des etat et mode de ses comptes 
        List<Account> LAccSansRetourEtat = new List<Account>(); //Cette liste sera utilisée pour les autres comptes
        system.debug('JMB LAccounts '+LAccounts);
        for(Account acc:LAccounts){
            //si on a changé les dates fin [PUDO_PB14_Retour_EtatMode]
            //Cette partie sera considérée seulement par les triggers car on fait une requête avec condition 'Date_de_fin_d_activite__c <> null' dans le batch 
            if(acc.Date_de_fin_d_activite__c == null && (acc.Etat__c == Label.Account_Etat_6 || acc.Etat__c == Label.Account_Etat_7)){
                system.debug('christine LAccRetourEtat 1 '+LAccRetourEtat);
                acc.Contexte__c = null;
                acc.Motif__c = null;
                LAccRetourEtat.add(acc);
                continue;                   //continuer le for, rien à faire avec les autres conditions
            }
            //Pour prendre en considération les pays INT
            else if(acc.RecordTypeId != null && (! Label.RT_Consigne_Compte.contains(acc.RecordTypeId) && acc.Date_de_fin_d_activite__c != null && acc.Date_de_fin_d_activite__c > Date.today().addDays(56) && (acc.Etat__c == '6' || acc.Etat__c == '7')) ){
                //else if(acc.RecordTypeId != Label.AccountConsigneRT_15 && acc.Date_de_fin_d_activite__c != null && acc.Date_de_fin_d_activite__c > Date.today().addDays(56) && (acc.Etat__c == '6' || acc.Etat__c == '7')){
                system.debug('christine LAccRetourEtat 2 '+LAccRetourEtat);
                system.debug('Date >= 56');
                acc.Etat__c = '5';
                acc.Mode__c = '300';
                isDFA56 = true;
                LAccRetourEtat.add(acc);
                continue;                   //continuer le for, rien à faire avec les autres conditions
            }
            else if(acc.Date_de_fin_d_activite__c == null && (acc.Etat__c == '2' || acc.Etat__c == '4' || acc.Etat__c == '5')){acc.Contexte__c = null;acc.Motif__c = null;
                                                                                                                              }
            //fin de partie
            
            system.debug('AP11_Account acc.RecordTypeId ' + acc.RecordTypeId);
            
            //Si recordType n'est pas PUS_FR_Consigne [PB07 - Changement Etat/Mode 6-7]
            if(acc.RecordTypeId != null && (!Label.RT_Consigne_Compte.contains(acc.RecordTypeId) )) { //Pour prendre en considération les pays INT
                //if(acc.RecordTypeId != Label.AccountConsigneRT_15){
                //quelque soit le contexte, si DFA > today + 56 : pas de changements
                system.debug('AP11_Account acc.Date_de_fin_d_activite__c ' + acc.Date_de_fin_d_activite__c);
                if(acc.Date_de_fin_d_activite__c != null && acc.Date_de_fin_d_activite__c <= Date.today().addDays(56)){
                    system.debug('Date <= 56');
                    //si today + 21 < DFA <= today + 56
                    //- contexte 'Résiliation'  : Passage à état 6, mode 740 (suggéré)
                    //- contexte 'Exclusion'    : Passage à état 6, mode 730
                    if(acc.Date_de_fin_d_activite__c > Date.today().addDays(21) ){
                        system.debug('21 < Date <= 56');
                        if(acc.Contexte__c == Label.Account_Contexte_Resiliation && acc.Mode__c != Label.Account_Mode_ResiliationSuggere){acc.Etat__c = Label.Account_Etat_6; acc.Mode__c = Label.Account_Mode_ResiliationSuggere;
                                                                                                                                         }
                        else if(acc.Contexte__c == Label.Account_Contexte_Exclusion && acc.Mode__c != Label.Account_Mode_ExclusionSuggere){
                            acc.Etat__c = Label.Account_Etat_6;
                            acc.Mode__c = Label.Account_Mode_ExclusionSuggere;
                        }
                    }else
                        //si today < DFA <= today + 21 et RecordType = PUDO Suivit OU non suivi OU Contact (pour le contact, si le contexte est vide, rien ne se passe)
                        //- contexte 'Résiliation'  : Passage à état 6, mode 745 (non suggéré)
                        //- contexte 'Exclusion'    : Passage à état 6, mode 735
                        if(acc.RecordTypeId != null && (acc.Date_de_fin_d_activite__c > Date.today() 
                                                        //Pour prendre en considération les pays INT
                                                        && (Label.RT_NonSuiviCo_Compte.contains(acc.RecordTypeId) || Label.RT_PickupContact_Compte.contains(acc.RecordTypeId)
                                                            ||Label.RT_SuiviCo_Compte.contains(acc.RecordTypeId))) ) {
                                                                /* if(acc.Date_de_fin_d_activite__c > Date.today()  
&& (acc.RecordTypeId == Label.AccountNonSuiviCoRT 
||acc.RecordTypeId == Label.AccountPickupContactRT || acc.RecordTypeId == Label.AccountPudoSuiviCoRT)){*/
                                                                system.debug('Today < Date <= 21');
                                                                if(acc.Contexte__c == Label.Account_Contexte_Resiliation && acc.Mode__c != Label.Account_Mode_ResiliationNonSuggere){
                                                                    acc.Etat__c = Label.Account_Etat_6;
                                                                    acc.Mode__c = Label.Account_Mode_ResiliationNonSuggere;
                                                                }
                                                                else if(acc.Contexte__c == Label.Account_Contexte_Exclusion && acc.Mode__c != Label.Account_Mode_ExclusionNonSuggere){
                                                                    acc.Etat__c = Label.Account_Etat_6;
                                                                    acc.Mode__c = Label.Account_Mode_ExclusionNonSuggere;
                                                                }
                                                            }
                    //Passage Etat 7, Mode 900 (Inactif)
                    //Pour prendre en considération les pays INT
                    else if(acc.RecordTypeId != null && (acc.Date_de_fin_d_activite__c != null &&  acc.Date_de_fin_d_activite__c <= Date.today()  
                                                         && (acc.Etat__c != Label.Account_Etat_7 || acc.Mode__c != Label.Account_Mode_Inactif || acc.En_attente_de_courrier__c != null)
                                                         && (Label.RT_SuiviCo_Compte.contains(acc.RecordTypeId) || Label.RT_PickupContact_Compte.contains(acc.RecordTypeId) ||  Label.RT_NonSuiviCo_Compte.contains(acc.RecordTypeId) || Label.RT_Consigne_Compte.contains(acc.RecordTypeId))) ){
                                                             /*else if(acc.Date_de_fin_d_activite__c != null &&  acc.Date_de_fin_d_activite__c <= Date.today()  
&& (acc.Etat__c != Label.Account_Etat_7 || acc.Mode__c != Label.Account_Mode_Inactif || acc.En_attente_de_courrier__c != null)
&& (acc.RecordTypeId == Label.AccountPudoSuiviCoRT 
|| acc.RecordTypeId == Label.AccountPickupContactRT || acc.RecordTypeId == Label.AccountNonSuiviCoRT || acc.RecordTypeId == Label.AccountConsigneRT_15)){*/
                                                             
                                                             acc.Etat__c = Label.Account_Etat_7;
                                                             acc.Mode__c = Label.Account_Mode_Inactif;
                                                             acc.En_attente_de_courrier__c = null;
                                                         }
                }
            }
            //Si recordtype est PUS_FR_Consigne  [CONS_PB01_Date_FDA_renseignee]
            else{
                System.debug('PUDO Consigne');
                //pas de condition sur TODAY + 56, si DFA > TODAY + 21, passage à Etat 6 et Mode selon le contexte
                if(acc.Date_de_fin_d_activite__c != null && acc.Date_de_fin_d_activite__c >= Date.today().addDays(22) ){
                    System.debug('Consigne DFA >= TODAY + 22');
                    if(acc.Contexte__c == Label.Account_Contexte_Exclusion && acc.Mode__c != Label.Account_Mode_ExclusionSuggere){
                        acc.Etat__c = Label.Account_Etat_6;
                        acc.Mode__c = Label.Account_Mode_ExclusionSuggere;
                    }
                    else if(acc.Contexte__c == Label.Account_Contexte_Resiliation && acc.Mode__c != Label.Account_Mode_ResiliationSuggere){
                        acc.Etat__c = Label.Account_Etat_6;
                        acc.Mode__c = Label.Account_Mode_ResiliationSuggere;
                    }
                }
                else if(acc.Date_de_fin_d_activite__c != null && acc.Date_de_fin_d_activite__c <= Date.today().addDays(21) && acc.Date_de_fin_d_activite__c > Date.today()){
                    if(acc.Contexte__c == Label.Account_Contexte_Exclusion && acc.Mode__c != Label.Account_Mode_ExclusionNonSuggere){
                        acc.Etat__c = Label.Account_Etat_6;
                        acc.Mode__c = Label.Account_Mode_ExclusionNonSuggere;
                    }
                    else if(acc.Contexte__c == Label.Account_Contexte_Resiliation && acc.Mode__c != Label.Account_Mode_ResiliationNonSuggere){
                        acc.Etat__c = Label.Account_Etat_6;
                        acc.Mode__c = Label.Account_Mode_ResiliationNonSuggere;
                    }
                }
                else if(acc.Date_de_fin_d_activite__c != null && acc.Date_de_fin_d_activite__c <= Date.today() 
                        && (acc.Etat__c != Label.Account_Etat_7 || acc.Mode__c != Label.Account_Mode_Inactif || acc.En_attente_de_courrier__c != null)){
                            System.debug('I am here');
                            acc.Etat__c = Label.Account_Etat_7;
                            acc.Mode__c = Label.Account_Mode_Inactif;
                            acc.En_attente_de_courrier__c = null;
                        }
            }
            LAccSansRetourEtat.add(acc);
        }
        //si dans un batch, faire un update (car le trigger c'est before update, alors les valeurs durant l'update seront les nouvelles valeurs)
        if(system.isBatch()){
            if(LAccSansRetourEtat.size() > 0){
                Database.SaveResult[] srList = Database.update(LAccSansRetourEtat, false);
                if(Label.is_Batch_Logs_Active == 'true'){
                    List<Batch_Log__c> LBatchLogs = new List<Batch_Log__c>();
                    //for (Database.SaveResult sr : srList) {
                    for (Integer i = 0; i < LAccSansRetourEtat.size(); i++) {
                        Database.SaveResult sr = srList[i];
                        Account origRecord = LAccSansRetourEtat[i];
                        if (!sr.isSuccess()) {
                            for(Database.Error err : sr.getErrors()) {
                                LBatchLogs.add(new Batch_log__c(Status_Code__c = 'AP11_Account ' + err.getStatusCode(),
                                                                Message__c = err.getMessage(),
                                                                Fields__c = '' + err.getFields(),
                                                                ID__c = origRecord.Id
                                                               ));
                            }
                        }
                    }
                    if(LBatchLogs.size() > 0){
                        insert LBatchLogs;
                    }
                }
            }
        }
        if(LAccRetourEtat.size() > 0){
            system.debug('christine LAccRetourEtat final '+LAccRetourEtat);
            Update_Etat(LAccRetourEtat);
        }
        System.debug('AP11_Account.changerEtatModeSelonDFA end');
    }
    
    //Function to replace the flow Update_Etat
    private static void Update_Etat(List<Account> LAccounts){
        System.debug('Update_Etat Start');
        List<Account> LAccountsToUpdate = new List<Account>(); //utilisée seulement par un batch
        
        List<Historique_Etat_Mode__c> LHEMexistant = [SELECT Compte__c, Tech_Age_Mode__c, Creerpar__c, Datedecreation__c, Etat__c, Mode__c 
                                                      FROM Historique_Etat_Mode__c 
                                                      WHERE Compte__c IN :LAccounts AND Etat__c <> :Label.Account_Etat_6 
                                                      ORDER By Datedecreation__c DESC];
        system.debug('christine LHEMexistant '+LHEMexistant);
        //Map pour mapper les comptes avec leur historique d'etat
        Map<Id, List<Historique_Etat_Mode__c>> MapCompteLHEM = new Map<Id, List<Historique_Etat_Mode__c>>();
        for(Historique_Etat_Mode__c HEM: LHEMexistant){
            if(MapCompteLHEM.get(HEM.Compte__c) == null){
                MapCompteLHEM.put(HEM.Compte__c, new List<Historique_Etat_Mode__c>());
            }
            MapCompteLHEM.get(HEM.Compte__c).add(HEM);
        }
        
        List<Historique_Etat_Mode__c> LHEM = new List<Historique_Etat_Mode__c>(); //cette liste est utilisée pour créer de nouvau ligne d'historique
        system.debug('christine LHEM '+LHEM);
        system.debug('AP11_Account isDFA56 ' + isDFA56);
        for(Account acc: LAccounts){
            if(MapCompteLHEM.get(acc.Id) != null && isDFA56 == false){
                for(Historique_Etat_Mode__c HEM: MapCompteLHEM.get(acc.Id)){
                    if(HEM.Etat__c != acc.Etat__c && HEM.Mode__c != acc.Mode__c){
                        system.debug('christine creation of a new record');
                        LHEM.add(new Historique_Etat_Mode__c(Compte__c = acc.Id,
                                                             Creerpar__c = User.FirstName + ' ' + User.LastName,
                                                             Datedecreation__c = DateTime.now(),
                                                             Etat__c = acc.Etat__c,
                                                             Mode__c = acc.Mode__c
                                                            ));
                        acc.Etat__c = HEM.Etat__c;
                        acc.Mode__c = HEM.Mode__c;
                        LAccountsToUpdate.add(acc);
                        system.debug('christine LAccountsToUpdate '+LAccountsToUpdate);
                        system.debug('christine LHEM '+LHEM);
                        break;
                    }
                }
            }
        }
        System.debug('LAccountsToUpdate: ' + LAccountsToUpdate);
        if(System.isBatch()){
            Database.SaveResult[] srList = Database.update(LAccountsToUpdate, false);
            
        }
        System.debug('LHEM: ' + LHEM);
        if(LHEM.size() > 0){	
            system.debug('christine LHEM insertion '+LHEM);
            insert LHEM;
        }
        System.debug('Update_Etat End');
    }
    
}