force-app/main/default/objects/Account/fields/Contact_operationnel_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_operationnel_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact opérationnel</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Requete_Conge__c</fullName>
        <label>ID_Requête_Congé</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Batch_Log__c.object
<CustomObject>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status_Code</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch_Log</label>
    <nameField>
        <displayFormat>BL-{0000000000}</displayFormat>
        <label>Nom de Batch_Logs</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Object_de_la_requete__c</fullName>
        <label>Objet de la requête</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anomalie de synchronisation d’un relais</fullName>
                    <label>Anomalie de synchronisation d&apos;un relais</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Sinistre / Travaux / Santé</fullName>
                    <label>Indisponibilité - Problème opérationnel Sinistre / Travaux / Santé</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Qualité de Service</fullName>
                    <label>Indisponibilité - Problème opérationnel Qualité de Service</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Panne PDA</fullName>
                    <label>Indisponibilité - Problème PDA / Panne PDA</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Problème de synchronisation</fullName>
                    <label>Indisponibilité - Problème PDA / Problème de synchronisation</label>
                </value>
                <value>
                    <fullName>Indisponibilité problème opérationnel - Injoignabilité</fullName>
                </value>
                <value>
                    <fullName>Démarrage d&apos;activité</fullName>
                </value>
                <value>
                    <fullName>Relais sans formation avec moyens de scans associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif avec plusieurs moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Les relais actifs avec terme contrat non respecté</fullName>
                </value>
                <value>
                    <fullName>Les Congés du relais</fullName>
                </value>
                <value>
                    <fullName>Relais inactif avec moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif sans moyen de scan associé</fullName>
                </value>
                <value>
                    <fullName>Les horaires insuffisants du relais</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Anomalie colis</fullName>
                    <isActive>false</isActive>
                    <label>Indisponibilité Problème opérationnel Anomalie colis</label>
                </value>
                <value>
                    <fullName>Relais actif sans formation avec moyen de scan associé</fullName>
                    <isActive>false</isActive>
                    <label>Relais actif sans formation avec moyen de scan associé</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Nom_du_compte__c</fullName>
        <label>Nom du compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TECH_Conges_Dispo_Juillet_Aout__c</fullName>
        <formula>IF( 
	AND(Date_de_debut__c &gt;= DATE( YEAR( TODAY()),07, 01 ), 
		Date_de_debut__c &lt;= DATE( YEAR( TODAY()),08, 31 ), 
		Date_de_fin__c &gt;= DATE( YEAR( TODAY()),07, 01 ), 
		Date_de_fin__c &lt;= DATE( YEAR( TODAY()),08, 31), 
		OR(RecordType.Id == $Label.RT_Conge_Indispo_Conge ,RecordType.Id == $Label.RT_Conge_Indispo_Disponibilite ) 
), true, false)</formula>
        <label>TECH Conges Dispo Juillet Aout</label>
        <type>Checkbox</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <recordTypes>
        <fullName>Conge</fullName>
        <active>true</active>
        <description>Permet de créer une période de congés.</description>
        <label>Congé</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AP07_Account.cls
/*--------------------------------------------------------------------------
*Author: Chahid Khalil
*Company : EI Technologies Liban
*Description: class used in Batch09_AccountRequette
*Test Class: Batch09_AccountRequette_Test
*Created Date: 27/04/2018
--------------------------------------------------------------------------*/
public class AP07_Account {
    
    public static void CreateCase(List<Account> newAccounts){
        List<Batch_Log__c> LBatchLogs = new List<Batch_Log__c>();
        Set<ID> congesRecordTypeIDs = new Set<Id>();
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id, MasterLabel, ID_Requete_Conge__c
                                                                            FROM Association_Record_Type_et_pays__mdt];
        Map<String,Association_Record_Type_et_pays__mdt> mapassociationRTPays =  new Map<String,Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord: associationRTPays)
        {
            mapassociationRTPays.put(mdtRecord.MasterLabel, mdtRecord);
            if (mdtRecord.ID_Requete_Conge__c != null)
            {                
                congesRecordTypeIDs.add(mdtRecord.ID_Requete_Conge__c);
            }
        }
        
        List<Case> NewCaseList = new List<Case>();
        Set<Id> AccountIds = New Set<Id>();
        List<Account> account_MetCondition =  new List<Account>();
        for(Account acc : newAccounts)
        {
            if (//(Label.RT_INT_Compte.contains(acc.RecordTypeId) || Label.RT_INT_Compte2.contains(acc.RecordTypeId)) &&
                !Label.RT_Consigne_Compte.contains(acc.RecordTypeId)) 
            {
                AccountIds.add(acc.Id); 
                account_MetCondition.add(acc); 
            }
        }
        if (AccountIds.size()>0)
        {
            Integer thisYear = Date.today().year();
            List<AggregateResult> AccountCase_List = [SELECT AccountId CaseAccountId ,count(Id) CaseCount 
                                                      FROM Case
                                                      WHERE AccountId in :AccountIds and
                                                      ((CALENDAR_YEAR(CreatedDate) =: thisYear 
                                                        and account.shippingcountry !='France')
                                                      or account.shippingcountry ='France')
                                                      and RecordTypeId IN : congesRecordTypeIDs         
                                                      GROUP BY AccountId];// case should be open
            Map<Id,Integer> MapAccount_Case  = new Map<Id,Integer>();
            for (AggregateResult result : AccountCase_List)
            {            
                MapAccount_Case.put((id)result.get('CaseAccountId'), (Integer)result.get('CaseCount'));
            }   
            
            List<Conge_Indispo__c> Conge_IndispoList =[SELECT Nom_du_compte__c 
                                                         FROM Conge_Indispo__c 
                                                        WHERE Nom_du_compte__c in :AccountIds and
                                                              TECH_Conges_Dispo_Juillet_Aout__c = true];
            //Map containing Account with conge List
            Map<Id,List<Conge_Indispo__c>> MapAccount_Conge = new Map<Id,List<Conge_Indispo__c>>();
            for (Conge_Indispo__c ci : Conge_IndispoList)
            {
                if(!MapAccount_Conge.containsKey(ci.Nom_du_compte__c))
                {
                    MapAccount_Conge.put(ci.Nom_du_compte__c, new List<Conge_Indispo__c>());
                }              
                MapAccount_Conge.get(ci.Nom_du_compte__c).add(ci);
            }   
            
            for(Account currentacc : account_MetCondition){ 
                if (!MapAccount_Conge.containsKey(currentacc.id) && !MapAccount_Case.containsKey(currentacc.id))               
                {
                    if (currentacc.ShippingCountry !='' && currentacc.ShippingCountry != null){
                        //France
                       if(currentacc.ShippingCountry == 'France'){
                        Case newCase = new Case();
                        newCase.Status = Label.ReQuette_En_attente_de_traitement;// no translation needed
                        Association_Record_Type_et_pays__mdt temp_Association_R = mapassociationRTPays.get(currentacc.ShippingCountry);
                        newCase.RecordTypeId = temp_Association_R.ID_Requete_Conge__c ;
                        newCase.ContactId = currentacc.Contact_operationnel_1__c;
                        newCase.AccountId = currentacc.id;
                        newCase.ownerId = label.FileWebHelp_ID_FR;
                        newCase.Object_de_la_requete__c='Les Congés du relais';
                        NewCaseList.add(newCase);
                        }
                     //BNL + Hongrie
                     else{
                        Case newCase = new Case();
                        newCase.Status = Label.ReQuette_En_attente_de_traitement;// no translation needed
                        Association_Record_Type_et_pays__mdt temp_Association_R = mapassociationRTPays.get(currentacc.ShippingCountry);
                        newCase.RecordTypeId = temp_Association_R.ID_Requete_Conge__c ;
                        newCase.ContactId = currentacc.Contact_operationnel_1__c;
                        newCase.AccountId = currentacc.id;
                        newCase.Object_de_la_requete__c='Les Congés du relais';
                        NewCaseList.add(newCase);  
                        }
                    }
                    else{
                         LBatchLogs.add(new Batch_log__c(Status_Code__c = 'AP07_Account', Message__c = Label.Message_No_Shipping_Country, Fields__c = Label.Shipping_Country, ID__c = currentacc.id
                            ));
                    }
                }
            }            
            Database.SaveResult[] srList = Database.insert(NewCaseList,false);
            if(Label.is_Batch_Logs_Active == 'true'){
                //List<Batch_Log__c> LBatchLogs = new List<Batch_Log__c>();
                for (Integer i = 0; i < NewCaseList.size(); i++) {
                    Database.SaveResult sr = srList[i];
                    Case origRecord = NewCaseList[i];
                    if (!sr.isSuccess()) {
                        for(Database.Error err : sr.getErrors()) {
                            LBatchLogs.add(new Batch_log__c(Status_Code__c = '' + err.getStatusCode(), Message__c = err.getMessage(), Fields__c = '' + err.getFields(), ID__c = sr.Id ));
                        }
                    }
                }
                if(LBatchLogs.size() > 0){
                    insert LBatchLogs;
                }
            }
        }
    }      
}