force-app/main/default/objects/Account/fields/Contexte__c.field-meta.xml
<CustomField>
    <fullName>Contexte__c</fullName>
    <label>Contexte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusion</fullName>
            </value>
            <value>
                <fullName>Résiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_fin_d_activite__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_d_activite__c</fullName>
    <label>Date de fin d&#39;activité</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/En_attente_de_courrier__c.field-meta.xml
<CustomField>
    <fullName>En_attente_de_courrier__c</fullName>
    <label>En attente de courrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Résiliation</fullName>
            </value>
            <value>
                <fullName>Exclusion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Etat__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_MOD</valueSetName>
    </valueSet>
</CustomField>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_MOD.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>200</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>220</fullName>
    </customValue>
    <customValue>
        <fullName>240</fullName>
    </customValue>
    <customValue>
        <fullName>250</fullName>
    </customValue>
    <customValue>
        <fullName>260</fullName>
    </customValue>
    <customValue>
        <fullName>264</fullName>
    </customValue>
    <customValue>
        <fullName>270</fullName>
    </customValue>
    <customValue>
        <fullName>300</fullName>
    </customValue>
    <customValue>
        <fullName>730</fullName>
    </customValue>
    <customValue>
        <fullName>735</fullName>
    </customValue>
    <customValue>
        <fullName>740</fullName>
    </customValue>
    <customValue>
        <fullName>745</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>900</fullName>
    </customValue>
    <customValue>
        <fullName>MC9</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de validation DOR</fullName>
    </customValue>
    <customValue>
        <fullName>65</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de signature</fullName>
    </customValue>
    <customValue>
        <fullName>Accord Pickup : Non retenu</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>280</fullName>
    </customValue>
    <customValue>
        <fullName>290</fullName>
    </customValue>
    <customValue>
        <fullName>310</fullName>
    </customValue>
    <description>Mode du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_MOD</masterLabel>
</GlobalValueSet>

src/classes/Batch_Account_Reprise.cls
/**
 * @author		: TMAEIL AHA
 * @Description	: Batch to replace Process Builders 'PB07 - Changement Etat/Mode 6-7', 'CONS_PB01_Date_FDA_renseignee' and 'PUDO_PB14_Retour_EtatMode'
 * @Test Class	: Batch_Account_Reprise_Test
 */

global class Batch_Account_Reprise implements Database.Batchable<sObject>{
    string query;


    global Batch_Account_Reprise(){
        
        query = 'SELECT Id, RecordTypeId, Date_de_fin_d_activite__c, Contexte__c, Etat__c, Mode__c, En_attente_de_courrier__c'
            + ' FROM Account'
            + ' WHERE Date_de_fin_d_activite__c <> NULL';    
    }
    
     global Batch_Account_Reprise(String id){
        query = 'SELECT Id, RecordTypeId, Date_de_fin_d_activite__c, Contexte__c, Etat__c, Mode__c, En_attente_de_courrier__c'
            + ' FROM Account'
            + ' WHERE Date_de_fin_d_activite__c <> NULL'
            + ' AND Id=\'' + id + '\'';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        //TODO: needs bypass?
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope){
    	AP11_Account.changerEtatModeSelonDFA(scope); 
    }
    
    global void finish(Database.BatchableContext BC){
    }
}