force-app/main/default/objects/Account/fields/Contact_operationnel_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_operationnel_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact opérationnel</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secteur__c.field-meta.xml
<CustomField>
    <fullName>Secteur__c</fullName>
    <formula>Zone_dimplantation__r.Secteur_parent__r.Secteur_parent__r.Secteur_parent__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secteur</label>
    <type>Text</type>
</CustomField>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Sens_du_contact__c</fullName>
        <label>Sens du contact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Entrant</fullName>
                    <default>true</default>
                    <label>Entrant</label>
                </value>
                <value>
                    <fullName>Sortant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sous_motif_1__c</fullName>
        <label>Sous-motif 1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Actions à réaliser</fullName>
                </value>
                <value>
                    <fullName>Anomalie colis</fullName>
                </value>
                <value>
                    <fullName>Autres</fullName>
                </value>
                <value>
                    <fullName>Changement de coordonnees</fullName>
                    <label>Changement de coordonnées</label>
                </value>
                <value>
                    <fullName>Colis volumineux</fullName>
                </value>
                <value>
                    <fullName>Collecte</fullName>
                </value>
                <value>
                    <fullName>Collecte Transporteur</fullName>
                </value>
                <value>
                    <fullName>Commandes</fullName>
                </value>
                <value>
                    <fullName>Comportement du point relais</fullName>
                </value>
                <value>
                    <fullName>Congé et disponibilité du point relais</fullName>
                </value>
                <value>
                    <fullName>Contre-remboursement (COD)</fullName>
                </value>
                <value>
                    <fullName>Demande d&apos;enlèvement colis</fullName>
                </value>
                <value>
                    <fullName>Demande de retour colis</fullName>
                </value>
                <value>
                    <fullName>Dépôt</fullName>
                </value>
                <value>
                    <fullName>Dévoyés</fullName>
                </value>
                <value>
                    <fullName>Dévoyés 100% cause relais</fullName>
                </value>
                <value>
                    <fullName>Dévoyés partiels cause relais</fullName>
                </value>
                <value>
                    <fullName>Echange</fullName>
                </value>
                <value>
                    <fullName>État du colis</fullName>
                </value>
                <value>
                    <fullName>Événement grave</fullName>
                </value>
                <value>
                    <fullName>Exclusion</fullName>
                </value>
                <value>
                    <fullName>Facturation</fullName>
                </value>
                <value>
                    <fullName>Horaires</fullName>
                </value>
                <value>
                    <fullName>Indemnisation colis</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité</fullName>
                </value>
                <value>
                    <fullName>Informations colis</fullName>
                </value>
                <value>
                    <fullName>Inventaire colis</fullName>
                </value>
                <value>
                    <fullName>Inventaire colis non réalisé</fullName>
                </value>
                <value>
                    <fullName>Livraison</fullName>
                </value>
                <value>
                    <fullName>Menace de résiliation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>TM_FR</fullName>
        <active>true</active>
        <businessProcess>TM_France</businessProcess>
        <description>Permet de créer une requête Ticket Manager FR</description>
        <label>TM_FR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Secteur__c.object
<CustomObject>
    <description>Un découpage géographique du territoire d&apos;un opérateur, pouvant se chevaucher. Il est aligné sur l&apos;organisation de l&apos;opérateur.</description>
    <label>Secteur</label>
    <nameField>
        <label>Nom du secteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secteurs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchCloseCaseMissRoutedPart_Test.cls
@isTest
private class BatchCloseCaseMissRoutedPart_Test{

    static testmethod void test() {        
        Test.startTest();
        Id accountRecordTypeId = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SObjectType = 'Account' and developerName='PUS_FR_PUDO_Suivi_CO'].Id;
        Id CaseRecordTypeId = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SObjectType = 'Case' and developerName='TM_FR'].Id;
        Macroprofil__c MP = Utils_TestMethods.CreateMacroprofil('MP1-Standard');
        MP.Name = 'MP1-Standard';
        insert MP;
        
        Contact acontact = Utils_TestMethods.CreateContact('contactPudo');
        insert acontact;
        Secteur__c asecteur= Utils_TestMethods.createSectorFR('secteurFR');
        insert asecteur;
        Account compte = Utils_TestMethods.CreateAccountPUS_FR_SuiviCo(acontact, MP, 'compte',asecteur );
        compte.Operateur_Global__c='PUS_FR';
        compte.Contact_operationnel_1__c=acontact.Id;
        compte.recordtypeId=accountRecordTypeId ;
        insert compte;
        Case testCase = new CAse(AccountId=compte.Id,reason='Colis', status='0',Sous_motif_1__c='Dévoyés partiels cause relais', Sens_du_contact__c='Sortant',recordtypeId=CaseRecordTypeId);
        insert testCase;
        
        BatchCloseCaseMissRoutedPart batchCloseCaseMissroutedPartiel = new BatchCloseCaseMissRoutedPart();
        Database.executeBatch(batchCloseCaseMissroutedPartiel);
        Test.stopTest();

    }
     public static testMethod void testschedule() {
        Test.StartTest();
        BatchCloseCaseMissroutedSchedule testsche = new BatchCloseCaseMissroutedSchedule();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, testsche );
        Test.stopTest();
    }
    
}