force-app/main/default/objects/Account/fields/Contrat_Joint__c.field-meta.xml
<CustomField>
    <fullName>Contrat_Joint__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Champ technique alimenté par un trigger. Il permet de savoir s&#39;il y a un fichier joint au format &quot;ID PUDO&quot; + &quot;_&quot; + une chaîne de caractères.</description>
    <label>Contrat Joint</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_internationale__c.field-meta.xml
<CustomField>
    <fullName>Reference_internationale__c</fullName>
    <externalId>true</externalId>
    <label>Référence internationale</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AP08_Attachement_Test.cls
@isTest
public class AP08_Attachement_Test {
    private static Account retrieveAccount(Id accountId) {
        return [SELECT Id, Contrat_Joint__c
                FROM Account
                where Id = : accountId
               ];
    }
    
    /*
     * Coverage for contentDocumentLink Triggers : after insert/update/delete
     * to be modified : to add functions in utils method + add content document with title equals to reference international
     */ 
    static testmethod void testContentDocumentLink() {
        
        ContentVersion testContentInsert = new ContentVersion(); 
        testContentInsert.ContentURL='http://www.google.com';
        testContentInsert.Title ='Google.com'; 
        insert testContentInsert; 
        
        
        //Create MP
        Macroprofil__c mp =  Utils_TestMethods.CreateMacroprofil('MP');
        insert mp;
        //Create Contact
        Contact contact =  Utils_TestMethods.CreateContact('contact');
        insert contact;
        //Create Account
        Account account = Utils_TestMethods.CreateAccount(contact, mp , 'Account');
        account.Reference_internationale__c = 'FR1234';
        insert account;
        
        //Create Content Version
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');
        ContentVersion cv = new ContentVersion();
        cv.title = 'FR1234_test';      
        cv.PathOnClient ='test';           
        cv.VersionData = beforeblob;          
        insert cv;         

        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];

        //Create ContentDocumentLink
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId = account.id;
        contentlink.ShareType= 'V'; // Viewer permission
        contentlink.ContentDocumentId= testcontent.ContentDocumentId; 
        insert contentlink;
         
        
        update contentlink;
        
        delete contentlink;
        
    }
    
    
    static testmethod void testAttachement() {
        
        //Create MP
        Macroprofil__c mp =  Utils_TestMethods.CreateMacroprofil('MP');
        insert mp;
        //Create Contact
        Contact contact =  Utils_TestMethods.CreateContact('contact');
        insert contact;
        //Create Account
        Account account = Utils_TestMethods.CreateAccount(contact, mp , 'Account');
        account.Reference_internationale__c = 'FR1234';
        insert account;
        
        //Create Non matching Attachment 
        Attachment attachment1 = Utils_TestMethods.createAttachment(account.Id , 'test body' , 'test');
        insert attachment1; 
        //System.assertEquals(false, retrieveAccount(account.Id).Contrat_Joint__c);
        
        //Create a matching Attachments
        Attachment attachment2 = Utils_TestMethods.createAttachment(account.Id , 'test body' , 'FR1234_Test1');
        insert attachment2;
        //System.assertEquals(true, retrieveAccount(account.Id).Contrat_Joint__c);
        
        //Update the matching Attachment
        attachment2.Name = 'test123';
        update attachment2;
        //System.assertEquals(false, retrieveAccount(account.Id).Contrat_Joint__c);
        
        //reUpdate the matching Attachment
        attachment2.Name = 'FR1234_GGG';
        update attachment2;
       // System.assertEquals(true, retrieveAccount(account.Id).Contrat_Joint__c);
        
        
        //deleting a matching attachment
        delete attachment2;
        //System.assertEquals(false, retrieveAccount(account.Id).Contrat_Joint__c);
        
    }
}