force-app/main/default/objects/Account/fields/Contexte__c.field-meta.xml
<CustomField>
    <fullName>Contexte__c</fullName>
    <label>Contexte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusion</fullName>
            </value>
            <value>
                <fullName>Résiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_fin_d_activite__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_d_activite__c</fullName>
    <label>Date de fin d&#39;activité</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Macroprofil de création.</inlineHelpText>
    <label>Macroprofil de référence</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>equals</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard, 23</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes (Macroprofil de référence)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Etat__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_MOD</valueSetName>
    </valueSet>
</CustomField>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ETA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_MOD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>220</fullName>
    </customValue>
    <customValue>
        <fullName>240</fullName>
    </customValue>
    <customValue>
        <fullName>250</fullName>
    </customValue>
    <customValue>
        <fullName>260</fullName>
    </customValue>
    <customValue>
        <fullName>264</fullName>
    </customValue>
    <customValue>
        <fullName>270</fullName>
    </customValue>
    <customValue>
        <fullName>300</fullName>
    </customValue>
    <customValue>
        <fullName>730</fullName>
    </customValue>
    <customValue>
        <fullName>735</fullName>
    </customValue>
    <customValue>
        <fullName>740</fullName>
    </customValue>
    <customValue>
        <fullName>745</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>900</fullName>
    </customValue>
    <customValue>
        <fullName>MC9</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de validation DOR</fullName>
    </customValue>
    <customValue>
        <fullName>65</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de signature</fullName>
    </customValue>
    <customValue>
        <fullName>Accord Pickup : Non retenu</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>280</fullName>
    </customValue>
    <customValue>
        <fullName>290</fullName>
    </customValue>
    <customValue>
        <fullName>310</fullName>
    </customValue>
    <description>Mode du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_MOD</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP11_Account_Test.cls
/**
*@Class: AP11_Account
*@Author: TMAEIL AHA
*@Date: 1/12/2017
*@Coverage: 77%
*@Description: Classe de test de la classe AP11_Account
*/

@isTest
public class AP11_Account_Test {
    
    static testMethod void testMAJ (){
        
        List<Account> listAccs = new List<Account>();
        
        // Object Account contains a lot of validation rules 
        User currentUser = [Select Id , BypassValidationRule__c
                            from User 
                            where Id=: UserInfo.getUserId()];
        currentUser.BypassValidationRule__c = true;
        update currentUser;
        
        
        //Create Macroprofil
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('MP2-Standard');        
        Macroprofil__c macroprofil2 = Utils_TestMethods.CreateMacroprofil('MPFR_Consigne');
        insert new list<Macroprofil__c> {macroprofil,macroprofil2};
                        
        //create account record
        Account acc1 = Utils_TestMethods.CreateAccount(null, macroprofil, 'acc1');
        acc1.Macroprofil_de_reference__c = macroprofil.Id;
        insert acc1;
        
        acc1.Date_de_fin_d_activite__c = system.today().addDays(18);
        acc1.Contexte__c = 'Exclusion' ;
        acc1.Etat__c = Label.Account_Etat_6;
        acc1.Mode__c = Label.Account_Mode_ResiliationSuggere;
        update acc1;
        
        acc1.Contexte__c = 'Résiliation';
        update acc1;
        
        acc1.Date_de_fin_d_activite__c = System.today().addDays(60);
        update acc1;
        
        acc1.Date_de_fin_d_activite__c = System.today().addDays(50);
        update acc1;
        
        acc1.Contexte__c = 'Exclusion';
        update acc1;
        
        acc1.Date_de_fin_d_activite__c = System.today();
        update acc1;
        
        acc1.Contexte__c = 'Résiliation';
        update acc1;
        listAccs.add(acc1);
        
        Account acc3 = Utils_TestMethods.CreateAccount(null, macroprofil, 'acc3');
        acc3.Macroprofil_de_reference__c = macroprofil.Id;
        acc3.Date_de_fin_d_activite__c = system.today().addDays(26);
        acc3.Contexte__c = 'Exclusion' ;
        listAccs.add(acc3);
        
        Account acc4 = Utils_TestMethods.CreateAccount(null, macroprofil, 'acc4');
        acc4.Macroprofil_de_reference__c = macroprofil.Id;
        acc4.Date_de_fin_d_activite__c = system.today();
        acc4.Contexte__c = 'Exclusion' ;
        listAccs.add(acc4);
        
        Account acc2 = Utils_TestMethods.CreateAccount(null, macroprofil2, 'acc2');
        acc2.Macroprofil_de_reference__c = macroprofil2.Id;
        acc2.RecordTypeId = '012580000005YcI';
        acc2.Date_de_fin_d_activite__c = system.today().addDays(25);
        acc2.Contexte__c = 'Résiliation' ;
        listAccs.add(acc2);
        
        Account acc5 = Utils_TestMethods.CreateAccount(null, macroprofil2, 'acc5');
        acc5.Macroprofil_de_reference__c = macroprofil2.Id;
        acc5.RecordTypeId = '012580000005YcI';
        acc5.Date_de_fin_d_activite__c = system.today().addDays(26);
        acc5.Contexte__c = 'Exclusion' ;
        listAccs.add(acc5);
        
        Account acc6 = Utils_TestMethods.CreateAccount(null, macroprofil2, 'acc6');
        acc6.Macroprofil_de_reference__c = macroprofil2.Id;
        acc6.RecordTypeId = '012580000005YcI';
        acc6.Date_de_fin_d_activite__c = system.today();
        acc6.Contexte__c = 'Résiliation' ;
        listAccs.add(acc6);
        
        Account acc7 = Utils_TestMethods.CreateAccount(null, macroprofil, 'acc7');
        acc7.Macroprofil_de_reference__c = macroprofil.Id;
        acc7.Date_de_fin_d_activite__c = null;
        acc7.Contexte__c = 'Résiliation' ;
        acc7.Etat__c='7';
        listAccs.add(acc7);
        
        AP11_Account.changerEtatModeSelonDFA(listAccs);
    } 
}