force-app/main/default/objects/Account/fields/Contact_operationnel_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_operationnel_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact opérationnel</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Indisponibilite_PB_Op_Qualite__c</fullName>
        <label>ID_Indisponibilite_PB_Op_ Qualite</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Indisponibilite_PB_Op_STS__c</fullName>
        <label>ID_Indisponibilite_PB_Op_ STS</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Indisponibilite_PB_PDA_Panne__c</fullName>
        <label>ID_Indisponibilite_PB_PDA_Panne</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Indisponibilite_PB_PDA_Synchro__c</fullName>
        <label>ID_Indisponibilite_PB_PDA_Synchro</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Indisponibilite_standard__c</fullName>
        <label>ID_Indisponibilite_standard</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Injoignable_Indisponible__c</fullName>
        <label>ID_Injoignable_Indisponible</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_WebHelpQueue__c</fullName>
        <description>Le propriétaire de la requête de type anomalie de synchronisation</description>
        <inlineHelpText>Le propriétaire de la requête de type anomalie de synchronisation</inlineHelpText>
        <label>ID_WebHelpQueue</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Indisponibilite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Indisponibilité</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Conge_Indispo__c.Nom_du_compte__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Conge_Indispo__c</referenceTo>
        <relationshipLabel>Requêtes</relationshipLabel>
        <relationshipName>Requ_tes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_de_la_requete__c</fullName>
        <label>Objet de la requête</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anomalie de synchronisation d’un relais</fullName>
                    <label>Anomalie de synchronisation d&apos;un relais</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Sinistre / Travaux / Santé</fullName>
                    <label>Indisponibilité - Problème opérationnel Sinistre / Travaux / Santé</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Qualité de Service</fullName>
                    <label>Indisponibilité - Problème opérationnel Qualité de Service</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Panne PDA</fullName>
                    <label>Indisponibilité - Problème PDA / Panne PDA</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Problème de synchronisation</fullName>
                    <label>Indisponibilité - Problème PDA / Problème de synchronisation</label>
                </value>
                <value>
                    <fullName>Indisponibilité problème opérationnel - Injoignabilité</fullName>
                </value>
                <value>
                    <fullName>Démarrage d&apos;activité</fullName>
                </value>
                <value>
                    <fullName>Relais sans formation avec moyens de scans associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif avec plusieurs moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Les relais actifs avec terme contrat non respecté</fullName>
                </value>
                <value>
                    <fullName>Les Congés du relais</fullName>
                </value>
                <value>
                    <fullName>Relais inactif avec moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif sans moyen de scan associé</fullName>
                </value>
                <value>
                    <fullName>Les horaires insuffisants du relais</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Anomalie colis</fullName>
                    <isActive>false</isActive>
                    <label>Indisponibilité Problème opérationnel Anomalie colis</label>
                </value>
                <value>
                    <fullName>Relais actif sans formation avec moyen de scan associé</fullName>
                    <isActive>false</isActive>
                    <label>Relais actif sans formation avec moyen de scan associé</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Raison_d_appel__c</fullName>
        <formula>TEXT( Indisponibilite__r.Raison_d_appel__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Raison d&apos;appel</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Date_de_debut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nom_du_compte__c</fullName>
        <label>Nom du compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Conges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Raison_d_appel__c</fullName>
        <label>Raison d&apos;appel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sous_type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Anomalie Colis</fullName>
                </value>
                <value>
                    <fullName>Anomalie de synchronisation</fullName>
                </value>
                <value>
                    <fullName>Autres</fullName>
                </value>
                <value>
                    <fullName>Démarrage d&apos;activité</fullName>
                </value>
                <value>
                    <fullName>Dévoyé</fullName>
                </value>
                <value>
                    <fullName>Dévoyés</fullName>
                    <isActive>false</isActive>
                    <label>Dévoyés</label>
                </value>
                <value>
                    <fullName>Enquête de bienvenue</fullName>
                </value>
                <value>
                    <fullName>Enquête de satisfaction</fullName>
                </value>
                <value>
                    <fullName>Exclusion</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité problème PDA</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité qualité de service</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité S/T/S</fullName>
                </value>
                <value>
                    <fullName>Injoignable</fullName>
                </value>
                <value>
                    <fullName>Menace de résiliation</fullName>
                    <label>Menaces de résiliation</label>
                </value>
                <value>
                    <fullName>Panne PDA</fullName>
                </value>
                <value>
                    <fullName>Pas de PDA associé</fullName>
                </value>
                <value>
                    <fullName>Problème synchronisation</fullName>
                </value>
                <value>
                    <fullName>Résiliation</fullName>
                </value>
                <value>
                    <fullName>Sinistre/Travaux/Santé</fullName>
                </value>
                <value>
                    <fullName>Surchage</fullName>
                    <isActive>false</isActive>
                    <label>Surchage</label>
                </value>
                <value>
                    <fullName>Surcharge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sous_type__c</fullName>
        <label>Sous type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_d_indisponibilite__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sinistre / Travaux / Santé</fullName>
                </value>
                <value>
                    <fullName>Qualité de service</fullName>
                </value>
                <value>
                    <fullName>Problème de synchronisation</fullName>
                </value>
                <value>
                    <fullName>Panne PDA</fullName>
                </value>
                <value>
                    <fullName>Injoignabilité</fullName>
                </value>
                <value>
                    <fullName>Pas de PDA associé</fullName>
                </value>
                <value>
                    <fullName>Anomalie colis</fullName>
                    <isActive>false</isActive>
                    <label>Anomalie colis</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_d_indisponibilite__c</fullName>
        <description>Ne pas activer l&apos;option &quot;Restreindre la liste sélectionnée aux valeurs définies dans l’ensemble de valeurs.	&quot; pour ne pas bloquer le PB qui crée automatiquement les indispos suite à des créations d&apos;anomalies.</description>
        <label>Type d&apos;indisponibilité</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>Planifiée</fullName>
                </value>
                <value>
                    <fullName>Imprévue</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AP09_Conge_Indispo.cls
/*
* The aim of this class is to create cases for unavailabilities
* @author: Christine Bayssary
* @date: 23/08/2018
* @Test: AP09_Conge_Indispo_Test
*/
public class AP09_Conge_Indispo {    
    /*--------------------------------------------------------------------------------------------------------------------------
     Author: Christine Bayssary
     Company: EI-technologies
     Description: Case creation for the unavailability
     Inputs: list of new unavailabilities
     Returns: -
    --------------------------------------------------------------------------------------------------------------------------*/    
    public static void createCase (list<Conge_Indispo__c> listIndispo){
        
        list<id> listIndispoSinistre = new list<id>();
        list<case> listCasestoInsert = new list<case>();
        list<id> listAccountIds = new list<id>();
        
        for(Conge_Indispo__c indispo : listIndispo){
            listAccountIds.add(indispo.Nom_du_compte__c);
        }
        
        map<id,account> mapAccount = new map<id,Account>([select id,Contact_operationnel_1__c
                                                            from account where id in:listAccountIds]);
        
                
        List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel,ID_Indisponibilite_standard__c,ID_Indisponibilite_PB_Op_STS__c,ID_WebHelpQueue__c,ID_Indisponibilite_PB_Op_Qualite__c,
                                                                                       ID_Indisponibilite_PB_PDA_Panne__c,ID_Indisponibilite_PB_PDA_Synchro__c,ID_Injoignable_Indisponible__c
                                                                             FROM Association_Record_Type_et_pays__mdt];
            
            
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
           associationRTPays.put(associationRT.MasterLabel, associationRT);  
        }
        
        for(Conge_Indispo__c indispo : listIndispo){
            if(indispo.Type_d_indisponibilite__c  == '1' 
               && indispo.sous_type__c == 'Sinistre / Travaux / Santé'
               && indispo.date_de_debut__c != null
               && indispo.recordtypeId == associationRTPays.get('France').ID_Indisponibilite_standard__c) {
                   case requete = new case();
                   requete.AccountId = indispo.Nom_du_compte__c;
                   requete.ContactId = mapAccount.get(indispo.Nom_du_compte__c).Contact_operationnel_1__c;
                   requete.Indisponibilite__c = indispo.id;
                   requete.OwnerId = associationRTPays.get('France').ID_WebHelpQueue__c;
                   requete.Status = 'En attente de traitement';
                   requete.Object_de_la_requete__c = 'Indisponibilité Problème opérationnel Sinistre / Travaux / Santé';
                   requete.RecordTypeId = associationRTPays.get('France').ID_Indisponibilite_PB_Op_STS__c;
                   requete.Subject = Label.Subject_Case_STS;
                   listCasestoInsert.add(requete);
               }
            else if(indispo.Type_d_indisponibilite__c  == '2' 
                    && indispo.sous_type__c == 'Problème de synchronisation'
                    && indispo.date_de_debut__c != null
                    && indispo.recordtypeId == associationRTPays.get('France').ID_Indisponibilite_standard__c){
                        case requete = new case();
                        requete.AccountId = indispo.Nom_du_compte__c;
                        requete.ContactId = mapAccount.get(indispo.Nom_du_compte__c).Contact_operationnel_1__c;
                        requete.Indisponibilite__c = indispo.id;
                        requete.OwnerId = Label.FileGestMat_ID_FR;
                        requete.Status = '0';
                        requete.Object_de_la_requete__c = 'Indisponibilité Problème PDA / Problème de synchronisation';
                        requete.RecordTypeId = associationRTPays.get('France').ID_Indisponibilite_PB_PDA_Synchro__c;
                        requete.Subject = label.Subject_Case_Prob_Synchro;
                        listCasestoInsert.add(requete);
                    } 
            else if(indispo.Type_d_indisponibilite__c  == '2' 
                    && indispo.sous_type__c == 'Panne PDA'
                    && indispo.date_de_debut__c != null
                    && indispo.recordtypeId == associationRTPays.get('France').ID_Indisponibilite_standard__c){
                        case requete = new case();
                        requete.AccountId = indispo.Nom_du_compte__c;
                        requete.ContactId = mapAccount.get(indispo.Nom_du_compte__c).Contact_operationnel_1__c;
                        requete.Indisponibilite__c = indispo.id;
                        requete.OwnerId = Label.FileGestMat_ID_FR;
                        requete.Status = '0';
                        requete.Object_de_la_requete__c = 'Indisponibilité Problème PDA / Panne PDA';
                        requete.RecordTypeId = associationRTPays.get('France').ID_Indisponibilite_PB_PDA_Panne__c;
                        requete.Subject = label.Subject_Case_Panne_PDA;
                        listCasestoInsert.add(requete);
                    }
            else if(indispo.Type_d_indisponibilite__c  == '1' 
                    && indispo.sous_type__c == 'Injoignabilité'
                    && indispo.date_de_debut__c != null
                    && indispo.recordtypeId == associationRTPays.get('France').ID_Indisponibilite_standard__c){
                        case requete = new case();
                        requete.AccountId = indispo.Nom_du_compte__c;
                        requete.ContactId = mapAccount.get(indispo.Nom_du_compte__c).Contact_operationnel_1__c;
                        requete.Indisponibilite__c = indispo.id;
                        
                        if(indispo.Raison_d_appel__c == 'Anomalie de synchronisation' || indispo.Raison_d_appel__c == 'Indisponibilité problème PDA'){
                            requete.OwnerId = label.FileGestMat_ID_FR;
                            requete.Status = '0';}
                        else{
                        requete.OwnerId = associationRTPays.get('France').ID_WebHelpQueue__c;
                        requete.Status = 'En attente de traitement'; }
                        requete.Object_de_la_requete__c = 'Indisponibilité problème opérationnel - Injoignabilité';
                        requete.RecordTypeId = associationRTPays.get('France').ID_Injoignable_Indisponible__c;
                        requete.Subject = label.Subject_Case_Indispo_Injoignabilit;
                        listCasestoInsert.add(requete);
                    } 
        }
        insert listCasestoInsert;      
    }
}