force-app/main/default/objects/Account/fields/Contact_operationnel_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_operationnel_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact opérationnel</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassApex__c</fullName>
        <label>BypassApex</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP01_Account</fullName>
                </value>
                <value>
                    <fullName>AP05_Account</fullName>
                </value>
                <value>
                    <fullName>AP06_MacroprofilReseau</fullName>
                </value>
                <value>
                    <fullName>Utils_PUS</fullName>
                </value>
                <value>
                    <fullName>AP04_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP02_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_CaseComment</fullName>
                </value>
                <value>
                    <fullName>AP08_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_CompteRenduRempli</fullName>
                </value>
                <value>
                    <fullName>AP01_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_Task</fullName>
                </value>
                <value>
                    <fullName>AP02_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP02_MacroprofilTransporteur</fullName>
                </value>
                <value>
                    <fullName>AP02_Task</fullName>
                </value>
                <value>
                    <fullName>AP03_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP03_MacroprofilService</fullName>
                </value>
                <value>
                    <fullName>AP03_ReseauAssocie</fullName>
                </value>
                <value>
                    <fullName>AP03_Task</fullName>
                </value>
                <value>
                    <fullName>AP04_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP05_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Account</fullName>
                </value>
                <value>
                    <fullName>AP08_Attachement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BypassProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassWorkflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ETA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Batch12_AccountCase.cls
global class Batch12_AccountCase Implements Database.batchable<sobject>
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {        
        UpdateUser(true, Label.BatchBypass);
        return Database.getQueryLocator([SELECT id,RecordTypeId,ShippingCountry,Etat__c,Type , Contact_operationnel_1__c
                                         FROM Account 
                                         WHERE((Etat__c = '4' or Etat__c = '5') and shippingCountry = 'France')]);       
    }
    
    global  void execute(Database.BatchableContext BC,List<Account> scope)
    {     
        AP07_Account.CreateCase(scope);
    }
    
    global void finish(Database.BatchableContext BC)
    {   
        UpdateUser(false, '');
    }
    
    private void UpdateUser(Boolean BypassworkflowProcessVR,String BypassTrigger){
        User currentUser = [Select id , name , BypassProcessBuilder__c, BypassWorkflow__c, BypassApex__c, BypassValidationRule__c
                            from User
                            where id =: UserInfo.getUserId()];
        currentUser.BypassProcessBuilder__c = BypassworkflowProcessVR;
        currentUser.BypassWorkflow__c = BypassworkflowProcessVR;
        currentUser.BypassValidationRule__c = BypassworkflowProcessVR;
        currentUser.BypassApex__c = BypassTrigger;
        update currentUser;
    }
}