force-app/main/default/objects/Account/fields/Contexte__c.field-meta.xml
<CustomField>
    <fullName>Contexte__c</fullName>
    <label>Contexte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusion</fullName>
            </value>
            <value>
                <fullName>Résiliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_fin_d_activite__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_d_activite__c</fullName>
    <label>Date de fin d&#39;activité</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_ferme__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Fermeture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Fermeture_Reference__c</fullName>
    <label>Horaire de fermeture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Ouverture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Ouverture_Reference__c</fullName>
    <label>Horaire d&#39;ouverture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Macroprofil de création.</inlineHelpText>
    <label>Macroprofil de référence</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>equals</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard, 23</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes (Macroprofil de référence)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mardi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Etat__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_MOD</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/N_de_rue_facturation__c.field-meta.xml
<CustomField>
    <fullName>N_de_rue_facturation__c</fullName>
    <label>N° de rue (adresse de facturation)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Responsable_facturation__c.field-meta.xml
<CustomField>
    <fullName>Responsable_facturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable facturation</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes (Responsable facturation)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Samedi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi fermé</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Responsable_facturation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Responsable facturation</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassApex__c</fullName>
        <label>BypassApex</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP01_Account</fullName>
                </value>
                <value>
                    <fullName>AP05_Account</fullName>
                </value>
                <value>
                    <fullName>AP06_MacroprofilReseau</fullName>
                </value>
                <value>
                    <fullName>Utils_PUS</fullName>
                </value>
                <value>
                    <fullName>AP04_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP02_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_CaseComment</fullName>
                </value>
                <value>
                    <fullName>AP08_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_CompteRenduRempli</fullName>
                </value>
                <value>
                    <fullName>AP01_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_Task</fullName>
                </value>
                <value>
                    <fullName>AP02_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP02_MacroprofilTransporteur</fullName>
                </value>
                <value>
                    <fullName>AP02_Task</fullName>
                </value>
                <value>
                    <fullName>AP03_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP03_MacroprofilService</fullName>
                </value>
                <value>
                    <fullName>AP03_ReseauAssocie</fullName>
                </value>
                <value>
                    <fullName>AP03_Task</fullName>
                </value>
                <value>
                    <fullName>AP04_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP05_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Account</fullName>
                </value>
                <value>
                    <fullName>AP08_Attachement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ETA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_HOR.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>19:00</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <description>Horaires d&#39;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_MOD.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>200</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>220</fullName>
    </customValue>
    <customValue>
        <fullName>240</fullName>
    </customValue>
    <customValue>
        <fullName>250</fullName>
    </customValue>
    <customValue>
        <fullName>260</fullName>
    </customValue>
    <customValue>
        <fullName>264</fullName>
    </customValue>
    <customValue>
        <fullName>270</fullName>
    </customValue>
    <customValue>
        <fullName>300</fullName>
    </customValue>
    <customValue>
        <fullName>730</fullName>
    </customValue>
    <customValue>
        <fullName>735</fullName>
    </customValue>
    <customValue>
        <fullName>740</fullName>
    </customValue>
    <customValue>
        <fullName>745</fullName>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
    </customValue>
    <customValue>
        <fullName>900</fullName>
    </customValue>
    <customValue>
        <fullName>MC9</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de validation DOR</fullName>
    </customValue>
    <customValue>
        <fullName>65</fullName>
    </customValue>
    <customValue>
        <fullName>En attente de signature</fullName>
    </customValue>
    <customValue>
        <fullName>Accord Pickup : Non retenu</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>280</fullName>
    </customValue>
    <customValue>
        <fullName>290</fullName>
    </customValue>
    <customValue>
        <fullName>310</fullName>
    </customValue>
    <description>Mode du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_MOD</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Batch_Account_Reprise_Test.cls
/**
*@Class: Batch_Account_DFA, Batch_Account_Reprise
*@Author: TMAEIL AHA
*@Date: 1/12/2017
*@Coverage: 100%
*@Description: Classe de test des batch Batch_Account_DFA et Batch_Account_Reprise
*/

@isTest
public class Batch_Account_Reprise_Test {
    
    testmethod static void testBatch() {
        
        
        User currentUser = [Select Id , BypassValidationRule__c,BypassApex__c
                            from User 
                            where Id=: UserInfo.getUserId()];
        currentUser.BypassValidationRule__c = true;
        currentUser.BypassApex__c = ('AP05_Account');
        update currentUser;
        
        system.runas(currentUser){
            
            Contact c = Utils_TestMethods.CreateContact('test');
            insert c;
            
            Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('MP');        
            Macroprofil__c macroprofil2 = Utils_TestMethods.CreateMacroprofil('MP2-Standard2');
           insert macroprofil;
            insert macroprofil2;
            
            Account acct = Utils_TestMethods.CreateAccount(c, macroprofil,'Account Test'); 
            acct.BillingStreet = 'Test';
            acct.BillingPostalCode = '25142';
            acct.BillingCountry = 'France';
            acct.BillingCountryCode = 'FR';
            acct.BillingCity = 'Paris';
            acct.ShippingPostalCode = '25142';
            acct.ShippingCountry = 'France';
            acct.ShippingCountryCode = 'FR';
            acct.ShippingCity = 'Paris';
            acct.ShippingStreet = 'Test';
            acct.Lundi_Ouverture__c = '01:00';
            acct.Lundi_Fermeture__c = '20:00';
            acct.lundi_debut_pause_dejeuner__c = '02:00';
            acct.lundi_fin_pause_dejeuner__c = '19:00';
            //acct.Mardi_ferme__c = true;
            acct.Mercredi_ferme__c = false;
            acct.Jeudi_ferme__c = false;
            acct.Vendredi_ferme__c = false;
            acct.Samedi_ferme__c = false;
            acct.Dimanche_ferme__c = false;
            acct.Horaire_Ouverture_Reference__c = '01:00';
            acct.Horaire_Fermeture_Reference__c = '20:00';
            acct.Type = 'Pickup store';
            acct.RecordTypeId = label.RT_Compte_Pickup_Contact;
            acct.Macroprofil_actuel__c = null;
            //acct.Macroprofil_de_reference__c = macroprofil2.id;
            acct.Responsable_facturation__c = c.id;
            acct.N_de_rue_facturation__c = 'test';
            acct.Date_de_fin_d_activite__c = system.today();
            acct.Contexte__c ='Exclusion';
            acct.Etat__c='2';
            acct.Mode__c=null;  
            insert acct;
            
            Test.startTest();
            Id batchJobId = Database.executeBatch(new Batch_Account_Reprise(), 200); 
            Id batchJobId2 = Database.executeBatch(new Batch_Account_Reprise(acct.id)); 
            Id batchJobId3 = Database.executeBatch(new Batch08_Account_DFA(), 200); 
            Id batchJobId4 = Database.executeBatch(new Batch08_Account_DFA(acct.id)); 
            Test.stopTest();
        }
    }    
}