force-app/main/default/objects/Account/fields/Contact_operationnel_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_operationnel_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact opérationnel</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_de_visite__c.field-meta.xml
<CustomField>
    <fullName>Date_de_visite__c</fullName>
    <label>Date de visite</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hauteur_cm__c.field-meta.xml
<CustomField>
    <fullName>Hauteur_cm__c</fullName>
    <label>Hauteur (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Largeur_cm__c.field-meta.xml
<CustomField>
    <fullName>Largeur_cm__c</fullName>
    <label>Largeur (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nom_Responsable_magasin__c.field-meta.xml
<CustomField>
    <fullName>Nom_Responsable_magasin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable magasin</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes (Gérant)</relationshipLabel>
    <relationshipName>Comptes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_detageres__c.field-meta.xml
<CustomField>
    <fullName>Nombre_detageres__c</fullName>
    <label>Nombre d&#39;étagères</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Profondeur_cm__c.field-meta.xml
<CustomField>
    <fullName>Profondeur_cm__c</fullName>
    <label>Profondeur (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_internationale__c.field-meta.xml
<CustomField>
    <fullName>Reference_internationale__c</fullName>
    <externalId>true</externalId>
    <label>Référence internationale</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Responsable_facturation__c.field-meta.xml
<CustomField>
    <fullName>Responsable_facturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable facturation</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes (Responsable facturation)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seuil_contractuel__c.field-meta.xml
<CustomField>
    <fullName>Seuil_contractuel__c</fullName>
    <label>Seuil contractuel</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Compte_rendu__c.object
<CustomObject>
    <description>Cet objet permet de sélectionner les questions CR en fonction du compte rendu sélectionné.</description>
    <fields>
        <fullName>Compte_rendu__c</fullName>
        <label>Compte rendu</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>INTER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_de_compte_rendu__c</fullName>
        <label>Type de compte rendu</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VA Standard</fullName>
                </value>
                <value>
                    <fullName>VALP</fullName>
                </value>
                <value>
                    <fullName>VA Quali</fullName>
                </value>
                <value>
                    <fullName>VA Orga</fullName>
                </value>
                <value>
                    <fullName>VAP PDA</fullName>
                </value>
                <value>
                    <fullName>VAP Seuil</fullName>
                </value>
                <value>
                    <fullName>VAP FDA</fullName>
                </value>
                <value>
                    <fullName>VAP Injoignable</fullName>
                </value>
                <value>
                    <fullName>VAP DA</fullName>
                </value>
                <value>
                    <fullName>VAP MEN</fullName>
                </value>
                <value>
                    <fullName>VAP VO</fullName>
                </value>
                <value>
                    <fullName>VAP QS</fullName>
                </value>
                <value>
                    <fullName>VAP Enquête de satisfaction</fullName>
                </value>
                <value>
                    <fullName>VAP Enquête de bienvenue</fullName>
                </value>
                <value>
                    <fullName>VAP FC</fullName>
                </value>
                <value>
                    <fullName>Recruitment visit report</fullName>
                </value>
                <value>
                    <fullName>Monitoring visit report</fullName>
                </value>
                <value>
                    <fullName>Course visit report</fullName>
                </value>
                <value>
                    <fullName>VA FDA</fullName>
                    <isActive>false</isActive>
                    <label>VA FDA</label>
                </value>
                <value>
                    <fullName>VA Injoignable</fullName>
                    <isActive>false</isActive>
                    <label>VA Injoignable</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compte rendu</label>
    <nameField>
        <label>Nom de compte rendu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes rendus</pluralLabel>
    <recordTypes>
        <fullName>VA</fullName>
        <active>true</active>
        <label>VA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compte_rendu_rempli__c.object
<CustomObject>
    <description>Compte rendu VA/VAP rempli suite à la visite d&apos;un animateur chez un PUDO.</description>
    <fields>
        <fullName>Compte_rendu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte rendu</label>
        <referenceTo>Compte_rendu__c</referenceTo>
        <relationshipName>Comptes_rendus_remplis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Comptes rendus remplis</relationshipLabel>
        <relationshipName>Comptes_rendus_remplis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsable_facturation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable facturation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Compte__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Comptes rendus remplis (Responsable facturation)</relationshipLabel>
        <relationshipName>Comptes_rendus_remplis2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seuil_contractuel__c</fullName>
        <label>Seuil contractuel</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Compte rendu de visite</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Nom de compte rendu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comptes rendus de visite</pluralLabel>
    <recordTypes>
        <fullName>VA</fullName>
        <active>true</active>
        <label>VA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Responsable_facturation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Responsable facturation</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questions_CR__c.object
<CustomObject>
    <description>Questions utilisés pour les questionnaires VA/VAP.</description>
    <fields>
        <fullName>Compte_rendu__c</fullName>
        <label>Nom du compte rendu</label>
        <referenceTo>Compte_rendu__c</referenceTo>
        <relationshipName>Questionnaires_VA_VAP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Questions CR</label>
    <nameField>
        <label>Numéro de question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions CR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/VFC14_DemarrageCompteRenduRempli_Test.cls
@isTest
public class VFC14_DemarrageCompteRenduRempli_Test {
    static testMethod void DemarrageCompteRenduRempli_Test() {
        
        List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_Converti__c
                                                                                  FROM Association_Record_Type_et_pays__mdt];
            
            
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
          associationRTPays.put(associationRT.MasterLabel, associationRT);}
        
        //Create Macro Profil
        Macroprofil__c MP = Utils_TestMethods.CreateMacroprofil('Name');
        insert MP;
        
        //Create Account France
        Account account1= Utils_TestMethods.CreateAccount(null, null, 'Test Account1');
        account1.RecordTypeId = associationRTPays.get('France').ID_Prospect_Converti__c;
        account1.ShippingCountry ='France';
        account1.ShippingCountrycode ='FR';
        account1.Etat__c = '0';
        account1.Operateur_Global__c='PUS_FR';
        account1.Reference_internationale__c ='121212';
        account1.Date_de_visite__c =Date.today();
        account1.Hauteur_cm__c = 250;
        account1.Largeur_cm__c=155;
        account1.Nombre_detageres__c=1;
        account1.Profondeur_cm__c=40;
        account1.Seuil_contractuel__c=1;
        account1.Macroprofil_actuel__c = MP.Id;
        insert account1;
        
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        testContact.AccountId = account1.id; 
        insert testContact;
        account1.Contact_operationnel_1__c =  testContact.id;
        account1.Responsable_facturation__c = testContact.id;
        account1.Nom_Responsable_magasin__c = testContact.id;
        update account1; 
        
        Id selectedRTT = [select id from RecordType where id =:id.valueOf(Label.VAVAP_recordTypeVA) limit 1].id;
        //Create CRobjectType =:Label.VAVAP_compteRenduRempliLabel
        Compte_rendu__c CR = new Compte_rendu__c(RecordTypeId = [select id, Name, SobjectType from RecordType where SobjectType ='Compte_rendu__c'  and Name ='VA'limit 1].id);
        CR.Name = 'name1';	
        CR.Type_de_compte_rendu__c = 'VA Standard';
        insert CR;
        
        Questions_CR__c ques = new Questions_CR__c();
        ques.Compte_rendu__c = CR.id;
        ques.Options_de_reponses__c = 'Oui;Non';
        ques.Questions__c = 'test?';
        ques.Type_de_reponse__c = 'Choix';
        ques.Follow_up__c = false;
        
        insert ques;
        
        Compte_rendu_rempli__c myCRR = new Compte_rendu_rempli__c();
        myCRR.Compte__c = account1.id;
        myCRR.Compte_rendu__c = CR.id;
        myCRR.RecordTypeId = Label.VAVAP_recordTypeVA;
        myCRR.Type_de_compte_rendu__c = 'VA Standard';
        myCRR.Statut__c = 'En attente de traitement';
        
        insert myCRR;
        
        Questions_CR__c quesMP = new Questions_CR__c();
        quesMP.Compte_rendu__c = CR.id;
        quesMP.Questions__c = 'test?';
        quesMP.Changement_macro_profil__c = false;
        insert quesMP;
        
        Reponse_CR__c rep = Utils_TestMethods.createReponseCR(myCRR.Id, quesMP.Id, '', 'MPFR_Consigne');
        insert rep;
        
        test.StartTest();
        PageReference pageRef = Page.VFP14_DemarrageCompteRenduRempli;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(new Compte_rendu_rempli__c( Compte__c = account1.Id));
        VFC14_DemarrageCompteRenduRempli demarrageCRR = new VFC14_DemarrageCompteRenduRempli(sc);
        demarrageCRR.CRR.Compte__c = account1.id;
        demarrageCRR.getCRTypes();
        demarrageCRR.selectedRT= selectedRTT;
        demarrageCRR.CRR.Contact_operationnel_rencontre__c = true;
        //demarrageCRR.CRR.Contact__c =  testContact.id;
        demarrageCRR.getOtherContact();
        demarrageCRR.getPickListValues();
        demarrageCRR.selectedRT= selectedRTT;
        demarrageCRR.CRR.Type_de_compte_rendu__c = 'VA Standard';
        demarrageCRR.redirectToQuestionnaire();
        demarrageCRR.selectedRT= selectedRTT;
        demarrageCRR.listWrapperQuestions[0].reponse='MPFR_Consigne';
        demarrageCRR.saveResponse();
        String myString;
        List<string> myList = new List<string>();
        myList = demarrageCRR.handleMultiPicklist('Testing');
        myString = demarrageCRR.multiToString(myList);
       
        // test Update
        PageReference pageRef2 = Page.VFP14_DemarrageCompteRenduRempli;
        Test.setCurrentPage(pageRef2);
        ApexPages.StandardController sc2 = new ApexPages.StandardController(myCRR);
        VFC14_DemarrageCompteRenduRempli demarrageCRR2 = new VFC14_DemarrageCompteRenduRempli(sc2); 
        demarrageCRR2.redirectToQuestionnaire();
        demarrageCRR2.saveResponse();
        
        
        myCRR.Date_de_la_visite__c = null;
        myCRR.Statut__c=Label.VAVAP_statutTermine;
        PageReference pageRef3 = Page.VFP14_DemarrageCompteRenduRempli;
        Test.setCurrentPage(pageRef3);
        ApexPages.StandardController sc3 = new ApexPages.StandardController(myCRR);
        VFC14_DemarrageCompteRenduRempli demarrageCRR3 = new VFC14_DemarrageCompteRenduRempli(sc3); 
    
        demarrageCRR3.redirectToQuestionnaire();
        demarrageCRR.listWrapperQuestions[0].reponse='Autre';
        demarrageCRR.CRR.Contact__c =  '0035E00000SEx3D';
        demarrageCRR.getOtherContact();
        demarrageCRR.CRR.Contact__c =  null;
        demarrageCRR.getOtherContact();
        demarrageCRR3.saveResponse();
        demarrageCRR3.closePage();
        test.stopTest();
    }
}