force-app/main/default/objects/Account/fields/Debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>Debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche__c.field-meta.xml
<CustomField>
    <fullName>Dimanche__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/dimanche_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>dimanche_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_ferme__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/dimanche_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>dimanche_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>Fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi__c.field-meta.xml
<CustomField>
    <fullName>Jeudi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/jeudi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>jeudi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/jeudi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>jeudi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi__c.field-meta.xml
<CustomField>
    <fullName>Lundi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Lundi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi__c.field-meta.xml
<CustomField>
    <fullName>Mardi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi__c.field-meta.xml
<CustomField>
    <fullName>Mercredi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi__c.field-meta.xml
<CustomField>
    <fullName>Samedi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/samedi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>samedi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/samedi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>samedi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_Number_Closing_Hour__c.field-meta.xml
<CustomField>
    <fullName>Tech_Number_Closing_Hour__c</fullName>
    <label>Tech Number Closing Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_Number_End_Lunch_Hour__c.field-meta.xml
<CustomField>
    <fullName>Tech_Number_End_Lunch_Hour__c</fullName>
    <label>Tech Number End Lunch Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_Number_Now__c.field-meta.xml
<CustomField>
    <fullName>Tech_Number_Now__c</fullName>
    <formula>VALUE(LEFT(MID(TEXT(NOW() + (VALUE($User.Tech_GMT_Offset_Formula__c) / 24)  ), 12, 5),2)) * 60 +  VALUE(RIGHT(MID(TEXT(NOW()+  (VALUE($User.Tech_GMT_Offset_Formula__c)/ 24)  ), 12, 5),2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tech Number Now</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_Number_Opening_Hour__c.field-meta.xml
<CustomField>
    <fullName>Tech_Number_Opening_Hour__c</fullName>
    <label>Tech Number Opening Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_Number_Start_Lunch_Hour__c.field-meta.xml
<CustomField>
    <fullName>Tech_Number_Start_Lunch_Hour__c</fullName>
    <label>Tech Number Start Lunch Hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi__c.field-meta.xml
<CustomField>
    <fullName>Vendredi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/vendredi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>vendredi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vendredi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>vendredi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

src/globalValueSets/LOV_GLO_HOR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <description>Horaires d&apos;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

src/classes/Batch02_Account.cls
global class Batch02_Account implements Database.Batchable<sObject> {
    
    String soqlQuery = 'SELECT Id, Tech_Number_Closing_Hour__c , Tech_Number_End_Lunch_Hour__c , Tech_Number_Now__c , Tech_Number_Opening_Hour__c , Tech_Number_Start_Lunch_Hour__c ,' +
        			   'Mardi__c , Mardi_Ouverture__c , Mardi_Fermeture__c , mardi_debut_pause_dejeuner__c , mardi_fin_pause_dejeuner__c , ' +
        			   'Mercredi__c , Mercredi_Ouverture__c , Mercredi_Fermeture__c , Mercredi_debut_pause_dejeuner__c , Mercredi_fin_pause_dejeuner__c ,' +
        	           'Jeudi__c , Jeudi_Ouverture__c , Jeudi_Fermeture__c , Jeudi_debut_pause_dejeuner__c , Jeudi_fin_pause_dejeuner__c ,' +
        			   'Vendredi__c , Vendredi_Ouverture__c , Vendredi_Fermeture__c , Vendredi_debut_pause_dejeuner__c , Vendredi_fin_pause_dejeuner__c ,' +
        			   'Samedi__c , Samedi_Ouverture__c , Samedi_Fermeture__c , Samedi_debut_pause_dejeuner__c , Samedi_fin_pause_dejeuner__c ,' +
        			   'Dimanche__c , Dimanche_Ouverture__c , Dimanche_Fermeture__c , Dimanche_debut_pause_dejeuner__c , Dimanche_fin_pause_dejeuner__c ,' +
        			   'Lundi__c , Lundi_Ouverture__c , Lundi_Fermeture__c , Lundi_debut_pause_dejeuner__c , Lundi_fin_pause_dejeuner__c , ' +
        			   'Dimanche_ferme__c,Lundi_ferme__c,Mardi_ferme__c,Mercredi_ferme__c,Jeudi_ferme__c,Vendredi_ferme__c,Samedi_ferme__c, ' + 
        			   'Horaire_Ouverture_Reference__c,Horaire_Fermeture_Reference__c,Debut_pause_dejeuner__c,Fin_pause_dejeuner__c ' +
          			   'FROM Account';
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        UpdateUser(true, Label.BatchBypass);
        return Database.getQueryLocator(soqlQuery);    
    }
    
    global void execute(Database.BatchableContext BC , List<sObject> scope) { 
        AP09_Account.defineAccountDailyDisponibility(scope, true); 
    }
     
    
    global void finish(Database.BatchableContext BC){ 
        UpdateUser(false, '');
        Database.executeBatch(new Batch06_AccountCongeIndispo(),Integer.valueOf(Label.Lot_Batch06_AccountCongeIndispo) );
    }
    
    private void UpdateUser(Boolean BypassworkflowProcessVR,String BypassTrigger){
        User currentUser = [Select id , name , BypassProcessBuilder__c, BypassWorkflow__c, BypassApex__c, BypassValidationRule__c
                           from User
                           where id =: UserInfo.getUserId()];
        currentUser.BypassProcessBuilder__c = BypassworkflowProcessVR;
        currentUser.BypassWorkflow__c = BypassworkflowProcessVR;
        currentUser.BypassValidationRule__c = BypassworkflowProcessVR;
        currentUser.BypassApex__c = BypassTrigger;
        update currentUser;
    }

}