force-app/main/default/objects/Account/fields/Debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>Debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche__c.field-meta.xml
<CustomField>
    <fullName>Dimanche__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/dimanche_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>dimanche_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_ferme__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/dimanche_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>dimanche_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>Fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Fermeture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Fermeture_Reference__c</fullName>
    <label>Horaire de fermeture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Ouverture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Ouverture_Reference__c</fullName>
    <label>Horaire d&#39;ouverture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/jeudi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>jeudi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/jeudi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>jeudi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi__c.field-meta.xml
<CustomField>
    <fullName>Lundi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Lundi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi__c.field-meta.xml
<CustomField>
    <fullName>Mardi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mardi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi__c.field-meta.xml
<CustomField>
    <fullName>Mercredi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/samedi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>samedi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Samedi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/samedi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>samedi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vendredi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>vendredi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vendredi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>vendredi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOV_GLO_HOR.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <description>Horaires d&#39;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP09_Account.cls
/*
* Class to show the disponibilte of an account
* @author: Georges Hobeika
* @date: 02/03/2017
* @Test: AP09_Account_Test
*/
public class AP09_Account {
    
    public static boolean firstRun = true;
    
    private static Map<Integer, String> mapOpeningHoursFields  = new Map<Integer, String>();
    private static Map<Integer, String> mapClosingHoursFields = new Map<Integer, String>();
    private static Map<Integer, String> mapStartLunchBreakFields = new Map<Integer, String>();
    private static Map<Integer, String> mapEndLunchBreakFields = new Map<Integer, String>();
    private static Map<Integer, String> mapOpeningDays = new Map<Integer ,String>();
    private static Map<Integer, String> mapDays = new Map<Integer, String>();
    private static String horaireOuvertureReference = 'Horaire_Ouverture_Reference__c';
    private static String horaireFermetureReference = 'Horaire_Fermeture_Reference__c';
    private static String debutPauseDejeuner = 'Debut_pause_dejeuner__c';
    private static String finPauseDejeuner = 'Fin_pause_dejeuner__c';
    
     private static void fillMaps() {
         
        mapOpeningHoursFields.put(0, 'Dimanche_Ouverture__c');
        mapOpeningHoursFields.put(1, 'Lundi_Ouverture__c');
        mapOpeningHoursFields.put(2, 'Mardi_Ouverture__c');
        mapOpeningHoursFields.put(3, 'Mercredi_Ouverture__c');
        mapOpeningHoursFields.put(4, 'Jeudi_Ouverture__c');
        mapOpeningHoursFields.put(5, 'Vendredi_Ouverture__c'); 
        mapOpeningHoursFields.put(6, 'Samedi_Ouverture__c'); 
        
        mapClosingHoursFields.put(0, 'Dimanche_Fermeture__c');
        mapClosingHoursFields.put(1, 'Lundi_Fermeture__c');
        mapClosingHoursFields.put(2, 'Mardi_Fermeture__c');
        mapClosingHoursFields.put(3, 'Mercredi_Fermeture__c');
        mapClosingHoursFields.put(4, 'Jeudi_Fermeture__c');
        mapClosingHoursFields.put(5, 'Vendredi_Fermeture__c'); 
        mapClosingHoursFields.put(6, 'Samedi_Fermeture__c');
        
        mapStartLunchBreakFields.put(0, 'dimanche_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(1, 'lundi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(2, 'mardi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(3, 'mercredi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(4, 'jeudi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(5, 'vendredi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(6, 'samedi_debut_pause_dejeuner__c');
         
        mapEndLunchBreakFields.put(0, 'dimanche_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(1, 'lundi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(2, 'mardi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(3, 'mercredi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(4, 'jeudi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(5, 'vendredi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(6, 'samedi_fin_pause_dejeuner__c');
         
         
        mapOpeningDays.put(0, 'Dimanche_ferme__c'); 
        mapOpeningDays.put(1, 'Lundi_ferme__c');
        mapOpeningDays.put(2, 'Mardi_ferme__c');
        mapOpeningDays.put(3, 'Mercredi_ferme__c');
        mapOpeningDays.put(4, 'Jeudi_ferme__c');
        mapOpeningDays.put(5, 'Vendredi_ferme__c');
        mapOpeningDays.put(6, 'Samedi_ferme__c');
         
        mapDays.put(0, 'Dimanche__c');
        mapDays.put(1, 'Lundi__c');
        mapDays.put(2, 'Mardi__c');
        mapDays.put(3, 'Mercredi__c');
        mapDays.put(4, 'Jeudi__c');
        mapDays.put(5, 'Vendredi__c');
        mapDays.put(6, 'Samedi__c');
         
        
    }
   
     
    public static void defineAccountDailyDisponibility(Map<Id,Account> mapNewAccounts ,Map<Id,Account> mapOldAccounts) {
        
        if(firstRun) {
            firstRun = false;        
        }
        
        Integer dayOfTheWeek = getDayOfTheWeek();
        //get the list of accounts with schedule of the current day modified or schedule of the lunch break;
        List<Account> lstAccountsToBeTreated = new List<Account>();
        
        Account oldAccount = null; 
        String strOpeningHourField;
        String strClosingHourField;
        String strStartLunchBreakField;
        String strEndLunchBreakField;
        String strReferenceDay;
        boolean bToBeTreated; 
        
        fillMaps();
		       	
        for(Account acct : mapNewAccounts.values()){ 
            bToBeTreated = false;
            oldAccount = mapOldAccounts.get(acct.Id);
            strOpeningHourField = mapOpeningHoursFields.get(dayOfTheWeek); 
            strClosingHourField = mapClosingHoursFields.get(dayOfTheWeek); 
            strStartLunchBreakField  = mapStartLunchBreakFields.get(dayOfTheWeek); 
            strEndLunchBreakField = mapEndLunchBreakFields.get(dayOfTheWeek); 
            strReferenceDay = mapDays.get(dayOfTheWeek);
            
            
            if(  acct.get(mapOpeningDays.get(dayOfTheWeek)) != oldAccount.get(mapOpeningDays.get(dayOfTheWeek)) ||
                 acct.get(strOpeningHourField) != oldAccount.get(strOpeningHourField) ||
                ( acct.get(strClosingHourField) != oldAccount.get(strClosingHourField))|| 
                (acct.get(strStartLunchBreakField) != oldAccount.get(strStartLunchBreakField)) ||
                (acct.get(strEndLunchBreakField) != oldAccount.get(strEndLunchBreakField)) ||
                (acct.Debut_pause_dejeuner__c != null && acct.Debut_pause_dejeuner__c != oldAccount.Debut_pause_dejeuner__c ) ||
                (acct.Fin_pause_dejeuner__c != null && acct.Fin_pause_dejeuner__c != oldAccount.Fin_pause_dejeuner__c  ) ||
               	acct.get(horaireOuvertureReference) != oldAccount.get(horaireOuvertureReference) ||
                acct.get(horaireFermetureReference) != oldAccount.get(horaireFermetureReference) ||
                acct.get(strReferenceDay) != OldAccount.get(strReferenceDay)
              ) {
                    lstAccountsToBeTreated.add(acct);
            }
        } 
        if(lstAccountsToBeTreated.size() > 0) {  
            defineAccountDailyDisponibility(lstAccountsToBeTreated,false);
        } 
    }
	
    public static void defineAccountDailyDisponibility(List<Account> lstAccounts , boolean fromBatch) {
	
        if(mapOpeningHoursFields.size() == 0){
            fillMaps();
        }
        
        Integer dayOfTheWeek = getDayOfTheWeek();
        System.debug('!!!gho dayOfTheWeek : ' + dayOfTheWeek);
        Integer intOpeningHour = -1;
        Integer intClosingHour = -1;
        Integer intStartLunchBreakHour = -1 ;
        Integer intEndLunchBreakHour = -1;
        Boolean bHoraireReference = false;
        for(Account acct : lstAccounts) {    
            
            bHoraireReference = Boolean.valueOf(acct.get(mapDays.get(dayOfTheWeek)));
             
            if(bHoraireReference){ 
                intOpeningHour = convertTimeToNumber((String)acct.get(horaireOuvertureReference)) ; 
            }else {
                if(acct.get(mapOpeningHoursFields.get(dayOfTheWeek)) != null) {
                    intOpeningHour = convertTimeToNumber((String) acct.get(mapOpeningHoursFields.get(dayOfTheWeek))); 
                }  
            }
                            
            if(bHoraireReference){
                intClosingHour = convertTimeToNumber((String)acct.get(horaireFermetureReference)) ; 
            }else {
                if(acct.get(mapClosingHoursFields.get(dayOfTheWeek)) != null) {
                    intClosingHour = convertTimeToNumber((String) acct.get(mapClosingHoursFields.get(dayOfTheWeek)));
                }
            }
           
            if(bHoraireReference) {
                intStartLunchBreakHour = convertTimeToNumber((String) acct.Debut_pause_dejeuner__c);
            }else {
                if(acct.get(mapStartLunchBreakFields.get(dayOfTheWeek)) != null) {
                    intStartLunchBreakHour = convertTimeToNumber((String) acct.get(mapStartLunchBreakFields.get(dayOfTheWeek)));//modified by TMAEITL FEK | convertTimeToNumber((String) acct.Debut_pause_dejeuner__c);
                }
            }
             
            
            if(bHoraireReference) {
                intEndLunchBreakHour = convertTimeToNumber((String) acct.Fin_pause_dejeuner__c);
            }else {
                if(acct.get(mapEndLunchBreakFields.get(dayOfTheWeek)) != null) {
                    intEndLunchBreakHour = convertTimeToNumber((String) acct.get(mapEndLunchBreakFields.get(dayOfTheWeek)));
                }
            }
          
              
            if(acct.get(mapOpeningDays.get(dayOfTheWeek)) == true) {
                acct.Tech_Number_Opening_Hour__c = -1;
                acct.Tech_Number_Closing_Hour__c = -1;
                acct.Tech_Number_Start_Lunch_Hour__c = -1;
                acct.Tech_Number_End_Lunch_Hour__c = -1;
            }else {
               
                acct.Tech_Number_Opening_Hour__c = intOpeningHour;
                acct.Tech_Number_Closing_Hour__c = intClosingHour; 
                acct.Tech_Number_Start_Lunch_Hour__c = intStartLunchBreakHour;
                acct.Tech_Number_End_Lunch_Hour__c = intEndLunchBreakHour;
            }
           
             
        }  
        
        if(fromBatch) {
            System.debug('AP09_Account updating account');
            Database.SaveResult[] srList = Database.update(lstAccounts,false);
            if(Label.is_Batch_Logs_Active == 'true'){
                List<Batch_Log__c> LBatchLogs = new List<Batch_Log__c>();
                //for (Database.SaveResult sr : srList) {
                for (Integer i = 0; i < lstAccounts.size(); i++) {
                    Database.SaveResult sr = srList[i];
                    Account origRecord = lstAccounts[i];
                    if (!sr.isSuccess()) {
                        for(Database.Error err : sr.getErrors()) {
                            LBatchLogs.add(new Batch_log__c(Status_Code__c = '' + err.getStatusCode(),
                                                            Message__c = err.getMessage(),
                                                            Fields__c = '' + err.getFields(),
                                                            ID__c = origRecord.Id
                                                           ));
                        }
                    }
                }
                if(LBatchLogs.size() > 0){
                    insert LBatchLogs;
                }
            }
        }
    }
    
    private static Integer convertTimeToNumber(String strTime) {
        // Convert time to number ex --> 08:30 = (08*60) + 30
        // To be Comparable
        Integer ret = -1;
		Integer intHour;
        Integer intMinutes; 
        
        if(strTime != null && strTime.indexOf(':') > -1) {
            intHour    = Integer.valueOf(strTime.substring(0,strTime.indexOf(':')));
            intMinutes = Integer.valueOf(strTime.substring(strTime.indexOf(':') + 1 ,strTime.length()));
        	ret = intHour * 60 + intMinutes;
        }                 
        return ret;
    }
    
    private static Integer getDayOfTheWeek() { 
        Integer ret = -1;
        Datetime dt = System.now();
        String currentDay  = dt.format('EEEE');
        if(currentDay.equals('Sunday')) {
            ret = 0;
        }
        else if(currentDay.equals('Monday')) {
            ret = 1;
        }
         else if(currentDay.equals('Tuesday')) {
            ret = 2;
        }
         else if(currentDay.equals('Wednesday')) {
            ret = 3;
        }
         else if(currentDay.equals('Thursday')) {
            ret = 4;
        }
         else if(currentDay.equals('Friday')) {
            ret = 5;
        }
         else if(currentDay.equals('Saturday')) {
            ret = 6 ;
        }
       
        return ret;
    }
    
}