force-app/main/default/objects/Account/fields/dimanche_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>dimanche_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_ferme__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dimanche fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/dimanche_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>dimanche_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Dimanche_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Dimanche_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimanche_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/jeudi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>jeudi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/jeudi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>jeudi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Jeudi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Jeudi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Jeudi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Lundi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lundi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>lundi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lundi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Lundi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lundi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mardi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mardi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mardi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mardi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mardi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mardi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/mercredi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>mercredi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mercredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Mercredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/samedi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>samedi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Samedi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Samedi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/samedi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>samedi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Samedi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Samedi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Samedi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vendredi_debut_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>vendredi_debut_pause_dejeuner__c</fullName>
    <label>Début pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_ferme__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_ferme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi fermé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Fermeture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Fermeture__c</fullName>
    <label>Fermeture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/vendredi_fin_pause_dejeuner__c.field-meta.xml
<CustomField>
    <fullName>vendredi_fin_pause_dejeuner__c</fullName>
    <label>Fin pause déjeuner</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendredi_Ouverture__c.field-meta.xml
<CustomField>
    <fullName>Vendredi_Ouverture__c</fullName>
    <label>Ouverture</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vendredi_ferme__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassWorkflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_HOR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:30</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>18:00</fullName>
    </customValue>
    <description>Horaires d&apos;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

src/classes/Batch02_Account_Test.cls
@isTest
public class Batch02_Account_Test {
    
    private static Map<Integer, String> mapOpeningHoursFields  = new Map<Integer, String>();
    private static Map<Integer, String> mapClosingHoursFields = new Map<Integer, String>();
    private static Map<Integer, String> mapStartLunchBreakFields = new Map<Integer, String>();
    private static Map<Integer, String> mapEndLunchBreakFields = new Map<Integer, String>();
    private static Map<Integer, String> mapOpeningDays = new Map<Integer ,String>();
    
    private static Integer getDayOfTheWeek() { 
        Integer ret = -1;
        Datetime dt = System.now();
        String currentDay  = dt.format('EEEE');
        if(currentDay.equals('Sunday')) {
            ret = 0;
        }
        else if(currentDay.equals('Monday')) {
            ret = 1;
        }
         else if(currentDay.equals('Tuesday')) {
            ret = 2;
        }
         else if(currentDay.equals('Wednesday')) {
            ret = 3;
        }
         else if(currentDay.equals('Thursday')) {
            ret = 4;
        }
         else if(currentDay.equals('Friday')) {
            ret = 5;
        }
         else if(currentDay.equals('Saturday')) {
            ret = 6 ;
        }
       
        return ret;
   }
    
    private static void fillMaps() {
         
        mapOpeningHoursFields.put(0, 'Dimanche_Ouverture__c');
        mapOpeningHoursFields.put(1, 'Lundi_Ouverture__c');
        mapOpeningHoursFields.put(2, 'Mardi_Ouverture__c');
        mapOpeningHoursFields.put(3, 'Mercredi_Ouverture__c');
        mapOpeningHoursFields.put(4, 'Jeudi_Ouverture__c');
        mapOpeningHoursFields.put(5, 'Vendredi_Ouverture__c'); 
        mapOpeningHoursFields.put(6, 'Samedi_Ouverture__c'); 
        
        mapClosingHoursFields.put(0, 'Dimanche_Fermeture__c');
        mapClosingHoursFields.put(1, 'Lundi_Fermeture__c');
        mapClosingHoursFields.put(2, 'Mardi_Fermeture__c');
        mapClosingHoursFields.put(3, 'Mercredi_Fermeture__c');
        mapClosingHoursFields.put(4, 'Jeudi_Fermeture__c');
        mapClosingHoursFields.put(5, 'Vendredi_Fermeture__c'); 
         mapClosingHoursFields.put(6, 'Samedi_Fermeture__c');
        
        mapStartLunchBreakFields.put(0, 'dimanche_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(1, 'lundi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(2, 'mardi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(3, 'mercredi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(4, 'jeudi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(5, 'vendredi_debut_pause_dejeuner__c');
        mapStartLunchBreakFields.put(6, 'samedi_debut_pause_dejeuner__c');
         
        mapEndLunchBreakFields.put(0, 'dimanche_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(1, 'lundi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(2, 'mardi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(3, 'mercredi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(4, 'jeudi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(5, 'vendredi_fin_pause_dejeuner__c');
        mapEndLunchBreakFields.put(6, 'samedi_fin_pause_dejeuner__c');
         
         
        mapOpeningDays.put(0, 'Dimanche_ferme__c'); 
        mapOpeningDays.put(1, 'Lundi_ferme__c');
        mapOpeningDays.put(2, 'Mardi_ferme__c');
        mapOpeningDays.put(3, 'Mercredi_ferme__c');
        mapOpeningDays.put(4, 'Jeudi_ferme__c');
        mapOpeningDays.put(5, 'Vendredi_ferme__c');
        mapOpeningDays.put(6, 'Samedi_ferme__c');
    }


     testmethod static void testBatch() {
         User currentUser = [Select id , name , BypassProcessBuilder__c, BypassWorkflow__c, BypassApex__c, BypassValidationRule__c
                           from User
                           where id =: UserInfo.getUserId()];
        currentUser.BypassProcessBuilder__c = true;
        currentUser.BypassWorkflow__c = true;
        currentUser.BypassValidationRule__c = true;
        update currentUser;
         
        fillMaps();
        // create contact
        Contact c = Utils_TestMethods.CreateContact('Georges Hobeika');
        insert c;
        
        // create Macroprofil
        Macroprofil__c mp = Utils_TestMethods.CreateMacroprofil('MP Test');
        insert mp;
        
        Account acct = Utils_TestMethods.CreateAccount(c, mp,'Account Test');
        
        Integer dayOfTheWeek = getDayOfTheWeek(); 
        
        acct.put(mapOpeningHoursFields.get(dayOfTheWeek),'08:00');
        acct.put(mapClosingHoursFields.get(dayOfTheWeek),'18:00'); 
         
          //TMA JSA  
        acct.put(mapStartLunchBreakFields.get(dayOfTheWeek),'10:30');
        acct.put(mapEndLunchBreakFields.get(dayOfTheWeek),'11:00');
        acct.put(mapOpeningDays.get(dayOfTheWeek),false);
        
        insert acct;
         Account insertedAccount = [SELECT Id ,DisponibiliteFormule__c 
                        		   FROM Account 
                                   WHERE id = : acct.Id
                                   ];
         
        Test.startTest();
        Id batchJobId = Database.executeBatch(new Batch02_Account(), 200);
        
        Test.stopTest();
    }    
    
}