force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Object_de_la_requete__c</fullName>
        <label>Objet de la requête</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anomalie de synchronisation d’un relais</fullName>
                    <label>Anomalie de synchronisation d&apos;un relais</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Sinistre / Travaux / Santé</fullName>
                    <label>Indisponibilité - Problème opérationnel Sinistre / Travaux / Santé</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Qualité de Service</fullName>
                    <label>Indisponibilité - Problème opérationnel Qualité de Service</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Panne PDA</fullName>
                    <label>Indisponibilité - Problème PDA / Panne PDA</label>
                </value>
                <value>
                    <fullName>Indisponibilité Problème PDA / Problème de synchronisation</fullName>
                    <label>Indisponibilité - Problème PDA / Problème de synchronisation</label>
                </value>
                <value>
                    <fullName>Indisponibilité problème opérationnel - Injoignabilité</fullName>
                </value>
                <value>
                    <fullName>Démarrage d&apos;activité</fullName>
                </value>
                <value>
                    <fullName>Relais sans formation avec moyens de scans associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif avec plusieurs moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Les relais actifs avec terme contrat non respecté</fullName>
                </value>
                <value>
                    <fullName>Les Congés du relais</fullName>
                </value>
                <value>
                    <fullName>Relais inactif avec moyens de scan associés</fullName>
                </value>
                <value>
                    <fullName>Relais actif sans moyen de scan associé</fullName>
                </value>
                <value>
                    <fullName>Les horaires insuffisants du relais</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité Problème opérationnel Anomalie colis</fullName>
                    <isActive>false</isActive>
                    <label>Indisponibilité Problème opérationnel Anomalie colis</label>
                </value>
                <value>
                    <fullName>Relais actif sans formation avec moyen de scan associé</fullName>
                    <isActive>false</isActive>
                    <label>Relais actif sans formation avec moyen de scan associé</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>DPD_BNL</fullName>
        <active>true</active>
        <businessProcess>DPD_BNL_Requêtes_Ponctuelles</businessProcess>
        <label>DPD_BNL_inactif_avec_scan_associé</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ETA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LC02_ConsignerUnAppel_Controller_Test.cls
@isTest
public class LC02_ConsignerUnAppel_Controller_Test {
    static testMethod void DemarrageActiviteAppelRelaisRepond() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt
                                                                         Where MasterLabel ='Belgium'
                                                                         Limit 1];
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        account1.recordTypeID = associationRTPays[0].ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.RT_BNL_Requete_Injoignabilite;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        LC02_ConsignerUnAppel_Controller.getCaseStatus(demarrageCase.id);
        
        //le relais repond
        LC02_ConsignerUnAppel_Controller.consignerUnappelController(Label.DA_OuiRelaisRepond, demarrageCase.id);
    }
    static testMethod void DemarrageActiviteAppelRelaisRepondPas() {
  List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt
                                                                         Where MasterLabel ='Belgium'
                                                                         Limit 1];
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        account1.recordTypeID = associationRTPays[0].ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.RT_BNL_Requete_Injoignabilite;
        demarrageCase.AccountId =account1.id;
        //demarrageCase.Object_de_la_requete__c ='currentRequest.Object_de_la_requete__c';
        insert demarrageCase;
        LC02_ConsignerUnAppel_Controller.consignerUnappelController(Label.DA_NonRelaisRepond, demarrageCase.id);
    }
    static testMethod void DemarrageActiviteAppelRelaisNull() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt
                                                                         Where MasterLabel ='Belgium'
                                                                         Limit 1];
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        account1.recordTypeID = associationRTPays[0].ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.RT_BNL_Requete_Injoignabilite;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        LC02_ConsignerUnAppel_Controller.consignerUnappelController(null, demarrageCase.id);
    }
    static testMethod void TraitementInterrompuDateRappel() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt
                                                                         Where MasterLabel ='Belgium'
                                                                         Limit 1];
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        account1.recordTypeID = associationRTPays[0].ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.RT_BNL_Requete_Injoignabilite;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        LC02_ConsignerUnAppel_Controller.consignerUnappelController(Label.DA_InterrompuLbl, demarrageCase.id);
    }
    
}