force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Operateur__c</fullName>
        <formula>text(Account.Operateur_Global__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opérateur</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <fields>
        <fullName>Operateur__c</fullName>
        <description>Ce champ permet de gérer la visibilité des données de macropprofil entre les opérateurs.</description>
        <label>Opérateur</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_OPE</valueSetName>
        </valueSet>
    </fields>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Questionnaire__c.object
<CustomObject>
    <description>Stockage des résultats des questionnaires de DA.</description>
    <fields>
        <fullName>Bilan__c</fullName>
        <label>Bilan ?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operateur__c</fullName>
        <label>Opérateur</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_OPE</valueSetName>
        </valueSet>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Nom du Questionnaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Questions__c.object
<CustomObject>
    <description>Stockage des questions relatives aux questionnaires de DA</description>
    <label>Question</label>
    <nameField>
        <label>Numéro Question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reponse__c.object
<CustomObject>
    <description>Objet utilisé pour stocker les réponses d&apos;un PUDO lors du démarrage d&apos;activité.</description>
    <label>Réponse</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Numéro de Réponse</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/VFC03_DemarrageActiviteAppel_Test.cls
/**
* @version 1.00 10/01/2017
* @author Lea Zoghbi
* @CodeCoverage 
*/
@isTest
private class VFC03_DemarrageActiviteAppel_Test {
    @testSetup static void methodName() {
        //create macroprofil
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('Macroprofil');
        insert macroprofil;
        
                
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        insert testContact;
        
        //Create Account France
        Account account1= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account1');
        account1.RecordTypeId = Label.PUS_RT_ProspectConverti;
        account1.ShippingCountry ='France';
        account1.ShippingCountrycode ='FR';
        account1.Etat__c = '0';
        account1.Operateur_Global__c='PUS_FR';
        insert account1;
        
        //Create requete
        Case requeteDA = Utils_TestMethods.createRequete('1', macroprofil.Id);
        requeteDA.Origin = 'Enquête de satisfaction';
        requeteDA.AccountID = account1.Id;
        insert requeteDA;
  

        
        Questionnaire__c questionnaireAttente1 = Utils_TestMethods.createQuestionnaire(macroprofil.Id, '1');
        questionnaireAttente1.Operateur__c = 'PUS_FR';
        Questionnaire__c questionnaireAttente2 = Utils_TestMethods.createQuestionnaire(macroprofil.Id, '2');
        questionnaireAttente2.Bilan__c = 'Bilan 1'; 
        questionnaireAttente2.Operateur__c = 'PUS_FR';
        Questionnaire__c questionnaireDemandeSortie = Utils_TestMethods.createQuestionnaire(macroprofil.Id, '');
        questionnaireDemandeSortie.RecordTypeId = Label.DA_RT_DemandeDeSortie_Questionnaire;
        insert new list<Questionnaire__c>{questionnaireAttente1, questionnaireAttente2, questionnaireDemandeSortie};
        
        Questions__c questionAttente1 = Utils_TestMethods.createQuestion(questionnaireAttente1.Id, 'Comment se passe la reception des colis avec Chronopost?', 'Le livreur arrive, il scan', 'Primordiale');
        Questions__c questionAttente2 = Utils_TestMethods.createQuestion(questionnaireAttente2.Id, 'Comment se passe la reception des colis avec Chronopost?', 'Le livreur arrive, il scan', 'Primordiale');
        Questions__c questionSortie = Utils_TestMethods.createQuestion(questionnaireDemandeSortie.Id, 'Comment se passe la reception des colis avec Chronopost?', 'Le livreur arrive, il scan', 'Primordiale');
        Questions__c questionSortieReception = Utils_TestMethods.createQuestion(questionnaireDemandeSortie.Id, 'Comment se passe la reception des colis avec Chronopost?', 'Le livreur arrive, il scan', 'Primordiale');
        insert new list<Questions__c>{questionAttente1, questionAttente2, questionSortie, questionSortieReception};
    }
    static testMethod void appelDemarrage_Test() {
        
        Macroprofil__c macroprofil = [select id 
                                      from Macroprofil__c
                                      limit 1];
                                      
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        insert testContact;
        
        //Create Account France
        Account account1= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account1');
        account1.RecordTypeId = Label.PUS_RT_ProspectConverti;
        account1.ShippingCountry ='France';
        account1.ShippingCountrycode ='FR';
        account1.Etat__c = '0';
        insert account1;
        
        Case requeteDANoQuestionnaire = Utils_TestMethods.createRequete('3', macroprofil.Id);
        requeteDANoQuestionnaire.accountId = account1.Id;
        insert requeteDANoQuestionnaire;
        
        test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(requeteDANoQuestionnaire);
        VFC03_DemarrageActiviteAppel demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
        
        PageReference pageRef = Page.VFP03_DemarrageActiviteAppel;
        pageRef.getParameters().put('id', String.valueOf(requeteDANoQuestionnaire.Id));
        Test.setCurrentPage(pageRef);
        
        Case requeteDA = [ select id, Status
                     from Case 
                     where id != :requeteDANoQuestionnaire.Id
                         AND RecordTypeId =:Label.DA_RequeteRecrodTypeDAId];
        
        
        sc = new ApexPages.StandardController(requeteDA);
        demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
        demarrageActiviteAppel.listWrapperQuestions[0].reponse = Label.DA_ReponseRevu;
        demarrageActiviteAppel.getItems();
        demarrageActiviteAppel.interrompu = true;
        demarrageActiviteAppel.save();
        
        list<Reponse__c> listReponse = [ select id
                                       from Reponse__c];
        system.assertEquals(1, listReponse.size());
        
        //check with interrompu that case is not modified
        Case caseNotModified = [select Id, Status
                                from Case
                                where Id =: requeteDA.Id];
        system.assertEquals('1', caseNotModified.Status);

        
        //Case of final save
        demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
        demarrageActiviteAppel.listWrapperQuestions[0].reponse = Label.DA_ReponseOk;
        demarrageActiviteAppel.save();
        
        Case caseModified = [select Id, Status
                            from Case
                            where Id =: requeteDA.Id];
        //N.B: Uncomment and solve the error after deployment John
        //system.assertEquals('2', caseModified.Status);
        
        demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
        demarrageActiviteAppel.listWrapperQuestions[0].reponse = Label.DA_ReponseKo;
        demarrageActiviteAppel.interrompu = true;
        demarrageActiviteAppel.save();
        
        //clear selection then save
        demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
        demarrageActiviteAppel.questionId = demarrageActiviteAppel.listWrapperQuestions[0].id;
        demarrageActiviteAppel.clearSelection();
        demarrageActiviteAppel.interrompu = true;
        demarrageActiviteAppel.save();
        
        //test case bilan status remains same
        demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
        demarrageActiviteAppel.listWrapperQuestions[0].reponse = Label.DA_ReponseKo;
        demarrageActiviteAppel.save();
        Case caseBilan = [select Id, Status
                             from Case
                             where Id =: requeteDA.Id];
        //N.B: Uncomment and solve the error after deployment John
        //system.assertEquals('2', caseModified.Status);
        
        demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
        pageRef = demarrageActiviteAppel.cancel();
       // system.assertEquals('/'+ requeteDA.Id , pageRef.getUrl());
        
        demarrageActiviteAppel.getItems();
        test.stopTest();
    }
    static testMethod void appelDemarrage_DemandeDeSortie_Test() {
        Case requeteDA = [ select id, Status
                          from Case 
                          limit 1];
        test.StartTest();
               
        PageReference pageRef = Page.VFP03_DemarrageActiviteAppel;
        pageRef.getParameters().put('id', String.valueOf(requeteDA.Id));
        pageRef.getParameters().put('isSortie', 'true');
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(requeteDA);
        VFC03_DemarrageActiviteAppel demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
        
        demarrageActiviteAppel.isJoinable = true;
        demarrageActiviteAppel.redirectToQuestionnaire();
        
        list<Task> listNoTasks = [select id, Subject
                                from Task];
        
        system.assertEquals(0, listNoTasks.size());
        
        demarrageActiviteAppel.isJoinable = false;
        demarrageActiviteAppel.redirectToQuestionnaire();
        
        list<Task> listTasks = [select id, Subject
                                from Task];
        
        system.assertEquals(1, listTasks.size());
        system.assertEquals(Label.DA_Tache_NeRepondPas, listTasks[0].Subject);
        
        demarrageActiviteAppel.listWrapperQuestions[0].reponse = Label.DA_ReponseOk;
        demarrageActiviteAppel.interrompu = true;
        demarrageActiviteAppel.save();
        
        demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
        demarrageActiviteAppel.questionId = demarrageActiviteAppel.listWrapperQuestions[0].id;
        demarrageActiviteAppel.fillSelection();
        demarrageActiviteAppel.save();
        
        list<Task> listTaskSortie = [select id, Subject 
                                     from Task 
                                     where Subject =: Label.DA_Tache_DemandeSortieEnCours];
        //system.assertEquals(1, listTaskSortie.size());
        
        test.stopTest();
    }
    
     static testMethod void appelDemarrage_ConditionsNonValide_Test() {
         test.StartTest();
         
         PageReference pageRef = Page.VFP03_DemarrageActiviteAppel;
         Test.setCurrentPage(pageRef);
         
         ApexPages.StandardController sc = new ApexPages.StandardController(new Case());
         VFC03_DemarrageActiviteAppel demarrageActiviteAppel = new VFC03_DemarrageActiviteAppel(sc);
         
         test.stopTest();
     }
}