force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/N_TVA__c.field-meta.xml
<CustomField>
    <fullName>N_TVA__c</fullName>
    <label>N° de TVA</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Requete_Conge__c</fullName>
        <label>ID_Requête_Congé</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Requete_ContratNonRespecte__c</fullName>
        <label>ID_Requete_ContratNonRespecte</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>DPD_BNL</fullName>
        <active>true</active>
        <businessProcess>DPD_BNL_Requêtes_Ponctuelles</businessProcess>
        <label>DPD_BNL_inactif_avec_scan_associé</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <recordTypes>
        <fullName>Conge</fullName>
        <active>true</active>
        <description>Permet de créer une période de congés.</description>
        <label>Congé</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ETA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Batch12_AccountCase_Test.cls
@isTest
public class Batch12_AccountCase_Test {
    
    static testmethod void testBatch() {
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('M1');
        insert macroprofil;
        
        List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c,ID_Requete_ContratNonRespecte__c,ID_Requete_Conge__c
                                                                                  FROM Association_Record_Type_et_pays__mdt];
            
            
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
          associationRTPays.put(associationRT.MasterLabel, associationRT);}
        
        //Account qui verifie les condition
        List<Account> Accounts = new List<Account>();
        Account account1 = Utils_TestMethods.CreateAccount(null, macroprofil, 'Account 1');
        account1.Etat__c = '4';
        account1.Type  = '2';
        account1.RecordTypeId = associationRTPays.get('Belgium').ID_suivi_CO__c;
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.BillingPostalCode ='1234';
        account1.ShippingPostalCode = '1243';        
        Accounts.add(account1);
        
        //Account avec conge
        Account account2= Utils_TestMethods.CreateAccount(null, null, 'Test Account');
        account2.RecordTypeId = associationRTPays.get('France').ID_PUDO_Non_Suivi__c;
        account2.ShippingCountry ='France';
        account2.ShippingCountryCode='FR';
        account2.Etat__c = '5';
        account2.Operateur_Global__c = 'PUS_FR';
        account2.ShippingPostalCode = '12345';
        account2.Type ='2';
        account2.N_TVA__c = 'Non';
        Accounts.add(account2);          
       
        //Account avec requete deja creer
        Account account4 = Utils_TestMethods.CreateAccount(null, macroprofil, 'Account 4');
        account4.Etat__c = '4';
        account4.Type  = '2';
        account4.RecordTypeId = associationRTPays.get('Belgium').ID_suivi_CO__c;
        account4.BillingCountry ='Belgium';
        account4.ShippingCountry ='Belgium';
        account4.BillingCountryCode = 'BE';
        account4.ShippingCountryCode ='BE';
        account4.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account4.Operateur_Global__c = 'DPD_BNL';
        account4.BillingPostalCode ='1234';
        account4.ShippingPostalCode = '1243';   
        Accounts.add(account4);
        insert Accounts;
        Integer thisYear = Date.today().year();
        Integer thisDay = Date.today().day();
        Integer thisMonth = Date.today().month();

        Conge_Indispo__c cong = Utils_TestMethods.CreateConge_Indispo(Label.RT_Conge_Indispo_Conge, 
                                                                      account2.id, 
                                                                      Date.newInstance(thisYear, thisMonth ,thisDay ), 
                                                                      Date.newInstance(thisYear, thisMonth ,thisDay ));
        insert cong;
        
        Case CaseAccount4 = new Case();
        CaseAccount4.Status = Label.ReQuette_En_attente_de_traitement;
        CaseAccount4.RecordTypeId = associationRTPays.get('Belgium').ID_Requete_Conge__c;
        CaseAccount4.AccountId  =  account4.id; 
        insert CaseAccount4; 
        
        Test.startTest();
        Batch12_AccountCase batchAccountRequette = new Batch12_AccountCase();
        Database.executeBatch(batchAccountRequette);
        Test.stopTest();
        
        
        /*List<Case> cases = [SELECT id, RecordTypeId
                            FROM Case 
                           where AccountId =: account1.Id and RecordTypeId =:associationRTPays.get('Belgium').ID_Requete_Conge__c
                           ];
        System.assertEquals( 1 , cases.size());
        System.assertEquals( associationRTPays.get('Belgium').ID_Requete_Conge__c , cases[0].RecordTypeId );*/
        
        List<account> listAccount = [select id,name,etat__c from account where id=:account2.Id];
        List<Case> cases1 = [SELECT id, RecordTypeId
                              FROM Case 
                             Where AccountId =: account2.Id and RecordTypeId =:associationRTPays.get('France').ID_Requete_Conge__c
                           ];      
        System.assertEquals( 1 , cases1.size() );
        /*List<Case> cases2 = [SELECT id, RecordTypeId
                              FROM Case 
                             Where AccountId =: account4.Id and RecordTypeId =:associationRTPays.get('Belgium').ID_Requete_Conge__c
                           ];   
        System.assertEquals( 1 , cases2.size() );*/
    }
}