force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <label>Partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_PAR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contact_operationnel__c</fullName>
        <formula>Account.Contact_operationnel_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact opérationnel</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>DPD_BNL</fullName>
        <active>true</active>
        <businessProcess>DPD_BNL_Requêtes_Ponctuelles</businessProcess>
        <label>DPD_BNL_inactif_avec_scan_associé</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_operationnel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact opérationnel</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Historique_des_Comptes_Rendus__c.object
<CustomObject>
    <label>Historique des Comptes-Rendus</label>
    <nameField>
        <label>Historique des comptes rendu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historiques des Comptes-Rendus</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_PAR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <customValue>
        <fullName>124</fullName>
    </customValue>
    <customValue>
        <fullName>125</fullName>
    </customValue>
    <customValue>
        <fullName>126</fullName>
    </customValue>
    <customValue>
        <fullName>134</fullName>
    </customValue>
    <customValue>
        <fullName>135</fullName>
    </customValue>
    <customValue>
        <fullName>140</fullName>
    </customValue>
    <customValue>
        <fullName>146</fullName>
    </customValue>
    <customValue>
        <fullName>177</fullName>
    </customValue>
    <customValue>
        <fullName>178</fullName>
    </customValue>
    <customValue>
        <fullName>179</fullName>
    </customValue>
    <customValue>
        <fullName>180</fullName>
    </customValue>
    <customValue>
        <fullName>181</fullName>
    </customValue>
    <customValue>
        <fullName>182</fullName>
    </customValue>
    <customValue>
        <fullName>183</fullName>
    </customValue>
    <customValue>
        <fullName>184</fullName>
    </customValue>
    <customValue>
        <fullName>185</fullName>
    </customValue>
    <customValue>
        <fullName>188</fullName>
    </customValue>
    <customValue>
        <fullName>189</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>190</fullName>
    </customValue>
    <customValue>
        <fullName>194</fullName>
    </customValue>
    <customValue>
        <fullName>195</fullName>
    </customValue>
    <customValue>
        <fullName>-2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>211</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <description>Liste des partenaires</description>
    <masterLabel>LOV_GLO_PAR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/VFC09_DemarrageActiviteAppel_TEST.cls
@isTest
public class VFC09_DemarrageActiviteAppel_TEST {
    
    static testMethod void DemarrageActiviteAppelRelaisRepond() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt];
        Map<String, Association_Record_Type_et_pays__mdt> mapOfInfoRTCongeIndispo = new Map<String, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord : associationRTPays)
        {
            mapOfInfoRTCongeIndispo.put(mdtRecord.MasterLabel, mdtRecord);
        } 
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        //account1.recordTypeID = associationRTPays[0].ID_suivi_CO__c;
        account1.recordTypeID = mapOfInfoRTCongeIndispo.get('Belgium').ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete('1', macroProf.id);//label.DA_EnAttenteAppel1Statut1
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
                VFC09_DemarrageActiviteAppel.getCaseStatus(demarrageCase.id);

      //le relais repond
        VFC09_DemarrageActiviteAppel.goToNextPage2(Label.DA_OuiRelaisRepond, demarrageCase.Status, demarrageCase.id);
    }
    static testMethod void DemarrageActiviteAppelRelaisRepondPas() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt];
        Map<String, Association_Record_Type_et_pays__mdt> mapOfInfoRTCongeIndispo = new Map<String, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord : associationRTPays)
        {
            mapOfInfoRTCongeIndispo.put(mdtRecord.MasterLabel, mdtRecord);
        }
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        account1.recordTypeID = mapOfInfoRTCongeIndispo.get('Belgium').ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        VFC09_DemarrageActiviteAppel.goToNextPage2(Label.DA_NonRelaisRepond, demarrageCase.Status, demarrageCase.id);
    }
    static testMethod void DemarrageActiviteAppelRelaisNull() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt];
        Map<String, Association_Record_Type_et_pays__mdt> mapOfInfoRTCongeIndispo = new Map<String, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord : associationRTPays)
        {
            mapOfInfoRTCongeIndispo.put(mdtRecord.MasterLabel, mdtRecord);
        }
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        account1.recordTypeID = mapOfInfoRTCongeIndispo.get('Belgium').ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        VFC09_DemarrageActiviteAppel.goToNextPage2(null, demarrageCase.Status, demarrageCase.id);
    }
    static testMethod void DemarrageActiviteAppelRelais() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt];
        Map<String, Association_Record_Type_et_pays__mdt> mapOfInfoRTCongeIndispo = new Map<String, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord : associationRTPays)
        {
            mapOfInfoRTCongeIndispo.put(mdtRecord.MasterLabel, mdtRecord);
        }
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        account1.recordTypeID = mapOfInfoRTCongeIndispo.get('Belgium').ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        VFC09_DemarrageActiviteAppel.goToNextPage2(null, demarrageCase.Status, null);
    }
    static testMethod void TraitementInterrompuDateRappel() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt];
        Map<String, Association_Record_Type_et_pays__mdt> mapOfInfoRTCongeIndispo = new Map<String, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord : associationRTPays)
        {
            mapOfInfoRTCongeIndispo.put(mdtRecord.MasterLabel, mdtRecord);
        }
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        testContact1.Contact_operationnel__c = true;
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        account1.recordTypeID = mapOfInfoRTCongeIndispo.get('Belgium').ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        Date dateRap = date.newinstance(system.now().year(),system.now().month(),system.now().day());
        String resultatappel = '3';
        Historique_des_Comptes_Rendus__c createHistorRecord = Utils_TestMethods.historiquePassageAppelSuivant(resultatappel,demarrageCase, dateRap, true);
        insert createHistorRecord;

        VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '3', demarrageCase.Status, demarrageCase.id,testContact1.id, 'Success');
    }
    static testMethod void TraitementInterrompuDateRappelVide() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt];
        Map<String, Association_Record_Type_et_pays__mdt> mapOfInfoRTCongeIndispo = new Map<String, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord : associationRTPays)
        {
            mapOfInfoRTCongeIndispo.put(mdtRecord.MasterLabel, mdtRecord);
        }
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        account1.recordTypeID = mapOfInfoRTCongeIndispo.get('Belgium').ID_suivi_CO__c;
        account1.Etat__c = '0';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        String resultatappel = '3';
        Historique_des_Comptes_Rendus__c createHistorRecord = Utils_TestMethods.historiquePassageAppelSuivant(resultatappel,demarrageCase, null, true);
        insert createHistorRecord;
        VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '3', demarrageCase.Status, demarrageCase.id, testContact1.id, 'Success');
    }
    static testMethod void TraitementNonInterrompuAppelN() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt];
        Map<String, Association_Record_Type_et_pays__mdt> mapOfInfoRTCongeIndispo = new Map<String, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord : associationRTPays)
        {
            mapOfInfoRTCongeIndispo.put(mdtRecord.MasterLabel, mdtRecord);
        }
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(null, null, 'Test Account');
        account1.recordTypeID = mapOfInfoRTCongeIndispo.get('Belgium').ID_suivi_CO__c;
        account1.Etat__c = '4';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        account1.Partenaire__c = '120';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        //En attent appel 1
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        String resultatappel = '3';
        Historique_des_Comptes_Rendus__c createHistorRecord = Utils_TestMethods.historiquePassageAppelSuivant(resultatappel, demarrageCase, null, false);
        insert createHistorRecord;
        VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '3', demarrageCase.Status, demarrageCase.id, testContact1.id, 'Success');
        //En attent appel 2
        demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel2Statut2, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        createHistorRecord = Utils_TestMethods.historiquePassageAppelSuivant(resultatappel,demarrageCase, null, false);
        insert createHistorRecord;
        VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '3', demarrageCase.Status, demarrageCase.id, testContact1.id, 'Success');
        //En attent appel 3
        demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel3Statut3, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        createHistorRecord = Utils_TestMethods.historiquePassageAppelSuivant(resultatappel,demarrageCase, null, false);
        insert createHistorRecord;
        VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '3', demarrageCase.Status, demarrageCase.id, testContact1.id, 'Success');
        //VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '4', demarrageCase.Status, demarrageCase.id);
    }
    static testMethod void TraitementNonInterrompuAppelNSelectedRadioBoxValue4() {
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id , MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c
                                                                         FROM Association_Record_Type_et_pays__mdt];
        Map<String, Association_Record_Type_et_pays__mdt> mapOfInfoRTCongeIndispo = new Map<String, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt mdtRecord : associationRTPays)
        {
            mapOfInfoRTCongeIndispo.put(mdtRecord.MasterLabel, mdtRecord);
        }
        //Create Contact
        Contact testContact1 = Utils_TestMethods.CreateContact('c2');
        Insert testContact1;
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(null, null, 'Test Account');
        account1.recordTypeID = mapOfInfoRTCongeIndispo.get('Belgium').ID_suivi_CO__c;
        account1.Etat__c = '4';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.ShippingPostalCode ='1234';
        account1.BillingPostalCode ='1234';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.type = '3';
        account1.Partenaire__c = '120';
        insert account1;
        Macroprofil__c macroProf = Utils_TestMethods.CreateMacroprofil('test');
        insert macroProf;
        //En attent appel 1
        Case demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel1Statut1, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        String resultatappel = '3';
        Historique_des_Comptes_Rendus__c createHistorRecord = Utils_TestMethods.historiquePassageAppelSuivant(resultatappel, demarrageCase, null, false);
        insert createHistorRecord;
        VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '3', demarrageCase.Status, demarrageCase.id, testContact1.id, 'Success');
        //En attent appel 2
        demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel2Statut2, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        createHistorRecord = Utils_TestMethods.historiquePassageAppelSuivant(resultatappel,demarrageCase, null, false);
        insert createHistorRecord;
        VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '3', demarrageCase.Status, demarrageCase.id, testContact1.id, 'Success');
        //En attent appel 3
        demarrageCase = Utils_TestMethods.createRequete(label.DA_EnAttenteAppel3Statut3, macroProf.id);
        demarrageCase.RecordTypeId = Label.DA_RequeteRecrodTypeDAId_BNL;
        demarrageCase.AccountId =account1.id;
        insert demarrageCase;
        createHistorRecord = Utils_TestMethods.historiquePassageAppelSuivant(resultatappel,demarrageCase, null, false);
        insert createHistorRecord;
        //VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '3', demarrageCase.Status, demarrageCase.id);
        VFC09_DemarrageActiviteAppel.insertCompteRendu(createHistorRecord, '4', demarrageCase.Status, demarrageCase.id, testContact1.id, 'Success');
    }
    
    
}