force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

src/objects/Anomalie__c.object
<CustomObject>
    <description>Objet technique permettant de stocker les anomalies associées au PUDO, en particulier les anomalies provenant de la télécollecte.</description>
    <fields>
        <fullName>PUDO__c</fullName>
        <label>PUDO</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Anomalies_de_Telecollecte</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SyncPudo</fullName>
                </value>
                <value>
                    <fullName>NoDevice</fullName>
                </value>
                <value>
                    <fullName>TooManyDevices</fullName>
                </value>
                <value>
                    <fullName>NoDecommissioned</fullName>
                </value>
                <value>
                    <fullName>Association à tort Etat 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Anomalie</label>
    <nameField>
        <label>Numéro de l&apos;anomalie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOV_GLO_ETA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP04_Anomalie.cls
/*
* The aim of this class is to close anomalie if the account state is changed
* @author: Christine Bayssary
* @date: 13/08/2018
* @Test: AP04_Anomalie_Test
*/
public class AP04_Anomalie {
    /*--------------------------------------------------------------------------------------------------------------------------
     Author: Christine Bayssary
     Company: EI-technologies
     Description: Close of the anomalie if the account state is changed
     Inputs: list of new accounts , map of old value
     Returns: -
    --------------------------------------------------------------------------------------------------------------------------*/
    
    public static void clotureAnomalie (list<account> listAccount, map<id, account> mapOldAccount){
        list<id> listAccountIds = new list<Id>();
        
        for(account acc: listAccount){
            if(acc.etat__c != mapOldAccount.get(acc.id).etat__c && mapOldAccount.get(acc.id).etat__c == '2'){
                listAccountIds.add(acc.id);                
            }            
        }
        system.debug('AP04_Anomalie listAccountIds ' + listAccountIds);
        list<Anomalie__c> listAnomalie = [select id,type__c,statut__c
                                          from anomalie__c 
                                          where pudo__c in :listAccountIds
                                          and statut__c ='1'
                                          and type__c ='Association à tort Etat 2'];
        system.debug('AP04_Anomalie Queried listAnomalie ' + listAnomalie);
        for(anomalie__c anom : listAnomalie){
            anom.statut__c ='0';
        }
        system.debug('AP04_Anomalie New listAnomalie ' + listAnomalie);
        update listAnomalie;
    }
}