force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Macroprofil_Service__c.object
<CustomObject>
    <description>Services ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclu__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclu</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interdit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interdit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Services par défaut</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Macroprofil liés à ce service</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Techatraiter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Techatraiter</label>
        <type>Checkbox</type>
    </fields>
    <label>Service par défaut</label>
    <nameField>
        <displayFormat>SPD-{0000}</displayFormat>
        <label>Numéro du Service par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>Un ensemble de prestations standards proposés aux destinataires par un relais.</description>
    <label>Service</label>
    <nameField>
        <label>Nom du Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Associe__c.object
<CustomObject>
    <description>Ensemble de services proposés par le Pudo selon le macro-profil affecté. Des services seront pilotables par l’action d’activation ou de désactivation.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Compte__c</fullName>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services associés</relationshipLabel>
        <relationshipName>Services_associes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exclu__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclu</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interdit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Interdit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <formula>Compte__r.Macroprofil_actuel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Macroprofil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Points relais pouvant activer le service</relationshipLabel>
        <relationshipName>Services_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tech_bypassNonModifiableCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <label>tech_bypassNonModifiableCheck</label>
        <type>Checkbox</type>
    </fields>
    <label>Service associé</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Numéro du Service associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/classes/Batch04_MP_Service.cls
global class Batch04_MP_Service implements Database.Batchable<sObject> {

    global Batch04_MP_Service() {}     
	
    global Database.QueryLocator start(Database.BatchableContext BC) {
		//Get the involved records
		List<Macroprofil_Service__c> newlist = [select Macroprofil__c, Service__c 
												from Macroprofil_Service__c 
												where Techatraiter__c = true];
		
	   //Set of Macroprofils
		Set<Id> setMacroprofils = new Set<Id>();
		//Set of Services
		Set<Id> setServices = new Set<Id>();
	   
		for(Macroprofil_Service__c neww : newlist)
		{
			setMacroprofils.add(neww.Macroprofil__c);
			setServices.add(neww.Service__c);
		}
		
        //get list of accounts concerned 
        String query =  'Select Id, Compte__c,Compte__r.Etat__c, Compte__r.Macroprofil_actuel__c ,Service__c, Active__c, Modifiable__c, tech_bypassNonModifiableCheck__c  ' +
                         'from Service_Associe__c where Compte__r.Macroprofil_actuel__c =: setMacroprofils And Service__c =: setServices' ;
                         
        return Database.getQueryLocator(query);    
    }
    
    global void execute(Database.BatchableContext BC , List<Service_Associe__c> scope) {
       
		List<Macroprofil_Service__c> newlist = [select Macroprofil__c, Service__c, Active__c, Modifiable__c, Interdit__c, Exclu__c
												from Macroprofil_Service__c 
												where Techatraiter__c = true];
		//Set of Macroprofils
		Set<Id> setMacroprofils = new Set<Id>();
		//Set of Services
		Set<Id> setServices = new Set<Id>();
		//Indexing
		map<String,Macroprofil_Service__c> mapIdMTMT = new map<String,Macroprofil_Service__c>();
		
		for(Macroprofil_Service__c neww : newlist)
		{
			setMacroprofils.add(neww.Macroprofil__c);
			setServices.add(neww.Service__c);
			mapIdMTMT.put(''+ neww.Macroprofil__c + neww.Service__c,neww);
		}
		
		
 	    Set<Id> accountIds = new Set<Id>();
		for(Service_Associe__c ta : scope)
		{			
			accountIds.add(ta.Compte__c);
			Macroprofil_Service__c mt = mapIdMTMT.get(''+ta.Compte__r.Macroprofil_actuel__c + ta.Service__c);
			if(mt!= null){
				ta.Active__c = mt.Active__c; 
				ta.Modifiable__c = mt.Modifiable__c;
				ta.Interdit__c = mt.Interdit__c;
				ta.Exclu__c = mt.Exclu__c;
				ta.tech_bypassNonModifiableCheck__c = !ta.tech_bypassNonModifiableCheck__c;
			}
		}
		
		update scope;
    }
    
    global void finish(Database.BatchableContext BC){
		system.debug('Batch04_MP_Service finish: ');
		Batch05_MP_Transporteur batch = new Batch05_MP_Transporteur();
        Database.executeBatch(batch, 200); 
    }

    
}