force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Fermeture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Fermeture_Reference__c</fullName>
    <label>Horaire de fermeture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Ouverture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Ouverture_Reference__c</fullName>
    <label>Horaire d&#39;ouverture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Macroprofil de création.</inlineHelpText>
    <label>Macroprofil de référence</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>equals</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard, 23</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes (Macroprofil de référence)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <label>Partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_PAR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Poids_maximal_accepte_par_colis__c.field-meta.xml
<CustomField>
    <fullName>Poids_maximal_accepte_par_colis__c</fullName>
    <label>Poids maximal accepté par colis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_POI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOV_GLO_ETA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&#39;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_HOR.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <description>Horaires d&#39;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_PAR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <customValue>
        <fullName>124</fullName>
    </customValue>
    <customValue>
        <fullName>125</fullName>
    </customValue>
    <customValue>
        <fullName>126</fullName>
    </customValue>
    <customValue>
        <fullName>134</fullName>
    </customValue>
    <customValue>
        <fullName>135</fullName>
    </customValue>
    <customValue>
        <fullName>140</fullName>
    </customValue>
    <customValue>
        <fullName>146</fullName>
    </customValue>
    <customValue>
        <fullName>177</fullName>
    </customValue>
    <customValue>
        <fullName>178</fullName>
    </customValue>
    <customValue>
        <fullName>179</fullName>
    </customValue>
    <customValue>
        <fullName>180</fullName>
    </customValue>
    <customValue>
        <fullName>181</fullName>
    </customValue>
    <customValue>
        <fullName>182</fullName>
    </customValue>
    <customValue>
        <fullName>183</fullName>
    </customValue>
    <customValue>
        <fullName>184</fullName>
    </customValue>
    <customValue>
        <fullName>185</fullName>
    </customValue>
    <customValue>
        <fullName>188</fullName>
    </customValue>
    <customValue>
        <fullName>189</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>190</fullName>
    </customValue>
    <customValue>
        <fullName>194</fullName>
    </customValue>
    <customValue>
        <fullName>195</fullName>
    </customValue>
    <customValue>
        <fullName>-2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>211</fullName>
    </customValue>
    <description>Liste des partenaires</description>
    <masterLabel>LOV_GLO_PAR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_POI.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <description>Poids maximal accepté par colis.</description>
    <masterLabel>LOV_GLO_POI</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP02_ReseauAssocie.cls
public class AP02_ReseauAssocie {
    
    public static void checkAssociations(Set<Id> setAccountIds)
    {
        //Check if the number of transporteur_associe is equal to 1, i.e. it's coming from the GUI so no need to call the batch 
        //else if the number is bigger than 1 than we need to call the trigger in order not to hit the limits.
        if(!System.isBatch()){
            list<Account> listAccounts = [select Id, Macroprofil_de_reference__c,Macroprofil_actuel__c, Type, Industry, Partenaire__c, Etat__c, RecordTypeId, 
                                          Horaire_Ouverture_Reference__c, Horaire_Fermeture_Reference__c, Poids_maximal_accepte_par_colis__c
                                          from Account where Id in : setAccountIds];
            System.debug('###gho listAccounts : ' + listAccounts);
            set<Id> setMacroprofilIds = new set<Id>();
            for(Account acc : listAccounts){
                setMacroprofilIds.add(acc.Macroprofil_actuel__c);
            }
            System.debug('###gho setMacroprofilIds : ' + setMacroprofilIds );
            AP04_Account ap04Acc = new AP04_Account();
            ap04Acc.UpdateReseauAssociations(listAccounts, setMacroprofilIds);
        }else{      
            //If size>1 the batch lunched from AP02_MacroprofilTransporteur or AP03_MacroptofilService should handle it
          
        }
    }
}