force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Requete_ContratNonRespecte__c</fullName>
        <label>ID_Requete_ContratNonRespecte</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CountriesSequence__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CountriesSequence</label>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/classes/AP05_Account_TEST.cls
@isTest
public class AP05_Account_TEST {
    
    private static Id PUS_FR_Prospect_Converti = Label.PUS_RT_ProspectConverti;     
    private static Id PUS_FR_Point_non_Suivi_par_le_CO = Label.PUS_RT_NonSuiviParCO;
    private static Id PUS_FR_Consigne = Label.PUS_RT_Consigne;
    
    static testmethod void testAccountInternationReferenceNumber() {
        //Create Contact
        Contact c = Utils_TestMethods.CreateContact('c1');
        insert c;
        
        //Create Macroprofil
        Macroprofil__c m1 = Utils_TestMethods.CreateMacroprofil('m1');
        insert m1;
        
        //Create Custom Settings
        CountriesSequence__c cs = new CountriesSequence__c(Name='France' , Sequence__c = 'FR00001');
        insert cs;
        
        List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c,ID_Requete_ContratNonRespecte__c
                                                                              FROM Association_Record_Type_et_pays__mdt];
            
            
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
           associationRTPays.put(associationRT.MasterLabel, associationRT);  
        }
        
        //Create List of Accounts
        // 2  Non Suivi par le CO and 1 Consigne
        List<Account>listAccountsToBeInserted = new List<Account>();
        Account account1 = Utils_TestMethods.CreateAccount(c,m1, 'a1');
        account1.Etat__c = '2';
        account1.RecordTypeId = associationRTPays.get('France').ID_PUDO_Non_Suivi__c;
 		
        Account account2 = Utils_TestMethods.CreateAccount(c,m1, 'a2');
        account2.Etat__c = '2';
        account2.RecordTypeId = associationRTPays.get('France').ID_PUDO_Non_Suivi__c;
        
        Account account3 = Utils_TestMethods.CreateAccount(c,m1, 'a3');
        account3.Etat__c = '2';
        account3.RecordTypeId = PUS_FR_Consigne;
        
        listAccountsToBeInserted.add(account1);
        listAccountsToBeInserted.add(account2);
        listAccountsToBeInserted.add(account3);
        
        //Create an account and modify it to TR : PUS_FR_Prospect_Converti
        Account account4 = Utils_TestMethods.CreateAccount(c,m1, 'a4');
        insert account4; 
        account4.RecordTypeId = associationRTPays.get('France').ID_Prospect_Converti__c;
        
        User user = [SELECT Id 
                     FROM User
                     Where Id =: UserInfo.getUserId()
                    ];
        user.BypassValidationRule__c = true;
        update user;
        System.runAs(user) {
            Test.startTest();
            insert listAccountsToBeInserted; 
            update account4;
            CountriesSequence__c countryInstance = CountriesSequence__c.getInstance('France');
           // System.assertEquals('FR00005', countryInstance.Sequence__c);
            Test.stopTest();
        } 
    }
}