force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Macroprofil de création.</inlineHelpText>
    <label>Macroprofil de référence</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>equals</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard, 23</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes (Macroprofil de référence)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <label>Partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_PAR</valueSetName>
    </valueSet>
</CustomField>

src/objects/Macroprofil_Reseau__c.object
<CustomObject>
    <description>Réseaux ajoutés par défaut au relais lors de son association avec un macroprofil</description>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Réseaux par défaut</relationshipLabel>
        <relationshipName>Reseaux_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reseau__c</fullName>
        <label>Réseau</label>
        <referenceTo>Reseau__c</referenceTo>
        <relationshipLabel>Macroprofils associés</relationshipLabel>
        <relationshipName>Reseaux_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Techatraiter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Techatraiter</label>
        <type>Checkbox</type>
    </fields>
    <label>Réseau par défaut</label>
    <nameField>
        <displayFormat>RPD-{0000}</displayFormat>
        <label>Numéro du Réseau par défaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réseaux par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil_Service__c.object
<CustomObject>
    <description>Services ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Services par défaut</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Macroprofil liés à ce service</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Techatraiter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Techatraiter</label>
        <type>Checkbox</type>
    </fields>
    <label>Service par défaut</label>
    <nameField>
        <displayFormat>SPD-{0000}</displayFormat>
        <label>Numéro du Service par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil_Transporteur__c.object
<CustomObject>
    <description>Transporteurs ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Transporteur par defaut</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Techatraiter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Techatraiter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <label>Transporteur</label>
        <referenceTo>Transporteur__c</referenceTo>
        <relationshipLabel>Macroprofils liés à ce transporteur</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transporteur par defaut</label>
    <nameField>
        <displayFormat>TPD-{0000}</displayFormat>
        <label>Numéro du Transporteur par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteur par defaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reseau__c.object
<CustomObject>
    <description>Un réseau est un ensemble de caractéristiques communes à des PUDO parmi : service, opérateur, pays, opérateur...</description>
    <fields>
        <fullName>Partenaire__c</fullName>
        <label>Partenaire</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_PAR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Techatraiter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Techatraiter</label>
        <type>Checkbox</type>
    </fields>
    <label>Réseau</label>
    <nameField>
        <label>Nom du Réseau</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réseaux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Reseau_Associe__c.object
<CustomObject>
    <description>Ensemble des réseaux associés à l&apos;instant t avec un relais.</description>
    <fields>
        <fullName>Compte__c</fullName>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Reseaux_clients_associes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <formula>Compte__r.Macroprofil_actuel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Macroprofil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reseau__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Réseau</label>
        <referenceTo>Reseau__c</referenceTo>
        <relationshipLabel>Points relais associés au réseau</relationshipLabel>
        <relationshipName>Reseaux_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Réseau associé</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Numéro du Réseau associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réseaux associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Associe__c.object
<CustomObject>
    <description>Ensemble de services proposés par le Pudo selon le macro-profil affecté. Des services seront pilotables par l’action d’activation ou de désactivation.</description>
    <fields>
        <fullName>Compte__c</fullName>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services associés</relationshipLabel>
        <relationshipName>Services_associes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <formula>Compte__r.Macroprofil_actuel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Macroprofil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Points relais pouvant activer le service</relationshipLabel>
        <relationshipName>Services_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service associé</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Numéro du Service associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transporteur_Associe__c.object
<CustomObject>
    <description>Ensemble des chargeurs associés à l&apos;instant avec un relais.Pour la France il est possible d’activer ou désactiver un ou des transporteurs par l’action d’activation ou de désactivation.</description>
    <fields>
        <fullName>Compte__c</fullName>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transporteurs associés</relationshipLabel>
        <relationshipName>Transporteurs_associes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <description>Ce champs sera utilisé comme filtre dans les vues de listes.</description>
        <formula>Compte__r.Macroprofil_actuel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Macroprofil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transporteur</label>
        <referenceTo>Transporteur__c</referenceTo>
        <relationshipLabel>Points relais associés</relationshipLabel>
        <relationshipName>Transporteurs_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Transporteur associé</label>
    <nameField>
        <displayFormat>TRA-{0000}</displayFormat>
        <label>Numéro du Transporteur associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteurs associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_PAR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <customValue>
        <fullName>124</fullName>
    </customValue>
    <customValue>
        <fullName>125</fullName>
    </customValue>
    <customValue>
        <fullName>126</fullName>
    </customValue>
    <customValue>
        <fullName>134</fullName>
    </customValue>
    <customValue>
        <fullName>135</fullName>
    </customValue>
    <customValue>
        <fullName>140</fullName>
    </customValue>
    <customValue>
        <fullName>146</fullName>
    </customValue>
    <customValue>
        <fullName>177</fullName>
    </customValue>
    <customValue>
        <fullName>178</fullName>
    </customValue>
    <customValue>
        <fullName>179</fullName>
    </customValue>
    <customValue>
        <fullName>180</fullName>
    </customValue>
    <customValue>
        <fullName>181</fullName>
    </customValue>
    <customValue>
        <fullName>182</fullName>
    </customValue>
    <customValue>
        <fullName>183</fullName>
    </customValue>
    <customValue>
        <fullName>184</fullName>
    </customValue>
    <customValue>
        <fullName>185</fullName>
    </customValue>
    <customValue>
        <fullName>188</fullName>
    </customValue>
    <customValue>
        <fullName>189</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>190</fullName>
    </customValue>
    <customValue>
        <fullName>194</fullName>
    </customValue>
    <customValue>
        <fullName>195</fullName>
    </customValue>
    <customValue>
        <fullName>-2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>211</fullName>
    </customValue>
    <description>Liste des partenaires</description>
    <masterLabel>LOV_GLO_PAR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/Batch03_Reseau.cls
global class Batch03_Reseau implements Database.Batchable<sObject> {
    private String  accountIdsConcatenated;
	private Set<Id> setAccountIds = new Set<Id>();
	
    global Batch03_Reseau(Set<Id> accountIds) {
        this.accountIdsConcatenated = '';
        for(Id id: accountIds){
            this.accountIdsConcatenated +=''+ id + ',';
        }
        accountIdsConcatenated = accountIdsConcatenated.removeEnd(',');
    }
    global Batch03_Reseau(){ 
	
	
        Set<Id> setMacroprofils = new Set<Id>();		
		Set<Id> setServices = new Set<Id>();	   
		Set<Id> setTransporteurs = new Set<Id>();
		Set<Id> setReseaux = new Set<Id>();
		
		
        this.accountIdsConcatenated = '';
		
		
		// get the accounts from service associated that should be recalculated
      	for( Macroprofil_Service__c mpService :  [select Macroprofil__c, Service__c 
												  from Macroprofil_Service__c 
												  where Techatraiter__c = true]) {
			setMacroprofils.add(mpService.Macroprofil__c);
			setServices.add(mpService.Service__c);				
		}
        
		for(Service_Associe__c servAss :  [Select Compte__c, Compte__r.Macroprofil_actuel__c
                         				   from Service_Associe__c 
                                           where Service__c =: setServices]) {
			if(servAss.Compte__c != null && setMacroprofils.contains(servAss.Compte__r.Macroprofil_actuel__c))
        		setAccountIds.add(servAss.Compte__c);
		}										
		
        
		
        // get the accounts from transporteur associated that should be recalculated
	    setMacroprofils.clear();
		for(Macroprofil_Transporteur__c trans : [select Macroprofil__c, Transporteur__c 
                                                     from Macroprofil_Transporteur__c 
                                                     where Techatraiter__c = true]){
			setMacroprofils.add(trans.Macroprofil__c);
            setTransporteurs.add(trans.Transporteur__c);
		}
				         
        for( Transporteur_Associe__c transAss : [Select Compte__c, Compte__r.Macroprofil_actuel__c
                         							  from Transporteur_Associe__c 
                                                      where Transporteur__c in: setTransporteurs]){
        	if(transAss.Compte__c != null && setMacroprofils.contains(transAss.Compte__r.Macroprofil_actuel__c))
        		setAccountIds.add(transAss.Compte__c);
        }
		
		
		
        
        // get the accounts from reseaux associated that should be recalculated
		setMacroprofils.clear();
		for (Macroprofil_Reseau__c  mpRes : [select Macroprofil__c, Reseau__c 
                                             from Macroprofil_Reseau__c 
                                             where Techatraiter__c = true]) { 
			setMacroprofils.add(mpRes.Macroprofil__c);
            setReseaux.add(mpRes.Reseau__c);
		}
					 
        for(Reseau_Associe__c resAss : [Select Compte__c, Compte__r.Macroprofil_actuel__c
                         			    from Reseau_Associe__c 
                                        where Reseau__c in: setReseaux]){
        	if(resAss.Compte__c != null && setMacroprofils.contains(resAss.Compte__r.Macroprofil_actuel__c))
        		setAccountIds.add(resAss.Compte__c);
        }
		
		setMacroprofils.clear();
		setReseaux.clear();
		setTransporteurs.clear();
		setServices.clear(); 
        
    }
        
    global Database.QueryLocator start(Database.BatchableContext BC) {  
        //get list of accounts concerned 
        String query =  'select Id, Macroprofil_de_reference__c,Etat__c, Macroprofil_actuel__c, Type, Industry, Partenaire__c, Horaire_Ouverture_Reference__c, Horaire_Fermeture_Reference__c, Poids_maximal_accepte_par_colis__c ' +
                        'from Account where Id in : setAccountIds' ;
        return Database.getQueryLocator(query);    
    }
	
    
    global void execute(Database.BatchableContext BC , List<Account> scope) {
        set<Id> setMacroprofilIds = new set<Id>();
        for(Account acc : scope){
            setMacroprofilIds.add(acc.macroprofil_de_reference__c);
        }
        AP04_Account ap04Acc = new AP04_Account();
        ap04Acc.UpdateReseauAssociations(scope, setMacroprofilIds);
    }
    
    global void finish(Database.BatchableContext BC){
 		List<Macroprofil_Service__c> newlist = [select Techatraiter__c
												from Macroprofil_Service__c 
												where Techatraiter__c = true];
        List<Macroprofil_Transporteur__c> newlistTrans = [select Techatraiter__c
                                                     from Macroprofil_Transporteur__c 
                                                     where Techatraiter__c = true];
        List<Macroprofil_Reseau__c> newlistRes = [select Techatraiter__c
                                                 from Macroprofil_Reseau__c
                                                 where Techatraiter__c = true];
        
        for(Macroprofil_Service__c mps: newlist)
            mps.techatraiter__c = false;
        for(Macroprofil_Transporteur__c mpt: newlistTrans)
            mpt.techatraiter__c = false;
         for(Macroprofil_Reseau__c mpr: newlistRes)
            mpr.techatraiter__c = false;
        
        
        update newlist;
        update newlistTrans;
		update newlistRes;
    }

    
}