force-app/main/default/objects/Account/fields/Etat__c.field-meta.xml
<CustomField>
    <fullName>Etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_ETA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

src/objects/Anomalie__c.object
<CustomObject>
    <description>Objet technique permettant de stocker les anomalies associées au PUDO, en particulier les anomalies provenant de la télécollecte.</description>
    <fields>
        <fullName>PUDO__c</fullName>
        <label>PUDO</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Anomalies_de_Telecollecte</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SyncPudo</fullName>
                </value>
                <value>
                    <fullName>NoDevice</fullName>
                </value>
                <value>
                    <fullName>TooManyDevices</fullName>
                </value>
                <value>
                    <fullName>NoDecommissioned</fullName>
                </value>
                <value>
                    <fullName>Association à tort Etat 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Anomalie</label>
    <nameField>
        <label>Numéro de l&apos;anomalie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_Conge__c</fullName>
        <label>ID_Conge</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Requete_Conge__c</fullName>
        <label>ID_Requête_Congé</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Anomalie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Anomalie</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Anomalie__c.PUDO__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Anomalie__c</referenceTo>
        <relationshipLabel>Requêtes</relationshipLabel>
        <relationshipName>Requ_tes</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>DPD_BNL</fullName>
        <active>true</active>
        <businessProcess>DPD_BNL_Requêtes_Ponctuelles</businessProcess>
        <label>DPD_BNL_inactif_avec_scan_associé</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Anomalie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Champ technique servant à référencer une anomalie</description>
        <label>Anomalie</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Anomalie__c.PUDO__c</field>
                <operation>equals</operation>
                <valueField>$Source.Nom_du_compte__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Anomalie__c</referenceTo>
        <relationshipLabel>Congés/disponibilités/indisponibilités</relationshipLabel>
        <relationshipName>Cong_s_disponibilit_s_indisponibilit_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_de_fin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>IF ( Date_de_debut__c &gt;  TODAY() ,$Label.CongeIndispo_A_Venir_2,
IF ( Date_de_fin__c  &lt;   TODAY() ,$Label.Conge_Indispo_Passe_2,$Label.CongeIndispo_En_Cours_2))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_d_indisponibilite__c</fullName>
        <description>Ne pas activer l&apos;option &quot;Restreindre la liste sélectionnée aux valeurs définies dans l’ensemble de valeurs.	&quot; pour ne pas bloquer le PB qui crée automatiquement les indispos suite à des créations d&apos;anomalies.</description>
        <label>Type d&apos;indisponibilité</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>Planifiée</fullName>
                </value>
                <value>
                    <fullName>Imprévue</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassWorkflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_ETA.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <description>Etat du cycle de vie d&apos;un PUDO</description>
    <masterLabel>LOV_GLO_ETA</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/AP02_Anomalie_Test.cls
@isTest
public class AP02_Anomalie_Test {
    @testSetup
    static void testSetupm()
    {
        User currentUser = [SELECT Id, Name, BypassValidationRule__c
                            FROM User
                            WHERE Id = : UserInfo.getUserId()];
        currentUser.BypassValidationRule__c = true;
        currentUser.BypassProcessBuilder__c = true;
        currentUser.BypassWorkflow__c = true;
        update currentUser;
    }
    static testMethod void moyenScan() 
    {
        // retrieve ID of belgium
         List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c,ID_Requete_Conge__c,ID_CONGE__c
                                                                              FROM Association_Record_Type_et_pays__mdt];
            
            
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
           associationRTPays.put(associationRT.MasterLabel, associationRT);  
        }    
        Integer anomalieSurrattributionCount = 0;
        Integer decommissionnementDeviceCount = 0;
        Integer absenceDeviceCount = 0;
        Integer absenceDevice1Count = 0;
        Integer associationtortEtat2Count = 0;
        Integer pasDePDAAssocieStandard = 0;
        Integer pasDePDAAssociePartenaire = 0;
        
        Contact testContact = Utils_TestMethods.CreateContact('Name');       
        Contact testContact1 = Utils_TestMethods.CreateContact('Name1'); 
        Contact testContact2 = Utils_TestMethods.CreateContact('Name2'); 
        insert new List<Contact> {testContact, testContact1, testContact2};
        list<Account> listAccounts = new list<Account>();
        //Account type 2
        Account newAccount= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account');
        newAccount.RecordTypeId = associationRTPays.get('Belgium').ID_Prospect_A_Valider__c;
        newAccount.ShippingCountry ='Belgium';
        newAccount.ShippingCountryCode='BE';
        newAccount.Etat__c = '0';
        newAccount.Operateur_Global__c = 'DPD_BNL';
        newAccount.ShippingPostalCode = '1234';
        newAccount.Type ='2';
        listAccounts.add(newAccount);
        //Account type 3
        Account newAccount1= Utils_TestMethods.CreateAccount(testContact1, null, 'Test Account');
        newAccount1.RecordTypeId = associationRTPays.get('Belgium').ID_Prospect_A_Valider__c;
        newAccount1.ShippingCountry ='Belgium';
        newAccount1.ShippingCountryCode='BE';
        newAccount1.Etat__c = '0';
        newAccount1.Operateur_Global__c = 'DPD_BNL';
        newAccount1.ShippingPostalCode = '1234';
        newAccount1.Type ='3';
        listAccounts.add(newAccount1);
        Account newAccount2= Utils_TestMethods.CreateAccount(testContact2, null, 'Test Account');
        newAccount2.RecordTypeId = associationRTPays.get('France').ID_Prospect_Converti__c;
        newAccount2.ShippingCountry ='France';
        newAccount2.ShippingCountryCode='FR';
        newAccount2.Etat__c = '0';
        newAccount2.Operateur_Global__c = 'PUS_FR';
        newAccount2.ShippingPostalCode = '12345';
        newAccount2.Type ='2';
        listAccounts.add(newAccount2);
        insert listAccounts;
        testContact.AccountId = newAccount.id;
        testContact1.AccountId = newAccount1.id;
        testContact2.AccountId = newAccount2.id;
        update new List<Contact>{testContact, testContact1, testContact2};
        
        list<anomalie__c> listAnomaliesToInsert = new list<anomalie__c>();
        list<anomalie__c> listAnomaliesToUpdate = new list<anomalie__c>();
        
        //Anomalie Surattribution de device ouverte
        Anomalie__c testAnomalieSurrattribution = Utils_TestMethods.createAnomalie(newAccount);
        testAnomalieSurrattribution.Statut__c='1';
        testAnomalieSurrattribution.Type__c='TooManyDevices';
        listAnomaliesToInsert.add(testAnomalieSurrattribution);
    Anomalie__c testAnomalieSurrattribution1 = Utils_TestMethods.createAnomalie(newAccount);
        testAnomalieSurrattribution1.Statut__c='1';
        testAnomalieSurrattribution1.Type__c='TooManyDevices';
        listAnomaliesToInsert.add(testAnomalieSurrattribution1);      
        Anomalie__c testAnomalieSurrattribution2 = Utils_TestMethods.createAnomalie(newAccount);
        testAnomalieSurrattribution2.Statut__c='1';
        testAnomalieSurrattribution2.Type__c='TooManyDevices';
        listAnomaliesToInsert.add(testAnomalieSurrattribution2); 
        Anomalie__c testAnomalieSurrattribution3 = Utils_TestMethods.createAnomalie(newAccount2);
        testAnomalieSurrattribution3.Statut__c='1';
        testAnomalieSurrattribution3.Type__c='TooManyDevices';
        listAnomaliesToInsert.add(testAnomalieSurrattribution3);
        
        //Anomalie Décommissionnement de device ouverte
        Anomalie__c testDecommissionnementDevice = Utils_TestMethods.createAnomalie(newAccount);
        testDecommissionnementDevice.Statut__c='1';
        testDecommissionnementDevice.Type__c='NoDecommissioned';
        listAnomaliesToInsert.add(testDecommissionnementDevice);
        Anomalie__c testDecommissionnementDevice1 = Utils_TestMethods.createAnomalie(newAccount);
        testDecommissionnementDevice1.Statut__c='1';
        testDecommissionnementDevice1.Type__c='NoDecommissioned';
        listAnomaliesToInsert.add(testDecommissionnementDevice1);
        Anomalie__c testDecommissionnementDevice2 = Utils_TestMethods.createAnomalie(newAccount2);
        testDecommissionnementDevice2.Statut__c='1';
        testDecommissionnementDevice2.Type__c='NoDecommissioned';
        listAnomaliesToInsert.add(testDecommissionnementDevice2);
        
        //Anomalie Absence de device associé type 2
        Anomalie__c testAbsenceDevice = Utils_TestMethods.createAnomalie(newAccount2);
        testAbsenceDevice.Statut__c='1';
        testAbsenceDevice.Type__c='NoDevice';
        listAnomaliesToInsert.add(testAbsenceDevice);
        
        //Anomalie Absence de device associé type 3
        Anomalie__c testAbsenceDevice1 = Utils_TestMethods.createAnomalie(newAccount2);
        testAbsenceDevice1.Statut__c='1';
        testAbsenceDevice1.Type__c='NoDevice';
        listAnomaliesToInsert.add(testAbsenceDevice1);
        
        //Anomalie Absence de device associé Fr
        Anomalie__c testAbsenceDevice2 = Utils_TestMethods.createAnomalie(newAccount2);
        testAbsenceDevice2.Statut__c='1';
        testAbsenceDevice2.Type__c='NoDevice';
        listAnomaliesToInsert.add(testAbsenceDevice2);
        
        //Anomalie Association à tort Etat 2
        Anomalie__c testAssociationtortEtat2 = Utils_TestMethods.createAnomalie(newAccount);
        testAssociationtortEtat2.Statut__c='1';
        testAssociationtortEtat2.Type__c='Association à tort Etat 2';        
        listAnomaliesToInsert.add(testAssociationtortEtat2);
        
        Anomalie__c testAssociationtortEtat2_2 = Utils_TestMethods.createAnomalie(newAccount2);
        testAssociationtortEtat2_2.Statut__c='1';
        testAssociationtortEtat2_2.Type__c='Association à tort Etat 2';
        listAnomaliesToInsert.add(testAssociationtortEtat2_2);
        
        insert listAnomaliesToInsert;
        
        List<Case> anomCaseInserted = [SELECT id, Anomalie__c, Anomalie__r.Statut__c, Anomalie__r.type__c, Account.type
                                       FROM Case
                                       WHERE Anomalie__r.Statut__c ='1'];
        List<Anomalie__c> anomCongeInserted = [SELECT id,Type__c, PUDO__r.type,
                                               (SELECT id FROM Cong_s_disponibilit_s_indisponibilit_s__r WHERE Type_d_indisponibilite__c = '4')
                                               FROM Anomalie__c
                                               WHERE Statut__c = '1'];    
        system.debug('anomCaseInserted '+anomCaseInserted);
        system.debug('anomCongeInserted '+anomCongeInserted);
        for(Case anomCase : anomCaseInserted)
        {
            system.debug('anomCase.Anomalie__c '+anomCase.Anomalie__c);
            system.debug('testAnomalieSurrattribution.id '+testAnomalieSurrattribution.id);
            system.debug('anomCase.Anomalie__r.type__c '+anomCase.Anomalie__r.type__c);
            system.debug('anomCase.Account.type '+anomCase.Account.type);
            
            if(anomCase.Anomalie__c == testAnomalieSurrattribution.id)
            {
                anomalieSurrattributionCount++;
            }
            else if(anomCase.Anomalie__c == testDecommissionnementDevice.id)
            {
                decommissionnementDeviceCount++;
            }
            else if(anomCase.Anomalie__c == testAbsenceDevice1.id)
            {
                absenceDevice1Count++;
            }
            else if(anomCase.Anomalie__c == testAssociationtortEtat2.id)
            {
                associationtortEtat2Count++;
            }
        }
        //Anomalie Surattribution de device fermer
        testAnomalieSurrattribution.Statut__c = '0';
        listAnomaliesToUpdate.add(testAnomalieSurrattribution);
        //update testAnomalieSurrattribution;
        
        //Anomalie Décommissionnement de device fermer
        testDecommissionnementDevice.Statut__c = '0';
        //update testDecommissionnementDevice;
        listAnomaliesToUpdate.add(testDecommissionnementDevice);
        
        //Anomalie Absence de device fermer type 2
        testAbsenceDevice.Statut__c = '0';
        //update testAbsenceDevice;
        
        //Anomalie Absence de device fermer type 3
        testAbsenceDevice1.Statut__c = '0';
        //update testAbsenceDevice1;
        
        //Anomalie Association à tort Etat 2
        testAssociationtortEtat2.Statut__c = '0';
        listAnomaliesToUpdate.add(testAssociationtortEtat2);
        
        testAssociationtortEtat2_2.Statut__c = '0';
        listAnomaliesToUpdate.add(testAssociationtortEtat2_2);
        
        testAnomalieSurrattribution3.Statut__c = '0';
        listAnomaliesToUpdate.add(testAnomalieSurrattribution3);
        
        testDecommissionnementDevice2.Statut__c = '0';
        listAnomaliesToUpdate.add(testDecommissionnementDevice2);
        
        testAbsenceDevice2.Statut__c = '0';
        listAnomaliesToUpdate.add(testAbsenceDevice2);

        update listAnomaliesToUpdate;
        
        anomalieSurrattributionCount = 0;
        decommissionnementDeviceCount = 0;
        absenceDeviceCount = 0;
        absenceDevice1Count = 0;
        associationtortEtat2Count = 0;
        pasDePDAAssocieStandard = 0;
        pasDePDAAssociePartenaire = 0;
        
        List<Case> anomCaseUpdated = [SELECT id, status, Anomalie__c, Anomalie__r.Statut__c
                                      FROM Case
                                      WHERE Anomalie__r.Statut__c ='0'];
        List<Anomalie__c> anomCongeUpdated = [SELECT id, PUDO__r.type,
                                              (SELECT id FROM Cong_s_disponibilit_s_indisponibilit_s__r WHERE Type_d_indisponibilite__c = '4' AND Date_de_fin__c = :Date.today())
                                              FROM Anomalie__c
                                              WHERE Statut__c = '0'];   
        for(Case anomCase : anomCaseUpdated)
        {
            if(anomCase.Anomalie__c == testAnomalieSurrattribution.id && anomCase.status == 'Terminée')
            {
                anomalieSurrattributionCount++;
            }
            else if(anomCase.Anomalie__c == testDecommissionnementDevice.id && anomCase.status == 'Terminée')
            {
                decommissionnementDeviceCount++;
            }
            else if(anomCase.Anomalie__c == testAssociationtortEtat2.id && anomCase.status == 'Terminée')
            {
                associationtortEtat2Count++;
            }
        }
      }
}