force-app/main/default/objects/Account/fields/Hauteur_cm__c.field-meta.xml
<CustomField>
    <fullName>Hauteur_cm__c</fullName>
    <label>Hauteur (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Largeur_cm__c.field-meta.xml
<CustomField>
    <fullName>Largeur_cm__c</fullName>
    <label>Largeur (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_detageres__c.field-meta.xml
<CustomField>
    <fullName>Nombre_detageres__c</fullName>
    <label>Nombre d&#39;étagères</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Profondeur_cm__c.field-meta.xml
<CustomField>
    <fullName>Profondeur_cm__c</fullName>
    <label>Profondeur (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seuil_contractuel__c.field-meta.xml
<CustomField>
    <fullName>Seuil_contractuel__c</fullName>
    <label>Seuil contractuel</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Compte_rendu__c.object
<CustomObject>
    <description>Cet objet permet de sélectionner les questions CR en fonction du compte rendu sélectionné.</description>
    <fields>
        <fullName>Compte_rendu__c</fullName>
        <label>Compte rendu</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>INTER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compte rendu</label>
    <nameField>
        <label>Nom de compte rendu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes rendus</pluralLabel>
    <recordTypes>
        <fullName>VA</fullName>
        <active>true</active>
        <label>VA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Compte_rendu_rempli__c.object
<CustomObject>
    <description>Compte rendu VA/VAP rempli suite à la visite d&apos;un animateur chez un PUDO.</description>
    <fields>
        <fullName>Compte_rendu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte rendu</label>
        <referenceTo>Compte_rendu__c</referenceTo>
        <relationshipName>Comptes_rendus_remplis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hauteur__c</fullName>
        <label>Hauteur</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Largeur__c</fullName>
        <label>Largeur</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Comptes rendus remplis</relationshipLabel>
        <relationshipName>Comptes_rendus_remplis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nombre_d_etageres__c</fullName>
        <label>Nombre d&apos;étagères</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profondeur__c</fullName>
        <label>Profondeur</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Seuil_contractuel__c</fullName>
        <label>Seuil contractuel</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>En attente de traitement</fullName>
                </value>
                <value>
                    <fullName>En cours de préparation</fullName>
                    <default>true</default>
                    <label>En cours de préparation</label>
                </value>
                <value>
                    <fullName>En attente de visite</fullName>
                    <label>En visite</label>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compte rendu de visite</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Nom de compte rendu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comptes rendus de visite</pluralLabel>
    <recordTypes>
        <fullName>VA</fullName>
        <active>true</active>
        <label>VA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Questions_CR__c.object
<CustomObject>
    <description>Questions utilisés pour les questionnaires VA/VAP.</description>
    <fields>
        <fullName>Changement_macro_profil__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Changement macro profil</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Compte_rendu__c</fullName>
        <label>Nom du compte rendu</label>
        <referenceTo>Compte_rendu__c</referenceTo>
        <relationshipName>Questionnaires_VA_VAP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Questions CR</label>
    <nameField>
        <label>Numéro de question</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions CR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reponse_CR__c.object
<CustomObject>
    <description>Réponses des questionnaires VA/VAP.</description>
    <fields>
        <fullName>Changement_macro_profil__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Changement macro profil</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Compte_rendu_rempli__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte rendu rempli</label>
        <referenceTo>Compte_rendu_rempli__c</referenceTo>
        <relationshipLabel>Comptes rendu de visite</relationshipLabel>
        <relationshipName>Reponses_CR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Questions_CR__c</fullName>
        <label>Questions CR</label>
        <referenceTo>Questions_CR__c</referenceTo>
        <relationshipLabel>Réponses CR (Questions CR)</relationshipLabel>
        <relationshipName>Reponses_CR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Réponse CR</label>
    <nameField>
        <label>Nom de réponse CR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réponses CR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/AP01_CompteRenduRempli_Test.cls
/*--------------------------------------------------------------------------------------------------------------------------
Author: Fadi Tannoury
Company: Ei-Technologies Lebanon
Description: Test Class for AP01_CompteRenduRempli
History
2018-06-08  Fadi Tannoury	  Creation
--------------------------------------------------------------------------------------------------------------------------*/

@isTest
public class AP01_CompteRenduRempli_Test {
    
    @isTest
    public static void testUpdateAccount(){
        
        Id CompteRendu_RTId = [SELECT id FROM RecordType WHERE DeveloperName = 'VA' AND SobjectType = 'Compte_rendu__c' LIMIT 1].Id;
        
        Macroprofil__c MP = Utils_TestMethods.CreateMacroprofil('MP1-Standard');
        MP.Name = 'MP1-Standard';
        insert MP;
        
        Account compte = Utils_TestMethods.CreateAccount(null, null, 'compte');
		compte.Type = '2';
        compte.Operateur_Global__c='PUS_FR';
        insert compte;
        
        System.debug('***compte : ' + compte);
        Compte_rendu_rempli__c CRR1 = Utils_TestMethods.createCompteRenduRempli(compte.Id, Label.VAVAP_statutEnAttente);
        Compte_rendu_rempli__c CRR2 = Utils_TestMethods.createCompteRenduRempli(compte.Id, Label.VAVAP_statutTermine);
        insert new List<Compte_rendu_rempli__c> {CRR1, CRR2};
        
        Compte_rendu__c CR = Utils_TestMethods.createCompteRendu('Compte Rendu', CompteRendu_RTId);
        insert CR;
        
        Questions_CR__c ques = Utils_TestMethods.createQuestionsCR(CR.id, 'Oui;Non', 'test?', 'Choix');
        insert ques;
 
        Reponse_CR__c Reponse = Utils_TestMethods.createReponseCR(CRR1.id, ques.Id, 'Question', 'MP1-Standard');
        Reponse.Changement_macro_profil__c = true;
        insert Reponse;
        
        CRR1.Statut__c = Label.VAVAP_statutTermine;
        CRR1.Hauteur__c = 250;
        CRR1.Largeur__c = 155;
        CRR1.Profondeur__c = 40;
        CRR1.Nombre_d_etageres__c = 1;
        CRR1.Seuil_contractuel__c = 20;
        
        Test.startTest();
        update CRR1;
        Test.stopTest();
        
        Account acc = [SELECT Id, Macroprofil_actuel__c, Hauteur_cm__c, Largeur_cm__c, 
                       Profondeur_cm__c, Nombre_detageres__c, Seuil_contractuel__c
                       FROM Account 
                       WHERE Id = :compte.Id LIMIT 1];
        
        //system.assertEquals(MP.Id, acc.Macroprofil_actuel__c);
        system.assertEquals(CRR1.Hauteur__c, acc.Hauteur_cm__c);
        system.assertEquals(CRR1.Largeur__c, acc.Largeur_cm__c);
        system.assertEquals(CRR1.Profondeur__c, acc.Profondeur_cm__c);
        system.assertEquals(CRR1.Nombre_d_etageres__c , acc.Nombre_detageres__c);
        system.assertEquals(CRR1.Seuil_contractuel__c, acc.Seuil_contractuel__c);
        
    }

}