force-app/main/default/objects/Account/fields/Hauteur_cm__c.field-meta.xml
<CustomField>
    <fullName>Hauteur_cm__c</fullName>
    <label>Hauteur (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Largeur_cm__c.field-meta.xml
<CustomField>
    <fullName>Largeur_cm__c</fullName>
    <label>Largeur (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_detageres__c.field-meta.xml
<CustomField>
    <fullName>Nombre_detageres__c</fullName>
    <label>Nombre d&#39;étagères</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Profondeur_cm__c.field-meta.xml
<CustomField>
    <fullName>Profondeur_cm__c</fullName>
    <label>Profondeur (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seuil_contractuel__c.field-meta.xml
<CustomField>
    <fullName>Seuil_contractuel__c</fullName>
    <label>Seuil contractuel</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Compte_rendu_rempli__c.object
<CustomObject>
    <description>Compte rendu VA/VAP rempli suite à la visite d&apos;un animateur chez un PUDO.</description>
    <fields>
        <fullName>Compte__c</fullName>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Comptes_rendus_remplis</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hauteur__c</fullName>
        <label>Hauteur</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Largeur__c</fullName>
        <label>Largeur</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_d_etageres__c</fullName>
        <label>Nombre d&apos;étagères</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profondeur__c</fullName>
        <label>Profondeur</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Seuil_contractuel__c</fullName>
        <label>Seuil contractuel</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Compte rendu de visite</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Nom de compte rendu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comptes rendus de visite</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reponse__c.object
<CustomObject>
    <description>Objet utilisé pour stocker les réponses d&apos;un PUDO lors du démarrage d&apos;activité.</description>
    <label>Réponse</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Numéro de Réponse</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reponse_CR__c.object
<CustomObject>
    <description>Réponses des questionnaires VA/VAP.</description>
    <fields>
        <fullName>Changement_macro_profil__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Changement macro profil</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Compte_rendu_rempli__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte rendu rempli</label>
        <referenceTo>Compte_rendu_rempli__c</referenceTo>
        <relationshipLabel>Comptes rendu de visite</relationshipLabel>
        <relationshipName>Reponses_CR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reponse__c</fullName>
        <label>Réponse</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Réponse CR</label>
    <nameField>
        <label>Nom de réponse CR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réponses CR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AP01_CompteRenduRempli.cls
/*--------------------------------------------------------------------------------------------------------------------------
Author: Fadi Tannoury
Company: Ei-Technologies Lebanon
Description: MAJ du MacroProfil du compte si le statut du compte rendu rempli est 'Terminé'
History
2018-06-08  Fadi Tannoury	  Creation
--------------------------------------------------------------------------------------------------------------------------*/

public class AP01_CompteRenduRempli {
    
    public static void UpdateMPifCRRTermine(Set<Id> CRRIds, Map<Id, Compte_rendu_rempli__c> oldCRRMap){

        Map<Id, Account> AccountsToUpdate = new Map<Id, Account>();
        Map<Id, String> AccMPMap = new Map<Id, String>();
        Map<String, Id> MPNameIdMap = new Map<String, Id>();
        
        List<Compte_rendu_rempli__c> CRRList = [SELECT Id, Compte__c, compte__r.Macroprofil_actuel__c, compte__r.Hauteur_cm__c, compte__r.Largeur_cm__c, 
                                                compte__r.Profondeur_cm__c, compte__r.Nombre_detageres__c, compte__r.Seuil_contractuel__c,
                                                Hauteur__c, Largeur__c, Profondeur__c, Nombre_d_etageres__c, Seuil_contractuel__c,
                                                (SELECT id, Changement_macro_profil__c, Reponse__c FROM Reponses_CR__r)
                                                FROM Compte_rendu_rempli__c
                                                WHERE Id IN :CRRIds]; 
        system.debug('1*** CRRList: '+CRRList);
       system.debug('1*** oldCRRMap: '+oldCRRMap);
        for(Compte_rendu_rempli__c CRR : CRRList){
            
            Compte_rendu_rempli__c oldCRR;
            Account acc = new Account(Id = CRR.Compte__c);
            
            if(oldCRRMap != null && oldCRRMap.containsKey(CRR.Id)){ 
                oldCRR = oldCRRMap.get(CRR.Id);
            }
            //if(oldCRRMap == null || (oldCRRMap != null && CRR.Hauteur__c != oldCRRMap.get(CRR.Id).Hauteur__c)){ 
                acc.Hauteur_cm__c = CRR.Hauteur__c;
            //}
           // if(oldCRRMap == null || (oldCRRMap != null && CRR.Largeur__c != oldCRRMap.get(CRR.Id).Largeur__c)){ 
                acc.Largeur_cm__c = CRR.Largeur__c;
           // }
           // if(oldCRRMap == null || (oldCRRMap != null && CRR.Profondeur__c != oldCRRMap.get(CRR.Id).Profondeur__c)){ 
                acc.Profondeur_cm__c = CRR.Profondeur__c;
            //}
           // if(oldCRRMap == null || (oldCRRMap != null && CRR.Nombre_d_etageres__c != oldCRRMap.get(CRR.Id).Nombre_d_etageres__c)){ 
                acc.Nombre_detageres__c = CRR.Nombre_d_etageres__c;
            //}
           // if(oldCRRMap == null || (oldCRRMap != null && CRR.Seuil_contractuel__c != oldCRRMap.get(CRR.Id).Seuil_contractuel__c)){ 
                acc.Seuil_contractuel__c = CRR.Seuil_contractuel__c;
           // }
            
            System.debug('');
            for(Reponse_CR__c reponse : CRR.Reponses_CR__r){
                
               // if(reponse.Changement_macro_profil__c && reponse.Reponse__c != Label.VAVAP_Autre && !String.isBlank(reponse.Reponse__c)){
                       // AccMPMap.put(acc.Id, reponse.Reponse__c);
               // }
            }
            AccountsToUpdate.put(acc.Id, acc);
        }
 
        if(AccountsToUpdate.size()>0){
      
              update AccountsToUpdate.values();  
           
        }
    }
    
}