force-app/main/default/objects/Account/fields/Horaire_Fermeture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Fermeture_Reference__c</fullName>
    <label>Horaire de fermeture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Horaire_Ouverture_Reference__c.field-meta.xml
<CustomField>
    <fullName>Horaire_Ouverture_Reference__c</fullName>
    <label>Horaire d&#39;ouverture de référence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_HOR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Macroprofil de création.</inlineHelpText>
    <label>Macroprofil de référence</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>equals</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard, 23</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes (Macroprofil de référence)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <label>Partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_PAR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Poids_maximal_accepte_par_colis__c.field-meta.xml
<CustomField>
    <fullName>Poids_maximal_accepte_par_colis__c</fullName>
    <label>Poids maximal accepté par colis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_POI</valueSetName>
    </valueSet>
</CustomField>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Macroprofil_Reseau__c.object
<CustomObject>
    <description>Réseaux ajoutés par défaut au relais lors de son association avec un macroprofil</description>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Réseaux par défaut</relationshipLabel>
        <relationshipName>Reseaux_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Réseau par défaut</label>
    <nameField>
        <displayFormat>RPD-{0000}</displayFormat>
        <label>Numéro du Réseau par défaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réseaux par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_HOR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>00:01</fullName>
    </customValue>
    <customValue>
        <fullName>00:15</fullName>
    </customValue>
    <customValue>
        <fullName>00:30</fullName>
    </customValue>
    <customValue>
        <fullName>00:45</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:15</fullName>
    </customValue>
    <customValue>
        <fullName>01:30</fullName>
    </customValue>
    <customValue>
        <fullName>01:45</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:15</fullName>
    </customValue>
    <customValue>
        <fullName>02:30</fullName>
    </customValue>
    <customValue>
        <fullName>02:45</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:15</fullName>
    </customValue>
    <customValue>
        <fullName>03:30</fullName>
    </customValue>
    <customValue>
        <fullName>03:45</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:15</fullName>
    </customValue>
    <customValue>
        <fullName>04:30</fullName>
    </customValue>
    <customValue>
        <fullName>04:45</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:15</fullName>
    </customValue>
    <customValue>
        <fullName>05:30</fullName>
    </customValue>
    <customValue>
        <fullName>05:45</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:15</fullName>
    </customValue>
    <customValue>
        <fullName>06:30</fullName>
    </customValue>
    <customValue>
        <fullName>06:45</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <description>Horaires d&apos;ouverture ou de fermeture de référence.</description>
    <masterLabel>LOV_GLO_HOR</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_PAR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <customValue>
        <fullName>124</fullName>
    </customValue>
    <customValue>
        <fullName>125</fullName>
    </customValue>
    <customValue>
        <fullName>126</fullName>
    </customValue>
    <customValue>
        <fullName>134</fullName>
    </customValue>
    <customValue>
        <fullName>135</fullName>
    </customValue>
    <customValue>
        <fullName>140</fullName>
    </customValue>
    <customValue>
        <fullName>146</fullName>
    </customValue>
    <customValue>
        <fullName>177</fullName>
    </customValue>
    <customValue>
        <fullName>178</fullName>
    </customValue>
    <customValue>
        <fullName>179</fullName>
    </customValue>
    <customValue>
        <fullName>180</fullName>
    </customValue>
    <customValue>
        <fullName>181</fullName>
    </customValue>
    <customValue>
        <fullName>182</fullName>
    </customValue>
    <customValue>
        <fullName>183</fullName>
    </customValue>
    <customValue>
        <fullName>184</fullName>
    </customValue>
    <customValue>
        <fullName>185</fullName>
    </customValue>
    <customValue>
        <fullName>188</fullName>
    </customValue>
    <customValue>
        <fullName>189</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>190</fullName>
    </customValue>
    <customValue>
        <fullName>194</fullName>
    </customValue>
    <customValue>
        <fullName>195</fullName>
    </customValue>
    <customValue>
        <fullName>-2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>211</fullName>
    </customValue>
    <description>Liste des partenaires</description>
    <masterLabel>LOV_GLO_PAR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_POI.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <description>Poids maximal accepté par colis.</description>
    <masterLabel>LOV_GLO_POI</masterLabel>
</GlobalValueSet>

src/classes/AP06_MacroprofilReseau.cls
/*
* Class to propagate creation or modification of any reseau transporteur on a MP to all accounts having this MP
* @author: Lea Zoghbi
* @date: 19/12/2016
* @Test: AP06_MacroprofilReseau_TEST
*/
public class AP06_MacroprofilReseau {
    public static void InsertUpdateReseauAssocie(list<Macroprofil_Reseau__c> listMacroprofilReseau){
        
        if(PAD.canTrigger('AP04_Account')) {
            System.debug('###gho 1');
			if(!Utils_PUS.firstAllRun){
                System.debug('###gho 2');
				AP04_Account ap04Acc = new AP04_Account();
				ap04Acc.listMacroprofilReseau = listMacroprofilReseau;
				ap04Acc.fillMacroprofilReseau(); 
				System.debug('###gho 3');
			
				//get list of macroprofils Ids
				set<Id> setMacroprofilIds = new set<Id>();
				for(Macroprofil_Reseau__c mpr: listMacroprofilReseau){
                    System.debug('###gho 4');
					setMacroprofilIds.add(mpr.Macroprofil__c);
				}
				
				//get list of accounts concerned 
				list<Account> listAccounts = [ select Id, Macroprofil_de_reference__c, Type, Industry, Partenaire__c, 
											  Horaire_Ouverture_Reference__c, Horaire_Fermeture_Reference__c, Poids_maximal_accepte_par_colis__c
											  from Account 
											  where Macroprofil_de_reference__c in : setMacroprofilIds]; 
				if(listAccounts.size() > 0) {
                    System.debug('###gho 5');
					ap04Acc.manipulateMacroprofilReseau(listAccounts, false);
				}
			}            
        }
    }
}