force-app/main/default/objects/Account/fields/Identifiant_android_du_Pudo__c.field-meta.xml
<CustomField>
    <fullName>Identifiant_android_du_Pudo__c</fullName>
    <formula>IF(
!AND(INCLUDES(Type_de_device__c, &quot;PDA Windows&quot;), Type_de_device_Selected__c = 1),
Reference_internationale__c+&#39;@pickup.com&#39;&amp; 
  IF
  (
    $Organization.Id = $Label.ID_ORG, $Label.Org_ext,&#39;&#39;
  )
  ,&#39;&#39;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Identifiant androïd du Pudo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nom_Responsable_magasin__c.field-meta.xml
<CustomField>
    <fullName>Nom_Responsable_magasin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable magasin</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes (Gérant)</relationshipLabel>
    <relationshipName>Comptes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_internationale__c.field-meta.xml
<CustomField>
    <fullName>Reference_internationale__c</fullName>
    <externalId>true</externalId>
    <label>Référence internationale</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_device__c.field-meta.xml
<CustomField>
    <fullName>Type_de_device__c</fullName>
    <label>Type de device</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDA Android</fullName>
            </value>
            <value>
                <fullName>PDA Windows</fullName>
            </value>
            <value>
                <fullName>BYOD</fullName>
            </value>
            <value>
                <fullName>WEBAPP</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VFC08_GenerateLien_Test.cls
@isTest
public class VFC08_GenerateLien_Test {
    
    public static testmethod void test_sendCreationMessage() {
        
        // create MP
        Macroprofil__c mp = Utils_TestMethods.CreateMacroprofil('MP1');
        insert mp;
        // create contact
        Contact contact = Utils_TestMethods.CreateContact('Contact Contact');
        insert contact;
        
        Account account = Utils_TestMethods.CreateAccount(contact, mp,'Account1');
        account.Reference_internationale__c = 'FR1234';
        account.ShippingPostalCode = '12345';
        account.ShippingCity       = 'Paris';
        account.ShippingStreet     = '92 BLR\n ligne2\n ligne3';
        account.ShippingCountry    = 'FRANCE';
        account.Type_de_device__c = 'PDA Android';
        account.Reference_internationale__c ='FE1212';
        insert account; 
        account acc = [select id ,Identifiant_android_du_Pudo__c,Nom_Responsable_magasin__r.Email
                       ,Reference_internationale__c
                        from account 
                       where id =: account.id limit 1];
        
        
        // set the current page reference 
        PageReference pageRef = Page.VFP08_GenerateLien_RM;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(acc);
        Test.startTest();
        WS_GenerateLienAndroid_MockImpl.correctAnswer = false;
        Test.setMock(WebServiceMock.class, new WS_GenerateLienAndroid_MockImpl());
        VFC08_GenerateLien generateLien = new VFC08_GenerateLien(sc); 
        generateLien.sendEmailRM();
        pageRef = Page.VFP08_GenerateLien_CU;
        Test.setCurrentPage(pageRef);
        generateLien.sendEmailCU();
        generateLien.sendEmailTest();
        WS_GenerateLienAndroid_MockImpl.correctAnswer = true;
        generateLien.sendEmailCU();
        generateLien.goToAccountpage();
         
    }
    
}