force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_internationale__c.field-meta.xml
<CustomField>
    <fullName>Reference_internationale__c</fullName>
    <externalId>true</externalId>
    <label>Référence internationale</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/VFC01_PageRedirect_Test.cls
@isTest
public class VFC01_PageRedirect_Test {
    public static  testmethod void redirectToInternationalReference(){
        
        PageReference pageRef = Page.VFP01_SalesForceRedirect;
        Test.setCurrentPage(pageRef);
        
        // Add parameters (ref) to page URL 
        // Invalid reference number
        ApexPages.currentPage().getParameters().put('ref' , 'FR0000');
        
        // Initiate the controller with the pagereference parameters
        VFC01_PageRedirect controller = new VFC01_PageRedirect();
         
        Test.startTest();
        controller.redirect();
        System.assertEquals(System.Label.Invalid_International_Reference + ' : FR0000', controller.strErrorMessage);       
        // Send empty reference number from URL 
        ApexPages.currentPage().getParameters().put('ref' , ''); 
        controller.redirect();
        System.assertEquals(Label.Empty_Reference_Number,controller.strErrorMessage);        
		
        
        // Create account with CN5000 as International Reference
        Contact contact = Utils_TestMethods.CreateContact('Georges');
        insert contact;
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('Macroprofil 1');
        insert macroprofil;
        Account account = Utils_TestMethods.CreateAccount(contact, macroprofil, 'account1 ');
		account.Reference_internationale__c = 'FR00001';
        account.Operateur_Global__c = 'PUS_FR';
        insert account;
        
        // Pass reference number from Visual Force Page 
        controller.vfReferenceInt = 'FR00001';
        controller.redirect();
        System.assertEquals(true,controller.isValidReferenceNumber);        
        Test.stopTest();
    }
}