force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_de_rappel_planifiee__c</fullName>
        <label>Date de rappel planifiée</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planifier_un_rappel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Planifier un rappel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Traitement_interrompu__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Traitement interrompu</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Batch11_ScheduleDACases_TEST.cls
@istest
public class Batch11_ScheduleDACases_TEST {
    static testMethod void runPositiveTestCases() {
        Test.startTest();
        Integer numberOfRecords = 40;        
        //Create Contacts
        List<Contact> contactsToInsertList = Utils_TestMethods.createMultipleContacts(numberOfRecords);
        insert contactsToInsertList;
        //Create Accounts
        List<Account> accountsToInsertList = Utils_TestMethods.createMultipleDAIntAccounts(contactsToInsertList.size(), contactsToInsertList);
        insert accountsToInsertList;
        //Create Macroprofils
        Macroprofil__c macroProfTest = Utils_TestMethods.createMacroprofil('Test Macro');
        insert macroProfTest;
        //Create Cases DA
        List<Case> casesToInsertList = Utils_TestMethods.createMultipleDAIntCases(accountsToInsertList.size(), macroProfTest, accountsToInsertList);
        system.debug('Batch11_ScheduleDACases_TEST casesToInsertList ' + casesToInsertList);
        insert casesToInsertList;
        //Update Cases DA Date_de_rappel_planifiee__c
        List<Case> casesToUpdateList = updateMultipleDAIntCases(casesToInsertList.size(), casesToInsertList);
        update casesToUpdateList;
        Set<ID> idCasesSet = new Set<ID>();
        for(Case caseUpdated: casesToUpdateList)
        {
            idCasesSet.add(caseUpdated.id);
        }
        //Execute Batch11_ScheduleDACases
        Database.executeBatch(new Batch11_ScheduleDACases(), 200);
        //Execute Batch11_ScheduleDACases for one record
        Database.executeBatch(new Batch11_ScheduleDACases(casesToUpdateList[0].id), 200);
        Test.stopTest();
        List<Case> caseDAAssertList = [Select id, Traitement_interrompu__c, Planifier_un_rappel__c, Date_de_rappel_planifiee__c
                                   From Case
                                   Where id in :idCasesSet];
        system.debug('Schedule_Batch11_ScheduleDACases_TEST caseDAAssertList ' + caseDAAssertList);
        system.assertEquals(caseDAAssertList.size(), numberOfRecords);
        system.assertEquals(caseDAAssertList[0].Traitement_interrompu__c, false);
        system.assertEquals(caseDAAssertList[0].Planifier_un_rappel__c, false);
        system.assertEquals(caseDAAssertList[0].Date_de_rappel_planifiee__c, null);
    }
    public static List<Case> updateMultipleDAIntCases(Integer numberOfCases, List<Case> casesInsertedList)
    {
        List<Case> caseListToUpdate = new List<Case>();
        for(Case caseToUpdate : casesInsertedList)
        {
            caseToUpdate.Traitement_interrompu__c= true;
            caseToUpdate.Planifier_un_rappel__c= true;
            caseToUpdate.Date_de_rappel_planifiee__c = system.today();
            caseListToUpdate.add(caseToUpdate);
        }
        return caseListToUpdate;
    }
}