force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_conge_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_conge_a_venir__c</fullName>
    <label>Tech date de début congé à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_conge_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_conge_en_cours__c</fullName>
    <label>Tech date de début congé en cours</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_disp_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_disp_a_venir__c</fullName>
    <label>Tech date de début disp à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_indisp_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_indisp_en_cours__c</fullName>
    <label>Tech date de début indisp en cours</label>
    <type>Date</type>
</CustomField>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <recordTypes>
        <fullName>Conge</fullName>
        <active>true</active>
        <description>Permet de créer une période de congés.</description>
        <label>Congé</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassApex__c</fullName>
        <label>BypassApex</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP01_Account</fullName>
                </value>
                <value>
                    <fullName>AP05_Account</fullName>
                </value>
                <value>
                    <fullName>AP06_MacroprofilReseau</fullName>
                </value>
                <value>
                    <fullName>Utils_PUS</fullName>
                </value>
                <value>
                    <fullName>AP04_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP02_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_CaseComment</fullName>
                </value>
                <value>
                    <fullName>AP08_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_CompteRenduRempli</fullName>
                </value>
                <value>
                    <fullName>AP01_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_Task</fullName>
                </value>
                <value>
                    <fullName>AP02_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP02_MacroprofilTransporteur</fullName>
                </value>
                <value>
                    <fullName>AP02_Task</fullName>
                </value>
                <value>
                    <fullName>AP03_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP03_MacroprofilService</fullName>
                </value>
                <value>
                    <fullName>AP03_ReseauAssocie</fullName>
                </value>
                <value>
                    <fullName>AP03_Task</fullName>
                </value>
                <value>
                    <fullName>AP04_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP05_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Account</fullName>
                </value>
                <value>
                    <fullName>AP08_Attachement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BypassProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassWorkflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch06_AccountCongeIndispo_Test.cls
@isTest
public class Batch06_AccountCongeIndispo_Test {
    
    private static Id congeRTypeId = Label.CongeRT_15;
    private static Id indispoStandardRTypeId = Label.IndispoStandardRT_15;
    private static Id indispoConsigneRTypeId = Label.IndispoConsigneRT_15;
    private static Id dispoRTypeId = Label.DispoRT_15;
    
    static testmethod void testBatch() {
        User currentUser = [Select id , name , BypassProcessBuilder__c, BypassWorkflow__c, BypassApex__c, BypassValidationRule__c
                           from User
                           where id =: UserInfo.getUserId()];
        currentUser.BypassProcessBuilder__c = true;
        currentUser.BypassWorkflow__c = true;
        currentUser.BypassValidationRule__c = true;
        currentUser.BypassApex__c = 'AP02_Conge_Indispo;AP06_Conge_Indispo';
        update currentUser;
       
        // Create Contact 
        Contact contact = Utils_TestMethods.CreateContact('contact');
        insert contact;
        
        // Create Macroprofil
        Macroprofil__c mp = Utils_TestMethods.CreateMacroprofil('mp');
        insert mp;
        
        // Create Account 
        Account account = Utils_TestMethods.CreateAccount(contact, mp,'Account');
        insert account;
        
        // Create Conge en cours
        Conge_Indispo__c conge1 = Utils_TestMethods.CreateConge_Indispo(congeRTypeId, account.Id, Date.today() , Date.today().addDays(10));
        insert conge1;
        
        // Create Conge a venir before the old one
        Conge_Indispo__c conge5 = Utils_TestMethods.CreateConge_Indispo(congeRTypeId, account.Id, Date.today().addDays(17) , Date.today().addDays(17));
        insert conge5;
        

        // Create Account 2 with no conges
        Account account2 = Utils_TestMethods.CreateAccount(contact, mp, 'Account 2');
        account2.Tech_date_debut_conge_en_cours__c = Date.Today();
        account2.Tech_date_debut_indisp_en_cours__c  = Date.today();
        account2.Tech_date_debut_conge_a_venir__c = Date.today().addDays(10);
        account2.Tech_date_debut_disp_a_venir__c = Date.today().addDays(11);
        insert account2;
      
        
        // Create Account3 with conge that became passé
        Account account3 = Utils_TestMethods.CreateAccount(contact, mp, 'Account 3');
        account3.Tech_date_debut_conge_en_cours__c = Date.Today();
        account3.Tech_date_debut_indisp_en_cours__c  = Date.today();
        account3.Tech_date_debut_conge_a_venir__c = Date.today().addDays(10);
        account3.Tech_date_debut_disp_a_venir__c = Date.today().addDays(11);
        insert account3;
        
       	Conge_Indispo__c conge6 = Utils_TestMethods.CreateConge_Indispo(congeRTypeId, account3.Id, Date.today() , Date.today().addDays(10));
        insert conge6;
     
      
         Test.startTest();
        Batch06_AccountCongeIndispo batchAccount = new Batch06_AccountCongeIndispo();
        Database.executeBatch(batchAccount,50); 
        Test.stopTest();
        
    }
}