force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Macroprofil de création.</inlineHelpText>
    <label>Macroprofil de référence</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>equals</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard, 23</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes (Macroprofil de référence)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Macroprofil_Reseau__c.object
<CustomObject>
    <description>Réseaux ajoutés par défaut au relais lors de son association avec un macroprofil</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Réseaux par défaut</relationshipLabel>
        <relationshipName>Reseaux_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reseau__c</fullName>
        <label>Réseau</label>
        <referenceTo>Reseau__c</referenceTo>
        <relationshipLabel>Macroprofils associés</relationshipLabel>
        <relationshipName>Reseaux_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Réseau par défaut</label>
    <nameField>
        <displayFormat>RPD-{0000}</displayFormat>
        <label>Numéro du Réseau par défaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réseaux par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil_Service__c.object
<CustomObject>
    <description>Services ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Services par défaut</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Macroprofil liés à ce service</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service par défaut</label>
    <nameField>
        <displayFormat>SPD-{0000}</displayFormat>
        <label>Numéro du Service par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil_Transporteur__c.object
<CustomObject>
    <description>Transporteurs ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Transporteur par defaut</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <label>Transporteur</label>
        <referenceTo>Transporteur__c</referenceTo>
        <relationshipLabel>Macroprofils liés à ce transporteur</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transporteur par defaut</label>
    <nameField>
        <displayFormat>TPD-{0000}</displayFormat>
        <label>Numéro du Transporteur par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteur par defaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reseau__c.object
<CustomObject>
    <description>Un réseau est un ensemble de caractéristiques communes à des PUDO parmi : service, opérateur, pays, opérateur...</description>
    <label>Réseau</label>
    <nameField>
        <label>Nom du Réseau</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réseaux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Reseau_Service__c.object
<CustomObject>
    <description>Objet de jonction (n to n) entre les réseaux et les services.</description>
    <fields>
        <fullName>Reseau__c</fullName>
        <label>Réseau</label>
        <referenceTo>Reseau__c</referenceTo>
        <relationshipLabel>Services associés à ce réseau</relationshipLabel>
        <relationshipName>Reseau_Service</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Réseaux auquels ce service est associé</relationshipLabel>
        <relationshipName>Reseau_Service</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Association Réseau Service</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Numéro de Réseau Service</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations Réseaux Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reseau_Transporteur__c.object
<CustomObject>
    <description>Objet de jonction (n to n) entre les réseaux et les transporteurs.</description>
    <fields>
        <fullName>Reseau__c</fullName>
        <label>Réseau</label>
        <referenceTo>Reseau__c</referenceTo>
        <relationshipLabel>Transporteurs associés à ce réseau</relationshipLabel>
        <relationshipName>Reseau_Transporteur</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <label>Transporteur</label>
        <referenceTo>Transporteur__c</referenceTo>
        <relationshipLabel>Réseaux auquels ce transporteur est associé</relationshipLabel>
        <relationshipName>Reseau_Transporteur</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Association Réseau Transporteur</label>
    <nameField>
        <displayFormat>RTR-{0000}</displayFormat>
        <label>Numéro de Réseau Transporteur</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associations Réseaux Transporteurs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>Un ensemble de prestations standards proposés aux destinataires par un relais.</description>
    <label>Service</label>
    <nameField>
        <label>Nom du Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Transporteur__c.object
<CustomObject>
    <description>Transporteur pouvant livrer un colis dans le Pudo.</description>
    <label>Transporteur</label>
    <nameField>
        <label>Nom du Transporteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteurs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AP06_MacroprofilReseau_Test.cls
/*
* @author: Lea Zoghbi
* @date: 05/01/2017
*/
@isTest
private class AP06_MacroprofilReseau_Test {
    static testMethod void InsertUpdateReseauAssocieTest() {
        
        //Create Macroprofil
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('Macroprofil');
        Macroprofil__c mp2 = Utils_TestMethods.CreateMacroprofil('mp2');
        insert new list<Macroprofil__c> {macroprofil, mp2};
         
        //Create Service
        Service__c service = Utils_TestMethods.CreateService('Service');
        insert service;
       
        //Create Transporteur
        Transporteur__c transporteur = Utils_TestMethods.CreateTransporteur('Transporteur');
        insert transporteur;
      
        //Create Reseau
        Reseau__c reseau = Utils_TestMethods.CreateReseau('Reseau');
        Reseau__c res_ft = Utils_TestMethods.CreateReseau('res_ft');
        insert new list<Reseau__c>{reseau, res_ft};
 
        //Create Macroprofil Service
        Macroprofil_Service__c macroService = Utils_TestMethods.CreateMacroprofilService(macroprofil, service);
        macroService.Active__c = true;
        macroService.Modifiable__c = true;
        Macroprofil_Service__c macroServiceMP2 = Utils_TestMethods.CreateMacroprofilService(mp2, service);
        macroServiceMP2.Active__c = true;
        macroServiceMP2.Modifiable__c = true;
        insert new list<Macroprofil_Service__c> {macroService, macroServiceMP2};
          
        //Create Macroprofil Transporteur
        Macroprofil_Transporteur__c macroTransporteur = Utils_TestMethods.CreateMacroprofilTransporteur(macroprofil, transporteur);
        macroTransporteur.Active__c = true;
        macroTransporteur.Modifiable__c = true;
        insert macroTransporteur;
        
        //Create Macroprofil Reseau
        Macroprofil_Reseau__c macroReseau = Utils_TestMethods.CreateMacroprofilReseau(macroprofil.Id, reseau.Id);
        
        insert macroReseau;
        
        //create Reseau Service
        Reseau_Service__c reseauService = Utils_TestMethods.CreateReseauService(reseau.Id, service.Id);
        insert reseauService;
         
        //create Reseau Transporteur
        Reseau_Transporteur__c reseauTransporteur = Utils_TestMethods.CreateReseauTransporteur(reseau.Id, transporteur.Id);
        insert reseauTransporteur;
        
        //create account record
        Account pudo = Utils_TestMethods.CreateAccount(null, macroprofil, 'PUDO 1');
        pudo.Macroprofil_de_reference__c = macroprofil.Id;
        insert pudo;
         
        test.startTest();
        Macroprofil_Reseau__c macroReseau_FT = Utils_TestMethods.CreateMacroprofilReseau(macroprofil.Id, res_ft.Id);
        insert macroReseau_FT;
        List<Macroprofil_Reseau__c> listMacroprofilReseau = new List<Macroprofil_Reseau__c>{macroReseau_FT}; 
        Utils_PUS.firstAllRun = false;
        AP06_MacroprofilReseau.InsertUpdateReseauAssocie(listMacroprofilReseau);
        
        
        macroReseau_FT.Active__c = false;
        update macroReseau_FT;
        
        test.stopTest();
    }
}