force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <label>Partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_PAR</valueSetName>
    </valueSet>
</CustomField>

src/objects/Association_PUDO_Macroprofil__mdt.object
<CustomObject>
    <description>Cet objet contient les pays et types de point associés à chaque Macroprofil d&apos;un PUDO</description>
    <fields>
        <fullName>Id_du_Macroprofil__c</fullName>
        <label>Id du Macroprofil</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partenaire__c</fullName>
        <label>Partenaire</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <label>Pays</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_de_point__c</fullName>
        <label>Type de point</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Association PUDO Macroprofil</label>
    <pluralLabel>Association PUDO Macroprofils</pluralLabel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Partenaire__c</fullName>
        <label>Partenaire</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_de_point__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_PAR</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_de_point__c</fullName>
        <label>Type de point</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_TYP</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_PAR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <customValue>
        <fullName>124</fullName>
    </customValue>
    <customValue>
        <fullName>125</fullName>
    </customValue>
    <customValue>
        <fullName>126</fullName>
    </customValue>
    <customValue>
        <fullName>134</fullName>
    </customValue>
    <customValue>
        <fullName>135</fullName>
    </customValue>
    <customValue>
        <fullName>140</fullName>
    </customValue>
    <customValue>
        <fullName>146</fullName>
    </customValue>
    <customValue>
        <fullName>177</fullName>
    </customValue>
    <customValue>
        <fullName>178</fullName>
    </customValue>
    <customValue>
        <fullName>179</fullName>
    </customValue>
    <customValue>
        <fullName>180</fullName>
    </customValue>
    <customValue>
        <fullName>181</fullName>
    </customValue>
    <customValue>
        <fullName>182</fullName>
    </customValue>
    <customValue>
        <fullName>183</fullName>
    </customValue>
    <customValue>
        <fullName>184</fullName>
    </customValue>
    <customValue>
        <fullName>185</fullName>
    </customValue>
    <customValue>
        <fullName>188</fullName>
    </customValue>
    <customValue>
        <fullName>189</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>190</fullName>
    </customValue>
    <customValue>
        <fullName>194</fullName>
    </customValue>
    <customValue>
        <fullName>195</fullName>
    </customValue>
    <customValue>
        <fullName>-2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>211</fullName>
    </customValue>
    <description>Liste des partenaires</description>
    <masterLabel>LOV_GLO_PAR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_TYP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>-3</fullName>
    </customValue>
    <customValue>
        <fullName>Pudo non suivi par le CO</fullName>
        <isActive>false</isActive>
        <label>Pudo non suivi par le CO</label>
    </customValue>
    <customValue>
        <fullName>Agences Coliposte</fullName>
        <isActive>false</isActive>
        <label>Agences Coliposte</label>
    </customValue>
    <customValue>
        <fullName>Bureaux de Postes</fullName>
        <isActive>false</isActive>
        <label>Bureaux de Postes</label>
    </customValue>
    <customValue>
        <fullName>Cytissimo</fullName>
        <isActive>false</isActive>
        <label>Cytissimo</label>
    </customValue>
    <customValue>
        <fullName>Centre Distribution Coliposte</fullName>
        <isActive>false</isActive>
        <label>Centre Distribution Coliposte</label>
    </customValue>
    <description>Type de point utilisé sur réseau et Prospect. Doit correspondre au champ standard type (Compte).</description>
    <masterLabel>LOV_GLO_TYP</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP11_AssociationPUDOMacroprofil.cls
/*
* Author: John Boutros
* Modified By: -
* Date : 04/01/2018
* Description: Renseigner automatiquement le champs Macroprofil_actuel__c lors de la creation d'un compte (before insert)
* Test classe: AP11_AssociationPUDOMacroprofil_TEST
Coverage : 100%
*/
public class AP11_AssociationPUDOMacroprofil {
    public static void associationPUDOMacroprofil(List<Account> newAccountList, map<id, Account> oldAccountMap)
    {
        set<id> setAccountId = new set<id>();
        for(account acc: newAccountList){
            if(acc.id != null){
                setAccountid.add(acc.id);}
        }
        system.debug('AP11_AssociationPUDOMacroprofil setAccountId '+setAccountId);
        String test = '';
        list<lead> listLeadConverted = new list<lead>();
        if(!setAccountId.isEmpty())
        {
            system.debug('AP11_AssociationPUDOMacroprofil setAccountId before if '+setAccountId);
            listLeadConverted = [select id,ConvertedAccountId,IsConverted,Type_de_point__c 
                                 from lead 
                                 where IsConverted =true and ConvertedAccountId in :setAccountId];        
        }
        
        
        map<id,lead> mapLeadAccount = new map<id,lead>();
        system.debug('listLeadConverted '+listLeadConverted);
        for(lead lead : listLeadConverted){
            mapLeadAccount.put(lead.ConvertedAccountId, lead); 
        }
        
        List<Account> accountsToUpdate = new List<Account>();
        system.debug('newAccountList '+newAccountList);
        for(Account accountTocheck: newAccountList){
            if(accountTocheck.Macroprofil_actuel__c == null){
                if(mapLeadAccount.containsKey(accountTocheck.Id)){
                    system.debug('mapLeadAccount.get(accountTocheck.id).Type_de_point__c '+mapLeadAccount.get(accountTocheck.id).Type_de_point__c);
                    if(mapLeadAccount.get(accountTocheck.id).Type_de_point__c != null){
                        accountTocheck.Type = mapLeadAccount.get(accountTocheck.id).Type_de_point__c;   
                    }
                }               
                accountsToUpdate.add(accountTocheck);   
            }
            else if (oldAccountMap!=null &&
                     (!(oldAccountMap.containsKey(accountTocheck.Id)) 
                      || accountTocheck.ShippingCountry != oldAccountMap.get(accountTocheck.Id).ShippingCountry 
                      || accountTocheck.Type != oldAccountMap.get(accountTocheck.Id).Type
                     )){
                         accountsToUpdate.add(accountTocheck);
                     }
        }
        system.debug('newAccountList '+newAccountList);
        //Liste des valeurs du custom setting AssociationPUDOMacroprofil__c
        List<Association_PUDO_Macroprofil__mdt> metadatasAssocPudoMacro = (List<Association_PUDO_Macroprofil__mdt>) new AssociationPUDOMacroprofil().getCustomMetadataRecords(
            'Select id, Pays__c, Partenaire__c, Type_de_point__c, Id_du_Macroprofil__c From Association_PUDO_Macroprofil__mdt'
        );
        Map<String, ID> metadataAssocPudoMacroMap = new Map<String, ID>();
        String key = '';
        String key1 = '';
        for(Association_PUDO_Macroprofil__mdt metadataAssocPudoMacro : metadatasAssocPudoMacro ){
            key = metadataAssocPudoMacro.Pays__c+'_'+ metadataAssocPudoMacro.Type_de_point__c;
            key1 = metadataAssocPudoMacro.Partenaire__c;
            if(key1 != null && !metadataAssocPudoMacroMap.containsKey(key1)){
                metadataAssocPudoMacroMap.put(key1, metadataAssocPudoMacro.Id_du_Macroprofil__c);
            }
            else if(!metadataAssocPudoMacroMap.containsKey(key)){
                metadataAssocPudoMacroMap.put(key, metadataAssocPudoMacro.Id_du_Macroprofil__c);
            }
        }
        for(Account newAccount : accountsToUpdate)
        {
            if(!LABEL.RT_France_Compte.contains(newAccount.recordTypeID) )
            {  
                key = newAccount.shippingCountry+'_'+newAccount.Type;
                system.debug('metadataAssocPudoMacroMap.get(newAccount.Partenaire__c) '+metadataAssocPudoMacroMap.get(newAccount.Partenaire__c));
                system.debug('metadataAssocPudoMacroMap.get(key) '+metadataAssocPudoMacroMap.get(key));
                if(metadataAssocPudoMacroMap.containsKey(newAccount.Partenaire__c))
                {
                    newAccount.Macroprofil_actuel__c = metadataAssocPudoMacroMap.get(newAccount.Partenaire__c);
                }
                else if(metadataAssocPudoMacroMap.containsKey(key))
                {
                    newAccount.Macroprofil_actuel__c = metadataAssocPudoMacroMap.get(key);
                }
            }
        }
    }
}