force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

src/objects/Anomalie__c.object
<CustomObject>
    <description>Objet technique permettant de stocker les anomalies associées au PUDO, en particulier les anomalies provenant de la télécollecte.</description>
    <fields>
        <fullName>PUDO__c</fullName>
        <label>PUDO</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Anomalies_de_Telecollecte</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SyncPudo</fullName>
                </value>
                <value>
                    <fullName>NoDevice</fullName>
                </value>
                <value>
                    <fullName>TooManyDevices</fullName>
                </value>
                <value>
                    <fullName>NoDecommissioned</fullName>
                </value>
                <value>
                    <fullName>Association à tort Etat 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Anomalie</label>
    <nameField>
        <label>Numéro de l&apos;anomalie</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Anomalie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Anomalie</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Anomalie__c.PUDO__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Anomalie__c</referenceTo>
        <relationshipLabel>Requêtes</relationshipLabel>
        <relationshipName>Requ_tes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/Batch09_CaseType_AnomSync_Test.cls
@isTest
public class Batch09_CaseType_AnomSync_Test {
    
    public static testmethod void  Btch09Test(){
        
        //Create Contact
        Contact c = Utils_TestMethods.CreateContact('c1');
        Insert c;
        
        //Create Macroprofil
        Macroprofil__c m1 = Utils_TestMethods.CreateMacroprofil('m1');
        insert m1;
        
        //Create Account
        Map<String, Id> mapRecordTypeDevNameToId = new Map<String, Id>();
        for(RecordType rt : [SELECT Id, DeveloperName
                             FROM RecordType
                             WHERE DeveloperName='PUS_FR_Pickup_Contact' or  DeveloperName='PUS_FR_Point_non_Suivi_par_le_CO' OR DeveloperName = 'PUS_FR_Consigne' OR DeveloperName = 'PUS_FR_Point_non_Suivi_par_le_CO' OR DeveloperName = 'PUS_FR_PUDO_Suivi_CO'])
        {
            mapRecordTypeDevNameToId.put(rt.DeveloperName, rt.Id);
        }
        
        Id PUS_FR_Pickup_Contact = mapRecordTypeDevNameToId.get('PUS_FR_Pickup_Contact');
       
        Account newaccount = Utils_TestMethods.CreateAccount(c,m1, 'a2');
		newaccount.Operateur_Global__c = 'PUS_FR';
        insert newaccount;

        Test.startTest();
        Anomalie__c newa=new Anomalie__c();
        newa.Name='newatest';
        newa.PUDO__c=newaccount.id;
        newa.Statut__c='0';
        newa.Type__c='SyncPudo';
        insert newa;

        Case newcas = Utils_TestMethods.createRequete('1', m1.id);
        newcas.AccountId = newaccount.Id;
        newcas.Anomalie__c = newa.id;
        //cas.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PUS_FR_Indisponibilité PB PDA Synchro').getRecordTypeId();
        insert newcas;
        
        Batch09_CaseType_AnomSync batchAnomSync = new Batch09_CaseType_AnomSync();
        Database.executeBatch(batchAnomSync); 
        test.stopTest();
        List<Case> CaseList = [select id,OwnerId from Case where  id =: newcas.id];
        for(Case currentcas:CaseList)
        {
          system.assertEquals(Label.FileGestMat_ID_FR, currentcas.OwnerId);
        }
    }
}