force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/N_TVA__c.field-meta.xml
<CustomField>
    <fullName>N_TVA__c</fullName>
    <label>N° de TVA</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>Un ensemble de prestations standards proposés aux destinataires par un relais.</description>
    <fields>
        <fullName>Nom_du_service_translated__c</fullName>
        <label>Nom du service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_SER</valueSetName>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Nom du Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Associe__c.object
<CustomObject>
    <description>Ensemble de services proposés par le Pudo selon le macro-profil affecté. Des services seront pilotables par l’action d’activation ou de désactivation.</description>
    <fields>
        <fullName>Compte__c</fullName>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services associés</relationshipLabel>
        <relationshipName>Services_associes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <formula>Compte__r.Macroprofil_actuel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Macroprofil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Points relais pouvant activer le service</relationshipLabel>
        <relationshipName>Services_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service associé</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Numéro du Service associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_SER.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Chronofresh</fullName>
    </customValue>
    <customValue>
        <fullName>Contre remboursement</fullName>
        <label>Contre-remboursement</label>
    </customValue>
    <customValue>
        <fullName>Contre remboursement_CASH</fullName>
        <label>Contre-remboursement CASH</label>
    </customValue>
    <customValue>
        <fullName>Contre remboursement_CB</fullName>
        <label>Contre-remboursement CB</label>
    </customValue>
    <customValue>
        <fullName>CtoC en sacoches bleues scellées</fullName>
    </customValue>
    <customValue>
        <fullName>Dépôt en sacoche bleue</fullName>
    </customValue>
    <customValue>
        <fullName>Dépôt express</fullName>
    </customValue>
    <customValue>
        <fullName>Dépôt payant</fullName>
    </customValue>
    <customValue>
        <fullName>Dépôt simple</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Parcel Label</fullName>
    </customValue>
    <customValue>
        <fullName>Instance</fullName>
    </customValue>
    <customValue>
        <fullName>LA POSTE RELAIS (LPR)</fullName>
    </customValue>
    <customValue>
        <fullName>PickupPassCAB2D</fullName>
        <label>PickupPass CAB2D</label>
    </customValue>
    <customValue>
        <fullName>Printer activation</fullName>
    </customValue>
    <customValue>
        <fullName>Redirection</fullName>
    </customValue>
    <customValue>
        <fullName>Relivraison STUART</fullName>
    </customValue>
    <customValue>
        <fullName>Retour</fullName>
    </customValue>
    <customValue>
        <fullName>Retrait</fullName>
    </customValue>
    <customValue>
        <fullName>Retrait de colis prepares</fullName>
        <label>Retrait de colis préparé</label>
    </customValue>
    <customValue>
        <fullName>Reverse swap desyncho en sacoches grises scellées</fullName>
        <label>Reverse swap desynchro en sacoches grises scellées</label>
    </customValue>
    <customValue>
        <fullName>ROD</fullName>
    </customValue>
    <customValue>
        <fullName>Shopident</fullName>
        <label>Shop Ident</label>
    </customValue>
    <customValue>
        <fullName>Swap Colis avec contrôle de contenu</fullName>
    </customValue>
    <customValue>
        <fullName>Swap Colis contre colis</fullName>
    </customValue>
    <customValue>
        <fullName>Transporteur multiple - DPD FR</fullName>
    </customValue>
    <customValue>
        <fullName>CARTE_FIDELITE</fullName>
        <label>Carte fidélité</label>
    </customValue>
    <description>Cette valeur de liste globale contient tous les services de la plate-forme Pickup.</description>
    <masterLabel>LOV_GLO_SER</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/AP01_ServiceAssocie_Test.cls
/* Class that test the functionality of AP01_ServiceAssocie*/

@isTest
public class AP01_ServiceAssocie_Test {
    
    public static testmethod void UpdateNomServiceTest (){
        
        List<Association_Record_Type_et_pays__mdt> associationRTPaysList = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c
                                                                            FROM Association_Record_Type_et_pays__mdt];
        
        
        map<string, Association_Record_Type_et_pays__mdt> associationRTPays = new map<string, Association_Record_Type_et_pays__mdt>();
        for(Association_Record_Type_et_pays__mdt associationRT : associationRTPaysList){
            associationRTPays.put(associationRT.MasterLabel, associationRT);}
        
        service__c testService1 = Utils_TestMethods.CreateService('test service 1');
        testService1.Nom_du_service_translated__c= 'Chronofresh';
        
        service__c testService2 = Utils_TestMethods.CreateService('test service 2');
        testService2.Nom_du_service_translated__c= 'Contre remboursement_CASH';
        insert new list<service__c> {testService1,testService2};
            
        Contact testContact = Utils_TestMethods.CreateContact('test contact');
        insert testContact;
        
        Macroprofil__c testMacrorofil = Utils_TestMethods.CreateMacroprofil('test Macrorofil');
        insert testMacrorofil;
        
        account testAccount = Utils_TestMethods.CreateAccount(testContact,testMacrorofil,'test account');
        testAccount.RecordTypeId = associationRTPays.get('Belgium').ID_PUDO_Non_Suivi__c;
        testAccount.N_TVA__c = '123';
        testAccount.Type = '20';
        testAccount.BillingCountry ='Belgium';
        testAccount.ShippingCountry ='Belgium';
        testAccount.BillingCountryCode = 'BE';
        testAccount.ShippingCountryCode ='BE';
        testAccount.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        testAccount.Operateur_Global__c = 'DPD_BNL';
        testAccount.BillingPostalCode ='1234';
        testAccount.ShippingPostalCode = '1234';
        testAccount.Long_Lat_adresse_de_livraison__Latitude__s=62;
        insert testAccount;
        
        service_associe__c testServiceAssociee = new service_associe__c();
        testServiceAssociee.Service__c = testService1.id;
        testServiceAssociee.Compte__c = testAccount.id;
        testServiceAssociee.Modifiable__c = true;
        insert testServiceAssociee;
        
        testService1.Nom_du_service_translated__c= 'Contre remboursement';
        update testService1;
        
        testServiceAssociee.Service__c  = testService2.id;
        update testServiceAssociee;
    }
}