force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_conge_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_conge_en_cours__c</fullName>
    <label>Tech date de début congé en cours</label>
    <type>Date</type>
</CustomField>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <recordTypes>
        <fullName>Conge</fullName>
        <active>true</active>
        <description>Permet de créer une période de congés.</description>
        <label>Congé</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch01_Account_Test.cls
@isTest
public class Batch01_Account_Test {
    private static Id congeRTypeId = Label.CongeRT_15;
    private static Id indispoStandardRTypeId = Label.IndispoStandardRT_15;
    private static Id indispoConsigneRTypeId = Label.IndispoConsigneRT_15;
    
    static testmethod void testBatch() {
 
        //create conge indispo that meets the query crieterias
        
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('M1');
        insert macroprofil;
        Contact contact = Utils_TestMethods.CreateContact('Contact1');
        insert contact;
        Account account = Utils_TestMethods.CreateAccount(contact, macroprofil, 'Account 1');
        insert account;
        Conge_Indispo__c congeIndispo = Utils_TestMethods.CreateConge_Indispo(congeRTypeId, account.Id , Date.today() , Date.today().addDays(10));
        insert congeIndispo;
        
        Test.startTest();
        Batch01_Account batchAccount = new Batch01_Account();
        Database.executeBatch(batchAccount);
        Test.stopTest();
        
        account = [SELECT Tech_date_debut_conge_en_cours__c
                   FROM Account 
                   Where Id =: account.Id
                  ]; 
        System.assertEquals( account.Tech_date_debut_conge_en_cours__c , Date.today());
        
    }
}