force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Macroprofil de création.</inlineHelpText>
    <label>Macroprofil de référence</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>equals</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard, 23</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes (Macroprofil de référence)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Macroprofil_Transporteur__c.object
<CustomObject>
    <description>Transporteurs ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Transporteur par defaut</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Techatraiter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Techatraiter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <label>Transporteur</label>
        <referenceTo>Transporteur__c</referenceTo>
        <relationshipLabel>Macroprofils liés à ce transporteur</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transporteur par defaut</label>
    <nameField>
        <displayFormat>TPD-{0000}</displayFormat>
        <label>Numéro du Transporteur par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteur par defaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transporteur__c.object
<CustomObject>
    <description>Transporteur pouvant livrer un colis dans le Pudo.</description>
    <label>Transporteur</label>
    <nameField>
        <label>Nom du Transporteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteurs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Batch05_MP_Transporteur_Test.cls
@isTest
public class Batch05_MP_Transporteur_Test {
    
    
    static testMethod void testBatch() {
        // create Macroprofil
        Macroprofil__c mp1 = Utils_TestMethods.CreateMacroprofil('MP1');
        insert mp1;   
        
        // Create transporteur
        Transporteur__c trans1 = Utils_TestMethods.CreateTransporteur('Transporteur1');
        insert trans1;
        
        // Create MP-Transporteur
        Macroprofil_Transporteur__c mptrans = Utils_TestMethods.CreateMacroprofilTransporteur(mp1, trans1);
        mptrans.Techatraiter__c = true;
        insert mptrans;
        
        // create contact
        Contact contact = Utils_TestMethods.CreateContact('Contact 1');
        insert contact;
        
        // Create Account
        Account acc = Utils_TestMethods.CreateAccount(contact, mp1, 'Account 1');
        acc.Macroprofil_de_reference__c = mp1.Id;
        insert acc;
        
        Test.startTest();
		Id batchJobId = Database.executeBatch(new Batch05_MP_Transporteur(), 200);         
        Test.stopTest();
    }
}