force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <fields>
        <fullName>Operateur__c</fullName>
        <description>Ce champ permet de gérer la visibilité des données de macropprofil entre les opérateurs.</description>
        <label>Opérateur</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_OPE</valueSetName>
        </valueSet>
    </fields>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Macroprofil_Service__c.object
<CustomObject>
    <description>Services ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Services par défaut</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Macroprofil liés à ce service</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service par défaut</label>
    <nameField>
        <displayFormat>SPD-{0000}</displayFormat>
        <label>Numéro du Service par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil_Transporteur__c.object
<CustomObject>
    <description>Transporteurs ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Transporteur par defaut</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <label>Transporteur</label>
        <referenceTo>Transporteur__c</referenceTo>
        <relationshipLabel>Macroprofils liés à ce transporteur</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transporteur par defaut</label>
    <nameField>
        <displayFormat>TPD-{0000}</displayFormat>
        <label>Numéro du Transporteur par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteur par defaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>Un ensemble de prestations standards proposés aux destinataires par un relais.</description>
    <fields>
        <fullName>Operateur__c</fullName>
        <label>Opérateur</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_OPE</valueSetName>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Nom du Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Transporteur__c.object
<CustomObject>
    <description>Transporteur pouvant livrer un colis dans le Pudo.</description>
    <fields>
        <fullName>Operateur__c</fullName>
        <label>Opérateur</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_OPE</valueSetName>
        </valueSet>
    </fields>
    <label>Transporteur</label>
    <nameField>
        <label>Nom du Transporteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteurs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Operateur__c</fullName>
        <description>Ce champ permet de gérer la visibilité des utilisateurs entre les opérateurs.</description>
        <label>Opérateur</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_OPE</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP01_Task_Test.cls
/* Author 		: Yorgo Nabhan
* Date 			: 2017-9-28
* Description 	: This Class is made to test the TacheBeforeDelete Trigger and Its Ap01_Task Class 
*/


@istest
public without sharing class AP01_Task_Test {
    
    @testsetup
    public static void createuser()
    {
        //Create User
        User newUser = Utils_TestMethods.createUser('Yorgo', 'Nabhan', 'yorgo.nabhan@ei-technologies.com', 'yorgo.nabhan@ei-technologies.com');
        newUser.FirstName = 'Yorgo';
        newUser.LastName  = 'Nabhan';
        newUser.LocaleSidKey = 'fr_FR';
        newUser.Username = 'yorgo.nabhan@ei-technologie.com';
        newUser.Email = 'yorgo.nabhan@ei-technologie.com';
        newUser.Alias = 'ynab';
        newUser.CommunityNickname = 'nabhan.yorgo';
        newUser.EmailEncodingKey = 'ISO-8859-1';
        newUser.ProfileId = '00e580000015APr';
        
        newUser.LanguageLocaleKey = 'fr';
        newUser.Operateur__c = 'PUS_FR';
        newUser.TimeZoneSidKey = 'Europe/Paris';
        newUser.UserRoleId='00E58000000c5amEAA';
        newUser.IsActive = true;
        //NewUser.UserRoleId=r.Id;
        insert newUser;
    }
    
    static testMethod void testService()
    {        
        User NewUser=[SELECT id, IsActive FROM USER Where UserName = 'yorgo.nabhan@ei-technologie.com' LIMIT 1];
        
        //Create Contact
        Contact c = Utils_TestMethods.CreateContact('c1');
        Insert c;
        
        //Create Macroprofil
        Macroprofil__c m1 = Utils_TestMethods.CreateMacroprofil('m1');
        Macroprofil__c m2 = Utils_TestMethods.CreateMacroprofil('m2');
        Macroprofil__c m3 = Utils_TestMethods.CreateMacroprofil('m3');
        insert new List<Macroprofil__c>{m1, m2, m3};
            
            
            //Create Services
            Service__c s1 = Utils_TestMethods.CreateService('s1');
        Service__c s2 = Utils_TestMethods.CreateService('s2');
        Service__c s3 = Utils_TestMethods.CreateService('s3');
        insert new List<Service__c>{s1, s2, s3};
            
            //Create Transporteurs
            Transporteur__c t1 = Utils_TestMethods.CreateTransporteur('t1');
        Transporteur__c t2 = Utils_TestMethods.CreateTransporteur('t2');
        Transporteur__c t3 = Utils_TestMethods.CreateTransporteur('t3');
        Insert new List<Transporteur__c>{t1, t2, t3};
            
            //Create Macroprofil Service
            Macroprofil_Service__c ms1 = Utils_TestMethods.CreateMacroprofilService(m1,s1);
        Macroprofil_Service__c ms2 = Utils_TestMethods.CreateMacroprofilService(m2,s2);
        Macroprofil_Service__c ms3 = Utils_TestMethods.CreateMacroprofilService(m2,s3);
        Insert new List<Macroprofil_Service__c>{ms1,ms2,ms3};    
            
            //Create Macroprofil Tranporteur
            Macroprofil_Transporteur__c mt1 = Utils_TestMethods.CreateMacroprofilTransporteur(m1,t1);
        Macroprofil_Transporteur__c mt2 = Utils_TestMethods.CreateMacroprofilTransporteur(m2,t2);
        Macroprofil_Transporteur__c mt3 = Utils_TestMethods.CreateMacroprofilTransporteur(m2,t3);
        Insert new List<Macroprofil_Transporteur__c>{mt1, mt2, mt3}; 
            
            
            
            //Create Account
            
            Account account= Utils_TestMethods.CreateAccount(c,m1, 'a1');
        insert account;
        
        //Create Task
        system.debug(newUser);
        System.debug(account);
        Task newtask= new Task(Subject='Task Test',WhatId=account.id,Priority='Elevée',Status='Ouvert');
        newtask.OwnerId=newUser.id;
        insert newtask;
        
        System.runAs(newUser){  
            Test.startTest();
            try
            {
                delete newtask;
            }
            catch(Exception ex)
            {
                
            }
            Test.stopTest();
        }
    }
}