force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Injoignable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Injoignable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Injoignable_depuis_le__c</fullName>
        <label>Injoignable depuis le</label>
        <type>Date</type>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Historique_Injoignabilites__c.object
<CustomObject>
    <description>Cet objet permet d&apos;historiser les période d&apos;injoignabilité d&apos;un PUDO.</description>
    <fields>
        <fullName>Date_de_debut1__c</fullName>
        <label>Date de début</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_de_fin1__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Indisponibilite__c</fullName>
        <label>Indisponibilité</label>
        <referenceTo>Conge_Indispo__c</referenceTo>
        <relationshipLabel>Historique Injoignabilités</relationshipLabel>
        <relationshipName>Historique_Injoignabilites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Historique Injoignabilité</label>
    <nameField>
        <displayFormat>HIN-{0000}</displayFormat>
        <label>Numero d&apos;historique d&apos;injoignabilité</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historique Injoignabilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AP04_Conge_Indispo_TEST.cls
@isTest
public class AP04_Conge_Indispo_TEST {

    static final Id congeRTypeId = Label.CongeRT_15;
    static final Id indispoStandardRTypeId = Label.IndispoStandardRT_15;
    static final Id indispoConsigneRTypeId = Label.IndispoConsigneRT_15;
    static final Id dispoRTypeId = Label.DispoRT_15;
    
    
     // Cas d'une création d'une injoignabilité sans date de début renseignée après modification de l'indisponibilité correspondante
    static testMethod void insertInjoignabiliteSansDateDeDebut(){
        
        List<Conge_Indispo__c> listeCongesToInsert = new List<Conge_Indispo__c>();  
        
        Account a = [Select Id, Name from Account where Name='TestPudoNoCo' LIMIT 1];
        
        Conge_Indispo__c indispo1 =  Utils_TestMethods.CreateConge_Indispo(indispoStandardRTypeId, a.Id, Date.today(), Date.today().addDays(10));     
        insert indispo1;

        indispo1.Injoignable__c = true;
        update indispo1;

        Historique_Injoignabilites__c hi = [Select Id, Name, Date_de_debut1__c, Indisponibilite__c from Historique_Injoignabilites__c where Indisponibilite__c=: indispo1.Id LIMIT 1];
        }
      // Cas d'une création d'une injoignabilité avec date de début renseignée après modification de l'indisponibilité correspondante
    static testMethod void insertInjoignabiliteAvecDateDeDebutEtFin(){
        
        List<Conge_Indispo__c> listeCongesToInsert = new List<Conge_Indispo__c>();  
        
        Account a = [Select Id, Name from Account where Name='TestPudoNoCo' LIMIT 1];
        
        Conge_Indispo__c indispo1 =  Utils_TestMethods.CreateConge_Indispo(indispoConsigneRTypeId, a.Id, Date.today(), Date.today().addDays(10));     
        insert indispo1;

        indispo1.Injoignable__c = true;
        indispo1.Injoignable_depuis_le__c = Date.today().addDays(-2);
        update indispo1;
        
        indispo1.Injoignable__c = false;
        update indispo1;

        Historique_Injoignabilites__c hi = [Select Id, Name, Date_de_debut1__c, Date_de_fin1__c, Indisponibilite__c from Historique_Injoignabilites__c where Indisponibilite__c=: indispo1.Id LIMIT 1];
        }
    
     // Cas de l'update de la date de début de l'injoignabilité
        static testMethod void injoignabiliteUpdateDateDeDebut(){
        
        List<Conge_Indispo__c> listeCongesToInsert = new List<Conge_Indispo__c>();  
        
        Account a = [Select Id, Name from Account where Name='TestPudoNoCo' LIMIT 1];
        
        Conge_Indispo__c indispo1 =  Utils_TestMethods.CreateConge_Indispo(indispoStandardRTypeId, a.Id, Date.today(), Date.today().addDays(10));     
        insert indispo1;

        indispo1.Injoignable__c = true; 
        update indispo1;
		
        indispo1.Injoignable_depuis_le__c = Date.today().addDays(-2);
        update indispo1;
          
        Historique_Injoignabilites__c hi = [Select Id, Name, Date_de_debut1__c, Indisponibilite__c from Historique_Injoignabilites__c where Indisponibilite__c=: indispo1.Id LIMIT 1];
        }
    
  
    @testSetup
    static void allTheDataForThisTestClass() {
        
        Macroprofil__c mp = Utils_TestMethods.CreateMacroprofil('mp1');
        insert mp;  
        Contact c = Utils_TestMethods.CreateContact('TestContact');
        Account a = Utils_TestMethods.CreateAccount(c, mp, 'TestPudoNoCo');    
        insert a;    
    }
    
}