force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Macroprofil de création.</inlineHelpText>
    <label>Macroprofil de référence</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>equals</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard, 23</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes (Macroprofil de référence)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Macroprofil_Reseau__c.object
<CustomObject>
    <description>Réseaux ajoutés par défaut au relais lors de son association avec un macroprofil</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Réseaux par défaut</relationshipLabel>
        <relationshipName>Reseaux_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reseau__c</fullName>
        <label>Réseau</label>
        <referenceTo>Reseau__c</referenceTo>
        <relationshipLabel>Macroprofils associés</relationshipLabel>
        <relationshipName>Reseaux_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Réseau par défaut</label>
    <nameField>
        <displayFormat>RPD-{0000}</displayFormat>
        <label>Numéro du Réseau par défaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réseaux par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil_Service__c.object
<CustomObject>
    <description>Services ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Services par défaut</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Macroprofil liés à ce service</relationshipLabel>
        <relationshipName>Services_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service par défaut</label>
    <nameField>
        <displayFormat>SPD-{0000}</displayFormat>
        <label>Numéro du Service par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil_Transporteur__c.object
<CustomObject>
    <description>Transporteurs ajoutés par défaut au relais lors de son association avec un macro-profil.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Transporteur par defaut</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <label>Transporteur</label>
        <referenceTo>Transporteur__c</referenceTo>
        <relationshipLabel>Macroprofils liés à ce transporteur</relationshipLabel>
        <relationshipName>Transporteur_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transporteur par defaut</label>
    <nameField>
        <displayFormat>TPD-{0000}</displayFormat>
        <label>Numéro du Transporteur par defaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteur par defaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reseau__c.object
<CustomObject>
    <description>Un réseau est un ensemble de caractéristiques communes à des PUDO parmi : service, opérateur, pays, opérateur...</description>
    <label>Réseau</label>
    <nameField>
        <label>Nom du Réseau</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réseaux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Reseau_Associe__c.object
<CustomObject>
    <description>Ensemble des réseaux associés à l&apos;instant t avec un relais.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Associé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <formula>Compte__r.Macroprofil_actuel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Macroprofil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reseau__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Réseau</label>
        <referenceTo>Reseau__c</referenceTo>
        <relationshipLabel>Points relais associés au réseau</relationshipLabel>
        <relationshipName>Reseaux_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Réseau associé</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Numéro du Réseau associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réseaux associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>Un ensemble de prestations standards proposés aux destinataires par un relais.</description>
    <label>Service</label>
    <nameField>
        <label>Nom du Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Associe__c.object
<CustomObject>
    <description>Ensemble de services proposés par le Pudo selon le macro-profil affecté. Des services seront pilotables par l’action d’activation ou de désactivation.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <formula>Compte__r.Macroprofil_actuel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Macroprofil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Points relais pouvant activer le service</relationshipLabel>
        <relationshipName>Services_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service associé</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Numéro du Service associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transporteur__c.object
<CustomObject>
    <description>Transporteur pouvant livrer un colis dans le Pudo.</description>
    <label>Transporteur</label>
    <nameField>
        <label>Nom du Transporteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteurs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Transporteur_Associe__c.object
<CustomObject>
    <description>Ensemble des chargeurs associés à l&apos;instant avec un relais.Pour la France il est possible d’activer ou désactiver un ou des transporteurs par l’action d’activation ou de désactivation.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <description>Ce champs sera utilisé comme filtre dans les vues de listes.</description>
        <formula>Compte__r.Macroprofil_actuel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Macroprofil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transporteur</label>
        <referenceTo>Transporteur__c</referenceTo>
        <relationshipLabel>Points relais associés</relationshipLabel>
        <relationshipName>Transporteurs_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Transporteur associé</label>
    <nameField>
        <displayFormat>TRA-{0000}</displayFormat>
        <label>Numéro du Transporteur associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteurs associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Utils_PUS_test.cls
/*
* @author: Lea Zoghbi
* @date: 20/12/2017
*/
@isTest
private class Utils_PUS_test {
    static testMethod void checksObjectNonModifiableTest() {
        //Create Macroprofil
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('Macroprofil');
        insert macroprofil;
        
        //Create Service
        Service__c service = Utils_TestMethods.CreateService('Service');
        insert service;
        
        //Create Transporteur
        Transporteur__c transporteur = Utils_TestMethods.CreateTransporteur('Transporteur');
        insert transporteur;
        
        //Create Reseau
        Reseau__c reseau = Utils_TestMethods.CreateReseau('Reseau');
        insert reseau;
        
        //Create Macroprofil Service
        Macroprofil_Service__c macroService = Utils_TestMethods.CreateMacroprofilService(macroprofil, service);
        macroService.Active__c = true;
        macroService.Modifiable__c = false;
        insert macroService;
        
        //Create Macroprofil Transporteur
        Macroprofil_Transporteur__c macroTransporteur = Utils_TestMethods.CreateMacroprofilTransporteur(macroprofil, transporteur);
        macroTransporteur.Active__c = true;
        macroTransporteur.Modifiable__c = false;
        insert macroTransporteur;
        
        //Create Macroprofil Reseau
        Macroprofil_Reseau__c macroReseau = Utils_TestMethods.CreateMacroprofilReseau(macroprofil.Id, reseau.Id);
        macroReseau.Active__c = true;
        macroReseau.Modifiable__c = false;
        insert macroReseau;
        //create account record
        Account pudo = Utils_TestMethods.CreateAccount(null, macroprofil, 'PUDO 1');
        pudo.Macroprofil_de_reference__c = macroprofil.Id;
        insert pudo;
        
        test.startTest();
        Service_Associe__c sa = [select id, Active__C , Modifiable__c 
                                from Service_Associe__c limit 1];
        
        sa.Modifiable__c = false;
        sa.Active__c = false;
        try{
            update sa;
        }catch(Exception ex){
            system.assert(true, ex.getMessage().contains(Label.SERA_ErrorNonModifiable));
        }
        
        Transporteur_Associe__c ta = [select id, Active__C , Modifiable__c 
                                from Transporteur_Associe__c limit 1];
        
        ta.Modifiable__c = false;
        ta.Active__c = false;
        try{
            update ta;
        }catch(Exception ex){
            system.assert(true, ex.getMessage().contains(Label.TRAA_ErrorNonModifiable));
        }
        
        Reseau_Associe__c ra = [select id, Active__C , Modifiable__c 
                                from Reseau_Associe__c limit 1];
        
        ra.Modifiable__c = false;
        ra.Active__c = false;
        try{
            update ra;
        }catch(Exception ex){
            system.assert(true, ex.getMessage().contains(Label.RESA_ErrorNonModifiable));
        }
        
        test.stopTest();
    }
}