force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secteur__c.field-meta.xml
<CustomField>
    <fullName>Secteur__c</fullName>
    <formula>Zone_dimplantation__r.Secteur_parent__r.Secteur_parent__r.Secteur_parent__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secteur</label>
    <type>Text</type>
</CustomField>

src/objects/Alert__c.object
<CustomObject>
    <fields>
        <fullName>MessagePDA_ID__c</fullName>
        <label>MessagePDA_ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Missguided_Type__c</fullName>
        <label>Missguided Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>alert_type__c</fullName>
        <label>Alert Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                    <isActive>false</isActive>
                    <label>3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>pudo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PUDO</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alerts</relationshipLabel>
        <relationshipName>Alertes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>recurrence_index__c</fullName>
        <label>Recurrence index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Alert</label>
    <nameField>
        <displayFormat>ASD-{00000}</displayFormat>
        <label>Alerte Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Secteur__c.object
<CustomObject>
    <description>Un découpage géographique du territoire d&apos;un opérateur, pouvant se chevaucher. Il est aligné sur l&apos;organisation de l&apos;opérateur.</description>
    <label>Secteur</label>
    <nameField>
        <label>Nom du secteur</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secteurs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/WsReturnMessagePDA_Test.cls
@isTest
public class WsReturnMessagePDA_Test {
    @isTest
    static void TestRestCallMsgPDA(){
        Id objectRecordTypeId = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SObjectType = 'Account' and developerName='PUS_FR_PUDO_Suivi_CO'].Id;
        Macroprofil__c MP = Utils_TestMethods.CreateMacroprofil('MP1-Standard');
        MP.Name = 'MP1-Standard';
        insert MP;
        
        Contact acontact = Utils_TestMethods.CreateContact('contactPudo');
        insert acontact;
        Secteur__c asecteur= Utils_TestMethods.createSectorFR('secteurFR');
        insert asecteur;
        Account compte = Utils_TestMethods.CreateAccountPUS_FR_SuiviCo(acontact, MP, 'compte',asecteur );
        compte.Operateur_Global__c='PUS_FR';
        compte.recordtypeId=objectRecordTypeId ;
        insert compte;
        Alert__c testAlert = new Alert__c(pudo__c=compte.Id,ALERT_TYPE__C='1');
        insert testAlert;
        //Alert__c testAlert1 = new Alert__c(pudo__c=compte.Id,ALERT_TYPE__C='2',MISSGUIDED_TYPE__C='2',recurrence_index__c=2 );
        //insert testAlert1;
        testAlert.MessagePDA_ID__c='1234';
        update testAlert;
        //testAlert1.MessagePDA_ID__c='12345';
        //update testAlert1;
        set<ID> Setids = new Set<ID>();
        Setids.add(testAlert.id);
        //Setids.add(testAlert1.id);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        WSCallMessagePDA.MsgPDACallout(Setids);
        Test.stopTest();
        List<WsReturnMessagePDA.ResponseMessagePDA> listresponse = new List<WsReturnMessagePDA.ResponseMessagePDA>();
        WsReturnMessagePDA.ResponseMessagePDA firstResponse = new WsReturnMessagePDA.ResponseMessagePDA();
        WsReturnMessagePDA.ResponseMessagePDA secondResponse = new WsReturnMessagePDA.ResponseMessagePDA();
        firstResponse.IDMessagePDA=testAlert.MessagePDA_ID__c;
        firstResponse.response_overload_capacity_reach='A';
        firstResponse.response_new_temporary_threshold='20';
        firstResponse.response_new_Contractual_threshold='22';
        listresponse.add(firstResponse);
        //secondResponse.IDMessagePDA=testAlert1.MessagePDA_ID__c;
        //secondResponse.response_missguided_full_cause_closure='B';
        //listresponse.add(secondResponse);
        RestRequest request = new RestRequest();
        RestContext.request = request;
        //Set request properties
        request.requestUri ='https://test.salesforce.com/services/apexrest/ReturnMsgPDA/';  
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{"listResponse":[{"IDMessagePDA":"1234","response_overload_capacity_reach":"A","response_new_temporary_threshold":"12"},{"IDMessagePDA":"12345","response_missguided_full_cause_closure":"B"}');
        RestContext.request = request;
        Boolean testRetour =WsReturnMessagePDA.updateAlertByMessagePDA(listresponse);
        System.assertEquals(testRetour, False);
        
    }
}