force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_de_reference__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_de_reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Macroprofil de création.</inlineHelpText>
    <label>Macroprofil de référence</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>equals</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard, 23</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes (Macroprofil de référence)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Macroprofil_Reseau__c.object
<CustomObject>
    <description>Réseaux ajoutés par défaut au relais lors de son association avec un macroprofil</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <label>Macroprofil</label>
        <referenceTo>Macroprofil__c</referenceTo>
        <relationshipLabel>Réseaux par défaut</relationshipLabel>
        <relationshipName>Reseaux_par_defaut</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reseau__c</fullName>
        <label>Réseau</label>
        <referenceTo>Reseau__c</referenceTo>
        <relationshipLabel>Macroprofils associés</relationshipLabel>
        <relationshipName>Reseaux_par_defaut</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Réseau par défaut</label>
    <nameField>
        <displayFormat>RPD-{0000}</displayFormat>
        <label>Numéro du Réseau par défaut</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réseaux par défaut</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reseau__c.object
<CustomObject>
    <description>Un réseau est un ensemble de caractéristiques communes à des PUDO parmi : service, opérateur, pays, opérateur...</description>
    <fields>
        <fullName>NombredePUDOAssocies__c</fullName>
        <label>Nombre de PUDO Associés</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Réseau</label>
    <nameField>
        <label>Nom du Réseau</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Réseaux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Reseau_Associe__c.object
<CustomObject>
    <description>Ensemble des réseaux associés à l&apos;instant t avec un relais.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Associé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Macroprofil__c</fullName>
        <formula>Compte__r.Macroprofil_actuel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Macroprofil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Modifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reseau__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Réseau</label>
        <referenceTo>Reseau__c</referenceTo>
        <relationshipLabel>Points relais associés au réseau</relationshipLabel>
        <relationshipName>Reseaux_associes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Réseau associé</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Numéro du Réseau associé</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réseaux associés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AP03_ReseauAssocie_Test.cls
@isTest
public class AP03_ReseauAssocie_Test {
    
    static testMethod void calculateReseauSeuil_test() {
        
        // Create Contact
        Contact contact = Utils_TestMethods.CreateContact('contact');
        insert contact;
        
        // Create Macroprofil__c
        Macroprofil__c mp = Utils_TestMethods.CreateMacroprofil('mp');
        insert mp;
        
        // Create Reseau__c
        Reseau__c res = Utils_TestMethods.CreateReseau('res');
        insert res;
        
        // Assign the Reseau__c to the Macroprofil__c(reseau par défaut : Macroprofil_Reseau__c)
        Macroprofil_Reseau__c mpr = Utils_TestMethods.CreateMacroprofilReseau(mp.Id, res.Id);
        mpr.Active__c = true;
        mpr.Modifiable__c = true;
        insert mpr;
        
        // Create Account
        // Account.Macroprofil_de_reference = mp --> res associé avec acct
        Account acct = Utils_TestMethods.CreateAccount(contact, mp, 'account');
        acct.Macroprofil_de_reference__c = mp.Id;
        acct.Macroprofil_actuel__c = mp.Id;
        Test.startTest();
        insert acct;
        
        
        // The inserted reseau should be associated only to one account : acct
        List<Reseau_Associe__c> lstRA = [SELECT Id
                                         FROM Reseau_Associe__c
                                         where Reseau__c =: res.Id
                                       ];
        //System.assertEquals(1,lstRa.size());
        
        
        // Check the number of accounts associated to the reseau inserted
        Reseau__c insertedReseau = [SELECT id , NombredePUDOAssocies__c
                                    FROM Reseau__c 
                                    Where Id =: res.Id
                                   ];  
        //System.assertEquals(1,insertedReseau.NombredePUDOAssocies__c);
        
        
        // Remove the reseau associe
        // The number of accounts associated to the reseau should become 0 
        
        lstRA = [SELECT Id
                 FROM Reseau_Associe__c
                 where Reseau__c =: res.Id
                 and Active__c = true
                ];
        if(lstRA.size() > 0) {
            Reseau_Associe__c ra = lstRA.get(0);
            ra.Active__c = false;
            ra.Modifiable__c = true;
            update ra; 
        }
        
        //System.assertEquals(0,lstRa.size());
       
        
        
        Test.stopTest();
    }
}