force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_internationale__c.field-meta.xml
<CustomField>
    <fullName>Reference_internationale__c</fullName>
    <externalId>true</externalId>
    <label>Référence internationale</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VFC06_PudoAnomalies_Test.cls
@isTest
public class VFC06_PudoAnomalies_Test {

    static testmethod void getPudoAnomalies_Test() {
      
        Contact contact = Utils_TestMethods.CreateContact('Test Contact');
        insert contact;
         
        Macroprofil__c mp = Utils_TestMethods.CreateMacroprofil('Test Macroprofil');
        insert mp;
         
        Account account = Utils_TestMethods.CreateAccount(contact, mp, 'Test Account');
        account.Reference_internationale__c = 'FR12345';
        insert account;
      
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockPudoAnomalies());
        ApexPages.StandardController sc = new ApexPages.StandardController(account);
        VFC06_PudoAnomalies accountExt = new VFC06_PudoAnomalies(sc);
        
        PageReference pageRef = Page.VFP06_PudoAnomalies;
        Test.setCurrentPage(pageRef);
        accountExt.getPudoAnomalies();
        Test.stopTest();
    } 
}