force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Macroprofil_actuel__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil_actuel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroprofil actuel</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(((1 AND 2) OR (3 AND 4) OR (5 AND 6)) AND 7) OR 8</booleanFilter>
        <errorMessage>La valeur ne correspond pas aux critères de filtre.</errorMessage>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Consigne</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MPFR_Consigne</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup contact</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP2-Standard</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Pickup store, Agence, Partenaire, Standard</value>
        </filterItems>
        <filterItems>
            <field>Macroprofil__c.Name</field>
            <operation>contains</operation>
            <value>MP</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>equals</operation>
            <value>PUS_FR</value>
        </filterItems>
        <filterItems>
            <field>$Source.Operateur_Global__c</field>
            <operation>notEqual</operation>
            <value>PUS_FR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Macroprofil__c</referenceTo>
    <relationshipLabel>Comptes</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Partenaire__c</fullName>
    <label>Partenaire</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_PAR</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville_de_l_adresse_de_livraison2__c.field-meta.xml
<CustomField>
    <fullName>Ville_de_l_adresse_de_livraison2__c</fullName>
    <label>Ville de l&#39;adresse de livraison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Association_PUDO_Macroprofil__mdt.object
<CustomObject>
    <description>Cet objet contient les pays et types de point associés à chaque Macroprofil d&apos;un PUDO</description>
    <fields>
        <fullName>Id_du_Macroprofil__c</fullName>
        <label>Id du Macroprofil</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partenaire__c</fullName>
        <label>Partenaire</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <label>Pays</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_de_point__c</fullName>
        <label>Type de point</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Association PUDO Macroprofil</label>
    <pluralLabel>Association PUDO Macroprofils</pluralLabel>
</CustomObject>

src/objects/Association_Record_Type_et_pays__mdt.object
<CustomObject>
    <description>Cet objet contient les type d&apos;enregistrement associés à chaque pays</description>
    <fields>
        <fullName>ID_PUDO_Non_Suivi__c</fullName>
        <label>ID PUDO Non Suivi</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_A_Valider__c</fullName>
        <label>ID Prospect A Valider</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Prospect_Converti__c</fullName>
        <label>ID Prospect Converti</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_suivi_CO__c</fullName>
        <label>ID suivi CO</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Association Record Type et pays</label>
    <pluralLabel>Association Record Type et pays</pluralLabel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CountriesSequence__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CountriesSequence</label>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <fields>
        <fullName>Pays__c</fullName>
        <label>Pays</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LOV_GLO_PAY</valueSetName>
        </valueSet>
    </fields>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/globalValueSets/LOV_GLO_PAR.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>119</fullName>
    </customValue>
    <customValue>
        <fullName>120</fullName>
    </customValue>
    <customValue>
        <fullName>124</fullName>
    </customValue>
    <customValue>
        <fullName>125</fullName>
    </customValue>
    <customValue>
        <fullName>126</fullName>
    </customValue>
    <customValue>
        <fullName>134</fullName>
    </customValue>
    <customValue>
        <fullName>135</fullName>
    </customValue>
    <customValue>
        <fullName>140</fullName>
    </customValue>
    <customValue>
        <fullName>146</fullName>
    </customValue>
    <customValue>
        <fullName>177</fullName>
    </customValue>
    <customValue>
        <fullName>178</fullName>
    </customValue>
    <customValue>
        <fullName>179</fullName>
    </customValue>
    <customValue>
        <fullName>180</fullName>
    </customValue>
    <customValue>
        <fullName>181</fullName>
    </customValue>
    <customValue>
        <fullName>182</fullName>
    </customValue>
    <customValue>
        <fullName>183</fullName>
    </customValue>
    <customValue>
        <fullName>184</fullName>
    </customValue>
    <customValue>
        <fullName>185</fullName>
    </customValue>
    <customValue>
        <fullName>188</fullName>
    </customValue>
    <customValue>
        <fullName>189</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>190</fullName>
    </customValue>
    <customValue>
        <fullName>194</fullName>
    </customValue>
    <customValue>
        <fullName>195</fullName>
    </customValue>
    <customValue>
        <fullName>-2</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>210</fullName>
    </customValue>
    <customValue>
        <fullName>211</fullName>
    </customValue>
    <description>Liste des partenaires</description>
    <masterLabel>LOV_GLO_PAR</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOV_GLO_PAY.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Belgique</fullName>
        <isActive>false</isActive>
        <label>Belgique</label>
    </customValue>
    <customValue>
        <fullName>Pays-Bas</fullName>
        <isActive>false</isActive>
        <label>Pays-Bas</label>
    </customValue>
    <description>Pays</description>
    <masterLabel>LOV_GLO_PAY</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP11_AssociationPUDOMacroprofil_TEST.cls
@isTest
public class AP11_AssociationPUDOMacroprofil_TEST {
    static testMethod void myTest() {
        
        //Create Contact
        Contact contactTest = Utils_TestMethods.CreateContact('c1');
        insert contactTest;
        //Create Custom Settings country sequence
        CountriesSequence__c cs = new CountriesSequence__c(Name='Belgium' , Sequence__c = 'BE0001');
        insert cs;
        //Create Contact
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        insert testContact;       
        
        Macroprofil__c testMacroprofil = Utils_TestMethods.CreateMacroprofil('test');
        insert testMacroprofil;
        Macroprofil__c testMacroprofil2 = Utils_TestMethods.CreateMacroprofil('test2');
        insert testMacroprofil2;
        Macroprofil__c testMacroprofil3 = Utils_TestMethods.CreateMacroprofil('test3');
        insert testMacroprofil3;
        
        String json1 = 
            '   [{'+
            '       \"Id_du_Macroprofil__c\": "'+testMacroprofil.id+'",'+
            '       \"MasterLabel\": \"MPBE1-Standard\",'+
            '       \"Pays__c\": \"Belgium\",'+
            '       \"Type_de_point__c\": \"20\"'+
            '   },{'+
            '       \"Id_du_Macroprofil__c\": "'+testMacroprofil2.id+'",'+
            '       \"MasterLabel\": \"MPBE1-Standard\",'+
            '       \"Type_de_point__c\": \"3\",'+
            '       \"Partenaire__c\": \"124\"'+
            '   },{'+
            '       \"Id_du_Macroprofil__c\": "'+testMacroprofil3.id+'",'+
            '       \"MasterLabel\": \"MPNL1-Standard\",'+
            '       \"Type_de_point__c\": \"20\",'+
            '       \"Pays__c\": \"Netherlands\"'+
            '	}]';        
        AssociationPUDOMacroprofil_Test.setMetadata(
            'Select id, Pays__c, Partenaire__c, Type_de_point__c, Id_du_Macroprofil__c From Association_PUDO_Macroprofil__mdt',
            (List<Association_PUDO_Macroprofil__mdt>) JSON.deserialize( json1,  List<Association_PUDO_Macroprofil__mdt>.class )
        );
        
        List< Association_Record_Type_et_pays__mdt> associationRTPays = [Select Id, MasterLabel, ID_Prospect_A_Valider__c, ID_Prospect_Converti__c, ID_suivi_CO__c, ID_PUDO_Non_Suivi__c
                                                                         FROM Association_Record_Type_et_pays__mdt
                                                                         Where MasterLabel ='Belgium'
                                                                         or MasterLabel ='Netherlands'
                                                                         order by MasterLabel ];
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account'); 
        account1.RecordTypeId =associationRTPays[0].ID_PUDO_Non_Suivi__c;
        account1.Type = '20';
        account1.BillingCountry ='Belgium';
        account1.ShippingCountry ='Belgium';
        account1.BillingCountryCode = 'BE';
        account1.ShippingCountryCode ='BE';
        account1.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account1.Operateur_Global__c = 'DPD_BNL';
        account1.BillingPostalCode ='1234';
        account1.ShippingPostalCode = '1243';
        insert account1;
        Account accountAssert = [Select Id, Macroprofil_actuel__c, BillingCountry, Type
                                 From Account 
                                 Where Id =: account1.Id];

        system.assertEquals(testMacroprofil.id, accountAssert.Macroprofil_actuel__c);
        //Create Account
        Account account2= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account');
        account2.RecordTypeId =associationRTPays[0].ID_PUDO_Non_Suivi__c;
        account2.Type = '3';
        account2.Partenaire__c = '124';
        account2.BillingCountry ='Belgium';
        account2.ShippingCountry ='Belgium';
        account2.BillingCountryCode = 'BE';
        account2.ShippingCountryCode ='BE';
        account2.Ville_de_l_adresse_de_livraison2__c = 'Belgium';
        account2.ShippingPostalCode = '1243';
        account2.BillingPostalCode ='1234';
        account2.Operateur_Global__c = 'DPD_BNL';
        insert account2;
        Account accountAssert2 = [Select Id, Macroprofil_actuel__c, BillingCountry, Type
                                  From Account 
                                  Where Id =: account2.Id];

        system.assertEquals(testMacroprofil2.id, accountAssert2.Macroprofil_actuel__c);
        account1.RecordTypeId =associationRTPays[1].ID_PUDO_Non_Suivi__c;
        account1.Type = '20';
        account1.ShippingCountry ='Netherlands';
        account1.ShippingCountryCode ='NL';
        account1.ShippingPostalCode = '1234 AB';
        update account1;

    }
}