force-app/main/default/objects/Account/fields/Macroprofil__c.field-meta.xml
<CustomField>
    <fullName>Macroprofil__c</fullName>
    <label>Macroprofil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

src/objects/Conge_Indispo__c.object
<CustomObject>
    <description>Permet de gérer les périodes de congés, de disponibilités et des indisponibilités des PUDO.</description>
    <fields>
        <fullName>Raison_d_appel__c</fullName>
        <label>Raison d&apos;appel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sous_type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Anomalie Colis</fullName>
                </value>
                <value>
                    <fullName>Anomalie de synchronisation</fullName>
                </value>
                <value>
                    <fullName>Autres</fullName>
                </value>
                <value>
                    <fullName>Démarrage d&apos;activité</fullName>
                </value>
                <value>
                    <fullName>Dévoyé</fullName>
                </value>
                <value>
                    <fullName>Dévoyés</fullName>
                    <isActive>false</isActive>
                    <label>Dévoyés</label>
                </value>
                <value>
                    <fullName>Enquête de bienvenue</fullName>
                </value>
                <value>
                    <fullName>Enquête de satisfaction</fullName>
                </value>
                <value>
                    <fullName>Exclusion</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité problème PDA</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité qualité de service</fullName>
                </value>
                <value>
                    <fullName>Indisponibilité S/T/S</fullName>
                </value>
                <value>
                    <fullName>Injoignable</fullName>
                </value>
                <value>
                    <fullName>Menace de résiliation</fullName>
                    <label>Menaces de résiliation</label>
                </value>
                <value>
                    <fullName>Panne PDA</fullName>
                </value>
                <value>
                    <fullName>Pas de PDA associé</fullName>
                </value>
                <value>
                    <fullName>Problème synchronisation</fullName>
                </value>
                <value>
                    <fullName>Résiliation</fullName>
                </value>
                <value>
                    <fullName>Sinistre/Travaux/Santé</fullName>
                </value>
                <value>
                    <fullName>Surchage</fullName>
                    <isActive>false</isActive>
                    <label>Surchage</label>
                </value>
                <value>
                    <fullName>Surcharge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sous_type__c</fullName>
        <label>Sous type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_d_indisponibilite__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sinistre / Travaux / Santé</fullName>
                </value>
                <value>
                    <fullName>Qualité de service</fullName>
                </value>
                <value>
                    <fullName>Problème de synchronisation</fullName>
                </value>
                <value>
                    <fullName>Panne PDA</fullName>
                </value>
                <value>
                    <fullName>Injoignabilité</fullName>
                </value>
                <value>
                    <fullName>Pas de PDA associé</fullName>
                </value>
                <value>
                    <fullName>Anomalie colis</fullName>
                    <isActive>false</isActive>
                    <label>Anomalie colis</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_d_indisponibilite__c</fullName>
        <description>Ne pas activer l&apos;option &quot;Restreindre la liste sélectionnée aux valeurs définies dans l’ensemble de valeurs.	&quot; pour ne pas bloquer le PB qui crée automatiquement les indispos suite à des créations d&apos;anomalies.</description>
        <label>Type d&apos;indisponibilité</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>Planifiée</fullName>
                </value>
                <value>
                    <fullName>Imprévue</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Congés/disponibilité/indisponibilité</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Numéro du Congé, Dispo ou Indispo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Congés/disponibilités/indisponibilités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Macroprofil__c.object
<CustomObject>
    <description>Un template de Profil Réseau. L&apos;instanciation d&apos;un macro-profil pour un PUDO créé un profil réseau.
Il s’agit d’un ensemble prédéfini de réseaux ayant une réalité métier correspondant à des Services.</description>
    <label>Macroprofil</label>
    <nameField>
        <label>Nom du Macroprofil</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroprofils</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP09_Conge_Indispo_Test.cls
/* Class that test the functionality of AP09_Conge_Indispo*/
@isTest
public class AP09_Conge_Indispo_Test { 
	static Id congeRTypeId = Label.CongeRT_15;
    static Id indispoStandardRTypeId = Label.IndispoStandardRT_15;
    static Id indispoConsigneRTypeId = Label.IndispoConsigneRT_15;
    static Id dispoRTypeId = Label.DispoRT_15;    
    
    static testmethod void testCreateCase() {
        
        List<Conge_Indispo__c> listCongeIndispoToBeAdded = new List<Conge_Indispo__c>(); 
        List<Conge_Indispo__c> listAccountToBeModified = new List<Conge_Indispo__c>();
        List<Conge_Indispo__c> listAccountToBeDeleted = new List<Conge_Indispo__c>();
        List<Account> listAccountToBeAdded = new List<Account>();
        
        List<Conge_Indispo__c> listDispo = new List<Conge_Indispo__c>();
        List<Conge_Indispo__c> listIndispo = new List<Conge_Indispo__c>();
        
        
        //create marcroprofil and contact
        Macroprofil__c macroprofil = Utils_TestMethods.CreateMacroprofil('M1');
        insert macroprofil;
        Contact contact1 = Utils_TestMethods.CreateContact('Contact1');
        Contact contact2 = Utils_TestMethods.CreateContact('Contact2');
        Contact contact3 = Utils_TestMethods.CreateContact('Contact3');
        Contact contact4 = Utils_TestMethods.CreateContact('Contact4');
        Contact contact5 = Utils_TestMethods.CreateContact('Contact5');
        insert new list<contact>{contact1,contact2,contact3,contact4,contact5};
        
        
        //create accounts
        Account account1 = Utils_TestMethods.CreateAccount(contact1, macroprofil, 'Account 1');
        account1.Operateur_Global__c = 'PUS_FR';
        Account account2 = Utils_TestMethods.CreateAccount(contact2, macroprofil, 'Account 2');
        account2.Operateur_Global__c = 'PUS_FR';
        Account account3 = Utils_TestMethods.CreateAccount(contact3, macroprofil, 'Account 3');
        account3.Operateur_Global__c = 'PUS_FR';
        Account account4 = Utils_TestMethods.CreateAccount(contact4, macroprofil, 'Account 4');
        account4.Operateur_Global__c = 'PUS_FR';
        Account account5 = Utils_TestMethods.CreateAccount(contact5, macroprofil, 'Account 5');
        account5.Operateur_Global__c = 'PUS_FR';
        listAccountToBeAdded.add(account1);
        listAccountToBeAdded.add(account2);
        listAccountToBeAdded.add(account3);
        listAccountToBeAdded.add(account4);
        listAccountToBeAdded.add(account5);
        insert listAccountToBeAdded;
        
        contact1.AccountId = account1.id;
        contact2.AccountId = account2.id;
        contact3.AccountId = account3.id;
        contact4.AccountId = account4.id;
        contact5.AccountId = account5.id;
        update new list<contact>{contact1,contact2,contact3,contact4,contact5};
                
        Conge_Indispo__c conge1 = Utils_TestMethods.CreateConge_Indispo(indispoStandardRTypeId, account1.Id , Date.today().addDays(11), Date.today().addDays(16));
        conge1.Type_d_indisponibilite__c = '1';
        conge1.Sous_type__c = 'Sinistre / Travaux / Santé';
        Conge_Indispo__c conge2 = Utils_TestMethods.CreateConge_Indispo(indispoStandardRTypeId, account2.Id , Date.today().addDays(5),Date.today().addDays(10));
        conge2.Type_d_indisponibilite__c = '2';
        conge2.Sous_type__c = 'Problème de synchronisation';
        Conge_Indispo__c conge3 = Utils_TestMethods.CreateConge_Indispo(indispoStandardRTypeId, account3.Id , Date.today().addDays(5),Date.today().addDays(10));
        conge3.Type_d_indisponibilite__c = '2';
        conge3.Sous_type__c = 'Panne PDA';
        Conge_Indispo__c conge4 = Utils_TestMethods.CreateConge_Indispo(indispoStandardRTypeId, account4.Id , Date.today().addDays(5),Date.today().addDays(10));
        conge4.Type_d_indisponibilite__c = '1';
        conge4.Sous_type__c = 'Qualité de service';
        conge4.Raison_d_appel__c = 'Indisponibilité qualité de service';
        Conge_Indispo__c conge5 = Utils_TestMethods.CreateConge_Indispo(indispoStandardRTypeId, account5.Id , Date.today().addDays(5),Date.today().addDays(10));
        conge5.Type_d_indisponibilite__c = '1';
        conge5.Sous_type__c = 'Injoignabilité';
        conge5.Raison_d_appel__c = 'Résiliation';
        listCongeIndispoToBeAdded.add(conge1);
        listCongeIndispoToBeAdded.add(conge2);
        listCongeIndispoToBeAdded.add(conge3);
        listCongeIndispoToBeAdded.add(conge4);
        listCongeIndispoToBeAdded.add(conge5);
        insert listCongeIndispoToBeAdded;    
    }	
}