force-app/main/default/objects/Account/fields/Operateur_Global__c.field-meta.xml
<CustomField>
    <fullName>Operateur_Global__c</fullName>
    <label>Opérateur Global</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOV_GLO_OPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Référence</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_internationale__c.field-meta.xml
<CustomField>
    <fullName>Reference_internationale__c</fullName>
    <externalId>true</externalId>
    <label>Référence internationale</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/globalValueSets/LOV_GLO_OPE.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PUS_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_BNL</fullName>
    </customValue>
    <customValue>
        <fullName>CLP_FR</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_HUN</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CHE</fullName>
    </customValue>
    <customValue>
        <fullName>DPD_CZE</fullName>
    </customValue>
    <description>Liste des opérateurs</description>
    <masterLabel>LOV_GLO_OPE</masterLabel>
</GlobalValueSet>

src/classes/VFC01_PageRedirect.cls
public class VFC01_PageRedirect {
    
    public boolean isValidReferenceNumber {get;set;}
    public String strErrorMessage {get;set;}
    public String vfReferenceInt {get;set;} 
    
    public PageReference redirect() { 
        String referenceNumber = '';
        isValidReferenceNumber = true;
        PageReference pr = null; 
        
        if(vfReferenceInt != null && vfReferenceInt.length() > 0) {
            referenceNumber = vfReferenceInt;
        } else {
            referenceNumber = ApexPages.currentPage().getParameters().get('ref');
        }
        
        if(referenceNumber == null || referenceNumber.length() == 0) {
            strErrorMessage = Label.Empty_Reference_Number;
            isValidReferenceNumber = false;
        }
        
        // check the availability of the account if any ref is sent
        if(isValidReferenceNumber) {
            List<Account> accountList = [SELECT Id,operateur_global__c FROM Account WHERE Reference_internationale__c =: referenceNumber OR Reference__c =: referenceNumber];
            if(accountList.size() >0)   {
                String accountId = accountList[0].Id;
                String accountOperateur = accountList[0].operateur_global__c;
                /*if(accountOperateur == 'PUS_FR'){   
                    pr = new PageReference('/console#%2F'+accountId);
                }
                else{*/
                    pr = new PageReference('/lightning/r/Account/'+accountId+'/view');
                //}
                
            } else {
                strErrorMessage = System.Label.Invalid_International_Reference + ' : ' + referenceNumber;
            }    
        } 
        return pr;
    }  
}