force-app/main/default/objects/Account/fields/Tech_date_debut_conge_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_conge_a_venir__c</fullName>
    <label>Tech date de début congé à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_conge_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_conge_en_cours__c</fullName>
    <label>Tech date de début congé en cours</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_disp_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_disp_a_venir__c</fullName>
    <label>Tech date de début disp à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_debut_indisp_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_debut_indisp_en_cours__c</fullName>
    <label>Tech date de début indisp en cours</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_fin_conge_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_fin_conge_a_venir__c</fullName>
    <label>Tech date de fin congé à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_fin_conge_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_fin_conge_en_cours__c</fullName>
    <label>Tech date de fin congé en cours</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_fin_disp_a_venir__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_fin_disp_a_venir__c</fullName>
    <label>Tech date de fin disp à venir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_date_fin_indisp_en_cours__c.field-meta.xml
<CustomField>
    <fullName>Tech_date_fin_indisp_en_cours__c</fullName>
    <label>Tech date de fin indisp en cours</label>
    <type>Date</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassApex__c</fullName>
        <label>BypassApex</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AP01_Account</fullName>
                </value>
                <value>
                    <fullName>AP05_Account</fullName>
                </value>
                <value>
                    <fullName>AP06_MacroprofilReseau</fullName>
                </value>
                <value>
                    <fullName>Utils_PUS</fullName>
                </value>
                <value>
                    <fullName>AP04_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP02_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP01_CaseComment</fullName>
                </value>
                <value>
                    <fullName>AP08_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP06_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_CompteRenduRempli</fullName>
                </value>
                <value>
                    <fullName>AP01_Case</fullName>
                </value>
                <value>
                    <fullName>AP01_Task</fullName>
                </value>
                <value>
                    <fullName>AP02_Account</fullName>
                </value>
                <value>
                    <fullName>AP02_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP02_MacroprofilTransporteur</fullName>
                </value>
                <value>
                    <fullName>AP02_Task</fullName>
                </value>
                <value>
                    <fullName>AP03_Account</fullName>
                </value>
                <value>
                    <fullName>AP03_Anomalie</fullName>
                </value>
                <value>
                    <fullName>AP03_MacroprofilService</fullName>
                </value>
                <value>
                    <fullName>AP03_ReseauAssocie</fullName>
                </value>
                <value>
                    <fullName>AP03_Task</fullName>
                </value>
                <value>
                    <fullName>AP04_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP05_Conge_Indispo</fullName>
                </value>
                <value>
                    <fullName>AP07_Account</fullName>
                </value>
                <value>
                    <fullName>AP08_Attachement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BypassProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassWorkflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch06_AccountCongeIndispo.cls
/*
* Author : gho
* Test Class : Batch06_AccountCongeIndispo_Test
* Daily Batch called by the schedule : Schedule_Batch03_Account
* Runs at mid-night and iterate through all accounts and modify their disponibilities
* Fields : Conge en cours , Indispo en cours, dispo en cours 
* Tech Fields Updated : Tech_date_debut_conge_en_cours__c , Tech_date_fin_conge_en_cours__c ...
* Lot size : 50 
*/
global class Batch06_AccountCongeIndispo implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        UpdateUser(true, Label.BatchBypass);
        
        // iterate through all accounts because Account's dispo changes on a daily basis
        String query =  'Select Id , Name , Tech_date_debut_conge_en_cours__c , Tech_date_fin_conge_en_cours__c , ' + 
           			    'Tech_date_debut_conge_a_venir__c , Tech_date_fin_conge_a_venir__c , '+
            			'Tech_date_debut_disp_a_venir__c , Tech_date_fin_disp_a_venir__c , '+
            		    'Tech_date_debut_indisp_en_cours__c , Tech_date_fin_indisp_en_cours__c ' + 
            		    'From Account';
        return Database.getQueryLocator(query);    
    }
    
    global void execute(Database.BatchableContext BC , List<sObject> scope) {
        AP10_Account.updateAccountCongeIndispoInformation(scope); 
    }
    
    
    global void finish(Database.BatchableContext BC){
        UpdateUser(false, '');
    }
    
    private void UpdateUser(Boolean BypassworkflowProcessVR,String BypassTrigger){
        User currentUser = [Select id , name , BypassProcessBuilder__c, BypassWorkflow__c, BypassApex__c, BypassValidationRule__c
                           from User
                           where id =: UserInfo.getUserId()];
        currentUser.BypassProcessBuilder__c = BypassworkflowProcessVR;
        currentUser.BypassWorkflow__c = BypassworkflowProcessVR;
        currentUser.BypassValidationRule__c = BypassworkflowProcessVR;
        currentUser.BypassApex__c = BypassTrigger;
        update currentUser;
    }
}