force-app/main/default/objects/Account/fields/Type_de_device__c.field-meta.xml
<CustomField>
    <fullName>Type_de_device__c</fullName>
    <label>Type de device</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDA Android</fullName>
            </value>
            <value>
                <fullName>PDA Windows</fullName>
            </value>
            <value>
                <fullName>BYOD</fullName>
            </value>
            <value>
                <fullName>WEBAPP</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CountriesSequence__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>CountriesSequence</label>
</CustomObject>

src/classes/AP03_Account_TEST.cls
@isTest
public class AP03_Account_TEST {
	static testMethod void testCheckTypeDeDevice() {
        //Create Custom Settings country sequence
        CountriesSequence__c cs = new CountriesSequence__c(Name='Belgium' , Sequence__c = 'BE0001');
        try{
            insert cs;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        try{
            insert testContact;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        //Create Account
        Account account1= Utils_TestMethods.CreateAccount(testContact, null, 'Test Account');
        account1.Type_de_device__c = 'PDA Android;PDA Windows';
        try{
            insert account1;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        account1.Type_de_device__c = 'BYOD';
        try{
            update account1;
        } catch(DmlException e) {
            system.debug('DmlException e '+ e);
        }
        account1.Type_de_device__c = 'PDA Android;PDA Windows;BYOD';
        try{
            update account1;
        }
        catch(exception e){
            system.assert(e.getmessage().contains(Label.Type_de_device_Error));
        }
        account1.Type_de_device__c =null;
        try{
            update account1;
        }
        catch(exception e){
            system.assert(e.getmessage().contains(Label.Type_de_device_Error));
        }
    }
    
}