force-app/main/default/objects/Account/fields/Type_de_device__c.field-meta.xml
<CustomField>
    <fullName>Type_de_device__c</fullName>
    <label>Type de device</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDA Android</fullName>
            </value>
            <value>
                <fullName>PDA Windows</fullName>
            </value>
            <value>
                <fullName>BYOD</fullName>
            </value>
            <value>
                <fullName>WEBAPP</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_device_Selected__c.field-meta.xml
<CustomField>
    <fullName>Type_de_device_Selected__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Type de device Selected</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass ValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Batch07_UpdateTypeDevice.cls
global class Batch07_UpdateTypeDevice implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext BC){
        User currentUser = [Select Id , BypassValidationRule__c
                            from User 
                            where Id=: UserInfo.getUserId()];
        currentUser.BypassValidationRule__c = true;
        update currentUser;
        String querySTMT ='SELECT id, Type_de_device__c, Type_de_device_Selected__c FROM Account ';
        querySTMT += 'WHERE Type_de_device_Selected__c = null AND Type_de_device__c != null ';
        return Database.getQueryLocator(querySTMT);
    }
    global void execute(Database.BatchableContext info, List<Account> scope){
        List <Account> accountToUpdate = new List<Account>();
        List<String> typeDeDeviceList = new List<String>();
        for(Account accountObject: scope){
            typeDeDeviceList= accountObject.Type_de_device__c.split(';');
            accountObject.Type_de_device_Selected__c = typeDeDeviceList.size();
            accountToUpdate.add(accountObject);
        }
        update accountToUpdate;
    }
    global void finish(Database.BatchableContext info){
        
    }
}