force-app/main/default/objects/Account/fields/Type_de_device__c.field-meta.xml
<CustomField>
    <fullName>Type_de_device__c</fullName>
    <label>Type de device</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDA Android</fullName>
            </value>
            <value>
                <fullName>PDA Windows</fullName>
            </value>
            <value>
                <fullName>BYOD</fullName>
            </value>
            <value>
                <fullName>WEBAPP</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_de_device_Selected__c.field-meta.xml
<CustomField>
    <fullName>Type_de_device_Selected__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Type de device Selected</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Désigne un contact lié à un compte.</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch07_UpdateTypeDevice_TEST.cls
@isTest
public class Batch07_UpdateTypeDevice_TEST {
    public static testmethod void testBatchUpdateTypeDevice(){
        // Step 1 : Set Up
        Contact testContact = Utils_TestMethods.CreateContact('Name');
        Account testAccount3 = new Account();
        insert testContact;
        system.debug('contact inserted testContact '+testContact);
        List<Account> accountsToAdd = new List<Account>();
        for(Integer i = 0; i < 4; i++)
        {
            testAccount3 = Utils_TestMethods.CreateAccount(testContact, null, 'Test Account');
            testAccount3.Type_de_device__c ='PDA Windows';
            accountsToAdd.add(testAccount3);
        }
        test.startTest();
        insert accountsToAdd;
        Batch07_UpdateTypeDevice updateTypeDev = new Batch07_UpdateTypeDevice();
        Database.QueryLocator ql = updateTypeDev.start(null);
        updateTypeDev.execute(null,accountsToAdd);
        updateTypeDev.Finish(null);
        test.stopTest();
        
        // Step 2 : Actual Test
        
        /*
        Id batchJobId = Database.executeBatch(new Batch07_UpdateTypeDevice(), 100);
        
        
        // Step 3 : Assert
        */
        // after the testing stops, assert records were updated properly
        System.assertEquals(0, [Select count()
                                From Account 
                                Where Type_de_device_Selected__c = null]);
        
    }       
}